// Sidebarv1_traduction.js
export const sidebarTranslations = {
  fr: {
    furnace: 'Four',
    addRotaryKiln: 'Ajouter four rotatif + post-combustion',
    addGrateFurnace: 'Ajouter un four à grille',
    addFluidizedBed: 'Ajouter un lit fluidisé',
    energyRecovery: 'Récupération d\'énergie',
    addWasteHeatBoiler: 'Ajouter une chaudière de récupération',
    addIACT: 'Ajouter IACT',
    dryTreatment: 'Traitement à sec',
    addBHF: 'Ajouter un filtre à manches',
    addElectrofilter: 'Ajouter un électrofiltre',
    addCyclone: 'Ajouter un cyclone',
    addReactor: 'Ajouter un réacteur',
    addAIRINJECTION: 'Ajouter injection d\'air',
    exit: 'Sortie',
    addIDFan: 'Ajouter un ventilateur ID',
    addStack: 'Ajouter une cheminée',
    addCO2Capture: 'Ajouter capture CO2',
    diagrams: 'Diagrammes',
    hzDiagram: 'Diagramme HZ',
    nhzDiagram: 'Diagramme NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Échangeurs',
    Cooling_HX_air: 'Échangeur air',
    Cooling_HX_eau: 'Échangeur eau',
    TubeAndShell: 'Échangeur tube et calandre',
    // Water Treatment
    waterTreatment: 'Traitement de l\'eau',
    addEauBruteEntree: 'Eau brute entrée',
    addBoueEntree: 'Boue entrée',
    addEauSortie: 'Eau sortie',
    addBoueSortie: 'Boue sortie',
    addEpaississement: 'Épaississement',
    addDeshydratation: 'Déshydratation',
    addDigesteur: 'Digesteur',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  en: {
    furnace: 'Furnace',
    addRotaryKiln: 'Add rotary kiln + post-combustion',
    addGrateFurnace: 'Add a Grate Furnace',
    addFluidizedBed: 'Add a Fluidized Bed',
    energyRecovery: 'Energy Recovery',
    addWasteHeatBoiler: 'Add a Waste Heat Boiler',
    addIACT: 'Add IACT',
    dryTreatment: 'Dry Treatment',
    addBHF: 'Add Bag Filter',
    addElectrofilter: 'Add Electrofilter',
    addCyclone: 'Add Cyclone',
    addReactor: 'Add Reactor',
    addAIRINJECTION: 'Add Air Injection',
    exit: 'Exit',
    addIDFan: 'Add ID Fan',
    addStack: 'Add Stack',
    addCO2Capture: 'Add CO2 Capture',
    diagrams: 'Diagrams',
    hzDiagram: 'HZ Diagram',
    nhzDiagram: 'NHZ Diagram',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Heat Exchangers',
    Cooling_HX_air: 'Air Cooler',
    Cooling_HX_eau: 'Water Cooler',
    TubeAndShell: 'Tube & Shell Exchanger',
    // Water Treatment
    waterTreatment: 'Water Treatment',
    addEauBruteEntree: 'Raw water inlet',
    addBoueEntree: 'Sludge inlet',
    addEauSortie: 'Water outlet',
    addBoueSortie: 'Sludge outlet',
    addEpaississement: 'Thickening',
    addDeshydratation: 'Dewatering',
    addDigesteur: 'Digester',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  es: {
    furnace: 'Horno',
    addRotaryKiln: 'Añadir horno rotativo + postcombustión',
    addGrateFurnace: 'Añadir horno de parrilla',
    addFluidizedBed: 'Añadir lecho fluidizado',
    energyRecovery: 'Recuperación de energía',
    addWasteHeatBoiler: 'Añadir caldera de recuperación de calor',
    addIACT: 'Añadir IACT',
    dryTreatment: 'Tratamiento seco',
    addBHF: 'Añadir filtro de mangas',
    addElectrofilter: 'Añadir electrofiltro',
    addCyclone: 'Añadir ciclón',
    addReactor: 'Añadir reactor',
    addAIRINJECTION: 'Añadir inyección de aire',
    exit: 'Salida',
    addIDFan: 'Añadir ventilador ID',
    addStack: 'Añadir chimenea',
    addCO2Capture: 'Añadir captura CO2',
    diagrams: 'Diagramas',
    hzDiagram: 'Diagrama HZ',
    nhzDiagram: 'Diagrama NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Intercambiadores de calor',
    Cooling_HX_air: 'Enfriador de aire',
    Cooling_HX_eau: 'Enfriador de agua',
    TubeAndShell: 'Intercambiador de tubo y carcasa',
    // Water Treatment
    waterTreatment: 'Tratamiento del agua',
    addEauBruteEntree: 'Entrada agua bruta',
    addBoueEntree: 'Entrada lodo',
    addEauSortie: 'Salida agua',
    addBoueSortie: 'Salida lodo',
    addEpaississement: 'Espesamiento',
    addDeshydratation: 'Deshidratación',
    addDigesteur: 'Digestor',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  de: {
    furnace: 'Ofen',
    addRotaryKiln: 'Drehrohrofen + Nachverbrennung hinzufügen',
    addGrateFurnace: 'Rostofen hinzufügen',
    addFluidizedBed: 'Wirbelschichtbett hinzufügen',
    energyRecovery: 'Energierückgewinnung',
    addWasteHeatBoiler: 'Abhitzekessel hinzufügen',
    addIACT: 'IACT hinzufügen',
    dryTreatment: 'Trockenbehandlung',
    addBHF: 'Schlauchfilter hinzufügen',
    addElectrofilter: 'Elektrofilter hinzufügen',
    addCyclone: 'Zyklon hinzufügen',
    addReactor: 'Reaktor hinzufügen',
    addAIRINJECTION: 'Lufteinblasung hinzufügen',
    exit: 'Ausgang',
    addIDFan: 'ID-Ventilator hinzufügen',
    addStack: 'Schornstein hinzufügen',
    addCO2Capture: 'CO2-Abscheidung hinzufügen',
    diagrams: 'Diagramme',
    hzDiagram: 'HZ-Diagramm',
    nhzDiagram: 'NHZ-Diagramm',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Wärmeaustauscher',
    Cooling_HX_air: 'Luftkühler',
    Cooling_HX_eau: 'Wasserkühler',
    TubeAndShell: 'Rohrbündel-Wärmeaustauscher',
    // Water Treatment
    waterTreatment: 'Wasseraufbereitung',
    addEauBruteEntree: 'Rohwassereingang',
    addBoueEntree: 'Schlammeingang',
    addEauSortie: 'Wasserausgang',
    addBoueSortie: 'Schlammausgang',
    addEpaississement: 'Eindickung',
    addDeshydratation: 'Entwässerung',
    addDigesteur: 'Faulturm',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Konv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  it: {
    furnace: 'Forno',
    addRotaryKiln: 'Aggiungi forno rotativo + postcombustione',
    addGrateFurnace: 'Aggiungi forno a griglia',
    addFluidizedBed: 'Aggiungi letto fluidizzato',
    energyRecovery: 'Recupero energia',
    addWasteHeatBoiler: 'Aggiungi caldaia di recupero calore',
    addIACT: 'Aggiungi IACT',
    dryTreatment: 'Trattamento a secco',
    addBHF: 'Aggiungi filtro a maniche',
    addElectrofilter: 'Aggiungi elettrofiltro',
    addCyclone: 'Aggiungi ciclone',
    addReactor: 'Aggiungi reattore',
    addAIRINJECTION: 'Aggiungi iniezione aria',
    exit: 'Uscita',
    addIDFan: 'Aggiungi ventilatore ID',
    addStack: 'Aggiungi camino',
    addCO2Capture: 'Aggiungi cattura CO2',
    diagrams: 'Diagrammi',
    hzDiagram: 'Diagramma HZ',
    nhzDiagram: 'Diagramma NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Scambiatori di calore',
    Cooling_HX_air: 'Raffreddatore ad aria',
    Cooling_HX_eau: 'Raffreddatore ad acqua',
    TubeAndShell: 'Scambiatore a fascio tubiero',
    // Water Treatment
    waterTreatment: 'Trattamento acque',
    addEauBruteEntree: 'Ingresso acqua grezza',
    addBoueEntree: 'Ingresso fanghi',
    addEauSortie: 'Uscita acqua',
    addBoueSortie: 'Uscita fanghi',
    addEpaississement: 'Ispessimento',
    addDeshydratation: 'Disidratazione',
    addDigesteur: 'Digestore',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  pt: {
    furnace: 'Forno',
    addRotaryKiln: 'Adicionar forno rotativo + pós-combustão',
    addGrateFurnace: 'Adicionar forno de grelha',
    addFluidizedBed: 'Adicionar leito fluidizado',
    energyRecovery: 'Recuperação de energia',
    addWasteHeatBoiler: 'Adicionar caldeira de recuperação de calor',
    addIACT: 'Adicionar IACT',
    dryTreatment: 'Tratamento seco',
    addBHF: 'Adicionar filtro de mangas',
    addElectrofilter: 'Adicionar eletrofiltro',
    addCyclone: 'Adicionar ciclone',
    addReactor: 'Adicionar reator',
    addAIRINJECTION: 'Adicionar injeção de ar',
    exit: 'Saída',
    addIDFan: 'Adicionar ventilador ID',
    addStack: 'Adicionar chaminé',
    addCO2Capture: 'Adicionar captura CO2',
    diagrams: 'Diagramas',
    hzDiagram: 'Diagrama HZ',
    nhzDiagram: 'Diagrama NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Trocadores de calor',
    Cooling_HX_air: 'Resfriador de ar',
    Cooling_HX_eau: 'Resfriador de água',
    TubeAndShell: 'Trocador de tubo e carcaça',
    // Water Treatment
    waterTreatment: 'Tratamento de água',
    addEauBruteEntree: 'Entrada água bruta',
    addBoueEntree: 'Entrada lodo',
    addEauSortie: 'Saída água',
    addBoueSortie: 'Saída lodo',
    addEpaississement: 'Espessamento',
    addDeshydratation: 'Desidratação',
    addDigesteur: 'Digestor',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  ar: {
    furnace: 'فرن',
    addRotaryKiln: 'إضافة فرن دوار + ما بعد الاحتراق',
    addGrateFurnace: 'إضافة فرن شبكي',
    addFluidizedBed: 'إضافة مفاعل مميع',
    energyRecovery: 'استرداد الطاقة',
    addWasteHeatBoiler: 'إضافة غلاية استرداد الحرارة',
    addIACT: 'إضافة IACT',
    dryTreatment: 'المعالجة الجافة',
    addBHF: 'إضافة فلتر الأكياس',
    addElectrofilter: 'إضافة مرشح كهربائي',
    addCyclone: 'إضافة إعصار',
    addReactor: 'إضافة مفاعل',
    addAIRINJECTION: 'إضافة حقن الهواء',
    exit: 'مخرج',
    addIDFan: 'إضافة مروحة السحب',
    addStack: 'إضافة مدخنة',
    addCO2Capture: 'إضافة التقاط ثاني أكسيد الكربون',
    diagrams: 'مخططات',
    hzDiagram: 'مخطط HZ',
    nhzDiagram: 'مخطط NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'مبادلات حرارية',
    Cooling_HX_air: 'مبرد هواء',
    Cooling_HX_eau: 'مبرد ماء',
    TubeAndShell: 'مبادل أنابيب وغلاف',
    // Water Treatment
    waterTreatment: 'معالجة المياه',
    addEauBruteEntree: 'مدخل المياه الخام',
    addBoueEntree: 'مدخل الحمأة',
    addEauSortie: 'مخرج المياه',
    addBoueSortie: 'مخرج الحمأة',
    addEpaississement: 'تكثيف',
    addDeshydratation: 'تجفيف',
    addDigesteur: 'هاضم',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'التشعب/التقارب',
    twotoone: 'محدد 2→1',
    onetotwo: 'موزع 1→2'
  },
  ru: {
    furnace: 'Печь',
    addRotaryKiln: 'Добавить вращающуюся печь + дожигание',
    addGrateFurnace: 'Добавить колосниковую печь',
    addFluidizedBed: 'Добавить псевдоожиженный слой',
    energyRecovery: 'Рекуперация энергии',
    addWasteHeatBoiler: 'Добавить котел-утилизатор',
    addIACT: 'Добавить IACT',
    dryTreatment: 'Сухая обработка',
    addBHF: 'Добавить рукавный фильтр',
    addElectrofilter: 'Добавить электрофильтр',
    addCyclone: 'Добавить циклон',
    addReactor: 'Добавить реактор',
    addAIRINJECTION: 'Добавить впрыск воздуха',
    exit: 'Выход',
    addIDFan: 'Добавить вентилятор ID',
    addStack: 'Добавить дымовую трубу',
    addCO2Capture: 'Добавить улавливание CO2',
    diagrams: 'Диаграммы',
    hzDiagram: 'Диаграмма HZ',
    nhzDiagram: 'Диаграмма NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Теплообменники',
    Cooling_HX_air: 'Воздушный охладитель',
    Cooling_HX_eau: 'Водяной охладитель',
    TubeAndShell: 'Кожухотрубный теплообменник',
    // Water Treatment
    waterTreatment: 'Водоподготовка',
    addEauBruteEntree: 'Вход сырой воды',
    addBoueEntree: 'Вход осадка',
    addEauSortie: 'Выход воды',
    addBoueSortie: 'Выход осадка',
    addEpaississement: 'Уплотнение',
    addDeshydratation: 'Обезвоживание',
    addDigesteur: 'Дигестор',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Разветвление/Сход',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  ja: {
    furnace: '炉',
    addRotaryKiln: 'ロータリーキルン+後燃焼を追加',
    addGrateFurnace: 'グレート炉を追加',
    addFluidizedBed: '流動床を追加',
    energyRecovery: 'エネルギー回収',
    addWasteHeatBoiler: '廃熱ボイラーを追加',
    addIACT: 'IACTを追加',
    dryTreatment: '乾式処理',
    addBHF: 'バグフィルターを追加',
    addElectrofilter: '電気集塵機を追加',
    addCyclone: 'サイクロンを追加',
    addReactor: '反応器を追加',
    addAIRINJECTION: '空気噴射を追加',
    exit: '出口',
    addIDFan: 'IDファンを追加',
    addStack: '煙突を追加',
    addCO2Capture: 'CO2回収を追加',
    diagrams: '図表',
    hzDiagram: 'HZ図',
    nhzDiagram: 'NHZ図',
    // Echangeurs (Heat Exchangers)
    Echangeurs: '熱交換器',
    Cooling_HX_air: '空気冷却器',
    Cooling_HX_eau: '水冷却器',
    TubeAndShell: 'チューブ・シェル式熱交換器',
    // Water Treatment
    waterTreatment: '水処理',
    addEauBruteEntree: '原水入口',
    addBoueEntree: '汚泥入口',
    addEauSortie: '水出口',
    addBoueSortie: '汚泥出口',
    addEpaississement: '濃縮',
    addDeshydratation: '脱水',
    addDigesteur: '消化槽',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: '分岐/合流',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  zh: {
    furnace: '炉子',
    addRotaryKiln: '添加回转窑+后燃烧',
    addGrateFurnace: '添加炉排炉',
    addFluidizedBed: '添加流化床',
    energyRecovery: '能源回收',
    addWasteHeatBoiler: '添加余热锅炉',
    addIACT: '添加IACT',
    dryTreatment: '干式处理',
    addBHF: '添加布袋除尘器',
    addElectrofilter: '添加电除尘器',
    addCyclone: '添加旋风分离器',
    addReactor: '添加反应器',
    addAIRINJECTION: '添加空气喷射',
    exit: '出口',
    addIDFan: '添加引风机',
    addStack: '添加烟囱',
    addCO2Capture: '添加CO2捕获',
    diagrams: '图表',
    hzDiagram: 'HZ图',
    nhzDiagram: 'NHZ图',
    // Echangeurs (Heat Exchangers)
    Echangeurs: '热交换器',
    Cooling_HX_air: '空气冷却器',
    Cooling_HX_eau: '水冷却器',
    TubeAndShell: '管壳式热交换器',
    // Water Treatment
    waterTreatment: '水处理',
    addEauBruteEntree: '原水进口',
    addBoueEntree: '污泥进口',
    addEauSortie: '水出口',
    addBoueSortie: '污泥出口',
    addEpaississement: '浓缩',
    addDeshydratation: '脱水',
    addDigesteur: '消化池',
    addExelys: 'Exelys',
    addBiothelys: 'Biothelys',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: '分流/合流',
    twotoone: '2→1',
    onetotwo: '1→2'
  }
};

// Fonction utilitaire pour obtenir les traductions avec fallback
export const getSidebarTranslations = (language = 'fr') => {
  return sidebarTranslations[language] || sidebarTranslations.fr;
};