// Sidebarv1_traduction.js
export const sidebarTranslations = {
  fr: {
    furnace: 'Four',
    addRotaryKiln: 'Ajouter four rotatif + post-combustion',
    addGrateFurnace: 'Ajouter un four à grille',
    addFluidizedBed: 'Ajouter un lit fluidisé',
    energyRecovery: 'Récupération d\'énergie',
    addWasteHeatBoiler: 'Ajouter une chaudière de récupération',
    addIACT: 'Ajouter IACT',
    dryTreatment: 'Traitement à sec',
    addBHF: 'Ajouter un filtre à manches',
    addElectrofilter: 'Ajouter un électrofiltre',
    addCyclone: 'Ajouter un cyclone',
    addReactor: 'Ajouter un réacteur',
    addAIRINJECTION: 'Ajouter injection d\'air',
    wetTreatment: 'Traitement humide',
    addQuench: 'Ajouter un Quench',
    addWATER_INJECTION: 'Ajouter injection d\'eau',
    addCoolingTower: 'Ajouter une tour de refroidissement vapeur',
    addDenoxCatalyst: 'Ajouter un catalyseur Denox',
    addScrubber: 'Ajouter un laveur',
    exit: 'Sortie',
    addIDFan: 'Ajouter un ventilateur ID',
    addStack: 'Ajouter une cheminée',
    addCO2Capture: 'Ajouter capture CO2',
    diagrams: 'Diagrammes',
    hzDiagram: 'Diagramme HZ',
    nhzDiagram: 'Diagramme NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Échangeurs',
    Cooling_HX_air: 'Échangeur air',
    Cooling_HX_eau: 'Échangeur eau',
    TubeAndShell: 'Échangeur tube et calandre',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  en: {
    furnace: 'Furnace',
    addRotaryKiln: 'Add rotary kiln + post-combustion',
    addGrateFurnace: 'Add a Grate Furnace',
    addFluidizedBed: 'Add a Fluidized Bed',
    energyRecovery: 'Energy Recovery',
    addWasteHeatBoiler: 'Add a Waste Heat Boiler',
    addIACT: 'Add IACT',
    dryTreatment: 'Dry Treatment',
    addBHF: 'Add Bag Filter',
    addElectrofilter: 'Add Electrofilter',
    addCyclone: 'Add Cyclone',
    addReactor: 'Add Reactor',
    addAIRINJECTION: 'Add Air Injection',
    wetTreatment: 'Wet Treatment',
    addQuench: 'Add Quench',
    addWATER_INJECTION: 'Add Water Injection',
    addCoolingTower: 'Add Steam Cooling Tower',
    addDenoxCatalyst: 'Add Denox Catalyst',
    addScrubber: 'Add Scrubber',
    exit: 'Exit',
    addIDFan: 'Add ID Fan',
    addStack: 'Add Stack',
    addCO2Capture: 'Add CO2 Capture',
    diagrams: 'Diagrams',
    hzDiagram: 'HZ Diagram',
    nhzDiagram: 'NHZ Diagram',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Heat Exchangers',
    Cooling_HX_air: 'Air Cooler',
    Cooling_HX_eau: 'Water Cooler',
    TubeAndShell: 'Tube & Shell Exchanger',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  es: {
    furnace: 'Horno',
    addRotaryKiln: 'Añadir horno rotativo + postcombustión',
    addGrateFurnace: 'Añadir horno de parrilla',
    addFluidizedBed: 'Añadir lecho fluidizado',
    energyRecovery: 'Recuperación de energía',
    addWasteHeatBoiler: 'Añadir caldera de recuperación de calor',
    addIACT: 'Añadir IACT',
    dryTreatment: 'Tratamiento seco',
    addBHF: 'Añadir filtro de mangas',
    addElectrofilter: 'Añadir electrofiltro',
    addCyclone: 'Añadir ciclón',
    addReactor: 'Añadir reactor',
    addAIRINJECTION: 'Añadir inyección de aire',
    wetTreatment: 'Tratamiento húmedo',
    addQuench: 'Añadir temple',
    addWATER_INJECTION: 'Añadir inyección de agua',
    addCoolingTower: 'Añadir torre de refrigeración de vapor',
    addDenoxCatalyst: 'Añadir catalizador Denox',
    addScrubber: 'Añadir lavador',
    exit: 'Salida',
    addIDFan: 'Añadir ventilador ID',
    addStack: 'Añadir chimenea',
    addCO2Capture: 'Añadir captura CO2',
    diagrams: 'Diagramas',
    hzDiagram: 'Diagrama HZ',
    nhzDiagram: 'Diagrama NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Intercambiadores de calor',
    Cooling_HX_air: 'Enfriador de aire',
    Cooling_HX_eau: 'Enfriador de agua',
    TubeAndShell: 'Intercambiador de tubo y carcasa',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  de: {
    furnace: 'Ofen',
    addRotaryKiln: 'Drehrohrofen + Nachverbrennung hinzufügen',
    addGrateFurnace: 'Rostofen hinzufügen',
    addFluidizedBed: 'Wirbelschichtbett hinzufügen',
    energyRecovery: 'Energierückgewinnung',
    addWasteHeatBoiler: 'Abhitzekessel hinzufügen',
    addIACT: 'IACT hinzufügen',
    dryTreatment: 'Trockenbehandlung',
    addBHF: 'Schlauchfilter hinzufügen',
    addElectrofilter: 'Elektrofilter hinzufügen',
    addCyclone: 'Zyklon hinzufügen',
    addReactor: 'Reaktor hinzufügen',
    addAIRINJECTION: 'Lufteinblasung hinzufügen',
    wetTreatment: 'Nassbehandlung',
    addQuench: 'Abschreckung hinzufügen',
    addWATER_INJECTION: 'Wassereinspritzung hinzufügen',
    addCoolingTower: 'Dampfkühlturm hinzufügen',
    addDenoxCatalyst: 'Denox-Katalysator hinzufügen',
    addScrubber: 'Wäscher hinzufügen',
    exit: 'Ausgang',
    addIDFan: 'ID-Ventilator hinzufügen',
    addStack: 'Schornstein hinzufügen',
    addCO2Capture: 'CO2-Abscheidung hinzufügen',
    diagrams: 'Diagramme',
    hzDiagram: 'HZ-Diagramm',
    nhzDiagram: 'NHZ-Diagramm',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Wärmeaustauscher',
    Cooling_HX_air: 'Luftkühler',
    Cooling_HX_eau: 'Wasserkühler',
    TubeAndShell: 'Rohrbündel-Wärmeaustauscher',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Konv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  it: {
    furnace: 'Forno',
    addRotaryKiln: 'Aggiungi forno rotativo + postcombustione',
    addGrateFurnace: 'Aggiungi forno a griglia',
    addFluidizedBed: 'Aggiungi letto fluidizzato',
    energyRecovery: 'Recupero energia',
    addWasteHeatBoiler: 'Aggiungi caldaia di recupero calore',
    addIACT: 'Aggiungi IACT',
    dryTreatment: 'Trattamento a secco',
    addBHF: 'Aggiungi filtro a maniche',
    addElectrofilter: 'Aggiungi elettrofiltro',
    addCyclone: 'Aggiungi ciclone',
    addReactor: 'Aggiungi reattore',
    addAIRINJECTION: 'Aggiungi iniezione aria',
    wetTreatment: 'Trattamento umido',
    addQuench: 'Aggiungi tempra',
    addWATER_INJECTION: 'Aggiungi iniezione acqua',
    addCoolingTower: 'Aggiungi torre di raffreddamento vapore',
    addDenoxCatalyst: 'Aggiungi catalizzatore Denox',
    addScrubber: 'Aggiungi scrubber',
    exit: 'Uscita',
    addIDFan: 'Aggiungi ventilatore ID',
    addStack: 'Aggiungi camino',
    addCO2Capture: 'Aggiungi cattura CO2',
    diagrams: 'Diagrammi',
    hzDiagram: 'Diagramma HZ',
    nhzDiagram: 'Diagramma NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Scambiatori di calore',
    Cooling_HX_air: 'Raffreddatore ad aria',
    Cooling_HX_eau: 'Raffreddatore ad acqua',
    TubeAndShell: 'Scambiatore a fascio tubiero',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  pt: {
    furnace: 'Forno',
    addRotaryKiln: 'Adicionar forno rotativo + pós-combustão',
    addGrateFurnace: 'Adicionar forno de grelha',
    addFluidizedBed: 'Adicionar leito fluidizado',
    energyRecovery: 'Recuperação de energia',
    addWasteHeatBoiler: 'Adicionar caldeira de recuperação de calor',
    addIACT: 'Adicionar IACT',
    dryTreatment: 'Tratamento seco',
    addBHF: 'Adicionar filtro de mangas',
    addElectrofilter: 'Adicionar eletrofiltro',
    addCyclone: 'Adicionar ciclone',
    addReactor: 'Adicionar reator',
    addAIRINJECTION: 'Adicionar injeção de ar',
    wetTreatment: 'Tratamento úmido',
    addQuench: 'Adicionar têmpera',
    addWATER_INJECTION: 'Adicionar injeção de água',
    addCoolingTower: 'Adicionar torre de resfriamento de vapor',
    addDenoxCatalyst: 'Adicionar catalisador Denox',
    addScrubber: 'Adicionar lavador',
    exit: 'Saída',
    addIDFan: 'Adicionar ventilador ID',
    addStack: 'Adicionar chaminé',
    addCO2Capture: 'Adicionar captura CO2',
    diagrams: 'Diagramas',
    hzDiagram: 'Diagrama HZ',
    nhzDiagram: 'Diagrama NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Trocadores de calor',
    Cooling_HX_air: 'Resfriador de ar',
    Cooling_HX_eau: 'Resfriador de água',
    TubeAndShell: 'Trocador de tubo e carcaça',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Div/Conv',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  ar: {
    furnace: 'فرن',
    addRotaryKiln: 'إضافة فرن دوار + ما بعد الاحتراق',
    addGrateFurnace: 'إضافة فرن شبكي',
    addFluidizedBed: 'إضافة مفاعل مميع',
    energyRecovery: 'استرداد الطاقة',
    addWasteHeatBoiler: 'إضافة غلاية استرداد الحرارة',
    addIACT: 'إضافة IACT',
    dryTreatment: 'المعالجة الجافة',
    addBHF: 'إضافة فلتر الأكياس',
    addElectrofilter: 'إضافة مرشح كهربائي',
    addCyclone: 'إضافة إعصار',
    addReactor: 'إضافة مفاعل',
    addAIRINJECTION: 'إضافة حقن الهواء',
    wetTreatment: 'المعالجة الرطبة',
    addQuench: 'إضافة تبريد سريع',
    addWATER_INJECTION: 'إضافة حقن الماء',
    addCoolingTower: 'إضافة برج تبريد بخاري',
    addDenoxCatalyst: 'إضافة محفز إزالة النيتروجين',
    addScrubber: 'إضافة جهاز تنظيف',
    exit: 'مخرج',
    addIDFan: 'إضافة مروحة السحب',
    addStack: 'إضافة مدخنة',
    addCO2Capture: 'إضافة التقاط ثاني أكسيد الكربون',
    diagrams: 'مخططات',
    hzDiagram: 'مخطط HZ',
    nhzDiagram: 'مخطط NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'مبادلات حرارية',
    Cooling_HX_air: 'مبرد هواء',
    Cooling_HX_eau: 'مبرد ماء',
    TubeAndShell: 'مبادل أنابيب وغلاف',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'التشعب/التقارب',
    twotoone: 'محدد 2→1',
    onetotwo: 'موزع 1→2'
  },
  ru: {
    furnace: 'Печь',
    addRotaryKiln: 'Добавить вращающуюся печь + дожигание',
    addGrateFurnace: 'Добавить колосниковую печь',
    addFluidizedBed: 'Добавить псевдоожиженный слой',
    energyRecovery: 'Рекуперация энергии',
    addWasteHeatBoiler: 'Добавить котел-утилизатор',
    addIACT: 'Добавить IACT',
    dryTreatment: 'Сухая обработка',
    addBHF: 'Добавить рукавный фильтр',
    addElectrofilter: 'Добавить электрофильтр',
    addCyclone: 'Добавить циклон',
    addReactor: 'Добавить реактор',
    addAIRINJECTION: 'Добавить впрыск воздуха',
    wetTreatment: 'Мокрая обработка',
    addQuench: 'Добавить закалку',
    addWATER_INJECTION: 'Добавить впрыск воды',
    addCoolingTower: 'Добавить паровую градирню',
    addDenoxCatalyst: 'Добавить катализатор Denox',
    addScrubber: 'Добавить скруббер',
    exit: 'Выход',
    addIDFan: 'Добавить вентилятор ID',
    addStack: 'Добавить дымовую трубу',
    addCO2Capture: 'Добавить улавливание CO2',
    diagrams: 'Диаграммы',
    hzDiagram: 'Диаграмма HZ',
    nhzDiagram: 'Диаграмма NHZ',
    // Echangeurs (Heat Exchangers)
    Echangeurs: 'Теплообменники',
    Cooling_HX_air: 'Воздушный охладитель',
    Cooling_HX_eau: 'Водяной охладитель',
    TubeAndShell: 'Кожухотрубный теплообменник',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: 'Разветвление/Сход',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  ja: {
    furnace: '炉',
    addRotaryKiln: 'ロータリーキルン+後燃焼を追加',
    addGrateFurnace: 'グレート炉を追加',
    addFluidizedBed: '流動床を追加',
    energyRecovery: 'エネルギー回収',
    addWasteHeatBoiler: '廃熱ボイラーを追加',
    addIACT: 'IACTを追加',
    dryTreatment: '乾式処理',
    addBHF: 'バグフィルターを追加',
    addElectrofilter: '電気集塵機を追加',
    addCyclone: 'サイクロンを追加',
    addReactor: '反応器を追加',
    addAIRINJECTION: '空気噴射を追加',
    wetTreatment: '湿式処理',
    addQuench: 'クエンチを追加',
    addWATER_INJECTION: '水噴射を追加',
    addCoolingTower: '蒸気冷却塔を追加',
    addDenoxCatalyst: 'Denox触媒を追加',
    addScrubber: 'スクラバーを追加',
    exit: '出口',
    addIDFan: 'IDファンを追加',
    addStack: '煙突を追加',
    addCO2Capture: 'CO2回収を追加',
    diagrams: '図表',
    hzDiagram: 'HZ図',
    nhzDiagram: 'NHZ図',
    // Echangeurs (Heat Exchangers)
    Echangeurs: '熱交換器',
    Cooling_HX_air: '空気冷却器',
    Cooling_HX_eau: '水冷却器',
    TubeAndShell: 'チューブ・シェル式熱交換器',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: '分岐/合流',
    twotoone: '2→1',
    onetotwo: '1→2'
  },
  zh: {
    furnace: '炉子',
    addRotaryKiln: '添加回转窑+后燃烧',
    addGrateFurnace: '添加炉排炉',
    addFluidizedBed: '添加流化床',
    energyRecovery: '能源回收',
    addWasteHeatBoiler: '添加余热锅炉',
    addIACT: '添加IACT',
    dryTreatment: '干式处理',
    addBHF: '添加布袋除尘器',
    addElectrofilter: '添加电除尘器',
    addCyclone: '添加旋风分离器',
    addReactor: '添加反应器',
    addAIRINJECTION: '添加空气喷射',
    wetTreatment: '湿式处理',
    addQuench: '添加淬火',
    addWATER_INJECTION: '添加水喷射',
    addCoolingTower: '添加蒸汽冷却塔',
    addDenoxCatalyst: '添加脱硝催化剂',
    addScrubber: '添加洗涤器',
    exit: '出口',
    addIDFan: '添加引风机',
    addStack: '添加烟囱',
    addCO2Capture: '添加CO2捕获',
    diagrams: '图表',
    hzDiagram: 'HZ图',
    nhzDiagram: 'NHZ图',
    // Echangeurs (Heat Exchangers)
    Echangeurs: '热交换器',
    Cooling_HX_air: '空气冷却器',
    Cooling_HX_eau: '水冷却器',
    TubeAndShell: '管壳式热交换器',
    // DivConv (Divergence/Convergence - Flow Dividers/Combiners)
    DivConv: '分流/合流',
    twotoone: '2→1',
    onetotwo: '1→2'
  }
};

// Fonction utilitaire pour obtenir les traductions avec fallback
export const getSidebarTranslations = (language = 'fr') => {
  return sidebarTranslations[language] || sidebarTranslations.fr;
};