export const translations = {
  fr: {

    'Flue gases': 'Gaz de combustion',
    'Pollutant Emissions': 'Émissions polluantes',
    'Design':  'Dimensionnement',
    'Opex': 'Opex',
    'Rapport': 'Rapport',
    'ELECTROFILTER Configuration': 'Configuration ELECTROFILTER',
    'Back to Flow': 'Retour au flux',

    // ===== SECTIONS PRINCIPALES =====
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Flue gas composition': 'Composition des gaz de combustion',
    'Input flue gas': 'Gaz d\'entrée',
    'Output flue gas': 'Gaz de sortie',
    'Pollutant Treatment Table': 'Tableau de traitement des polluants',
    'Residus calculated': 'Résidus calculés',
    
    // ===== BOUTONS =====
    'Reset to Default Values': 'Réinitialiser aux valeurs par défaut',
    'Clear memory': 'Effacer la mémoire',
    'Results': 'Résultats',
    
    // ===== COLONNES TABLEAU TRAITEMENT POLLUANTS =====
    'Pollutant': 'Polluant',
    'Reagent': 'Réactif',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Efficacité (%)',
    'Stoich. Coeff.': 'Coeff. Stœch.',
    'Output Mass': 'Masse sortie',
    'Residue Mass': 'Masse résidu',
    'Reagent Mass': 'Masse réactif',
    'Abated Mass': 'Masse abattue',
    
    // ===== PARAMETRES FLUE GAS =====
    'Flue gas temperature outlet [°C]': 'Température gaz de combustion sortie [°C]',
    'Ambient air temperature [°C]': 'Température air ambiant [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume air entrant [Nm3/h]',
    'Thermal losses [%]': 'Pertes thermiques [%]',
    'Cooling water temperature [°C]': 'Température eau de refroidissement [°C]',
    
    // ===== ÉLÉMENTS CALCULÉS FLUE GAS =====
    'Temperature inlet ELECTROFILTER [°C]': 'Température à l\'entrée électrofiltre [°C]',
    'Delta enthalpies [kJ/kg]': 'Variation d\'enthalpie [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Eau refroidissement pulvérisée [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gaz de combustion sortie [Nm3/h]',
    
    // ===== DESCRIPTIONS DE GAZ =====
    'Flue gas inlet at inlet temperature': 'Gaz de combustion à l\'entrée à température d\'entrée',
    'Air ingress at ambient temperature': 'Air entrant à température ambiante',
    'Flue gas outlet at outlet temperature': 'Gaz de combustion à la sortie à température de sortie',
    
    // ===== PARAMETRES POLLUTANT EMISSION =====
    'Waste Flow [kg/h]': 'Débit de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit gaz de combustion humide [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit gaz de combustion sec [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'inert mass [kg/h]': 'Masse inerte [kg/h]',
    
    // ===== PARAMETRES CENDRES ET RESIDUS =====
    'Fly ashes content [g/Nm3]': 'Contenu cendres volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité cendres de foyer [%]',
    'O2 ref [%]': 'O2 réf [%]',
    'Dry residus [kg/h]': 'Résidus secs [kg/h]',
    'Wet residus [kg/h]': 'Résidus humides [kg/h]',
    
    // ===== DESIGN - PERTES DE CHARGE =====
    'Pertes de charge aéraulique': 'Pertes de charge aéraulique',
    'Pression aéraulique [mmCE]': 'Pression aéraulique [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Pression de sortie [mmCE]',
    
    // ===== DESIGN - DIMENSIONNEMENT =====
    'Dimensionnement de l\'électrofiltre': 'Dimensionnement de l\'électrofiltre',
    'Rendement de capture [%]': 'Rendement de capture [%]',
    'Vitesse de migration [m/s]': 'Vitesse de migration [m/s]',
    'PDC électrofiltre [mmCE]': 'PDC électrofiltre [mmCE]',
    'Surface des plaques [m²]': 'Surface des plaques [m²]',
    'Nombre de plaques [Nb]': 'Nombre de plaques [Nb]',
    
    // ===== DESIGN - CONSOMMATION ELECTRIQUE =====
    'Estimation des consommations électriques': 'Estimation des consommations électriques',
    'Consommation élec des champs [kW]': 'Consommation élec des champs [kW]',
    'Consommation élec des champs': 'Consommation électrique des champs',
    'Consommation vis de transport [kW]': 'Consommation vis de transport [kW]',
    'consommation vis de transport [kW]': 'Consommation vis de transport [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Consommation électrique des marteaux débatisseurs [kW]',
    'Consommation élec des marteaux débatisseurs': 'Consommation électrique des marteaux débatisseurs',
    
    // ===== DESIGN - AIR COMPRIME =====
    'Consommation d\'air comprimé': 'Consommation d\'air comprimé',
    'Nombre de cycles de nettoyage [Nb]': 'Nombre de cycles de nettoyage [Nb]',
    'Pression air comprimé [Bar]': 'Pression air comprimé [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Air comprimé par cycle [Nm3/cycle]',
    'Consommation air comprimé [Nm3/h]': 'Consommation air comprimé [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consommation élec air comprimé [kW]',
    'Air comprimé': 'Air comprimé',
    
    // ===== DESIGN - EVACUATION =====
    'Évacuation des résidus électrofiltre': 'Évacuation des résidus électrofiltre',
    'Residus électrofiltre [kg/h]': 'Résidus électrofiltre [kg/h]',
    'Type de camion': 'Type de camion',
    'Distance [km]': 'Distance [km]',
    'CO2 transport total [kg]': 'CO2 transport total [kg]',
    'Coût transport total [€]': 'Coût transport total [€]',
    
    // ===== DESIGN - RESUME =====
    'Résumé des paramètres principaux': 'Résumé des paramètres principaux',
    'Paramètres calculés détaillés': 'Paramètres calculés détaillés',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Électrofiltre — Rapport de synthèse',
    '1. Gaz de combustion': '1. Gaz de combustion',
    'Température de sortie': 'Température de sortie',
    'O₂ mesuré (sec)': 'O₂ mesuré (sec)',
    'Débit humide total [kg/h]': 'Débit humide total [kg/h]',
    'Débit sec [Nm³/h]': 'Débit sec [Nm³/h]',
    'Débit humide [Nm³/h]': 'Débit humide [Nm³/h]',
    'Composition gaz de sortie': 'Composition gaz de sortie',
    '2. Émissions polluantes': '2. Émissions polluantes',
    'Gaz en entrée [kg/h]': 'Gaz en entrée [kg/h]',
    'Gaz en sortie [kg/h]': 'Gaz en sortie [kg/h]',
    'Résidus calculés': 'Résidus calculés',
    'Cendres lourdes sèches [kg/h]': 'Cendres lourdes sèches [kg/h]',
    'Cendres volantes [kg/h]': 'Cendres volantes [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Consommations électriques',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Données non disponibles (ouvrir l\'onglet Design)',
    '4. OPEX — Coûts horaires': '4. OPEX — Coûts horaires',
    'Rapport généré automatiquement': 'Rapport généré automatiquement',
    'Consommateur': 'Consommateur',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'Coûts OPEX non disponibles — ouvrir l\'onglet Design.',
    'Électricité': 'Électricité',
    'Eau': 'Eau',
    'Réactifs': 'Réactifs',
    'Énergie': 'Énergie',
    'Total coût': 'Total coût',
    'Coût horaire': 'Coût horaire',
    'Coût annuel': 'Coût annuel',
    'an': 'an',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ électricité',
    'Total CO₂': 'Total CO₂',

  },

  en: {

    'Flue gases': 'Flue gases',
    'Pollutant Emissions': 'Pollutant Emissions',
    'Design': 'Design',
    'Opex': 'Opex',
    'ELECTROFILTER Configuration': 'ELECTROFILTER Configuration',
    'Back to Flow': 'Back to Flow',


    // ===== MAIN SECTIONS =====
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Flue gas composition': 'Flue gas composition',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',
    'Pollutant Treatment Table': 'Pollutant Treatment Table',
    'Residus calculated': 'Residus calculated',
    
    // ===== BUTTONS =====
    'Reset to Default Values': 'Reset to Default Values',
    'Clear memory': 'Clear memory',
    
    'Results': 'Results',
    
    // ===== POLLUTANT TREATMENT TABLE COLUMNS =====
    'Pollutant': 'Pollutant',
    'Reagent': 'Reagent',
    'Mass (kg/h)': 'Mass (kg/h)',
    'Efficiency (%)': 'Efficiency (%)',
    'Stoich. Coeff.': 'Stoich. Coeff.',
    'Output Mass': 'Output Mass',
    'Residue Mass': 'Residue Mass',
    'Reagent Mass': 'Reagent Mass',
    'Abated Mass': 'Abated Mass',
    
    // ===== FLUE GAS PARAMETERS =====
    'Flue gas temperature outlet [°C]': 'Flue gas temperature outlet [°C]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume of air ingress [Nm3/h]',
    'Thermal losses [%]': 'Thermal losses [%]',
    'Cooling water temperature [°C]': 'Cooling water temperature [°C]',
    
    // ===== CALCULATED FLUE GAS ELEMENTS =====
    'Temperature inlet ELECTROFILTER [°C]': 'Temperature inlet ELECTROFILTER [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprayed/cooling water [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Outlet flue gas volume [Nm3/h]',
    
    // ===== GAS DESCRIPTIONS =====
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Air ingress at ambient temperature': 'Air ingress at ambient temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',
    
    // ===== POLLUTANT EMISSION PARAMETERS =====
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'inert mass [kg/h]': 'inert mass [kg/h]',
    
    // ===== ASH AND RESIDUE PARAMETERS =====
    'Fly ashes content [g/Nm3]': 'Fly ashes content [g/Nm3]',
    'siccity bottom ash [%]': 'siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'Dry residus [kg/h]': 'Dry residus [kg/h]',
    'Wet residus [kg/h]': 'Wet residus [kg/h]',
    
    // ===== DESIGN - PRESSURE DROPS =====
    'Pertes de charge aéraulique': 'Aeraulic pressure drops',
    'Pression aéraulique [mmCE]': 'Aeraulic pressure [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Outlet pressure [mmCE]',
    
    // ===== DESIGN - SIZING =====
    'Dimensionnement de l\'électrofiltre': 'Electrofilter sizing',
    'Rendement de capture [%]': 'Capture efficiency [%]',
    'Vitesse de migration [m/s]': 'Migration velocity [m/s]',
    'PDC électrofiltre [mmCE]': 'Electrofilter PDC [mmCE]',
    'Surface des plaques [m²]': 'Plate surface area [m²]',
    'Nombre de plaques [Nb]': 'Number of plates [Nb]',
    
    // ===== DESIGN - POWER CONSUMPTION =====
    'Estimation des consommations électriques': 'Estimation of power consumption',
    'Consommation élec des champs [kW]': 'Power consumption of fields [kW]',
    'Consommation élec des champs': 'Power consumption of fields',
    'Consommation vis de transport [kW]': 'Transport screw consumption [kW]',
    'consommation vis de transport [kW]': 'Transport screw consumption [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Power consumption of hammer shakers [kW]',
    'Consommation élec des marteaux débatisseurs': 'Power consumption of hammer shakers',
    
    // ===== DESIGN - COMPRESSED AIR =====
    'Consommation d\'air comprimé': 'Compressed air consumption',
    'Nombre de cycles de nettoyage [Nb]': 'Number of cleaning cycles [Nb]',
    'Pression air comprimé [Bar]': 'Compressed air pressure [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Compressed air per cycle [Nm3/cycle]',
    'Consommation air comprimé [Nm3/h]': 'Compressed air consumption [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Power consumption compressed air [kW]',
    'Air comprimé': 'Compressed air',
    
    // ===== DESIGN - RESIDUE EVACUATION =====
    'Évacuation des résidus électrofiltre': 'Electrofilter residue evacuation',
    'Residus électrofiltre [kg/h]': 'Electrofilter residues [kg/h]',
    'Type de camion': 'Truck type',
    'Distance [km]': 'Distance [km]',
    'CO2 transport total [kg]': 'Total transport CO2 [kg]',
    'Coût transport total [€]': 'Total transport cost [€]',
    
    // ===== DESIGN - SUMMARY =====
    'Résumé des paramètres principaux': 'Summary of main parameters',
    'Paramètres calculés détaillés': 'Detailed calculated parameters',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Electrofilter — Synthesis Report',
    '1. Gaz de combustion': '1. Flue gases',
    'Température de sortie': 'Outlet temperature',
    'O₂ mesuré (sec)': 'O₂ measured (dry)',
    'Débit humide total [kg/h]': 'Total wet flow rate [kg/h]',
    'Débit sec [Nm³/h]': 'Dry flow rate [Nm³/h]',
    'Débit humide [Nm³/h]': 'Wet flow rate [Nm³/h]',
    'Composition gaz de sortie': 'Outlet gas composition',
    '2. Émissions polluantes': '2. Pollutant emissions',
    'Gaz en entrée [kg/h]': 'Inlet gas [kg/h]',
    'Gaz en sortie [kg/h]': 'Outlet gas [kg/h]',
    'Résidus calculés': 'Calculated residues',
    'Cendres lourdes sèches [kg/h]': 'Dry bottom ash [kg/h]',
    'Cendres volantes [kg/h]': 'Fly ash [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Power consumption',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Data not available (open the Design tab)',
    '4. OPEX — Coûts horaires': '4. OPEX — Hourly costs',
    'Rapport généré automatiquement': 'Report generated automatically',
    'Consommateur': 'Consumer',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'OPEX costs not available — open the Design tab.',
    'Électricité': 'Electricity',
    'Eau': 'Water',
    'Réactifs': 'Reagents',
    'Énergie': 'Energy',
    'Total coût': 'Total cost',
    'Coût horaire': 'Hourly cost',
    'Coût annuel': 'Annual cost',
    'an': 'yr',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricity',
    'Total CO₂': 'Total CO₂',
    'Rapport': 'Report',

  },

  de: {

    'Flue gases': 'Abgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Design': 'Design',
    'Opex': 'Betriebskosten',
    'ELECTROFILTER Configuration': 'ELECTROFILTER-Konfiguration',
    'Back to Flow': 'Zurück zum Fluss',




    'Calculation parameters': 'Berechnungsparameter',
    'Calculated parameters': 'Berechnete Parameter',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Input flue gas': 'Einlassrauchgas',
    'Output flue gas': 'Ausgangsrauchgas',
    'Pollutant Treatment Table': 'Schadstoffbehandlungstabelle',
    'Residus calculated': 'Berechnete Residuen',
    
    'Reset to Default Values': 'Auf Standardwerte zurücksetzen',
    'Clear memory': 'Speicher löschen',
 
    'Results': 'Ergebnisse',
    
    'Pollutant': 'Schadstoff',
    'Reagent': 'Reagenz',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Effizienz (%)',
    'Stoich. Coeff.': 'Stöch. Koeff.',
    'Output Mass': 'Ausgangsmasse',
    'Residue Mass': 'Residuenmasse',
    'Reagent Mass': 'Reagenzmasse',
    'Abated Mass': 'Entfernte Masse',
    
    'Flue gas temperature outlet [°C]': 'Rauchgastemperatur Auslass [°C]',
    'Ambient air temperature [°C]': 'Außenlufttemperatur [°C]',
    'Volume of air ingress [Nm3/h]': 'Lufteinlassvolumen [Nm3/h]',
    'Thermal losses [%]': 'Wärmeverluste [%]',
    'Cooling water temperature [°C]': 'Kühlwassertemperatur [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'Temperatur Elektrofilter Einlass [°C]',
    'Delta enthalpies [kJ/kg]': 'Enthalpieänderung [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Versprühtes Kühlwasser [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Rauchgasauslassvolumen [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': 'Rauchgas am Einlass bei Einlasstemperatur',
    'Air ingress at ambient temperature': 'Lufteinlass bei Umgebungstemperatur',
    'Flue gas outlet at outlet temperature': 'Rauchgas am Auslass bei Auslasstemperatur',
    
    'Waste Flow [kg/h]': 'Abfallfluss [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Rauchgasfluss nass [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Rauchgasfluss trocken [Nm3/h]',
    'O2 calculated [%]': 'O2 berechnet [%]',
    'inert mass [kg/h]': 'Inertmasse [kg/h]',
    
    'Fly ashes content [g/Nm3]': 'Flugaschegehalt [g/Nm3]',
    'siccity bottom ash [%]': 'Bodenasche-Trockenheit [%]',
    'O2 ref [%]': 'O2 Ref [%]',
    'Dry residus [kg/h]': 'Trockene Residuen [kg/h]',
    'Wet residus [kg/h]': 'Feuchte Residuen [kg/h]',
    
    'Pertes de charge aéraulique': 'Aeraulische Druckverluste',
    'Pression aéraulique [mmCE]': 'Aeraulischer Druck [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Auslassdruck [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'Elektrofilter-Dimensionierung',
    'Rendement de capture [%]': 'Abscheidungseffizienz [%]',
    'Vitesse de migration [m/s]': 'Migrationgeschwindigkeit [m/s]',
    'PDC électrofiltre [mmCE]': 'Elektrofilter-PDC [mmCE]',
    'Surface des plaques [m²]': 'Plattenfläche [m²]',
    'Nombre de plaques [Nb]': 'Anzahl Platten [Nb]',
    
    'Estimation des consommations électriques': 'Schätzung des Stromverbrauchs',
    'Consommation élec des champs [kW]': 'Stromverbrauch der Felder [kW]',
    'Consommation élec des champs': 'Stromverbrauch der Felder',
    'Consommation vis de transport [kW]': 'Transportschneckenverbrauch [kW]',
    'consommation vis de transport [kW]': 'Transportschneckenverbrauch [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Stromverbrauch Schüttelhämmer [kW]',
    'Consommation élec des marteaux débatisseurs': 'Stromverbrauch Schüttelhämmer',
    
    'Consommation d\'air comprimé': 'Druckluftvbrauch',
    'Nombre de cycles de nettoyage [Nb]': 'Anzahl Reinigungszyklen [Nb]',
    'Pression air comprimé [Bar]': 'Druckluftdruck [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Druckluft pro Zyklus [Nm3/Zyklus]',
    'Consommation air comprimé [Nm3/h]': 'Druckluftvbrauch [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Stromverbrauch Druckluft [kW]',
    'Air comprimé': 'Druckluft',
    
    'Évacuation des résidus électrofiltre': 'Elektrofilter-Abfallentsorgung',
    'Residus électrofiltre [kg/h]': 'Elektrofilter-Residuen [kg/h]',
    'Type de camion': 'Lkw-Typ',
    'Distance [km]': 'Entfernung [km]',
    'CO2 transport total [kg]': 'Gesamt-Transport-CO2 [kg]',
    'Coût transport total [€]': 'Gesamttransportkosten [€]',
    
    'Résumé des paramètres principaux': 'Zusammenfassung der Hauptparameter',
    'Paramètres calculés détaillés': 'Detaillierte berechnete Parameter',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Elektrofilter — Synthesebericht',
    '1. Gaz de combustion': '1. Abgase',
    'Température de sortie': 'Austrittstemperatur',
    'O₂ mesuré (sec)': 'O₂ gemessen (trocken)',
    'Débit humide total [kg/h]': 'Gesamter Nassvolumenstrom [kg/h]',
    'Débit sec [Nm³/h]': 'Trockener Volumenstrom [Nm³/h]',
    'Débit humide [Nm³/h]': 'Nasser Volumenstrom [Nm³/h]',
    'Composition gaz de sortie': 'Ausgangsgaszusammensetzung',
    '2. Émissions polluantes': '2. Schadstoffemissionen',
    'Gaz en entrée [kg/h]': 'Einlassgas [kg/h]',
    'Gaz en sortie [kg/h]': 'Auslassgas [kg/h]',
    'Résidus calculés': 'Berechnete Rückstände',
    'Cendres lourdes sèches [kg/h]': 'Trockene Bodenasche [kg/h]',
    'Cendres volantes [kg/h]': 'Flugasche [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Stromverbrauch',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Daten nicht verfügbar (Design-Tab öffnen)',
    '4. OPEX — Coûts horaires': '4. OPEX — Stündliche Kosten',
    'Rapport généré automatiquement': 'Bericht automatisch erstellt',
    'Consommateur': 'Verbraucher',
    'Total': 'Gesamt',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'OPEX-Kosten nicht verfügbar — Design-Tab öffnen.',
    'Électricité': 'Elektrizität',
    'Eau': 'Wasser',
    'Réactifs': 'Reagenzien',
    'Énergie': 'Energie',
    'Total coût': 'Gesamtkosten',
    'Coût horaire': 'Stündliche Kosten',
    'Coût annuel': 'Jährliche Kosten',
    'an': 'Jahr',
    'Total CO₂ [kg/h]': 'Gesamt CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ Elektrizität',
    'Total CO₂': 'Gesamt CO₂',
    'Rapport': 'Bericht',

  },

  es: {

    'Flue gases': 'Gases de escape',
    'Pollutant Emissions': 'Emisiones de contaminantes',
    'Design': 'Diseño',
    'Opex': 'Gastos operativos',
    'ELECTROFILTER Configuration': 'Configuración de ELECTROFILTER',
    'Back to Flow': 'Volver al flujo',


    'Calculation parameters': 'Parámetros de cálculo',
    'Calculated parameters': 'Parámetros calculados',
    'Flue gas composition': 'Composición de gases de combustión',
    'Input flue gas': 'Gas de entrada',
    'Output flue gas': 'Gas de salida',
    'Pollutant Treatment Table': 'Tabla de tratamiento de contaminantes',
    'Residus calculated': 'Residuos calculados',
    
    'Reset to Default Values': 'Restablecer valores predeterminados',
    'Clear memory': 'Borrar memoria',
 
    'Results': 'Resultados',
    
    'Pollutant': 'Contaminante',
    'Reagent': 'Reactivo',
    'Mass (kg/h)': 'Masa (kg/h)',
    'Efficiency (%)': 'Eficiencia (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Masa de salida',
    'Residue Mass': 'Masa de residuo',
    'Reagent Mass': 'Masa de reactivo',
    'Abated Mass': 'Masa eliminada',
    
    'Flue gas temperature outlet [°C]': 'Temperatura gas combustión salida [°C]',
    'Ambient air temperature [°C]': 'Temperatura aire ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volumen aire entrada [Nm3/h]',
    'Thermal losses [%]': 'Pérdidas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura agua refrigeración [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'Temperatura entrada electrofilter [°C]',
    'Delta enthalpies [kJ/kg]': 'Variación entalpía [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Agua refrigeración pulverizada [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volumen gas combustión salida [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': 'Gas combustión entrada a temperatura entrada',
    'Air ingress at ambient temperature': 'Aire entrada a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Gas combustión salida a temperatura salida',
    
    'Waste Flow [kg/h]': 'Flujo de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flujo gas combustión húmedo [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flujo gas combustión seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Masa inerte [kg/h]',
    
    'Fly ashes content [g/Nm3]': 'Contenido cenizas volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Sequedad cenizas de foyer [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'Dry residus [kg/h]': 'Residuos secos [kg/h]',
    'Wet residus [kg/h]': 'Residuos húmedos [kg/h]',
    
    'Pertes de charge aéraulique': 'Pérdidas carga aéraulica',
    'Pression aéraulique [mmCE]': 'Presión aéraulica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Presión salida [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'Dimensionamiento electrofilter',
    'Rendement de capture [%]': 'Eficiencia captura [%]',
    'Vitesse de migration [m/s]': 'Velocidad migración [m/s]',
    'PDC électrofiltre [mmCE]': 'PDC electrofilter [mmCE]',
    'Surface des plaques [m²]': 'Superficie placas [m²]',
    'Nombre de plaques [Nb]': 'Número placas [Nb]',
    
    'Estimation des consommations électriques': 'Estimación consumo eléctrico',
    'Consommation élec des champs [kW]': 'Consumo eléctrico campos [kW]',
    'Consommation élec des champs': 'Consumo eléctrico campos',
    'Consommation vis de transport [kW]': 'Consumo tornillo transporte [kW]',
    'consommation vis de transport [kW]': 'Consumo tornillo transporte [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Consumo eléctrico martillos sacudidores [kW]',
    'Consommation élec des marteaux débatisseurs': 'Consumo eléctrico martillos sacudidores',
    
    'Consommation d\'air comprimé': 'Consumo aire comprimido',
    'Nombre de cycles de nettoyage [Nb]': 'Número ciclos limpieza [Nb]',
    'Pression air comprimé [Bar]': 'Presión aire comprimido [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Aire comprimido por ciclo [Nm3/ciclo]',
    'Consommation air comprimé [Nm3/h]': 'Consumo aire comprimido [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo eléctrico aire comprimido [kW]',
    'Air comprimé': 'Aire comprimido',
    
    'Évacuation des résidus électrofiltre': 'Evacuación residuos electrofilter',
    'Residus électrofiltre [kg/h]': 'Residuos electrofilter [kg/h]',
    'Type de camion': 'Tipo camión',
    'Distance [km]': 'Distancia [km]',
    'CO2 transport total [kg]': 'CO2 transporte total [kg]',
    'Coût transport total [€]': 'Costo transporte total [€]',
    
    'Résumé des paramètres principaux': 'Resumen parámetros principales',
    'Paramètres calculés détaillés': 'Parámetros calculados detallados',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Electrofiltro — Informe de síntesis',
    '1. Gaz de combustion': '1. Gases de combustión',
    'Température de sortie': 'Temperatura de salida',
    'O₂ mesuré (sec)': 'O₂ medido (seco)',
    'Débit humide total [kg/h]': 'Caudal húmedo total [kg/h]',
    'Débit sec [Nm³/h]': 'Caudal seco [Nm³/h]',
    'Débit humide [Nm³/h]': 'Caudal húmedo [Nm³/h]',
    'Composition gaz de sortie': 'Composición gas de salida',
    '2. Émissions polluantes': '2. Emisiones contaminantes',
    'Gaz en entrée [kg/h]': 'Gas de entrada [kg/h]',
    'Gaz en sortie [kg/h]': 'Gas de salida [kg/h]',
    'Résidus calculés': 'Residuos calculados',
    'Cendres lourdes sèches [kg/h]': 'Cenizas de fondo secas [kg/h]',
    'Cendres volantes [kg/h]': 'Cenizas volantes [kg/h]',
    '3. Design': '3. Diseño',
    'Consommations électriques': 'Consumos eléctricos',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Datos no disponibles (abrir la pestaña Diseño)',
    '4. OPEX — Coûts horaires': '4. OPEX — Costes horarios',
    'Rapport généré automatiquement': 'Informe generado automáticamente',
    'Consommateur': 'Consumidor',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'Costes OPEX no disponibles — abrir la pestaña Diseño.',
    'Électricité': 'Electricidad',
    'Eau': 'Agua',
    'Réactifs': 'Reactivos',
    'Énergie': 'Energía',
    'Total coût': 'Coste total',
    'Coût horaire': 'Coste horario',
    'Coût annuel': 'Coste anual',
    'an': 'año',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricidad',
    'Total CO₂': 'Total CO₂',
    'Rapport': 'Informe',

  },

  it: {

    'Flue gases': 'Gas di scarico',
    'Pollutant Emissions': 'Emissioni inquinanti',
    'Design': 'Progettazione',
    'Opex': 'Spese operative',
    'ELECTROFILTER Configuration': 'Configurazione ELECTROFILTER',
    'Back to Flow': 'Torna al flusso',


    'Calculation parameters': 'Parametri di calcolo',
    'Calculated parameters': 'Parametri calcolati',
    'Flue gas composition': 'Composizione dei fumi',
    'Input flue gas': 'Fumi in ingresso',
    'Output flue gas': 'Fumi in uscita',
    'Pollutant Treatment Table': 'Tabella di trattamento degli inquinanti',
    'Residus calculated': 'Residui calcolati',
    
    'Reset to Default Values': 'Ripristina valori predefiniti',
    'Clear memory': 'Cancella memoria',
  
    'Results': 'Risultati',
    
    'Pollutant': 'Inquinante',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Efficienza (%)',
    'Stoich. Coeff.': 'Coef. Stechiomet.',
    'Output Mass': 'Massa uscita',
    'Residue Mass': 'Massa residuo',
    'Reagent Mass': 'Massa reagente',
    'Abated Mass': 'Massa rimossa',
    
    'Flue gas temperature outlet [°C]': 'Temperatura fumi uscita [°C]',
    'Ambient air temperature [°C]': 'Temperatura aria ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume aria in ingresso [Nm3/h]',
    'Thermal losses [%]': 'Perdite termiche [%]',
    'Cooling water temperature [°C]': 'Temperatura acqua refrigerazione [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'Temperatura ingresso elettrofiltro [°C]',
    'Delta enthalpies [kJ/kg]': 'Variazione entalpia [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Acqua refrigerazione polverizzata [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume fumi uscita [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': 'Fumi all\'ingresso a temperatura ingresso',
    'Air ingress at ambient temperature': 'Aria in ingresso a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Fumi all\'uscita a temperatura uscita',
    
    'Waste Flow [kg/h]': 'Portata rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Portata fumi umida [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Portata fumi secca [Nm3/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    
    'Fly ashes content [g/Nm3]': 'Contenuto ceneri volatili [g/Nm3]',
    'siccity bottom ash [%]': 'Siccità ceneri di fondo [%]',
    'O2 ref [%]': 'O2 riferimento [%]',
    'Dry residus [kg/h]': 'Residui secchi [kg/h]',
    'Wet residus [kg/h]': 'Residui umidi [kg/h]',
    
    'Pertes de charge aéraulique': 'Perdite carico aerodinamico',
    'Pression aéraulique [mmCE]': 'Pressione aerodinamica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Pressione uscita [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'Dimensionamento elettrofiltro',
    'Rendement de capture [%]': 'Efficienza cattura [%]',
    'Vitesse de migration [m/s]': 'Velocità migrazione [m/s]',
    'PDC électrofiltre [mmCE]': 'PDC elettrofiltro [mmCE]',
    'Surface des plaques [m²]': 'Superficie piastre [m²]',
    'Nombre de plaques [Nb]': 'Numero piastre [Nb]',
    
    'Estimation des consommations électriques': 'Stima dei consumi elettrici',
    'Consommation élec des champs [kW]': 'Consumo elettrico campi [kW]',
    'Consommation élec des champs': 'Consumo elettrico campi',
    'Consommation vis de transport [kW]': 'Consumo vite trasporto [kW]',
    'consommation vis de transport [kW]': 'Consumo vite trasporto [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Consumo elettrico martelli vibro [kW]',
    'Consommation élec des marteaux débatisseurs': 'Consumo elettrico martelli vibro',
    
    'Consommation d\'air comprimé': 'Consumo aria compressa',
    'Nombre de cycles de nettoyage [Nb]': 'Numero cicli pulizia [Nb]',
    'Pression air comprimé [Bar]': 'Pressione aria compressa [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Aria compressa per ciclo [Nm3/ciclo]',
    'Consommation air comprimé [Nm3/h]': 'Consumo aria compressa [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo elettrico aria compressa [kW]',
    'Air comprimé': 'Aria compressa',
    
    'Évacuation des résidus électrofiltre': 'Evacuazione residui elettrofiltro',
    'Residus électrofiltre [kg/h]': 'Residui elettrofiltro [kg/h]',
    'Type de camion': 'Tipo camion',
    'Distance [km]': 'Distanza [km]',
    'CO2 transport total [kg]': 'CO2 trasporto totale [kg]',
    'Coût transport total [€]': 'Costo trasporto totale [€]',
    
    'Résumé des paramètres principaux': 'Riepilogo parametri principali',
    'Paramètres calculés détaillés': 'Parametri calcolati dettagliati',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Elettrofiltro — Rapporto di sintesi',
    '1. Gaz de combustion': '1. Gas di combustione',
    'Température de sortie': 'Temperatura di uscita',
    'O₂ mesuré (sec)': 'O₂ misurato (secco)',
    'Débit humide total [kg/h]': 'Portata umida totale [kg/h]',
    'Débit sec [Nm³/h]': 'Portata secca [Nm³/h]',
    'Débit humide [Nm³/h]': 'Portata umida [Nm³/h]',
    'Composition gaz de sortie': 'Composizione gas di uscita',
    '2. Émissions polluantes': '2. Emissioni inquinanti',
    'Gaz en entrée [kg/h]': 'Gas in ingresso [kg/h]',
    'Gaz en sortie [kg/h]': 'Gas in uscita [kg/h]',
    'Résidus calculés': 'Residui calcolati',
    'Cendres lourdes sèches [kg/h]': 'Ceneri di fondo secche [kg/h]',
    'Cendres volantes [kg/h]': 'Ceneri volanti [kg/h]',
    '3. Design': '3. Progettazione',
    'Consommations électriques': 'Consumi elettrici',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Dati non disponibili (aprire la scheda Progettazione)',
    '4. OPEX — Coûts horaires': '4. OPEX — Costi orari',
    'Rapport généré automatiquement': 'Rapporto generato automaticamente',
    'Consommateur': 'Consumatore',
    'Total': 'Totale',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'Costi OPEX non disponibili — aprire la scheda Progettazione.',
    'Électricité': 'Elettricità',
    'Eau': 'Acqua',
    'Réactifs': 'Reagenti',
    'Énergie': 'Energia',
    'Total coût': 'Costo totale',
    'Coût horaire': 'Costo orario',
    'Coût annuel': 'Costo annuale',
    'an': 'anno',
    'Total CO₂ [kg/h]': 'Totale CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ elettricità',
    'Total CO₂': 'Totale CO₂',
    'Rapport': 'Rapporto',

  },

  pt: {
    'Flue gases': 'Gases de combustão',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Design': 'Design',
    'Opex': 'Despesas operacionais',
    'ELECTROFILTER Configuration': 'Configuração do ELECTROFILTER',
    'Back to Flow': 'Voltar ao fluxo',

    'Calculation parameters': 'Parâmetros de cálculo',
    'Calculated parameters': 'Parâmetros calculados',
    'Flue gas composition': 'Composição do gás de combustão',
    'Input flue gas': 'Gás de entrada',
    'Output flue gas': 'Gás de saída',
    'Pollutant Treatment Table': 'Tabela de tratamento de poluentes',
    'Residus calculated': 'Resíduos calculados',
    
    'Reset to Default Values': 'Restaurar valores padrão',
    'Clear memory': 'Limpar memória',
    'Results': 'Resultados',
    
    'Pollutant': 'Poluente',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Eficiência (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Massa de saída',
    'Residue Mass': 'Massa residual',
    'Reagent Mass': 'Massa reativa',
    'Abated Mass': 'Massa removida',
    
    'Flue gas temperature outlet [°C]': 'Temperatura gás saída [°C]',
    'Ambient air temperature [°C]': 'Temperatura ar ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume ar entrada [Nm3/h]',
    'Thermal losses [%]': 'Perdas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura água refrigeração [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'Temperatura entrada eletrofiltro [°C]',
    'Delta enthalpies [kJ/kg]': 'Variação entalpia [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Água refrigeração pulverizada [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gás saída [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': 'Gás combustão entrada a temperatura entrada',
    'Air ingress at ambient temperature': 'Ar entrada a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Gás combustão saída a temperatura saída',
    
    'Waste Flow [kg/h]': 'Fluxo de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Fluxo de gás úmido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Fluxo de gás seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    
    'Fly ashes content [g/Nm3]': 'Conteúdo de cinzas volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Secagem cinzas fundo [%]',
    'O2 ref [%]': 'O2 referência [%]',
    'Dry residus [kg/h]': 'Resíduos secos [kg/h]',
    'Wet residus [kg/h]': 'Resíduos úmidos [kg/h]',
    
    'Pertes de charge aéraulique': 'Perdas carga aerodinâmica',
    'Pression aéraulique [mmCE]': 'Pressão aerodinâmica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Pressão saída [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'Dimensionamento eletrofiltro',
    'Rendement de capture [%]': 'Eficiência captura [%]',
    'Vitesse de migration [m/s]': 'Velocidade migração [m/s]',
    'PDC électrofiltre [mmCE]': 'PDC eletrofiltro [mmCE]',
    'Surface des plaques [m²]': 'Área placas [m²]',
    'Nombre de plaques [Nb]': 'Número placas [Nb]',
    
    'Estimation des consommations électriques': 'Estimativa de consumo elétrico',
    'Consommation élec des champs [kW]': 'Consumo elétrico campos [kW]',
    'Consommation élec des champs': 'Consumo elétrico campos',
    'Consommation vis de transport [kW]': 'Consumo parafuso transporte [kW]',
    'consommation vis de transport [kW]': 'Consumo parafuso transporte [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Consumo elétrico martelos vibratórios [kW]',
    'Consommation élec des marteaux débatisseurs': 'Consumo elétrico martelos vibratórios',
    
    'Consommation d\'air comprimé': 'Consumo ar comprimido',
    'Nombre de cycles de nettoyage [Nb]': 'Número ciclos limpeza [Nb]',
    'Pression air comprimé [Bar]': 'Pressão ar comprimido [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'Ar comprimido por ciclo [Nm3/ciclo]',
    'Consommation air comprimé [Nm3/h]': 'Consumo ar comprimido [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo elétrico ar comprimido [kW]',
    'Air comprimé': 'Ar comprimido',
    
    'Évacuation des résidus électrofiltre': 'Evacuação resíduos eletrofiltro',
    'Residus électrofiltre [kg/h]': 'Resíduos eletrofiltro [kg/h]',
    'Type de camion': 'Tipo caminhão',
    'Distance [km]': 'Distância [km]',
    'CO2 transport total [kg]': 'CO2 transporte total [kg]',
    'Coût transport total [€]': 'Custo transporte total [€]',
    
    'Résumé des paramètres principaux': 'Resumo parâmetros principais',
    'Paramètres calculés détaillés': 'Parâmetros calculados detalhados',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Eletrofiltro — Relatório de síntese',
    '1. Gaz de combustion': '1. Gases de combustão',
    'Température de sortie': 'Temperatura de saída',
    'O₂ mesuré (sec)': 'O₂ medido (seco)',
    'Débit humide total [kg/h]': 'Vazão úmida total [kg/h]',
    'Débit sec [Nm³/h]': 'Vazão seca [Nm³/h]',
    'Débit humide [Nm³/h]': 'Vazão úmida [Nm³/h]',
    'Composition gaz de sortie': 'Composição do gás de saída',
    '2. Émissions polluantes': '2. Emissões poluentes',
    'Gaz en entrée [kg/h]': 'Gás de entrada [kg/h]',
    'Gaz en sortie [kg/h]': 'Gás de saída [kg/h]',
    'Résidus calculés': 'Resíduos calculados',
    'Cendres lourdes sèches [kg/h]': 'Cinzas de fundo secas [kg/h]',
    'Cendres volantes [kg/h]': 'Cinzas volantes [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Consumos elétricos',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Dados não disponíveis (abrir a aba Design)',
    '4. OPEX — Coûts horaires': '4. OPEX — Custos horários',
    'Rapport généré automatiquement': 'Relatório gerado automaticamente',
    'Consommateur': 'Consumidor',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'Custos OPEX não disponíveis — abrir a aba Design.',
    'Électricité': 'Eletricidade',
    'Eau': 'Água',
    'Réactifs': 'Reagentes',
    'Énergie': 'Energia',
    'Total coût': 'Custo total',
    'Coût horaire': 'Custo horário',
    'Coût annuel': 'Custo anual',
    'an': 'ano',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ eletricidade',
    'Total CO₂': 'Total CO₂',
    'Rapport': 'Relatório',

  },

  ru: {

    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязняющих веществ',
    'Design': 'Дизайн',
    'Opex': 'Операционные расходы',
    'ELECTROFILTER Configuration': 'Конфигурация ЭЛЕКТРОФИЛЬТРА',
    'Back to Flow': 'Вернуться к потоку',


    'Calculation parameters': 'Параметры расчета',
    'Calculated parameters': 'Рассчитанные параметры',
    'Flue gas composition': 'Состав дымовых газов',
    'Input flue gas': 'Входящие дымовые газы',
    'Output flue gas': 'Выходящие дымовые газы',
    'Pollutant Treatment Table': 'Таблица обработки загрязняющих веществ',
    'Residus calculated': 'Рассчитанные остатки',
    
    'Reset to Default Values': 'Восстановить значения по умолчанию',
    'Clear memory': 'Очистить память',

    'Results': 'Результаты',
    
    'Pollutant': 'Загрязняющее вещество',
    'Reagent': 'Реагент',
    'Mass (kg/h)': 'Масса (кг/ч)',
    'Efficiency (%)': 'Эффективность (%)',
    'Stoich. Coeff.': 'Коэф. стехиометрии',
    'Output Mass': 'Выходная масса',
    'Residue Mass': 'Остаточная масса',
    'Reagent Mass': 'Масса реагента',
    'Abated Mass': 'Удаленная масса',
    
    'Flue gas temperature outlet [°C]': 'Температура выхода дымовых газов [°C]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Volume of air ingress [Nm3/h]': 'Объем поступления воздуха [Nm3/ч]',
    'Thermal losses [%]': 'Тепловые потери [%]',
    'Cooling water temperature [°C]': 'Температура охлаждающей воды [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'Температура входа электрофильтра [°C]',
    'Delta enthalpies [kJ/kg]': 'Изменение энтальпии [кДж/кг]',
    'Sprayed/cooling water [kg/h]': 'Распыленная/охлаждающая вода [кг/ч]',
    'Outlet flue gas volume [Nm3/h]': 'Объем выходящих дымовых газов [Nm3/ч]',
    
    'Flue gas inlet at inlet temperature': 'Входящие дымовые газы при температуре входа',
    'Air ingress at ambient temperature': 'Поступление воздуха при температуре окружающей среды',
    'Flue gas outlet at outlet temperature': 'Выходящие дымовые газы при температуре выхода',
    
    'Waste Flow [kg/h]': 'Поток отходов [кг/ч]',
    'Flue gas Flow Wet [Nm3/h]': 'Поток влажных дымовых газов [Nm3/ч]',
    'Flue gas Flow Dry [Nm3/h]': 'Поток сухих дымовых газов [Nm3/ч]',
    'O2 calculated [%]': 'Рассчитанный O2 [%]',
    'inert mass [kg/h]': 'Инертная масса [кг/ч]',
    
    'Fly ashes content [g/Nm3]': 'Содержание летучей золы [г/Nm3]',
    'siccity bottom ash [%]': 'Сухость шлака [%]',
    'O2 ref [%]': 'O2 эталонное [%]',
    'Dry residus [kg/h]': 'Сухие остатки [кг/ч]',
    'Wet residus [kg/h]': 'Влажные остатки [кг/ч]',
    
    'Pertes de charge aéraulique': 'Потери аэродинамического давления',
    'Pression aéraulique [mmCE]': 'Аэродинамическое давление [mmCE]',
    'PDC [mmCE]': 'Пад [mmCE]',
    'Pression de sortie [mmCE]': 'Давление выхода [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'Размеры электрофильтра',
    'Rendement de capture [%]': 'Эффективность улавливания [%]',
    'Vitesse de migration [m/s]': 'Скорость миграции [м/с]',
    'PDC électrofiltre [mmCE]': 'Пад электрофильтра [mmCE]',
    'Surface des plaques [m²]': 'Площадь пластин [м²]',
    'Nombre de plaques [Nb]': 'Количество пластин [Кол-во]',
    
    'Estimation des consommations électriques': 'Расчет электропотребления',
    'Consommation élec des champs [kW]': 'Потребление электроэнергии полями [кВт]',
    'Consommation élec des champs': 'Потребление электроэнергии полями',
    'Consommation vis de transport [kW]': 'Потребление транспортного шнека [кВт]',
    'consommation vis de transport [kW]': 'Потребление транспортного шнека [кВт]',
    'Consommation élec des marteaux débatisseurs [kW]': 'Потребление вибрирующих молотков [кВт]',
    'Consommation élec des marteaux débatisseurs': 'Потребление вибрирующих молотков',
    
    'Consommation d\'air comprimé': 'Потребление сжатого воздуха',
    'Nombre de cycles de nettoyage [Nb]': 'Количество циклов очистки [Кол-во]',
    'Pression air comprimé [Bar]': 'Давление сжатого воздуха [Бар]',
    'Air comprime par cycle [Nm3/cycle]': 'Сжатый воздух за цикл [Nm3/цикл]',
    'Consommation air comprimé [Nm3/h]': 'Потребление сжатого воздуха [Nm3/ч]',
    'Conso élec air comprimé [kW]': 'Потребление электроэнергии сжатого воздуха [кВт]',
    'Air comprimé': 'Сжатый воздух',
    
    'Évacuation des résidus électrofiltre': 'Удаление остатков электрофильтра',
    'Residus électrofiltre [kg/h]': 'Остатки электрофильтра [кг/ч]',
    'Type de camion': 'Тип грузовика',
    'Distance [km]': 'Расстояние [км]',
    'CO2 transport total [kg]': 'Общий CO2 транспорта [кг]',
    'Coût transport total [€]': 'Общая стоимость транспорта [€]',
    
    'Résumé des paramètres principaux': 'Резюме основных параметров',
    'Paramètres calculés détaillés': 'Подробные рассчитанные параметры',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'Электрофильтр — Сводный отчёт',
    '1. Gaz de combustion': '1. Дымовые газы',
    'Température de sortie': 'Температура выхода',
    'O₂ mesuré (sec)': 'O₂ измеренный (сухой)',
    'Débit humide total [kg/h]': 'Общий влажный расход [кг/ч]',
    'Débit sec [Nm³/h]': 'Сухой расход [Nm³/ч]',
    'Débit humide [Nm³/h]': 'Влажный расход [Nm³/ч]',
    'Composition gaz de sortie': 'Состав выходного газа',
    '2. Émissions polluantes': '2. Выбросы загрязняющих веществ',
    'Gaz en entrée [kg/h]': 'Входящий газ [кг/ч]',
    'Gaz en sortie [kg/h]': 'Выходящий газ [кг/ч]',
    'Résidus calculés': 'Рассчитанные остатки',
    'Cendres lourdes sèches [kg/h]': 'Сухая донная зола [кг/ч]',
    'Cendres volantes [kg/h]': 'Летучая зола [кг/ч]',
    '3. Design': '3. Дизайн',
    'Consommations électriques': 'Электропотребление',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Данные недоступны (открыть вкладку Дизайн)',
    '4. OPEX — Coûts horaires': '4. ОПЕКС — Почасовые затраты',
    'Rapport généré automatiquement': 'Отчёт сформирован автоматически',
    'Consommateur': 'Потребитель',
    'Total': 'Итого',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'Затраты ОПЕКС недоступны — откройте вкладку Дизайн.',
    'Électricité': 'Электричество',
    'Eau': 'Вода',
    'Réactifs': 'Реагенты',
    'Énergie': 'Энергия',
    'Total coût': 'Итоговые затраты',
    'Coût horaire': 'Почасовые затраты',
    'Coût annuel': 'Годовые затраты',
    'an': 'год',
    'Total CO₂ [kg/h]': 'Итого CO₂ [кг/ч]',
    'CO₂ électricité': 'CO₂ электричество',
    'Total CO₂': 'Итого CO₂',
    'Rapport': 'Отчёт',

  },

  zh: {


    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Design': '设计',
    'Opex': '运营成本',
    'ELECTROFILTER Configuration': '静电除尘器配置',
    'Back to Flow': '返回流程',


    'Calculation parameters': '计算参数',
    'Calculated parameters': '计算后的参数',
    'Flue gas composition': '烟气成分',
    'Input flue gas': '进入烟气',
    'Output flue gas': '烟气出口',
    'Pollutant Treatment Table': '污染物处理表',
    'Residus calculated': '计算残留物',
    
    'Reset to Default Values': '恢复默认值',
    'Clear memory': '清除内存',

    'Results': '结果',
    
    'Pollutant': '污染物',
    'Reagent': '试剂',
    'Mass (kg/h)': '质量 (kg/h)',
    'Efficiency (%)': '效率 (%)',
    'Stoich. Coeff.': '化学计量系数',
    'Output Mass': '输出质量',
    'Residue Mass': '残留质量',
    'Reagent Mass': '试剂质量',
    'Abated Mass': '去除质量',
    
    'Flue gas temperature outlet [°C]': '烟气出口温度 [°C]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Volume of air ingress [Nm3/h]': '进入空气体积 [Nm3/h]',
    'Thermal losses [%]': '热损失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': '电除尘器进口温度 [°C]',
    'Delta enthalpies [kJ/kg]': '焓变 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '喷射/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '烟气出口体积 [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': '烟气进口(进口温度)',
    'Air ingress at ambient temperature': '空气进入(环境温度)',
    'Flue gas outlet at outlet temperature': '烟气出口(出口温度)',
    
    'Waste Flow [kg/h]': '废弃物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流量 [Nm3/h]',
    'O2 calculated [%]': '计算O2含量 [%]',
    'inert mass [kg/h]': '惯性质量 [kg/h]',
    
    'Fly ashes content [g/Nm3]': '飞灰含量 [g/Nm3]',
    'siccity bottom ash [%]': '底灰干度 [%]',
    'O2 ref [%]': 'O2参考值 [%]',
    'Dry residus [kg/h]': '干残留物 [kg/h]',
    'Wet residus [kg/h]': '湿残留物 [kg/h]',
    
    'Pertes de charge aéraulique': '气动压力损失',
    'Pression aéraulique [mmCE]': '气动压力 [mmCE]',
    'PDC [mmCE]': '压降 [mmCE]',
    'Pression de sortie [mmCE]': '出口压力 [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': '电除尘器尺寸设计',
    'Rendement de capture [%]': '捕集效率 [%]',
    'Vitesse de migration [m/s]': '迁移速度 [m/s]',
    'PDC électrofiltre [mmCE]': '电除尘器压降 [mmCE]',
    'Surface des plaques [m²]': '极板面积 [m²]',
    'Nombre de plaques [Nb]': '极板数量 [个]',
    
    'Estimation des consommations électriques': '电力消耗估算',
    'Consommation élec des champs [kW]': '电场电力消耗 [kW]',
    'Consommation élec des champs': '电场电力消耗',
    'Consommation vis de transport [kW]': '输送螺旋电力消耗 [kW]',
    'consommation vis de transport [kW]': '输送螺旋电力消耗 [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': '振动锤电力消耗 [kW]',
    'Consommation élec des marteaux débatisseurs': '振动锤电力消耗',
    
    'Consommation d\'air comprimé': '压缩空气消耗',
    'Nombre de cycles de nettoyage [Nb]': '清洁周期数 [个]',
    'Pression air comprimé [Bar]': '压缩空气压力 [Bar]',
    'Air comprime par cycle [Nm3/cycle]': '单周期压缩空气 [Nm3/周期]',
    'Consommation air comprimé [Nm3/h]': '压缩空气消耗 [Nm3/h]',
    'Conso élec air comprimé [kW]': '压缩空气电力消耗 [kW]',
    'Air comprimé': '压缩空气',
    
    'Évacuation des résidus électrofiltre': '电除尘器残留物排放',
    'Residus électrofiltre [kg/h]': '电除尘器残留物 [kg/h]',
    'Type de camion': '卡车类型',
    'Distance [km]': '距离 [km]',
    'CO2 transport total [kg]': '总运输CO2 [kg]',
    'Coût transport total [€]': '总运输成本 [€]',
    
    'Résumé des paramètres principaux': '主要参数摘要',
    'Paramètres calculés détaillés': '详细计算参数',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': '静电除尘器 — 综合报告',
    '1. Gaz de combustion': '1. 烟气',
    'Température de sortie': '出口温度',
    'O₂ mesuré (sec)': 'O₂ 测量值（干态）',
    'Débit humide total [kg/h]': '总湿流量 [kg/h]',
    'Débit sec [Nm³/h]': '干流量 [Nm³/h]',
    'Débit humide [Nm³/h]': '湿流量 [Nm³/h]',
    'Composition gaz de sortie': '出口气体成分',
    '2. Émissions polluantes': '2. 污染物排放',
    'Gaz en entrée [kg/h]': '入口气体 [kg/h]',
    'Gaz en sortie [kg/h]': '出口气体 [kg/h]',
    'Résidus calculés': '计算残留物',
    'Cendres lourdes sèches [kg/h]': '干底灰 [kg/h]',
    'Cendres volantes [kg/h]': '飞灰 [kg/h]',
    '3. Design': '3. 设计',
    'Consommations électriques': '电力消耗',
    'Données non disponibles (ouvrir l\'onglet Design)': '数据不可用（请打开设计选项卡）',
    '4. OPEX — Coûts horaires': '4. OPEX — 每小时费用',
    'Rapport généré automatiquement': '自动生成报告',
    'Consommateur': '消费者',
    'Total': '合计',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'OPEX 费用不可用 — 请打开设计选项卡。',
    'Électricité': '电力',
    'Eau': '水',
    'Réactifs': '试剂',
    'Énergie': '能源',
    'Total coût': '总费用',
    'Coût horaire': '每小时费用',
    'Coût annuel': '年度费用',
    'an': '年',
    'Total CO₂ [kg/h]': '总 CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ 电力',
    'Total CO₂': '总 CO₂',
    'Rapport': '报告',

  },

  ja: {
    'Flue gases': '排ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Design': 'デザイン',
    'Opex': '運営費',
    'ELECTROFILTER Configuration': '静電除塵装置の構成',
    'Back to Flow': 'フローに戻る',

    'Calculation parameters': '計算パラメータ',
    'Calculated parameters': '計算済みパラメータ',
    'Flue gas composition': '排ガス組成',
    'Input flue gas': '入口排ガス',
    'Output flue gas': '出口排ガス',
    'Pollutant Treatment Table': '汚染物質処理表',
    'Residus calculated': '計算された残留物',
    
    'Reset to Default Values': 'デフォルト値にリセット',
    'Clear memory': 'メモリをクリア',

    'Results': '結果',
    
    'Pollutant': '汚染物質',
    'Reagent': '試薬',
    'Mass (kg/h)': '質量 (kg/h)',
    'Efficiency (%)': '効率 (%)',
    'Stoich. Coeff.': '化学量論係数',
    'Output Mass': '出力質量',
    'Residue Mass': '残留質量',
    'Reagent Mass': '試薬質量',
    'Abated Mass': '除去質量',
    
    'Flue gas temperature outlet [°C]': '排ガス出口温度 [°C]',
    'Ambient air temperature [°C]': '周囲空気温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空気導入体積 [Nm3/h]',
    'Thermal losses [%]': '熱損失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': '電気集塵機入口温度 [°C]',
    'Delta enthalpies [kJ/kg]': 'エンタルピー変化 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '噴射/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '出口排ガス体積 [Nm3/h]',
    
    'Flue gas inlet at inlet temperature': '排ガス入口(入口温度)',
    'Air ingress at ambient temperature': '空気導入(周囲温度)',
    'Flue gas outlet at outlet temperature': '排ガス出口(出口温度)',
    
    'Waste Flow [kg/h]': '廃棄物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿り排ガス流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾き排ガス流量 [Nm3/h]',
    'O2 calculated [%]': '計算O2濃度 [%]',
    'inert mass [kg/h]': '不活性質量 [kg/h]',
    
    'Fly ashes content [g/Nm3]': 'フライアッシュ含有量 [g/Nm3]',
    'siccity bottom ash [%]': 'ボトムアッシュ乾燥度 [%]',
    'O2 ref [%]': 'O2基準値 [%]',
    'Dry residus [kg/h]': '乾き残留物 [kg/h]',
    'Wet residus [kg/h]': '湿り残留物 [kg/h]',
    
    'Pertes de charge aéraulique': '空気動力学的圧力損失',
    'Pression aéraulique [mmCE]': '空気動力学的圧力 [mmCE]',
    'PDC [mmCE]': '圧力損失 [mmCE]',
    'Pression de sortie [mmCE]': '出口圧力 [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': '電気集塵機の寸法設計',
    'Rendement de capture [%]': '捕集効率 [%]',
    'Vitesse de migration [m/s]': '移動速度 [m/s]',
    'PDC électrofiltre [mmCE]': '電気集塵機圧力損失 [mmCE]',
    'Surface des plaques [m²]': '極板面積 [m²]',
    'Nombre de plaques [Nb]': '極板数 [個]',
    
    'Estimation des consommations électriques': '電力消費量推定',
    'Consommation élec des champs [kW]': '電界電力消費量 [kW]',
    'Consommation élec des champs': '電界電力消費量',
    'Consommation vis de transport [kW]': '搬送スクリュー電力消費量 [kW]',
    'consommation vis de transport [kW]': '搬送スクリュー電力消費量 [kW]',
    'Consommation élec des marteaux débatisseurs [kW]': '振動ハンマー電力消費量 [kW]',
    'Consommation élec des marteaux débatisseurs': '振動ハンマー電力消費量',
    
    'Consommation d\'air comprimé': '圧縮空気消費量',
    'Nombre de cycles de nettoyage [Nb]': '清浄サイクル数 [個]',
    'Pression air comprimé [Bar]': '圧縮空気圧力 [Bar]',
    'Air comprime par cycle [Nm3/cycle]': 'サイクル当たり圧縮空気 [Nm3/サイクル]',
    'Consommation air comprimé [Nm3/h]': '圧縮空気消費量 [Nm3/h]',
    'Conso élec air comprimé [kW]': '圧縮空気電力消費量 [kW]',
    'Air comprimé': '圧縮空気',
    
    'Évacuation des résidus électrofiltre': '電気集塵機残留物排出',
    'Residus électrofiltre [kg/h]': '電気集塵機残留物 [kg/h]',
    'Type de camion': 'トラック種別',
    'Distance [km]': '距離 [km]',
    'CO2 transport total [kg]': '総輸送CO2 [kg]',
    'Coût transport total [€]': '総輸送コスト [€]',
    
    'Résumé des paramètres principaux': '主要パラメータ概要',
    'Paramètres calculés détaillés': '詳細計算パラメータ',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': '電気集塵機 — 総合レポート',
    '1. Gaz de combustion': '1. 排ガス',
    'Température de sortie': '出口温度',
    'O₂ mesuré (sec)': 'O₂ 測定値（乾き）',
    'Débit humide total [kg/h]': '総湿り流量 [kg/h]',
    'Débit sec [Nm³/h]': '乾き流量 [Nm³/h]',
    'Débit humide [Nm³/h]': '湿り流量 [Nm³/h]',
    'Composition gaz de sortie': '出口ガス組成',
    '2. Émissions polluantes': '2. 汚染物質排出',
    'Gaz en entrée [kg/h]': '入口ガス [kg/h]',
    'Gaz en sortie [kg/h]': '出口ガス [kg/h]',
    'Résidus calculés': '計算された残留物',
    'Cendres lourdes sèches [kg/h]': '乾き底灰 [kg/h]',
    'Cendres volantes [kg/h]': 'フライアッシュ [kg/h]',
    '3. Design': '3. 設計',
    'Consommations électriques': '電力消費量',
    'Données non disponibles (ouvrir l\'onglet Design)': 'データ未利用（設計タブを開いてください）',
    '4. OPEX — Coûts horaires': '4. OPEX — 時間当たりコスト',
    'Rapport généré automatiquement': 'レポート自動生成',
    'Consommateur': '消費者',
    'Total': '合計',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'OPEXコスト未利用 — 設計タブを開いてください。',
    'Électricité': '電力',
    'Eau': '水',
    'Réactifs': '試薬',
    'Énergie': 'エネルギー',
    'Total coût': '総コスト',
    'Coût horaire': '時間当たりコスト',
    'Coût annuel': '年間コスト',
    'an': '年',
    'Total CO₂ [kg/h]': '総 CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ 電力',
    'Total CO₂': '総 CO₂',
    'Rapport': 'レポート',

  },

  ar: {

    'Flue gases': 'غازات العادم',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Design': 'التصميم',
    'Opex': 'نفقات التشغيل',
    'ELECTROFILTER Configuration': 'تكوين مرشح كهربائي',
    'Back to Flow': 'العودة إلى التدفق',

    
    'Calculation parameters': 'معاملات الحساب',
    'Calculated parameters': 'المعاملات المحسوبة',
    'Flue gas composition': 'تكوين غاز المداخن',
    'Input flue gas': 'غاز المداخن الداخل',
    'Output flue gas': 'غاز المداخن الخارج',
    'Pollutant Treatment Table': 'جدول معالجة الملوثات',
    'Residus calculated': 'البقايا المحسوبة',
    
    'Reset to Default Values': 'استعادة القيم الافتراضية',
    'Clear memory': 'مسح الذاكرة',
  
    'Results': 'النتائج',
    
    'Pollutant': 'ملوث',
    'Reagent': 'كاشف',
    'Mass (kg/h)': 'الكتلة (كجم/ساعة)',
    'Efficiency (%)': 'الكفاءة (%)',
    'Stoich. Coeff.': 'معامل القياس المتكافئ',
    'Output Mass': 'كتلة الإخراج',
    'Residue Mass': 'كتلة البقايا',
    'Reagent Mass': 'كتلة الكاشف',
    'Abated Mass': 'الكتلة المزالة',
    
    'Flue gas temperature outlet [°C]': 'درجة حرارة مخرج غاز المداخن [°C]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Volume of air ingress [Nm3/h]': 'حجم الهواء الداخل [Nm3/ساعة]',
    'Thermal losses [%]': 'الفقد الحراري [%]',
    'Cooling water temperature [°C]': 'درجة حرارة ماء التبريد [°C]',
    
    'Temperature inlet ELECTROFILTER [°C]': 'درجة حرارة مدخل المرشح الكهربائي [°C]',
    'Delta enthalpies [kJ/kg]': 'تغيير الإنثالبيا [كيلوجول/كغ]',
    'Sprayed/cooling water [kg/h]': 'ماء الرش/التبريد [كغ/ساعة]',
    'Outlet flue gas volume [Nm3/h]': 'حجم غاز المداخن الخارج [Nm3/ساعة]',
    
    'Flue gas inlet at inlet temperature': 'غاز المداخن الداخل عند درجة حرارة المدخل',
    'Air ingress at ambient temperature': 'دخول الهواء عند درجة الحرارة المحيطة',
    'Flue gas outlet at outlet temperature': 'غاز المداخن الخارج عند درجة حرارة المخرج',
    
    'Waste Flow [kg/h]': 'تدفق النفايات [كغ/ساعة]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق غاز المداخن الرطب [Nm3/ساعة]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق غاز المداخن الجاف [Nm3/ساعة]',
    'O2 calculated [%]': 'O2 المحسوبة [%]',
    'inert mass [kg/h]': 'الكتلة الخاملة [كغ/ساعة]',
    
    'Fly ashes content [g/Nm3]': 'محتوى الرماد المتطاير [غرام/Nm3]',
    'siccity bottom ash [%]': 'جفاف رماد القاع [%]',
    'O2 ref [%]': 'O2 المرجع [%]',
    'Dry residus [kg/h]': 'البقايا الجافة [كغ/ساعة]',
    'Wet residus [kg/h]': 'البقايا الرطبة [كغ/ساعة]',
    
    'Pertes de charge aéraulique': 'فقد الضغط الديناميكي الهوائي',
    'Pression aéraulique [mmCE]': 'الضغط الديناميكي الهوائي [mmCE]',
    'PDC [mmCE]': 'فقد الضغط [mmCE]',
    'Pression de sortie [mmCE]': 'ضغط المخرج [mmCE]',
    
    'Dimensionnement de l\'électrofiltre': 'تصميم المرشح الكهربائي',
    'Rendement de capture [%]': 'كفاءة الالتقاط [%]',
    'Vitesse de migration [m/s]': 'سرعة الهجرة [م/ثانية]',
    'PDC électrofiltre [mmCE]': 'فقد ضغط المرشح الكهربائي [mmCE]',
    'Surface des plaques [m²]': 'مساحة الألواح [م²]',
    'Nombre de plaques [Nb]': 'عدد الألواح [عدد]',
    
    'Estimation des consommations électriques': 'تقدير استهلاك الكهرباء',
    'Consommation élec des champs [kW]': 'استهلاك الكهرباء للحقول [كيلوواط]',
    'Consommation élec des champs': 'استهلاك الكهرباء للحقول',
    'Consommation vis de transport [kW]': 'استهلاك مسمار النقل [كيلوواط]',
    'consommation vis de transport [kW]': 'استهلاك مسمار النقل [كيلوواط]',
    'Consommation élec des marteaux débatisseurs [kW]': 'استهلاك مطارق الاهتزاز [كيلوواط]',
    'Consommation élec des marteaux débatisseurs': 'استهلاك مطارق الاهتزاز',
    
    'Consommation d\'air comprimé': 'استهلاك الهواء المضغوط',
    'Nombre de cycles de nettoyage [Nb]': 'عدد دورات التنظيف [عدد]',
    'Pression air comprimé [Bar]': 'ضغط الهواء المضغوط [بار]',
    'Air comprime par cycle [Nm3/cycle]': 'هواء مضغوط لكل دورة [Nm3/دورة]',
    'Consommation air comprimé [Nm3/h]': 'استهلاك الهواء المضغوط [Nm3/ساعة]',
    'Conso élec air comprimé [kW]': 'استهلاك الكهرباء للهواء المضغوط [كيلوواط]',
    'Air comprimé': 'هواء مضغوط',
    
    'Évacuation des résidus électrofiltre': 'إزالة بقايا المرشح الكهربائي',
    'Residus électrofiltre [kg/h]': 'بقايا المرشح الكهربائي [كغ/ساعة]',
    'Type de camion': 'نوع الشاحنة',
    'Distance [km]': 'المسافة [كم]',
    'CO2 transport total [kg]': 'إجمالي CO2 المواصلات [كغ]',
    'Coût transport total [€]': 'إجمالي تكلفة المواصلات [€]',
    
    'Résumé des paramètres principaux': 'ملخص المعاملات الرئيسية',
    'Paramètres calculés détaillés': 'المعاملات المحسوبة التفصيلية',

    // ===== REPORT =====
    'Électrofiltre — Rapport de synthèse': 'المرشح الكهربائي — تقرير الملخص',
    '1. Gaz de combustion': '1. غازات العادم',
    'Température de sortie': 'درجة حرارة المخرج',
    'O₂ mesuré (sec)': 'O₂ مقاس (جاف)',
    'Débit humide total [kg/h]': 'إجمالي التدفق الرطب [كغ/ساعة]',
    'Débit sec [Nm³/h]': 'التدفق الجاف [Nm³/ساعة]',
    'Débit humide [Nm³/h]': 'التدفق الرطب [Nm³/ساعة]',
    'Composition gaz de sortie': 'تركيب غاز المخرج',
    '2. Émissions polluantes': '2. انبعاثات الملوثات',
    'Gaz en entrée [kg/h]': 'غاز المدخل [كغ/ساعة]',
    'Gaz en sortie [kg/h]': 'غاز المخرج [كغ/ساعة]',
    'Résidus calculés': 'البقايا المحسوبة',
    'Cendres lourdes sèches [kg/h]': 'رماد القاع الجاف [كغ/ساعة]',
    'Cendres volantes [kg/h]': 'الرماد المتطاير [كغ/ساعة]',
    '3. Design': '3. التصميم',
    'Consommations électriques': 'الاستهلاك الكهربائي',
    'Données non disponibles (ouvrir l\'onglet Design)': 'البيانات غير متاحة (افتح تبويب التصميم)',
    '4. OPEX — Coûts horaires': '4. OPEX — التكاليف الساعية',
    'Rapport généré automatiquement': 'تقرير مُنشأ تلقائياً',
    'Consommateur': 'المستهلك',
    'Total': 'المجموع',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Design.': 'تكاليف OPEX غير متاحة — افتح تبويب التصميم.',
    'Électricité': 'الكهرباء',
    'Eau': 'الماء',
    'Réactifs': 'الكواشف',
    'Énergie': 'الطاقة',
    'Total coût': 'التكلفة الإجمالية',
    'Coût horaire': 'التكلفة الساعية',
    'Coût annuel': 'التكلفة السنوية',
    'an': 'سنة',
    'Total CO₂ [kg/h]': 'إجمالي CO₂ [كغ/ساعة]',
    'CO₂ électricité': 'CO₂ الكهرباء',
    'Total CO₂': 'إجمالي CO₂',
    'Rapport': 'تقرير',

  },

};