export const translations = {
  fr: {
    'SEP12 Parameters': 'Paramètres SEP12',
    'Clear memory': 'Effacer la mémoire',
    'SEP12 — 1 to 2 Separator': 'SEP12 — Séparateur 1 vers 2',
    'Inlet stream': 'Flux entrant',
    'Total mass flow [kg/h]': 'Débit massique total [kg/h]',
    'Split ratio': 'Rapport de séparation',
    '% to Flux 1': '% vers Flux 1',
    '% to Flux 2': '% vers Flux 2',
    'Flux 1 — to next node': 'Flux 1 — vers nœud suivant',
    'Flux 2 — evacuated': 'Flux 2 — évacué',
    'Dry flow [Nm³/h]': 'Débit sec [Nm³/h]',
    'Wet flow [Nm³/h]': 'Débit humide [Nm³/h]',
    'Flue Gas Separator': 'Séparateur gaz de fumée',
    'Back to Flow': 'Retour au Flow',
    'Send Data': 'Envoyer les données',
  },
  en: {
    'SEP12 Parameters': 'SEP12 Parameters',
    'Clear memory': 'Clear memory',
    'SEP12 — 1 to 2 Separator': 'SEP12 — 1 to 2 Separator',
    'Inlet stream': 'Inlet stream',
    'Total mass flow [kg/h]': 'Total mass flow [kg/h]',
    'Split ratio': 'Split ratio',
    '% to Flux 1': '% to Flux 1',
    '% to Flux 2': '% to Flux 2',
    'Flux 1 — to next node': 'Flux 1 — to next node',
    'Flux 2 — evacuated': 'Flux 2 — evacuated',
    'Dry flow [Nm³/h]': 'Dry flow [Nm³/h]',
    'Wet flow [Nm³/h]': 'Wet flow [Nm³/h]',
    'Flue Gas Separator': 'Flue Gas Separator',
    'Back to Flow': 'Back to Flow',
    'Send Data': 'Send Data',
  },
  es: {
    'SEP12 Parameters': 'Parámetros SEP12',
    'Clear memory': 'Borrar memoria',
    'SEP12 — 1 to 2 Separator': 'SEP12 — Separador 1 a 2',
    'Inlet stream': 'Flujo de entrada',
    'Total mass flow [kg/h]': 'Caudal másico total [kg/h]',
    'Split ratio': 'Relación de separación',
    '% to Flux 1': '% hacia Flujo 1',
    '% to Flux 2': '% hacia Flujo 2',
    'Flux 1 — to next node': 'Flujo 1 — hacia nodo siguiente',
    'Flux 2 — evacuated': 'Flujo 2 — evacuado',
    'Dry flow [Nm³/h]': 'Caudal seco [Nm³/h]',
    'Wet flow [Nm³/h]': 'Caudal húmedo [Nm³/h]',
    'Flue Gas Separator': 'Separador de gases de combustión',
    'Back to Flow': 'Volver al flujo',
    'Send Data': 'Enviar datos',
  },
  de: {
    'SEP12 Parameters': 'SEP12-Parameter',
    'Clear memory': 'Speicher löschen',
    'SEP12 — 1 to 2 Separator': 'SEP12 — 1-zu-2-Separator',
    'Inlet stream': 'Eintrittsstrom',
    'Total mass flow [kg/h]': 'Gesamtmassenstrom [kg/h]',
    'Split ratio': 'Aufteilungsverhältnis',
    '% to Flux 1': '% zu Strom 1',
    '% to Flux 2': '% zu Strom 2',
    'Flux 1 — to next node': 'Strom 1 — zum nächsten Knoten',
    'Flux 2 — evacuated': 'Strom 2 — abgeführt',
    'Dry flow [Nm³/h]': 'Trockenstrom [Nm³/h]',
    'Wet flow [Nm³/h]': 'Feuchtstrom [Nm³/h]',
    'Flue Gas Separator': 'Rauchgasabscheider',
    'Back to Flow': 'Zurück zum Fluss',
    'Send Data': 'Daten senden',
  },
  it: {
    'SEP12 Parameters': 'Parametri SEP12',
    'Clear memory': 'Cancella memoria',
    'SEP12 — 1 to 2 Separator': 'SEP12 — Separatore 1 a 2',
    'Inlet stream': 'Flusso in ingresso',
    'Total mass flow [kg/h]': 'Portata massica totale [kg/h]',
    'Split ratio': 'Rapporto di separazione',
    '% to Flux 1': '% verso Flusso 1',
    '% to Flux 2': '% verso Flusso 2',
    'Flux 1 — to next node': 'Flusso 1 — verso nodo successivo',
    'Flux 2 — evacuated': 'Flusso 2 — evacuato',
    'Dry flow [Nm³/h]': 'Portata secca [Nm³/h]',
    'Wet flow [Nm³/h]': 'Portata umida [Nm³/h]',
    'Flue Gas Separator': 'Separatore gas di combustione',
    'Back to Flow': 'Torna al flusso',
    'Send Data': 'Invia dati',
  },
  pt: {
    'SEP12 Parameters': 'Parâmetros SEP12',
    'Clear memory': 'Limpar memória',
    'SEP12 — 1 to 2 Separator': 'SEP12 — Separador 1 para 2',
    'Inlet stream': 'Fluxo de entrada',
    'Total mass flow [kg/h]': 'Vazão mássica total [kg/h]',
    'Split ratio': 'Razão de separação',
    '% to Flux 1': '% para Fluxo 1',
    '% to Flux 2': '% para Fluxo 2',
    'Flux 1 — to next node': 'Fluxo 1 — para nó seguinte',
    'Flux 2 — evacuated': 'Fluxo 2 — evacuado',
    'Dry flow [Nm³/h]': 'Vazão seca [Nm³/h]',
    'Wet flow [Nm³/h]': 'Vazão úmida [Nm³/h]',
    'Flue Gas Separator': 'Separador de gás de combustão',
    'Back to Flow': 'Voltar ao fluxo',
    'Send Data': 'Enviar dados',
  },
  zh: {
    'SEP12 Parameters': 'SEP12参数',
    'Clear memory': '清除内存',
    'SEP12 — 1 to 2 Separator': 'SEP12 — 1对2分离器',
    'Inlet stream': '入口流',
    'Total mass flow [kg/h]': '总质量流量 [kg/h]',
    'Split ratio': '分离比',
    '% to Flux 1': '% 至流量1',
    '% to Flux 2': '% 至流量2',
    'Flux 1 — to next node': '流量1 — 至下一节点',
    'Flux 2 — evacuated': '流量2 — 排出',
    'Dry flow [Nm³/h]': '干流量 [Nm³/h]',
    'Wet flow [Nm³/h]': '湿流量 [Nm³/h]',
    'Flue Gas Separator': '烟气分离器',
    'Back to Flow': '返回流程',
    'Send Data': '发送数据',
  },
  ja: {
    'SEP12 Parameters': 'SEP12パラメータ',
    'Clear memory': 'メモリをクリア',
    'SEP12 — 1 to 2 Separator': 'SEP12 — 1対2セパレータ',
    'Inlet stream': '入口流',
    'Total mass flow [kg/h]': '総質量流量 [kg/h]',
    'Split ratio': '分離比',
    '% to Flux 1': '% → 流れ1',
    '% to Flux 2': '% → 流れ2',
    'Flux 1 — to next node': '流れ1 — 次のノードへ',
    'Flux 2 — evacuated': '流れ2 — 排出',
    'Dry flow [Nm³/h]': '乾燥流量 [Nm³/h]',
    'Wet flow [Nm³/h]': '湿流量 [Nm³/h]',
    'Flue Gas Separator': '排ガスセパレータ',
    'Back to Flow': 'フローに戻る',
    'Send Data': 'データ送信',
  },
  ru: {
    'SEP12 Parameters': 'Параметры SEP12',
    'Clear memory': 'Очистить память',
    'SEP12 — 1 to 2 Separator': 'SEP12 — Сепаратор 1 в 2',
    'Inlet stream': 'Входной поток',
    'Total mass flow [kg/h]': 'Общий массовый расход [кг/ч]',
    'Split ratio': 'Коэффициент разделения',
    '% to Flux 1': '% в Поток 1',
    '% to Flux 2': '% в Поток 2',
    'Flux 1 — to next node': 'Поток 1 — к следующему узлу',
    'Flux 2 — evacuated': 'Поток 2 — отведён',
    'Dry flow [Nm³/h]': 'Сухой расход [Нм³/ч]',
    'Wet flow [Nm³/h]': 'Влажный расход [Нм³/ч]',
    'Flue Gas Separator': 'Сепаратор дымовых газов',
    'Back to Flow': 'Назад к схеме',
    'Send Data': 'Отправить данные',
  },
  ar: {
    'SEP12 Parameters': 'معاملات SEP12',
    'Clear memory': 'مسح الذاكرة',
    'SEP12 — 1 to 2 Separator': 'SEP12 — فاصل 1 إلى 2',
    'Inlet stream': 'تدفق الدخول',
    'Total mass flow [kg/h]': 'إجمالي تدفق الكتلة [كغ/س]',
    'Split ratio': 'نسبة الفصل',
    '% to Flux 1': '% إلى التدفق 1',
    '% to Flux 2': '% إلى التدفق 2',
    'Flux 1 — to next node': 'التدفق 1 — إلى العقدة التالية',
    'Flux 2 — evacuated': 'التدفق 2 — مُخلى',
    'Dry flow [Nm³/h]': 'التدفق الجاف [نم³/س]',
    'Wet flow [Nm³/h]': 'التدفق الرطب [نم³/س]',
    'Flue Gas Separator': 'فاصل غازات الدخان',
    'Back to Flow': 'العودة إلى التدفق',
    'Send Data': 'إرسال البيانات',
  },
};
