// WHB_traduction.js
export const translations = {
  fr: {
    // ===== COMMUNES =====
    calculationParameters: 'Paramètres de calcul',
    calculatedParameters: 'Paramètres calculés',
    resetValues: 'Réinitialiser les valeurs',
    resetDefaultValues: 'Réinitialiser aux valeurs par défaut',
    clearMemory: 'Vider la mémoire',
    export: 'Exporter',
    backToFlow: 'Retour au flux',
    sendData: 'Envoyer les données',
    rapport: 'Rapport',
    title: 'Configuration Chaudière de Récupération de Chaleur',

    stepMM: 'Pas de calcul',
    chaleurRecuperee: 'Chaleur récupérée',
    surfaceTotal: 'Surface totale',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Sans Turbine',
    sansTurbineDesc: 'Calcul des propriétés vapeur uniquement',
    contrepression: 'Contre-pression',
    contrepressionDesc: 'Extraction à une pression fixe',
    deuxEtages: '2 Étages',
    deuxEtagesDesc: 'Turbine à 2 étages de détente',
    troisEtages: '3 Étages',
    troisEtagesDesc: 'Turbine à 3 étages de détente',
    condensationVide: 'Condensation (Vide)',
    condensationVideDesc: 'Condensation sous vide',
    pressureLevelsConfiguration: 'Configuration des niveaux de pression',
    extractionConfiguration: 'Configuration des soutirages',
    totalFlows: 'Total des débits',
    quality: 'Titre',
    wetSteamWarning: 'Vapeur humide - Présence de gouttelettes d’eau',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Paramètres de calcul de la chaudière',
    flueGasCalculation: 'Calcul des gaz de combustion',
    feedWaterCalculation: 'Calcul de l’eau d’alimentation',
    steamCalculation: 'Calcul de la vapeur',
    drumParameters: 'Paramètres du ballon',
    boilerOutletTemperature: 'Température de sortie chaudière [°C]',
    estimatedThermalLoss: 'Pertes thermiques estimées [%]',
    feedwaterTemperature: 'Température de l’eau d’alimentation [°C]',
    steamType: 'Type de vapeur',
    superheatedSteamTemperature: 'Température vapeur surchauffée [°C]',
    boilerPressure: 'Pression chaudière [bar]',
    blowdownRate: 'Taux de purge [%]',
    saturated: 'Saturée',
    superheated: 'Surchauffée',
    flueGasTemperatureInlet: 'Température gaz d’entrée [°C]',
    flueGasEnthalpyIn: 'Enthalpie gaz d’entrée [kJ/h]',
    flueGasEnthalpyOut: 'Enthalpie gaz de sortie [kJ/h]',
    flueGasEnthalpyDifference: 'Différence enthalpie gaz [kJ/h]',
    feedwaterFlow: 'Débit eau d’alimentation [kg/h]',
    feedwaterPressure: 'Pression eau d’alimentation [bar]',
    blowdownMassFlow: 'Débit purge [kg/h]',
    enthalpyFeedwater: 'Enthalpie eau d’alimentation [kW]',
    saturatedSteamTemperature: 'Température vapeur saturante [°C]',
    deltaEnthalpies: 'Delta enthalpies gaz [kJ/h]',
    steamEnthalpy: 'Enthalpie vapeur [kJ/h]',
    steamFlow: 'Débit vapeur [kg/h]',
    ventFlashSteamDrum: 'Évacuation/flash ballon [kJ/h]',
    liquidRejected: 'Liquide rejeté [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Température gaz de sortie [°C]',
    ambiantAirTemperature: 'Température de l’air ambiant [°C]',
    volumeAirIngrease: 'Volume d’air d’apport [Nm³/h]',
    temperatureInletWHB: 'Température entrée WHB [°C]',
    temperatureOutletWHB: 'Température sortie WHB [°C]',
    flueGasComposition: 'Composition gaz de combustion',
    flueGasInlet: 'Gaz de combustion à l’entrée',
    flueGasOutlet: 'Gaz de combustion à la sortie',
    airIngrease: 'Apport d’air ambiant',
    flueGasOutletConsideringAirIngrease: 'Gaz de combustion sortie avec apport d’air',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Émissions polluantes',
    flyAshesContentOutlet: 'Teneur cendres volantes sortie [g/Nm³]',
    siccityBottomAsh: 'Siccité cendres lourdes [%]',
    o2Ref: 'O2 référence [%]',
    wasteFlow: 'Débit déchets [kg/h]',
    flueGasFlowWet: 'Débit gaz humide [Nm³/h]',
    flueGasFlowDry: 'Débit gaz sec [Nm³/h]',
    o2Calculated: 'O2 calculé [%]',
    inputFlueGas: 'Gaz de combustion d’entrée',
    outputFlueGas: 'Gaz de combustion de sortie',
    residuesCalculated: 'Résidus calculés',
    boilerAsh: 'Cendres chaudière [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Pertes de charge aérauliques',
    thermicalLossParameters: 'Paramètres de pertes thermiques',
    rotaryKilnDesign: 'Design du four rotatif',
    lanceEstimation: 'Estimation des lances',
    facadeCooling: 'Refroidissement façade',
    facadeThermicalLosses: 'Pertes thermiques façade',
    shellCooling: 'Refroidissement virole',
    sccDimensioning: 'Dimensionnement SCC',
    sccBurners: 'Brûleurs SCC',
    sccThermicalLosses: 'Pertes thermiques SCC',
    extractorConsumption: 'Consommation extracteur',
    combustionAirFan: 'Ventilateur air de combustion',
    extractorWaterEvaporation: 'Évaporation eau extracteur',
    poutMmce: 'Pression sortie [mmCE]',
    waterRecallConsumption: 'Rappel consommations eau',
    waterPurgeLosses: 'Pertes eau de purge [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Calculateur de production électrique',
    turbineVaporWithTaps: 'Turbine vapeur avec soutirages',
    estimationPerformances: 'Estimation des performances',
    turbineConfiguration: 'Configuration turbine',
    turbineType: 'Type de turbine',
    inletPressure: 'Pression d’entrée [bar]',
    inletTemperature: 'Température d’entrée [°C]',
    outletPressure: 'Pression de sortie [bar]',
    ambientTemperature: 'Température ambiante [°C]',
    efficiencyParameters: 'Paramètres de rendement',
    turbineEfficiency: 'Rendement turbine [%]',
    mechanicalEfficiency: 'Rendement mécanique [%]',
    generatorEfficiency: 'Rendement générateur [%]',
    pressureLevel1: 'Niveau 1 (Haute pression)',
    pressureLevel2: 'Niveau 2 (Pression moyenne)',
    pressureLevel3: 'Niveau 3 (Basse pression)',
    extraction1: 'Soutirage 1',
    extraction2: 'Soutirage 2',
    extraction3: 'Soutirage 3',
    performanceResults: 'Résultats de performance',
    steamVaporProperties: 'Propriétés de la vapeur d’entrée',
    inletEnthalpy: 'Enthalpie d’entrée',
    inletEntropy: 'Entropie d’entrée',
    saturationTemperature: 'Température de saturation',
    superheating: 'Surchauffe',
    electricPower: 'Puissance électrique',
    mechanicalPower: 'Puissance mécanique',
    specificWork: 'Travail spécifique',
    specificConsumption: 'Consommation spécifique',
    globalEfficiency: 'Rendement global',
    expansionRatio: 'Rapport de détente',
    carnotEfficiency: 'Efficacité Carnot',
    remainingFlow: 'Débit restant',
    extractionDetails: 'Détails des soutirages',
    performanceCurves: 'Courbes de performance en fonction du débit',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Calculateur chaudière tubes d’eau',
    dimensioningEN12952: 'Dimensionnement selon EN 12952-3',
    basicData: 'Données de base',
    serviceTemperature: 'Température de service [°C]',
    servicePressure : 'Pression de service [bar]',
    vaporFlow: 'Débit vapeur [kg/h]',
    feedwaterTemp: 'Température eau alimentation [°C]',
    wasteHHV: 'PCI déchets [MJ/kg]',
    combustionEfficiency: 'Rendement combustion [%]',
    materialCharacteristics: 'Caractéristiques matériaux',
    material: 'Matériau',
    admissibleStress: 'Contrainte admissible [N/mm²]',
    weldingCoefficient: 'Coefficient soudure',
    corrosionAllowance: 'Supplément corrosion [mm]',
    bodyGeometry: 'Géométrie du corps',
    bodyInnerDiameter: 'Diamètre intérieur corps [mm]',
    bodyLength: 'Longueur corps [mm]',
    tubeNumber: 'Nombre de tubes',
    tubeOuterDiameter: 'Diamètre extérieur tubes [mm]',
    tubeInnerDiameter: 'Diamètre intérieur tubes [mm]',
    checks: 'Vérifications',
    mainResults: 'Résultats principaux',
    calculationPressure: 'Pression de calcul',
    bodyThickness: 'Épaisseur corps',
    tubeThickness: 'Épaisseur tubes',
    steamPower: 'Puissance vapeur',
    errorMessage: 'Erreur : ',
    conformityCheck: 'Dimensionnement conforme aux exigences EN 12952-3',
    warningThickness: 'Épaisseur corps < 6 mm - Vérifier épaisseur minimale',
    warningFluxDensity: 'Densité de flux élevée - Risque d’encrassement',
    errorVelocity: 'Vitesse excessive - Risque d’érosion critique',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Configuration Chaudière de Récupération de Chaleur',
    steamParameters: 'Paramètres vapeur',
    flueGases: 'Gaz de combustion',
    steamValorization: 'Valorisation vapeur',
    whbDesign: 'Design WHB',
    whbOpex: 'Opex WHB',
    boilerDimensioning: 'Dimensionnement chaudière',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Chaudière de récupération (WHB) — Rapport de synthèse',
    steamProduction: 'Production de vapeur',
    steamPressure: 'Pression vapeur [bar]',
    steamTemperature: 'Température vapeur [°C]',
    boilerBlowdown: 'Purge chaudière [kg/h]',
    flashDrumSteam: 'Flash drum vapeur [kg/h]',
    temperatures: 'Températures',
    flueGasInletTemp: 'Température entrée fumées [°C]',
    flueGasOutletTemp: 'Température sortie fumées [°C]',
    o2Measured: 'O₂ mesuré (sec)',
    wetFlowTotal: 'Débit humide total [kg/h]',
    dryFlow: 'Débit sec [Nm³/h]',
    wetFlow: 'Débit humide [Nm³/h]',
    outletGasComposition: 'Composition gaz de sortie',
    netProduction: 'Production nette',
    netSteamProduced: 'Vapeur nette produite [kg/h]',
    recoveredPower: 'Puissance récupérée [kW]',
    turbineValorization: 'Turbine / Valorisation',
    electricConsumptions: 'Consommations électriques',
    dataNotAvailableDesign: "Données non disponibles (ouvrir l'onglet Design)",
    hourlyCosts: 'Coûts horaires',
    opexNotAvailable: 'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.',
    electricity: 'Électricité',
    water: 'Eau',
    totalCost: 'Total coût',
    hourlyCost: 'Coût horaire',
    annualCost: 'Coût annuel',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ électricité',
    totalCO2kgh: 'Total CO₂',
    reportGenerated: 'Rapport généré automatiquement',
    consumer: 'Consommateur',
    total: 'Total',
  },

  en: {
    // ===== COMMONS =====
    calculationParameters: 'Calculation Parameters',
    calculatedParameters: 'Calculated Parameters',
    resetValues: 'Reset Values',
    resetDefaultValues: 'Reset to Default Values',
    clearMemory: 'Clear Memory',
    export: 'Export',
    backToFlow: 'Back to Flow',
    sendData: 'Send Data',
    title: 'Waste Heat Boiler Configuration',

    stepMM: 'Calculation step [mm]',
    chaleurRecuperee: 'Heat recovered [kW]',
    surfaceTotal: 'Total exchange surface [m²]',

    // ===== VALORIZATION =====
    sansTurbine: 'No Turbine',
    sansTurbineDesc: 'Steam properties calculation only',
    contrepression: 'Back Pressure',
    contrepressionDesc: 'Extraction at fixed pressure',
    deuxEtages: '2 Stages',
    deuxEtagesDesc: 'Turbine with 2 expansion stages',
    troisEtages: '3 Stages',
    troisEtagesDesc: 'Turbine with 3 expansion stages',
    condensationVide: 'Condensation (Vacuum)',
    condensationVideDesc: 'Vacuum condensation',
    pressureLevelsConfiguration: 'Pressure Levels Configuration',
    extractionConfiguration: 'Extraction Configuration',
    totalFlows: 'Total flows',
    quality: 'Quality',
    wetSteamWarning: 'Wet steam - Presence of water droplets',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Boiler Calculation Parameters',
    flueGasCalculation: 'Flue Gas Calculation',
    feedWaterCalculation: 'Feed Water Calculation',
    steamCalculation: 'Steam Calculation',
    drumParameters: 'Drum Parameters',
    boilerOutletTemperature: 'Boiler Outlet Temperature [°C]',
    estimatedThermalLoss: 'Estimated Thermal Loss [%]',
    feedwaterTemperature: 'Feedwater Temperature [°C]',
    steamType: 'Steam Type',
    superheatedSteamTemperature: 'Superheated Steam Temperature [°C]',
    boilerPressure: 'Boiler Pressure [bar]',
    blowdownRate: 'Blowdown Rate [%]',
    saturated: 'Saturated',
    superheated: 'Superheated',
    flueGasTemperatureInlet: 'Flue gas temperature inlet [°C]',
    flueGasEnthalpyIn: 'Flue gas enthalpy in [kJ/h]',
    flueGasEnthalpyOut: 'Flue gas enthalpy out [kJ/h]',
    flueGasEnthalpyDifference: 'Flue gas enthalpy in - out [kJ/h]',
    feedwaterFlow: 'Feedwater Flow [kg/h]',
    feedwaterPressure: 'Feedwater Pressure [bar]',
    blowdownMassFlow: 'Blowdown Mass Flow [kg/h]',
    enthalpyFeedwater: 'Enthalpy feedwater [kW]',
    saturatedSteamTemperature: 'Saturated steam temperature [°C]',
    deltaEnthalpies: 'Delta enthalpies flue gases [kJ/h]',
    steamEnthalpy: 'Steam enthalpy [kJ/h]',
    steamFlow: 'Steam Flow [kg/h]',
    ventFlashSteamDrum: 'Vent/flash steam drum [kJ/h]',
    liquidRejected: 'Liquid rejected [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Flue gas temperature outlet [°C]',
    ambiantAirTemperature: 'Ambient air temperature [°C]',
    volumeAirIngrease: 'Volume of air increase [Nm³/h]',
    temperatureInletWHB: 'Temperature inlet WHB [°C]',
    temperatureOutletWHB: 'Temperature outlet WHB [°C]',
    flueGasComposition: 'Flue gas composition',
    flueGasInlet: 'Flue gas inlet at inlet temperature',
    flueGasOutlet: 'Flue gas outlet at outlet temperature',
    airIngrease: 'Air increase at ambient temperature',
    flueGasOutletConsideringAirIngrease: 'Flue gas at outlet temperature considering air increase',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Pollutant Emissions',
    flyAshesContentOutlet: 'Fly ashes content outlet [g/Nm³]',
    siccityBottomAsh: 'Siccity bottom ash [%]',
    o2Ref: 'O2 ref [%]',
    wasteFlow: 'Waste Flow [kg/h]',
    flueGasFlowWet: 'Flue Gas Flow (Wet) [Nm³/h]',
    flueGasFlowDry: 'Flue Gas Flow (Dry) [Nm³/h]',
    o2Calculated: 'O2 calculated [%]',
    inputFlueGas: 'Input flue gas',
    outputFlueGas: 'Output flue gas',
    residuesCalculated: 'Residues calculated',
    boilerAsh: 'Boiler ash [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Aeraulic Pressure Loss',
    thermicalLossParameters: 'Thermal Loss Parameters',
    rotaryKilnDesign: 'Rotary Kiln Design',
    lanceEstimation: 'Lance Estimation',
    facadeCooling: 'Facade Cooling',
    facadeThermicalLosses: 'Facade Thermal Losses',
    shellCooling: 'Shell Cooling',
    sccDimensioning: 'SCC Dimensioning',
    sccBurners: 'SCC Burners',
    sccThermicalLosses: 'SCC Thermal Losses',
    extractorConsumption: 'Extractor Consumption',
    combustionAirFan: 'Combustion Air Fan',
    extractorWaterEvaporation: 'Extractor Water Evaporation',
    poutMmce: 'Outlet Pressure [mmCE]',
    waterRecallConsumption: 'Recall of water consumptions',
    waterPurgeLosses: 'Water purge losses [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Electrical Production Calculator',
    turbineVaporWithTaps: 'Steam Turbine with Extractions',
    estimationPerformances: 'Performance Estimation',
    turbineConfiguration: 'Turbine Configuration',
    turbineType: 'Turbine Type',
    inletPressure: 'Inlet Pressure [bar]',
    inletTemperature: 'Inlet Temperature [°C]',
    outletPressure: 'Outlet Pressure [bar]',
    ambientTemperature: 'Ambient Temperature [°C]',
    efficiencyParameters: 'Efficiency Parameters',
    turbineEfficiency: 'Turbine Efficiency [%]',
    mechanicalEfficiency: 'Mechanical Efficiency [%]',
    generatorEfficiency: 'Generator Efficiency [%]',
    pressureLevel1: 'Level 1 (High Pressure)',
    pressureLevel2: 'Level 2 (Medium Pressure)',
    pressureLevel3: 'Level 3 (Low Pressure)',
    extraction1: 'Extraction 1',
    extraction2: 'Extraction 2',
    extraction3: 'Extraction 3',
    performanceResults: 'Performance Results',
    steamVaporProperties: 'Steam Vapor Properties at Inlet',
    inletEnthalpy: 'Inlet Enthalpy',
    inletEntropy: 'Inlet Entropy',
    saturationTemperature: 'Saturation Temperature',
    superheating: 'Superheating',
    electricPower: 'Electric Power',
    mechanicalPower: 'Mechanical Power',
    specificWork: 'Specific Work',
    specificConsumption: 'Specific Consumption',
    globalEfficiency: 'Global Efficiency',
    expansionRatio: 'Expansion Ratio',
    carnotEfficiency: 'Carnot Efficiency',
    remainingFlow: 'Remaining Flow',
    extractionDetails: 'Extraction Details',
    performanceCurves: 'Performance Curves as Function of Flow',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Water Tube Boiler Calculator',
    dimensioningEN12952: 'Dimensioning according to EN 12952-3',
    basicData: 'Basic Data',
    serviceTemperature: 'Service Temperature [°C]',
    servicePressure : 'Service Pressure [bar]',
    vaporFlow: 'Steam Flow [kg/h]',
    feedwaterTemp: 'Feedwater Temperature [°C]',
    wasteHHV: 'Waste HHV [MJ/kg]',
    combustionEfficiency: 'Combustion Efficiency [%]',
    materialCharacteristics: 'Material Characteristics',
    material: 'Material',
    admissibleStress: 'Admissible Stress [N/mm²]',
    weldingCoefficient: 'Welding Coefficient',
    corrosionAllowance: 'Corrosion Allowance [mm]',
    bodyGeometry: 'Body Geometry',
    bodyInnerDiameter: 'Body Inner Diameter [mm]',
    bodyLength: 'Body Length [mm]',
    tubeNumber: 'Number of Tubes',
    tubeOuterDiameter: 'Tube Outer Diameter [mm]',
    tubeInnerDiameter: 'Tube Inner Diameter [mm]',
    checks: 'Checks',
    mainResults: 'Main Results',
    calculationPressure: 'Calculation Pressure',
    bodyThickness: 'Body Thickness',
    tubeThickness: 'Tube Thickness',
    steamPower: 'Steam Power',
    errorMessage: 'Error: ',
    conformityCheck: 'Design compliant with EN 12952-3 requirements',
    warningThickness: 'Body thickness < 6 mm - Verify minimum thickness',
    warningFluxDensity: 'High flux density - Fouling risk',
    errorVelocity: 'Excessive velocity - Critical erosion risk',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Waste Heat Boiler Configuration',
    steamParameters: 'Steam Parameters',
    flueGases: 'Flue Gases',
    steamValorization: 'Steam Valorization',
    whbDesign: 'WHB Design',
    whbOpex: 'WHB Opex',
    boilerDimensioning: 'Boiler Dimensioning',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Waste Heat Boiler (WHB) — Synthesis Report',
    steamProduction: 'Steam Production',
    steamPressure: 'Steam Pressure [bar]',
    steamTemperature: 'Steam Temperature [°C]',
    boilerBlowdown: 'Boiler Blowdown [kg/h]',
    flashDrumSteam: 'Flash Drum Steam [kg/h]',
    temperatures: 'Temperatures',
    flueGasInletTemp: 'Flue Gas Inlet Temperature [°C]',
    flueGasOutletTemp: 'Flue Gas Outlet Temperature [°C]',
    o2Measured: 'O₂ measured (dry)',
    wetFlowTotal: 'Total wet flow [kg/h]',
    dryFlow: 'Dry flow [Nm³/h]',
    wetFlow: 'Wet flow [Nm³/h]',
    outletGasComposition: 'Outlet gas composition',
    netProduction: 'Net Production',
    netSteamProduced: 'Net steam produced [kg/h]',
    recoveredPower: 'Recovered power [kW]',
    turbineValorization: 'Turbine / Valorization',
    electricConsumptions: 'Electrical consumptions',
    dataNotAvailableDesign: 'Data not available (open Design tab)',
    hourlyCosts: 'Hourly costs',
    opexNotAvailable: 'OPEX costs not available — open Design and OPEX tabs.',
    electricity: 'Electricity',
    water: 'Water',
    totalCost: 'Total cost',
    hourlyCost: 'Hourly cost',
    annualCost: 'Annual cost',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricity',
    totalCO2kgh: 'Total CO₂',
    reportGenerated: 'Automatically generated report',
    consumer: 'Consumer',
    total: 'Total',
  },



  de: {
    // ===== COMMUNES =====
    calculationParameters: 'Berechnungsparameter',
    calculatedParameters: 'Berechnete Parameter',
    resetValues: 'Werte zurücksetzen',
    resetDefaultValues: 'Auf Standardwerte zurücksetzen',
    clearMemory: 'Speicher löschen',
    export: 'Exportieren',
    backToFlow: 'Zurück zum Fluss',
    sendData: 'Daten senden',
    title: 'Abwärmekessel-Konfiguration',

    stepMM: 'Berechnungsschritt [mm]',
    chaleurRecuperee: 'Rückgewonnene Wärmeleistung [kW]',
    surfaceTotal: 'Gesamtaustauschfläche [m²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Ohne Turbine',
    sansTurbineDesc: 'Nur Dampfeigenschaften-Berechnung',
    contrepression: 'Gegendruckturbine',
    contrepressionDesc: 'Entnahme bei festem Druck',
    deuxEtages: '2 Stufen',
    deuxEtagesDesc: 'Turbine mit 2 Expansionsstufen',
    troisEtages: '3 Stufen',
    troisEtagesDesc: 'Turbine mit 3 Expansionsstufen',
    condensationVide: 'Kondensation (Vakuum)',
    condensationVideDesc: 'Untervakuum-Kondensation',
    pressureLevelsConfiguration: 'Konfiguration der Druckstufen',
    extractionConfiguration: 'Konfiguration der Entnahmen',
    totalFlows: 'Gesamtmassenströme',
    quality: 'Qualität',
    wetSteamWarning: 'Nassdampf - Wassertröpfchen vorhanden',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Kesselberechnungsparameter',
    flueGasCalculation: 'Rauchgasberechnung',
    feedWaterCalculation: 'Speisewasserberechnung',
    steamCalculation: 'Dampfberechnung',
    drumParameters: 'Trommelparameter',
    boilerOutletTemperature: 'Kesselausgangstemperatur [°C]',
    estimatedThermalLoss: 'Geschätzte Wärmeverluste [%]',
    feedwaterTemperature: 'Speisewassertemperatur [°C]',
    steamType: 'Dampfart',
    superheatedSteamTemperature: 'Überhitzter Dampf Temperatur [°C]',
    boilerPressure: 'Kesseldruck [bar]',
    blowdownRate: 'Absperrrate [%]',
    saturated: 'Satt',
    superheated: 'Überhitzt',
    flueGasTemperatureInlet: 'Rauchgastemperatur Eingang [°C]',
    flueGasEnthalpyIn: 'Rauchgasenthalpie Eingang [kJ/h]',
    flueGasEnthalpyOut: 'Rauchgasenthalpie Ausgang [kJ/h]',
    flueGasEnthalpyDifference: 'Differenz Rauchgasenthalpie [kJ/h]',
    feedwaterFlow: 'Speisewassermassenstrom [kg/h]',
    feedwaterPressure: 'Speisewasserdruck [bar]',
    blowdownMassFlow: 'Absperrwassermassenstrom [kg/h]',
    enthalpyFeedwater: 'Speisewasser-Enthalpie [kW]',
    saturatedSteamTemperature: 'Sattdampftemperatur [°C]',
    deltaEnthalpies: 'Delta Rauchgasenthalpien [kJ/h]',
    steamEnthalpy: 'Dampfenthalpie [kJ/h]',
    steamFlow: 'Dampfmassenstrom [kg/h]',
    ventFlashSteamDrum: 'Entlüftung/Blitzentladeung Trommel [kJ/h]',
    liquidRejected: 'Flüssigkeit ausgestoßen [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Rauchgastemperatur Ausgang [°C]',
    ambiantAirTemperature: 'Umgebungslufttemperatur [°C]',
    volumeAirIngrease: 'Luftzugabevolumen [Nm³/h]',
    temperatureInletWHB: 'Temperatur Eingang Abwärmekessel [°C]',
    temperatureOutletWHB: 'Temperatur Ausgang Abwärmekessel [°C]',
    flueGasComposition: 'Rauchgaszusammensetzung',
    flueGasInlet: 'Rauchgas beim Eingang',
    flueGasOutlet: 'Rauchgas beim Ausgang',
    airIngrease: 'Luftzugabe bei Umgebungstemperatur',
    flueGasOutletConsideringAirIngrease: 'Rauchgas beim Ausgang mit Luftzugabe',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Schadstoffemissionen',
    flyAshesContentOutlet: 'Flugaschegehalt Ausgang [g/Nm³]',
    siccityBottomAsh: 'Trockenheit Bodenteile [%]',
    o2Ref: 'O2 Referenz [%]',
    wasteFlow: 'Abfallmassenstrom [kg/h]',
    flueGasFlowWet: 'Rauchgasmassenstrom (Nass) [Nm³/h]',
    flueGasFlowDry: 'Rauchgasmassenstrom (Trocken) [Nm³/h]',
    o2Calculated: 'O2 berechnet [%]',
    inputFlueGas: 'Eingangsrauchgas',
    outputFlueGas: 'Ausgangsrauchgas',
    residuesCalculated: 'Berechnete Rückstände',
    boilerAsh: 'Kesselasche [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Aerodynamischer Druckverlust',
    thermicalLossParameters: 'Wärmeverlustparameter',
    rotaryKilnDesign: 'Drehofen-Design',
    lanceEstimation: 'Lanzenschätzung',
    facadeCooling: 'Fassadenkühlung',
    facadeThermicalLosses: 'Fassaden-Wärmeverluste',
    shellCooling: 'Manttelkühlung',
    sccDimensioning: 'SCC-Dimensionierung',
    sccBurners: 'SCC-Brenner',
    sccThermicalLosses: 'SCC-Wärmeverluste',
    extractorConsumption: 'Extraktor-Stromverbrauch',
    combustionAirFan: 'Verbrennungslüfter',
    extractorWaterEvaporation: 'Extraktor-Wasserverdampfung',
    poutMmce: 'Ausgangsdruck [mmWS]',
    waterRecallConsumption: 'Rückruf Wasserverbräuche',
    waterPurgeLosses: 'Spülwasserverluste [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Stromproduktionsrechner',
    turbineVaporWithTaps: 'Dampfturbine mit Entnahmen',
    estimationPerformances: 'Leistungsschätzung',
    turbineConfiguration: 'Turbinenkonfiguration',
    turbineType: 'Turbinentyp',
    inletPressure: 'Eingangsdruck [bar]',
    inletTemperature: 'Eingangstemperatur [°C]',
    outletPressure: 'Ausgangsdruck [bar]',
    ambientTemperature: 'Umgebungstemperatur [°C]',
    efficiencyParameters: 'Wirkungsgradparameter',
    turbineEfficiency: 'Turbinenwirkungsgrad [%]',
    mechanicalEfficiency: 'Mechanischer Wirkungsgrad [%]',
    generatorEfficiency: 'Generatorwirkungsgrad [%]',
    pressureLevel1: 'Stufe 1 (Hochdruck)',
    pressureLevel2: 'Stufe 2 (Mitteldruck)',
    pressureLevel3: 'Stufe 3 (Niederdruck)',
    extraction1: 'Entnahme 1',
    extraction2: 'Entnahme 2',
    extraction3: 'Entnahme 3',
    performanceResults: 'Leistungsergebnisse',
    steamVaporProperties: 'Dampfeigenschaften beim Eingang',
    inletEnthalpy: 'Eingangsenthalpie',
    inletEntropy: 'Eingangsentropie',
    saturationTemperature: 'Sättigungstemperatur',
    superheating: 'Überhitzung',
    electricPower: 'Elektrische Leistung',
    mechanicalPower: 'Mechanische Leistung',
    specificWork: 'Spezifische Arbeit',
    specificConsumption: 'Spezifischer Verbrauch',
    globalEfficiency: 'Gesamtwirkungsgrad',
    expansionRatio: 'Expansionsverhältnis',
    carnotEfficiency: 'Carnot-Effizienz',
    remainingFlow: 'Verbleibender Massenstrom',
    extractionDetails: 'Entnahmedetails',
    performanceCurves: 'Leistungskurven in Abhängigkeit vom Massenstrom',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Wasserrohr-Kesselrechner',
    dimensioningEN12952: 'Bemessung nach EN 12952-3',
    basicData: 'Grunddaten',
    serviceTemperature: 'Betriebstemperatur [°C]',
    servicePressure : 'Betriebsdruck [bar]',
    vaporFlow: 'Dampfmassenstrom [kg/h]',
    feedwaterTemp: 'Speisewassertemperatur [°C]',
    wasteHHV: 'Abfall OCV [MJ/kg]',
    combustionEfficiency: 'Verbrennungswirkungsgrad [%]',
    materialCharacteristics: 'Materialeigenschaften',
    material: 'Material',
    admissibleStress: 'Zulässige Spannung [N/mm²]',
    weldingCoefficient: 'Schweißkoeffizient',
    corrosionAllowance: 'Korrosionszuschlag [mm]',
    bodyGeometry: 'Körpergeometrie',
    bodyInnerDiameter: 'Innendurchmesser des Körpers [mm]',
    bodyLength: 'Körperlänge [mm]',
    tubeNumber: 'Anzahl der Rohre',
    tubeOuterDiameter: 'Außendurchmesser der Rohre [mm]',
    tubeInnerDiameter: 'Innendurchmesser der Rohre [mm]',
    checks: 'Überprüfungen',
    mainResults: 'Hauptergebnisse',
    calculationPressure: 'Berechnungsdruck',
    bodyThickness: 'Körperdicke',
    tubeThickness: 'Rohrdicke',
    steamPower: 'Dampfleistung',
    errorMessage: 'Fehler: ',
    conformityCheck: 'Bemessung gemäß EN 12952-3 Anforderungen konform',
    warningThickness: 'Körperdicke < 6 mm - Mindestdicke überprüfen',
    warningFluxDensity: 'Hohe Flussdichte - Verschmutzungsrisiko',
    errorVelocity: 'Übermäßige Geschwindigkeit - Kritisches Erosionsrisiko',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Abwärmekessel-Konfiguration',
    steamParameters: 'Dampfparameter',
    flueGases: 'Rauchgase',
    steamValorization: 'Dampfverwertung',
    whbDesign: 'Abwärmekessel-Design',
    whbOpex: 'Abwärmekessel-Betriebskosten',
    boilerDimensioning: 'Kesselbemessung',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Abhitzekessel (WHB) — Synthesebericht',
    steamProduction: 'Dampferzeugung',
    steamPressure: 'Dampfdruck [bar]',
    steamTemperature: 'Dampftemperatur [°C]',
    boilerBlowdown: 'Kesselentleerung [kg/h]',
    flashDrumSteam: 'Entspannungstrommel [kg/h]',
    temperatures: 'Temperaturen',
    flueGasInletTemp: 'Rauchgaseingangstemperatur [°C]',
    flueGasOutletTemp: 'Rauchgasausgangstemperatur [°C]',
    o2Measured: 'O₂ gemessen (trocken)',
    wetFlowTotal: 'Gesamter Feuchtstrom [kg/h]',
    dryFlow: 'Trockenstrom [Nm³/h]',
    wetFlow: 'Feuchtgasstrom [Nm³/h]',
    outletGasComposition: 'Ausgangsgaszusammensetzung',
    netProduction: 'Nettoproduktion',
    netSteamProduced: 'Netto produzierter Dampf [kg/h]',
    recoveredPower: 'Rückgewonnene Leistung [kW]',
    turbineValorization: 'Turbine / Verwertung',
    electricConsumptions: 'Stromverbräuche',
    dataNotAvailableDesign: 'Daten nicht verfügbar (Design-Registerkarte öffnen)',
    hourlyCosts: 'Stündliche Kosten',
    opexNotAvailable: 'OPEX-Kosten nicht verfügbar — Design- und OPEX-Registerkarten öffnen.',
    electricity: 'Elektrizität',
    water: 'Wasser',
    totalCost: 'Gesamtkosten',
    hourlyCost: 'Stündliche Kosten',
    annualCost: 'Jährliche Kosten',
    totalCO2: 'Gesamt CO₂ [kg/h]',
    co2Electricity: 'CO₂ Elektrizität',
    totalCO2kgh: 'Gesamt CO₂',
    reportGenerated: 'Automatisch generierter Bericht',
    consumer: 'Verbraucher',
    total: 'Gesamt',
  },




  es: {
    // ===== COMMUNES =====
    calculationParameters: 'Parámetros de cálculo',
    calculatedParameters: 'Parámetros calculados',
    resetValues: 'Restablecer valores',
    resetDefaultValues: 'Restablecer valores predeterminados',
    clearMemory: 'Limpiar memoria',
    export: 'Exportar',
    backToFlow: 'Volver al flujo',
    sendData: 'Enviar datos',
    title: 'Configuración de Caldera de Recuperación de Calor',

    stepMM: 'Paso de cálculo [mm]',
    chaleurRecuperee: 'Calor recuperado [kW]',
    surfaceTotal: 'Superficie total de intercambio [m²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Sin turbina',
    sansTurbineDesc: 'Solo cálculo de propiedades del vapor',
    contrepression: 'Contrapresión',
    contrepressionDesc: 'Extracción a presión fija',
    deuxEtages: '2 Etapas',
    deuxEtagesDesc: 'Turbina con 2 etapas de expansión',
    troisEtages: '3 Etapas',
    troisEtagesDesc: 'Turbina con 3 etapas de expansión',
    condensationVide: 'Condensación (Vacío)',
    condensationVideDesc: 'Condensación al vacío',
    pressureLevelsConfiguration: 'Configuración de niveles de presión',
    extractionConfiguration: 'Configuración de extracciones',
    totalFlows: 'Caudales totales',
    quality: 'Calidad',
    wetSteamWarning: 'Vapor húmedo - Presencia de gotitas de agua',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Parámetros de cálculo de la caldera',
    flueGasCalculation: 'Cálculo de gases de combustión',
    feedWaterCalculation: 'Cálculo de agua de alimentación',
    steamCalculation: 'Cálculo de vapor',
    drumParameters: 'Parámetros del tambor',
    boilerOutletTemperature: 'Temperatura de salida de la caldera [°C]',
    estimatedThermalLoss: 'Pérdidas térmicas estimadas [%]',
    feedwaterTemperature: 'Temperatura de agua de alimentación [°C]',
    steamType: 'Tipo de vapor',
    superheatedSteamTemperature: 'Temperatura de vapor sobrecalentado [°C]',
    boilerPressure: 'Presión de la caldera [bar]',
    blowdownRate: 'Tasa de purga [%]',
    saturated: 'Saturado',
    superheated: 'Sobrecalentado',
    flueGasTemperatureInlet: 'Temperatura gases de entrada [°C]',
    flueGasEnthalpyIn: 'Entalpía gases de entrada [kJ/h]',
    flueGasEnthalpyOut: 'Entalpía gases de salida [kJ/h]',
    flueGasEnthalpyDifference: 'Diferencia entalpía gases [kJ/h]',
    feedwaterFlow: 'Caudal de agua de alimentación [kg/h]',
    feedwaterPressure: 'Presión de agua de alimentación [bar]',
    blowdownMassFlow: 'Caudal másico de purga [kg/h]',
    enthalpyFeedwater: 'Entalpía agua de alimentación [kW]',
    saturatedSteamTemperature: 'Temperatura de vapor saturado [°C]',
    deltaEnthalpies: 'Delta entalpías gases [kJ/h]',
    steamEnthalpy: 'Entalpía del vapor [kJ/h]',
    steamFlow: 'Caudal de vapor [kg/h]',
    ventFlashSteamDrum: 'Ventilación/vapor flash tambor [kJ/h]',
    liquidRejected: 'Líquido rechazado [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Temperatura gases de salida [°C]',
    ambiantAirTemperature: 'Temperatura del aire ambiente [°C]',
    volumeAirIngrease: 'Volumen de aire de aporte [Nm³/h]',
    temperatureInletWHB: 'Temperatura entrada caldera recuperación [°C]',
    temperatureOutletWHB: 'Temperatura salida caldera recuperación [°C]',
    flueGasComposition: 'Composición de gases de combustión',
    flueGasInlet: 'Gases de combustión a la entrada',
    flueGasOutlet: 'Gases de combustión a la salida',
    airIngrease: 'Aporte de aire ambiente',
    flueGasOutletConsideringAirIngrease: 'Gases de combustión salida considerando aporte de aire',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Emisiones contaminantes',
    flyAshesContentOutlet: 'Contenido de cenizas volantes salida [g/Nm³]',
    siccityBottomAsh: 'Contenido de humedad cenizas pesadas [%]',
    o2Ref: 'O2 referencia [%]',
    wasteFlow: 'Caudal de residuos [kg/h]',
    flueGasFlowWet: 'Caudal de gases húmedo [Nm³/h]',
    flueGasFlowDry: 'Caudal de gases seco [Nm³/h]',
    o2Calculated: 'O2 calculado [%]',
    inputFlueGas: 'Gases de combustión entrada',
    outputFlueGas: 'Gases de combustión salida',
    residuesCalculated: 'Residuos calculados',
    boilerAsh: 'Cenizas caldera [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Pérdida de carga aerodinámica',
    thermicalLossParameters: 'Parámetros de pérdidas térmicas',
    rotaryKilnDesign: 'Diseño del horno rotatorio',
    lanceEstimation: 'Estimación de lanzas',
    facadeCooling: 'Enfriamiento de fachada',
    facadeThermicalLosses: 'Pérdidas térmicas de fachada',
    shellCooling: 'Enfriamiento de carcasa',
    sccDimensioning: 'Dimensionamiento SCC',
    sccBurners: 'Quemadores SCC',
    sccThermicalLosses: 'Pérdidas térmicas SCC',
    extractorConsumption: 'Consumo del extractor',
    combustionAirFan: 'Ventilador de aire de combustión',
    extractorWaterEvaporation: 'Evaporación de agua del extractor',
    poutMmce: 'Presión de salida [mmCA]',
    waterRecallConsumption: 'Recuerdo de consumos de agua',
    waterPurgeLosses: 'Pérdidas de agua de purga [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Calculadora de producción eléctrica',
    turbineVaporWithTaps: 'Turbina de vapor con extracciones',
    estimationPerformances: 'Estimación de rendimientos',
    turbineConfiguration: 'Configuración de la turbina',
    turbineType: 'Tipo de turbina',
    inletPressure: 'Presión de entrada [bar]',
    inletTemperature: 'Temperatura de entrada [°C]',
    outletPressure: 'Presión de salida [bar]',
    ambientTemperature: 'Temperatura ambiente [°C]',
    efficiencyParameters: 'Parámetros de rendimiento',
    turbineEfficiency: 'Rendimiento de la turbina [%]',
    mechanicalEfficiency: 'Rendimiento mecánico [%]',
    generatorEfficiency: 'Rendimiento del generador [%]',
    pressureLevel1: 'Nivel 1 (Alta presión)',
    pressureLevel2: 'Nivel 2 (Presión media)',
    pressureLevel3: 'Nivel 3 (Baja presión)',
    extraction1: 'Extracción 1',
    extraction2: 'Extracción 2',
    extraction3: 'Extracción 3',
    performanceResults: 'Resultados de rendimiento',
    steamVaporProperties: 'Propiedades del vapor a la entrada',
    inletEnthalpy: 'Entalpía de entrada',
    inletEntropy: 'Entropía de entrada',
    saturationTemperature: 'Temperatura de saturación',
    superheating: 'Sobrecalentamiento',
    electricPower: 'Potencia eléctrica',
    mechanicalPower: 'Potencia mecánica',
    specificWork: 'Trabajo específico',
    specificConsumption: 'Consumo específico',
    globalEfficiency: 'Rendimiento global',
    expansionRatio: 'Ratio de expansión',
    carnotEfficiency: 'Eficiencia de Carnot',
    remainingFlow: 'Caudal restante',
    extractionDetails: 'Detalles de extracciones',
    performanceCurves: 'Curvas de rendimiento en función del caudal',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Calculadora de caldera de tubos de agua',
    dimensioningEN12952: 'Dimensionamiento según EN 12952-3',
    basicData: 'Datos básicos',
    serviceTemperature: 'Temperatura de servicio [°C]',
    servicePressure : 'Presión de servicio [bar]',
    vaporFlow: 'Caudal de vapor [kg/h]',
    feedwaterTemp: 'Temperatura de agua de alimentación [°C]',
    wasteHHV: 'PCS residuos [MJ/kg]',
    combustionEfficiency: 'Rendimiento de combustión [%]',
    materialCharacteristics: 'Características de materiales',
    material: 'Material',
    admissibleStress: 'Tensión admisible [N/mm²]',
    weldingCoefficient: 'Coeficiente de soldadura',
    corrosionAllowance: 'Tolerancia por corrosión [mm]',
    bodyGeometry: 'Geometría del cuerpo',
    bodyInnerDiameter: 'Diámetro interior del cuerpo [mm]',
    bodyLength: 'Longitud del cuerpo [mm]',
    tubeNumber: 'Número de tubos',
    tubeOuterDiameter: 'Diámetro exterior de los tubos [mm]',
    tubeInnerDiameter: 'Diámetro interior de los tubos [mm]',
    checks: 'Verificaciones',
    mainResults: 'Resultados principales',
    calculationPressure: 'Presión de cálculo',
    bodyThickness: 'Espesor del cuerpo',
    tubeThickness: 'Espesor de los tubos',
    steamPower: 'Potencia de vapor',
    errorMessage: 'Error: ',
    conformityCheck: 'Dimensionamiento conforme a los requisitos EN 12952-3',
    warningThickness: 'Espesor del cuerpo < 6 mm - Verificar espesor mínimo',
    warningFluxDensity: 'Densidad de flujo alta - Riesgo de incrustación',
    errorVelocity: 'Velocidad excesiva - Riesgo de erosión crítica',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Configuración de caldera de recuperación de calor',
    steamParameters: 'Parámetros de vapor',
    flueGases: 'Gases de combustión',
    steamValorization: 'Valorización de vapor',
    whbDesign: 'Diseño caldera recuperación',
    whbOpex: 'Opex caldera recuperación',
    boilerDimensioning: 'Dimensionamiento de caldera',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Caldera de recuperación (WHB) — Informe de síntesis',
    steamProduction: 'Producción de vapor',
    steamPressure: 'Presión de vapor [bar]',
    steamTemperature: 'Temperatura de vapor [°C]',
    boilerBlowdown: 'Purga de caldera [kg/h]',
    flashDrumSteam: 'Vapor flash drum [kg/h]',
    temperatures: 'Temperaturas',
    flueGasInletTemp: 'Temperatura entrada humos [°C]',
    flueGasOutletTemp: 'Temperatura salida humos [°C]',
    o2Measured: 'O₂ medido (seco)',
    wetFlowTotal: 'Caudal húmedo total [kg/h]',
    dryFlow: 'Caudal seco [Nm³/h]',
    wetFlow: 'Caudal húmedo [Nm³/h]',
    outletGasComposition: 'Composición gas de salida',
    netProduction: 'Producción neta',
    netSteamProduced: 'Vapor neto producido [kg/h]',
    recoveredPower: 'Potencia recuperada [kW]',
    turbineValorization: 'Turbina / Valorización',
    electricConsumptions: 'Consumos eléctricos',
    dataNotAvailableDesign: 'Datos no disponibles (abrir pestaña Diseño)',
    hourlyCosts: 'Costos horarios',
    opexNotAvailable: 'Costos OPEX no disponibles — abrir pestañas Diseño y OPEX.',
    electricity: 'Electricidad',
    water: 'Agua',
    totalCost: 'Costo total',
    hourlyCost: 'Costo horario',
    annualCost: 'Costo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricidad',
    totalCO2kgh: 'Total CO₂',
    reportGenerated: 'Informe generado automáticamente',
    consumer: 'Consumidor',
    total: 'Total',
  },

  it: {
    // ===== COMMUNES =====
    calculationParameters: 'Parametri di calcolo',
    calculatedParameters: 'Parametri calcolati',
    resetValues: 'Ripristina valori',
    resetDefaultValues: 'Ripristina valori predefiniti',
    clearMemory: 'Cancella memoria',
    export: 'Esporta',
    backToFlow: 'Torna al flusso',
    sendData: 'Invia dati',
    title: 'Configurazione Caldaia di Recupero Calore',

    stepMM: 'Passo di calcolo [mm]',
    chaleurRecuperee: 'Calore recuperato [kW]',
    surfaceTotal: 'Superficie totale di scambio [m²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Senza turbina',
    sansTurbineDesc: 'Solo calcolo proprietà vapore',
    contrepression: 'Contropressione',
    contrepressionDesc: 'Estrazione a pressione fissa',
    deuxEtages: '2 Stadi',
    deuxEtagesDesc: 'Turbina con 2 stadi di espansione',
    troisEtages: '3 Stadi',
    troisEtagesDesc: 'Turbina con 3 stadi di espansione',
    condensationVide: 'Condensazione (Vuoto)',
    condensationVideDesc: 'Condensazione sottovuoto',
    pressureLevelsConfiguration: 'Configurazione livelli di pressione',
    extractionConfiguration: 'Configurazione estrazioni',
    totalFlows: 'Portate totali',
    quality: 'Titolo',
    wetSteamWarning: 'Vapore umido - Presenza di goccioline d\'acqua',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Parametri di calcolo della caldaia',
    flueGasCalculation: 'Calcolo gas di combustione',
    feedWaterCalculation: 'Calcolo acqua di alimentazione',
    steamCalculation: 'Calcolo vapore',
    drumParameters: 'Parametri tamburo',
    boilerOutletTemperature: 'Temperatura uscita caldaia [°C]',
    estimatedThermalLoss: 'Perdite termiche stimate [%]',
    feedwaterTemperature: 'Temperatura acqua di alimentazione [°C]',
    steamType: 'Tipo di vapore',
    superheatedSteamTemperature: 'Temperatura vapore surriscaldato [°C]',
    boilerPressure: 'Pressione caldaia [bar]',
    blowdownRate: 'Tasso di spurgo [%]',
    saturated: 'Saturo',
    superheated: 'Surriscaldato',
    flueGasTemperatureInlet: 'Temperatura gas entrata [°C]',
    flueGasEnthalpyIn: 'Entalpia gas entrata [kJ/h]',
    flueGasEnthalpyOut: 'Entalpia gas uscita [kJ/h]',
    flueGasEnthalpyDifference: 'Differenza entalpia gas [kJ/h]',
    feedwaterFlow: 'Portata acqua di alimentazione [kg/h]',
    feedwaterPressure: 'Pressione acqua di alimentazione [bar]',
    blowdownMassFlow: 'Portata massica spurgo [kg/h]',
    enthalpyFeedwater: 'Entalpia acqua di alimentazione [kW]',
    saturatedSteamTemperature: 'Temperatura vapore saturo [°C]',
    deltaEnthalpies: 'Delta entalpie gas [kJ/h]',
    steamEnthalpy: 'Entalpia vapore [kJ/h]',
    steamFlow: 'Portata vapore [kg/h]',
    ventFlashSteamDrum: 'Sfogo/flash tamburo [kJ/h]',
    liquidRejected: 'Liquido rigettato [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Temperatura gas uscita [°C]',
    ambiantAirTemperature: 'Temperatura aria ambiente [°C]',
    volumeAirIngrease: 'Volume aria di apporto [Nm³/h]',
    temperatureInletWHB: 'Temperatura ingresso caldaia recupero [°C]',
    temperatureOutletWHB: 'Temperatura uscita caldaia recupero [°C]',
    flueGasComposition: 'Composizione gas di combustione',
    flueGasInlet: 'Gas di combustione all\'ingresso',
    flueGasOutlet: 'Gas di combustione all\'uscita',
    airIngrease: 'Apporto aria ambiente',
    flueGasOutletConsideringAirIngrease: 'Gas di combustione uscita con apporto aria',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Emissioni inquinanti',
    flyAshesContentOutlet: 'Contenuto ceneri volanti uscita [g/Nm³]',
    siccityBottomAsh: 'Siccità ceneri pesanti [%]',
    o2Ref: 'O2 riferimento [%]',
    wasteFlow: 'Portata rifiuti [kg/h]',
    flueGasFlowWet: 'Portata gas umido [Nm³/h]',
    flueGasFlowDry: 'Portata gas secco [Nm³/h]',
    o2Calculated: 'O2 calcolato [%]',
    inputFlueGas: 'Gas di combustione ingresso',
    outputFlueGas: 'Gas di combustione uscita',
    residuesCalculated: 'Residui calcolati',
    boilerAsh: 'Ceneri caldaia [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Perdite di carico aerodinamiche',
    thermicalLossParameters: 'Parametri perdite termiche',
    rotaryKilnDesign: 'Progetto forno rotativo',
    lanceEstimation: 'Stima lance',
    facadeCooling: 'Raffreddamento facciata',
    facadeThermicalLosses: 'Perdite termiche facciata',
    shellCooling: 'Raffreddamento mantello',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Bruciatori SCC',
    sccThermicalLosses: 'Perdite termiche SCC',
    extractorConsumption: 'Consumo estrattore',
    combustionAirFan: 'Ventilatore aria di combustione',
    extractorWaterEvaporation: 'Evaporazione acqua estrattore',
    poutMmce: 'Pressione uscita [mmCA]',
    waterRecallConsumption: 'Richiamo consumi acqua',
    waterPurgeLosses: 'Perdite acqua di spurgo [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Calcolatore produzione elettrica',
    turbineVaporWithTaps: 'Turbina a vapore con estrazioni',
    estimationPerformances: 'Stima prestazioni',
    turbineConfiguration: 'Configurazione turbina',
    turbineType: 'Tipo di turbina',
    inletPressure: 'Pressione ingresso [bar]',
    inletTemperature: 'Temperatura ingresso [°C]',
    outletPressure: 'Pressione uscita [bar]',
    ambientTemperature: 'Temperatura ambiente [°C]',
    efficiencyParameters: 'Parametri di rendimento',
    turbineEfficiency: 'Rendimento turbina [%]',
    mechanicalEfficiency: 'Rendimento meccanico [%]',
    generatorEfficiency: 'Rendimento generatore [%]',
    pressureLevel1: 'Livello 1 (Alta pressione)',
    pressureLevel2: 'Livello 2 (Media pressione)',
    pressureLevel3: 'Livello 3 (Bassa pressione)',
    extraction1: 'Estrazione 1',
    extraction2: 'Estrazione 2',
    extraction3: 'Estrazione 3',
    performanceResults: 'Risultati prestazioni',
    steamVaporProperties: 'Proprietà vapore all\'ingresso',
    inletEnthalpy: 'Entalpia ingresso',
    inletEntropy: 'Entropia ingresso',
    saturationTemperature: 'Temperatura di saturazione',
    superheating: 'Surriscaldamento',
    electricPower: 'Potenza elettrica',
    mechanicalPower: 'Potenza meccanica',
    specificWork: 'Lavoro specifico',
    specificConsumption: 'Consumo specifico',
    globalEfficiency: 'Rendimento globale',
    expansionRatio: 'Rapporto di espansione',
    carnotEfficiency: 'Efficienza Carnot',
    remainingFlow: 'Portata rimanente',
    extractionDetails: 'Dettagli estrazioni',
    performanceCurves: 'Curve di prestazione in funzione della portata',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Calcolatore caldaia a tubi d\'acqua',
    dimensioningEN12952: 'Dimensionamento secondo EN 12952-3',
    basicData: 'Dati di base',
    serviceTemperature: 'Temperatura di servizio [°C]',
    servicePressure : 'Pressione di servizio [bar]',
    vaporFlow: 'Portata vapore [kg/h]',
    feedwaterTemp: 'Temperatura acqua di alimentazione [°C]',
    wasteHHV: 'PCI rifiuti [MJ/kg]',
    combustionEfficiency: 'Rendimento combustione [%]',
    materialCharacteristics: 'Caratteristiche materiali',
    material: 'Materiale',
    admissibleStress: 'Tensione ammissibile [N/mm²]',
    weldingCoefficient: 'Coefficiente saldatura',
    corrosionAllowance: 'Tolleranza corrosione [mm]',
    bodyGeometry: 'Geometria corpo',
    bodyInnerDiameter: 'Diametro interno corpo [mm]',
    bodyLength: 'Lunghezza corpo [mm]',
    tubeNumber: 'Numero di tubi',
    tubeOuterDiameter: 'Diametro esterno tubi [mm]',
    tubeInnerDiameter: 'Diametro interno tubi [mm]',
    checks: 'Verifiche',
    mainResults: 'Risultati principali',
    calculationPressure: 'Pressione di calcolo',
    bodyThickness: 'Spessore corpo',
    tubeThickness: 'Spessore tubi',
    steamPower: 'Potenza vapore',
    errorMessage: 'Errore: ',
    conformityCheck: 'Dimensionamento conforme ai requisiti EN 12952-3',
    warningThickness: 'Spessore corpo < 6 mm - Verificare spessore minimo',
    warningFluxDensity: 'Densità di flusso elevata - Rischio di incrostazione',
    errorVelocity: 'Velocità eccessiva - Rischio di erosione critica',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Configurazione caldaia di recupero calore',
    steamParameters: 'Parametri vapore',
    flueGases: 'Gas di combustione',
    steamValorization: 'Valorizzazione vapore',
    whbDesign: 'Progetto caldaia recupero',
    whbOpex: 'Opex caldaia recupero',
    boilerDimensioning: 'Dimensionamento caldaia',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Caldaia a recupero (WHB) — Rapporto di sintesi',
    steamProduction: 'Produzione di vapore',
    steamPressure: 'Pressione vapore [bar]',
    steamTemperature: 'Temperatura vapore [°C]',
    boilerBlowdown: 'Spurgo caldaia [kg/h]',
    flashDrumSteam: 'Flash drum vapore [kg/h]',
    temperatures: 'Temperature',
    flueGasInletTemp: 'Temperatura entrata fumi [°C]',
    flueGasOutletTemp: 'Temperatura uscita fumi [°C]',
    o2Measured: 'O₂ misurato (secco)',
    wetFlowTotal: 'Portata umida totale [kg/h]',
    dryFlow: 'Portata secca [Nm³/h]',
    wetFlow: 'Portata umida [Nm³/h]',
    outletGasComposition: 'Composizione gas in uscita',
    netProduction: 'Produzione netta',
    netSteamProduced: 'Vapore netto prodotto [kg/h]',
    recoveredPower: 'Potenza recuperata [kW]',
    turbineValorization: 'Turbina / Valorizzazione',
    electricConsumptions: 'Consumi elettrici',
    dataNotAvailableDesign: 'Dati non disponibili (aprire scheda Progetto)',
    hourlyCosts: 'Costi orari',
    opexNotAvailable: 'Costi OPEX non disponibili — aprire le schede Progetto e OPEX.',
    electricity: 'Elettricità',
    water: 'Acqua',
    totalCost: 'Costo totale',
    hourlyCost: 'Costo orario',
    annualCost: 'Costo annuale',
    totalCO2: 'Totale CO₂ [kg/h]',
    co2Electricity: 'CO₂ elettricità',
    totalCO2kgh: 'Totale CO₂',
    reportGenerated: 'Rapporto generato automaticamente',
    consumer: 'Consumatore',
    total: 'Totale',
  },


  pt: {
    // ===== COMMUNES =====
    calculationParameters: 'Parâmetros de cálculo',
    calculatedParameters: 'Parâmetros calculados',
    resetValues: 'Redefinir valores',
    resetDefaultValues: 'Redefinir para valores padrão',
    clearMemory: 'Limpar memória',
    export: 'Exportar',
    backToFlow: 'Voltar ao fluxo',
    sendData: 'Enviar dados',
    title: 'Configuração da Caldeira de Recuperação de Calor',

    stepMM: 'Passo de cálculo [mm]',
    chaleurRecuperee: 'Calor recuperado [kW]',
    surfaceTotal: 'Superfície total de troca [m²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Sem turbina',
    sansTurbineDesc: 'Apenas cálculo das propriedades do vapor',
    contrepression: 'Contrapressão',
    contrepressionDesc: 'Extração a pressão fixa',
    deuxEtages: '2 Estágios',
    deuxEtagesDesc: 'Turbina com 2 estágios de expansão',
    troisEtages: '3 Estágios',
    troisEtagesDesc: 'Turbina com 3 estágios de expansão',
    condensationVide: 'Condensação (Vácuo)',
    condensationVideDesc: 'Condensação sob vácuo',
    pressureLevelsConfiguration: 'Configuração dos níveis de pressão',
    extractionConfiguration: 'Configuração das extrações',
    totalFlows: 'Vazões totais',
    quality: 'Título',
    wetSteamWarning: 'Vapor úmido - Presença de gotículas de água',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Parâmetros de cálculo da caldeira',
    flueGasCalculation: 'Cálculo dos gases de combustão',
    feedWaterCalculation: 'Cálculo da água de alimentação',
    steamCalculation: 'Cálculo do vapor',
    drumParameters: 'Parâmetros do tambor',
    boilerOutletTemperature: 'Temperatura de saída da caldeira [°C]',
    estimatedThermalLoss: 'Perdas térmicas estimadas [%]',
    feedwaterTemperature: 'Temperatura da água de alimentação [°C]',
    steamType: 'Tipo de vapor',
    superheatedSteamTemperature: 'Temperatura do vapor superaquecido [°C]',
    boilerPressure: 'Pressão da caldeira [bar]',
    blowdownRate: 'Taxa de purga [%]',
    saturated: 'Saturado',
    superheated: 'Superaquecido',
    flueGasTemperatureInlet: 'Temperatura dos gases de entrada [°C]',
    flueGasEnthalpyIn: 'Entalpia dos gases de entrada [kJ/h]',
    flueGasEnthalpyOut: 'Entalpia dos gases de saída [kJ/h]',
    flueGasEnthalpyDifference: 'Diferença de entalpia dos gases [kJ/h]',
    feedwaterFlow: 'Vazão de água de alimentação [kg/h]',
    feedwaterPressure: 'Pressão da água de alimentação [bar]',
    blowdownMassFlow: 'Vazão mássica de purga [kg/h]',
    enthalpyFeedwater: 'Entalpia da água de alimentação [kW]',
    saturatedSteamTemperature: 'Temperatura do vapor saturado [°C]',
    deltaEnthalpies: 'Delta entalpias dos gases [kJ/h]',
    steamEnthalpy: 'Entalpia do vapor [kJ/h]',
    steamFlow: 'Vazão de vapor [kg/h]',
    ventFlashSteamDrum: 'Ventilação/vapor flash tambor [kJ/h]',
    liquidRejected: 'Líquido rejeitado [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Temperatura dos gases de saída [°C]',
    ambiantAirTemperature: 'Temperatura do ar ambiente [°C]',
    volumeAirIngrease: 'Volume de ar de aporte [Nm³/h]',
    temperatureInletWHB: 'Temperatura de entrada na caldeira de recuperação [°C]',
    temperatureOutletWHB: 'Temperatura de saída na caldeira de recuperação [°C]',
    flueGasComposition: 'Composição dos gases de combustão',
    flueGasInlet: 'Gases de combustão na entrada',
    flueGasOutlet: 'Gases de combustão na saída',
    airIngrease: 'Aporte de ar ambiente',
    flueGasOutletConsideringAirIngrease: 'Gases de combustão na saída considerando aporte de ar',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Emissões de poluentes',
    flyAshesContentOutlet: 'Conteúdo de cinzas volantes na saída [g/Nm³]',
    siccityBottomAsh: 'Secura das cinzas pesadas [%]',
    o2Ref: 'O2 referência [%]',
    wasteFlow: 'Vazão de resíduos [kg/h]',
    flueGasFlowWet: 'Vazão de gases úmido [Nm³/h]',
    flueGasFlowDry: 'Vazão de gases seco [Nm³/h]',
    o2Calculated: 'O2 calculado [%]',
    inputFlueGas: 'Gases de combustão entrada',
    outputFlueGas: 'Gases de combustão saída',
    residuesCalculated: 'Resíduos calculados',
    boilerAsh: 'Cinzas da caldeira [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Perda de carga aerodinâmica',
    thermicalLossParameters: 'Parâmetros de perdas térmicas',
    rotaryKilnDesign: 'Projeto do forno rotativo',
    lanceEstimation: 'Estimativa de lançadores',
    facadeCooling: 'Resfriamento da fachada',
    facadeThermicalLosses: 'Perdas térmicas da fachada',
    shellCooling: 'Resfriamento da carcaça',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Queimadores SCC',
    sccThermicalLosses: 'Perdas térmicas SCC',
    extractorConsumption: 'Consumo do extrator',
    combustionAirFan: 'Ventilador de ar de combustão',
    extractorWaterEvaporation: 'Evaporação de água do extrator',
    poutMmce: 'Pressão de saída [mmCA]',
    waterRecallConsumption: 'Recordação de consumos de água',
    waterPurgeLosses: 'Perdas de água de purga [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Calculadora de produção elétrica',
    turbineVaporWithTaps: 'Turbina a vapor com extrações',
    estimationPerformances: 'Estimativa de desempenho',
    turbineConfiguration: 'Configuração da turbina',
    turbineType: 'Tipo de turbina',
    inletPressure: 'Pressão de entrada [bar]',
    inletTemperature: 'Temperatura de entrada [°C]',
    outletPressure: 'Pressão de saída [bar]',
    ambientTemperature: 'Temperatura ambiente [°C]',
    efficiencyParameters: 'Parâmetros de eficiência',
    turbineEfficiency: 'Eficiência da turbina [%]',
    mechanicalEfficiency: 'Eficiência mecânica [%]',
    generatorEfficiency: 'Eficiência do gerador [%]',
    pressureLevel1: 'Nível 1 (Alta pressão)',
    pressureLevel2: 'Nível 2 (Pressão média)',
    pressureLevel3: 'Nível 3 (Baixa pressão)',
    extraction1: 'Extração 1',
    extraction2: 'Extração 2',
    extraction3: 'Extração 3',
    performanceResults: 'Resultados de desempenho',
    steamVaporProperties: 'Propriedades do vapor na entrada',
    inletEnthalpy: 'Entalpia de entrada',
    inletEntropy: 'Entropia de entrada',
    saturationTemperature: 'Temperatura de saturação',
    superheating: 'Superaquecimento',
    electricPower: 'Potência elétrica',
    mechanicalPower: 'Potência mecânica',
    specificWork: 'Trabalho específico',
    specificConsumption: 'Consumo específico',
    globalEfficiency: 'Eficiência global',
    expansionRatio: 'Taxa de expansão',
    carnotEfficiency: 'Eficiência de Carnot',
    remainingFlow: 'Vazão restante',
    extractionDetails: 'Detalhes das extrações',
    performanceCurves: 'Curvas de desempenho em função da vazão',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Calculadora de caldeira de tubos de água',
    dimensioningEN12952: 'Dimensionamento de acordo com EN 12952-3',
    basicData: 'Dados básicos',
    serviceTemperature: 'Temperatura de serviço [°C]',
    servicePressure : 'Pressão de serviço [bar]',
    vaporFlow: 'Vazão de vapor [kg/h]',
    feedwaterTemp: 'Temperatura da água de alimentação [°C]',
    wasteHHV: 'PCS resíduos [MJ/kg]',
    combustionEfficiency: 'Eficiência de combustão [%]',
    materialCharacteristics: 'Características dos materiais',
    material: 'Material',
    admissibleStress: 'Tensão admissível [N/mm²]',
    weldingCoefficient: 'Coeficiente de soldagem',
    corrosionAllowance: 'Tolerância de corrosão [mm]',
    bodyGeometry: 'Geometria do corpo',
    bodyInnerDiameter: 'Diâmetro interno do corpo [mm]',
    bodyLength: 'Comprimento do corpo [mm]',
    tubeNumber: 'Número de tubos',
    tubeOuterDiameter: 'Diâmetro externo dos tubos [mm]',
    tubeInnerDiameter: 'Diâmetro interno dos tubos [mm]',
    checks: 'Verificações',
    mainResults: 'Resultados principais',
    calculationPressure: 'Pressão de cálculo',
    bodyThickness: 'Espessura do corpo',
    tubeThickness: 'Espessura dos tubos',
    steamPower: 'Potência do vapor',
    errorMessage: 'Erro: ',
    conformityCheck: 'Dimensionamento em conformidade com os requisitos EN 12952-3',
    warningThickness: 'Espessura do corpo < 6 mm - Verificar espessura mínima',
    warningFluxDensity: 'Densidade de fluxo alta - Risco de incrustação',
    errorVelocity: 'Velocidade excessiva - Risco de erosão crítica',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Configuração da caldeira de recuperação de calor',
    steamParameters: 'Parâmetros do vapor',
    flueGases: 'Gases de combustão',
    steamValorization: 'Valorização do vapor',
    whbDesign: 'Projeto da caldeira de recuperação',
    whbOpex: 'Opex da caldeira de recuperação',
    boilerDimensioning: 'Dimensionamento da caldeira',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Caldeira de recuperação (WHB) — Relatório de síntese',
    steamProduction: 'Produção de vapor',
    steamPressure: 'Pressão de vapor [bar]',
    steamTemperature: 'Temperatura de vapor [°C]',
    boilerBlowdown: 'Purga da caldeira [kg/h]',
    flashDrumSteam: 'Vapor flash drum [kg/h]',
    temperatures: 'Temperaturas',
    flueGasInletTemp: 'Temperatura de entrada de fumos [°C]',
    flueGasOutletTemp: 'Temperatura de saída de fumos [°C]',
    o2Measured: 'O₂ medido (seco)',
    wetFlowTotal: 'Caudal húmido total [kg/h]',
    dryFlow: 'Caudal seco [Nm³/h]',
    wetFlow: 'Caudal húmido [Nm³/h]',
    outletGasComposition: 'Composição do gás de saída',
    netProduction: 'Produção líquida',
    netSteamProduced: 'Vapor líquido produzido [kg/h]',
    recoveredPower: 'Potência recuperada [kW]',
    turbineValorization: 'Turbina / Valorização',
    electricConsumptions: 'Consumos elétricos',
    dataNotAvailableDesign: 'Dados não disponíveis (abrir separador Projeto)',
    hourlyCosts: 'Custos horários',
    opexNotAvailable: 'Custos OPEX não disponíveis — abrir separadores Projeto e OPEX.',
    electricity: 'Eletricidade',
    water: 'Água',
    totalCost: 'Custo total',
    hourlyCost: 'Custo horário',
    annualCost: 'Custo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ eletricidade',
    totalCO2kgh: 'Total CO₂',
    reportGenerated: 'Relatório gerado automaticamente',
    consumer: 'Consumidor',
    total: 'Total',
  },


  ru: {
    // ===== COMMUNES =====
    calculationParameters: 'Параметры расчета',
    calculatedParameters: 'Вычисленные параметры',
    resetValues: 'Сброс значений',
    resetDefaultValues: 'Восстановить значения по умолчанию',
    clearMemory: 'Очистить память',
    export: 'Экспорт',
    backToFlow: 'Вернуться к потоку',
    sendData: 'Отправить данные',
    title: 'Конфигурация котла утилизации тепла',

    stepMM: 'Шаг расчета [мм]',
    chaleurRecuperee: 'Утилизированное тепло [кВт]',
    surfaceTotal: 'Полная поверхность теплообмена [м²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'Без турбины',
    sansTurbineDesc: 'Только расчет свойств пара',
    contrepression: 'Противодавление',
    contrepressionDesc: 'Отбор при фиксированном давлении',
    deuxEtages: '2 ступени',
    deuxEtagesDesc: 'Турбина с 2 ступенями расширения',
    troisEtages: '3 ступени',
    troisEtagesDesc: 'Турбина с 3 ступенями расширения',
    condensationVide: 'Конденсация (Вакуум)',
    condensationVideDesc: 'Конденсация в вакууме',
    pressureLevelsConfiguration: 'Конфигурация уровней давления',
    extractionConfiguration: 'Конфигурация отборов',
    totalFlows: 'Общие расходы',
    quality: 'Качество',
    wetSteamWarning: 'Влажный пар - Присутствие капель воды',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'Параметры расчета котла',
    flueGasCalculation: 'Расчет дымовых газов',
    feedWaterCalculation: 'Расчет питательной воды',
    steamCalculation: 'Расчет пара',
    drumParameters: 'Параметры барабана',
    boilerOutletTemperature: 'Температура выхода котла [°C]',
    estimatedThermalLoss: 'Предполагаемые тепловые потери [%]',
    feedwaterTemperature: 'Температура питательной воды [°C]',
    steamType: 'Тип пара',
    superheatedSteamTemperature: 'Температура перегретого пара [°C]',
    boilerPressure: 'Давление в котле [bar]',
    blowdownRate: 'Коэффициент продувки [%]',
    saturated: 'Насыщенный',
    superheated: 'Перегретый',
    flueGasTemperatureInlet: 'Температура дымовых газов на входе [°C]',
    flueGasEnthalpyIn: 'Энтальпия дымовых газов на входе [кДж/ч]',
    flueGasEnthalpyOut: 'Энтальпия дымовых газов на выходе [кДж/ч]',
    flueGasEnthalpyDifference: 'Разница энтальпии дымовых газов [кДж/ч]',
    feedwaterFlow: 'Расход питательной воды [кг/ч]',
    feedwaterPressure: 'Давление питательной воды [bar]',
    blowdownMassFlow: 'Массовый расход продувки [кг/ч]',
    enthalpyFeedwater: 'Энтальпия питательной воды [кВт]',
    saturatedSteamTemperature: 'Температура насыщенного пара [°C]',
    deltaEnthalpies: 'Дельта энтальпии дымовых газов [кДж/ч]',
    steamEnthalpy: 'Энтальпия пара [кДж/ч]',
    steamFlow: 'Расход пара [кг/ч]',
    ventFlashSteamDrum: 'Вентиляция/испарение барабана [кДж/ч]',
    liquidRejected: 'Отведенная жидкость [кг/ч]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'Температура дымовых газов на выходе [°C]',
    ambiantAirTemperature: 'Температура окружающего воздуха [°C]',
    volumeAirIngrease: 'Объем подаваемого воздуха [Нм³/ч]',
    temperatureInletWHB: 'Температура на входе котла утилизации [°C]',
    temperatureOutletWHB: 'Температура на выходе котла утилизации [°C]',
    flueGasComposition: 'Состав дымовых газов',
    flueGasInlet: 'Дымовые газы на входе',
    flueGasOutlet: 'Дымовые газы на выходе',
    airIngrease: 'Подача окружающего воздуха',
    flueGasOutletConsideringAirIngrease: 'Дымовые газы на выходе с учетом подачи воздуха',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'Выбросы загрязняющих веществ',
    flyAshesContentOutlet: 'Содержание летучей золы на выходе [г/Нм³]',
    siccityBottomAsh: 'Сухость тяжелой золы [%]',
    o2Ref: 'O2 эталон [%]',
    wasteFlow: 'Расход отходов [кг/ч]',
    flueGasFlowWet: 'Расход дымовых газов (влажный) [Нм³/ч]',
    flueGasFlowDry: 'Расход дымовых газов (сухой) [Нм³/ч]',
    o2Calculated: 'O2 рассчитанный [%]',
    inputFlueGas: 'Входящие дымовые газы',
    outputFlueGas: 'Выходящие дымовые газы',
    residuesCalculated: 'Рассчитанные остатки',
    boilerAsh: 'Котельная зола [кг/ч]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'Аэродинамическое падение давления',
    thermicalLossParameters: 'Параметры тепловых потерь',
    rotaryKilnDesign: 'Конструкция вращающейся печи',
    lanceEstimation: 'Оценка форсунок',
    facadeCooling: 'Охлаждение фасада',
    facadeThermicalLosses: 'Тепловые потери фасада',
    shellCooling: 'Охлаждение оболочки',
    sccDimensioning: 'Расчет размеров SCC',
    sccBurners: 'Горелки SCC',
    sccThermicalLosses: 'Тепловые потери SCC',
    extractorConsumption: 'Потребление экстрактора',
    combustionAirFan: 'Вентилятор воздуха сгорания',
    extractorWaterEvaporation: 'Испарение воды экстрактора',
    poutMmce: 'Давление на выходе [мм вод.ст.]',
    waterRecallConsumption: 'Напоминание потребления воды',
    waterPurgeLosses: 'Потери воды продувки [кг/ч]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'Калькулятор электроэнергии',
    turbineVaporWithTaps: 'Паровая турбина с отборами',
    estimationPerformances: 'Оценка производительности',
    turbineConfiguration: 'Конфигурация турбины',
    turbineType: 'Тип турбины',
    inletPressure: 'Давление на входе [bar]',
    inletTemperature: 'Температура на входе [°C]',
    outletPressure: 'Давление на выходе [bar]',
    ambientTemperature: 'Температура окружающей среды [°C]',
    efficiencyParameters: 'Параметры КПД',
    turbineEfficiency: 'КПД турбины [%]',
    mechanicalEfficiency: 'Механический КПД [%]',
    generatorEfficiency: 'КПД генератора [%]',
    pressureLevel1: 'Уровень 1 (Высокое давление)',
    pressureLevel2: 'Уровень 2 (Среднее давление)',
    pressureLevel3: 'Уровень 3 (Низкое давление)',
    extraction1: 'Отбор 1',
    extraction2: 'Отбор 2',
    extraction3: 'Отбор 3',
    performanceResults: 'Результаты производительности',
    steamVaporProperties: 'Свойства пара на входе',
    inletEnthalpy: 'Энтальпия на входе',
    inletEntropy: 'Энтропия на входе',
    saturationTemperature: 'Температура насыщения',
    superheating: 'Перегрев',
    electricPower: 'Электрическая мощность',
    mechanicalPower: 'Механическая мощность',
    specificWork: 'Удельная работа',
    specificConsumption: 'Удельный расход',
    globalEfficiency: 'Глобальный КПД',
    expansionRatio: 'Коэффициент расширения',
    carnotEfficiency: 'Эффективность Карно',
    remainingFlow: 'Оставшийся расход',
    extractionDetails: 'Детали отборов',
    performanceCurves: 'Кривые производительности в зависимости от расхода',
    bar: 'bar',
    percent: '%',
    kW: 'кВт',
    MW: 'МВт',
    kJperKg: 'кДж/кг',
    kJperKgK: 'кДж/кг·К',
    kgperKWh: 'кг/кВтч',
    degreeC: '°C',
    Nm3perH: 'Нм³/ч',
    tonperH: 'т/ч',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'Калькулятор водотрубного котла',
    dimensioningEN12952: 'Расчет размеров по EN 12952-3',
    basicData: 'Основные данные',
    serviceTemperature: 'Температура обслуживания [°C]',
    servicePressure : 'Давление обслуживания [bar]',
    vaporFlow: 'Расход пара [кг/ч]',
    feedwaterTemp: 'Температура питательной воды [°C]',
    wasteHHV: 'Высший теплотворный потенциал отходов [МДж/кг]',
    combustionEfficiency: 'КПД сгорания [%]',
    materialCharacteristics: 'Характеристики материала',
    material: 'Материал',
    admissibleStress: 'Допустимое напряжение [Н/мм²]',
    weldingCoefficient: 'Коэффициент сварки',
    corrosionAllowance: 'Припуск на коррозию [мм]',
    bodyGeometry: 'Геометрия корпуса',
    bodyInnerDiameter: 'Внутренний диаметр корпуса [мм]',
    bodyLength: 'Длина корпуса [мм]',
    tubeNumber: 'Количество труб',
    tubeOuterDiameter: 'Внешний диаметр труб [мм]',
    tubeInnerDiameter: 'Внутренний диаметр труб [мм]',
    checks: 'Проверки',
    mainResults: 'Основные результаты',
    calculationPressure: 'Расчетное давление',
    bodyThickness: 'Толщина корпуса',
    tubeThickness: 'Толщина труб',
    steamPower: 'Мощность пара',
    errorMessage: 'Ошибка: ',
    conformityCheck: 'Расчет размеров соответствует требованиям EN 12952-3',
    warningThickness: 'Толщина корпуса < 6 мм - Проверить минимальную толщину',
    warningFluxDensity: 'Высокая плотность потока - Риск отложения',
    errorVelocity: 'Чрезмерная скорость - Риск критической эрозии',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'Конфигурация котла утилизации тепла',
    steamParameters: 'Параметры пара',
    flueGases: 'Дымовые газы',
    steamValorization: 'Утилизация пара',
    whbDesign: 'Конструкция котла утилизации',
    whbOpex: 'Операционные расходы котла утилизации',
    boilerDimensioning: 'Расчет размеров котла',

    // ===== WHB_REPORT =====
    whbReportTitle: 'Котёл-утилизатор (WHB) — Сводный отчёт',
    steamProduction: 'Производство пара',
    steamPressure: 'Давление пара [бар]',
    steamTemperature: 'Температура пара [°C]',
    boilerBlowdown: 'Продувка котла [кг/ч]',
    flashDrumSteam: 'Мгновенный испаритель [кг/ч]',
    temperatures: 'Температуры',
    flueGasInletTemp: 'Температура газов на входе [°C]',
    flueGasOutletTemp: 'Температура газов на выходе [°C]',
    o2Measured: 'O₂ измеренный (сухой)',
    wetFlowTotal: 'Общий влажный расход [кг/ч]',
    dryFlow: 'Сухой расход [Нм³/ч]',
    wetFlow: 'Влажный расход [Нм³/ч]',
    outletGasComposition: 'Состав газа на выходе',
    netProduction: 'Нетто производство',
    netSteamProduced: 'Нетто пара [кг/ч]',
    recoveredPower: 'Рекуперированная мощность [кВт]',
    turbineValorization: 'Турбина / Использование',
    electricConsumptions: 'Потребление электроэнергии',
    dataNotAvailableDesign: 'Данные недоступны (открыть вкладку Конструкция)',
    hourlyCosts: 'Почасовые расходы',
    opexNotAvailable: 'Расходы OPEX недоступны — открыть вкладки Конструкция и OPEX.',
    electricity: 'Электроэнергия',
    water: 'Вода',
    totalCost: 'Общая стоимость',
    hourlyCost: 'Почасовая стоимость',
    annualCost: 'Годовая стоимость',
    totalCO2: 'Всего CO₂ [кг/ч]',
    co2Electricity: 'CO₂ электроэнергия',
    totalCO2kgh: 'Всего CO₂',
    reportGenerated: 'Отчёт создан автоматически',
    consumer: 'Потребитель',
    total: 'Итого',
  },

  zh: {
    // ===== COMMUNES =====
    calculationParameters: '计算参数',
    calculatedParameters: '计算后的参数',
    resetValues: '重置值',
    resetDefaultValues: '重置为默认值',
    clearMemory: '清除内存',
    export: '导出',
    backToFlow: '返回流程',
    sendData: '发送数据',
    title: '余热锅炉配置',

    stepMM: '计算步长 [毫米]',
    chaleurRecuperee: '回收热量 [千瓦]',
    surfaceTotal: '总换热面积 [平方米]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: '无涡轮机',
    sansTurbineDesc: '仅蒸汽性质计算',
    contrepression: '背压',
    contrepressionDesc: '固定压力下的提取',
    deuxEtages: '2级',
    deuxEtagesDesc: '2级膨胀涡轮机',
    troisEtages: '3级',
    troisEtagesDesc: '3级膨胀涡轮机',
    condensationVide: '冷凝(真空)',
    condensationVideDesc: '真空冷凝',
    pressureLevelsConfiguration: '压力级别配置',
    extractionConfiguration: '提取配置',
    totalFlows: '总流量',
    quality: '质量',
    wetSteamWarning: '湿蒸汽 - 存在水滴',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: '锅炉计算参数',
    flueGasCalculation: '烟气计算',
    feedWaterCalculation: '给水计算',
    steamCalculation: '蒸汽计算',
    drumParameters: '鼓形参数',
    boilerOutletTemperature: '锅炉出口温度 [°C]',
    estimatedThermalLoss: '估计热损失 [%]',
    feedwaterTemperature: '给水温度 [°C]',
    steamType: '蒸汽类型',
    superheatedSteamTemperature: '过热蒸汽温度 [°C]',
    boilerPressure: '锅炉压力 [巴]',
    blowdownRate: '排污率 [%]',
    saturated: '饱和',
    superheated: '过热',
    flueGasTemperatureInlet: '烟气进口温度 [°C]',
    flueGasEnthalpyIn: '烟气进口焓 [千焦/小时]',
    flueGasEnthalpyOut: '烟气出口焓 [千焦/小时]',
    flueGasEnthalpyDifference: '烟气焓差 [千焦/小时]',
    feedwaterFlow: '给水流量 [千克/小时]',
    feedwaterPressure: '给水压力 [巴]',
    blowdownMassFlow: '排污质量流量 [千克/小时]',
    enthalpyFeedwater: '给水焓 [千瓦]',
    saturatedSteamTemperature: '饱和蒸汽温度 [°C]',
    deltaEnthalpies: '烟气焓差 [千焦/小时]',
    steamEnthalpy: '蒸汽焓 [千焦/小时]',
    steamFlow: '蒸汽流量 [千克/小时]',
    ventFlashSteamDrum: '通风/闪蒸鼓 [千焦/小时]',
    liquidRejected: '液体排出 [千克/小时]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: '烟气出口温度 [°C]',
    ambiantAirTemperature: '环境空气温度 [°C]',
    volumeAirIngrease: '进风量 [标准立方米/小时]',
    temperatureInletWHB: '余热锅炉进口温度 [°C]',
    temperatureOutletWHB: '余热锅炉出口温度 [°C]',
    flueGasComposition: '烟气成分',
    flueGasInlet: '进口烟气',
    flueGasOutlet: '出口烟气',
    airIngrease: '环境空气进风',
    flueGasOutletConsideringAirIngrease: '考虑进风的出口烟气',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: '污染物排放',
    flyAshesContentOutlet: '飞灰含量 [克/标准立方米]',
    siccityBottomAsh: '底灰干燥度 [%]',
    o2Ref: 'O2参考 [%]',
    wasteFlow: '废物流量 [千克/小时]',
    flueGasFlowWet: '烟气流量(湿) [标准立方米/小时]',
    flueGasFlowDry: '烟气流量(干) [标准立方米/小时]',
    o2Calculated: 'O2计算值 [%]',
    inputFlueGas: '输入烟气',
    outputFlueGas: '输出烟气',
    residuesCalculated: '计算残渣',
    boilerAsh: '锅炉灰 [千克/小时]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: '气动压力损失',
    thermicalLossParameters: '热损失参数',
    rotaryKilnDesign: '回转窑设计',
    lanceEstimation: '喷枪估计',
    facadeCooling: '外壳冷却',
    facadeThermicalLosses: '外壳热损失',
    shellCooling: '壳体冷却',
    sccDimensioning: 'SCC尺寸设计',
    sccBurners: 'SCC燃烧器',
    sccThermicalLosses: 'SCC热损失',
    extractorConsumption: '提取器消耗',
    combustionAirFan: '燃烧空气风扇',
    extractorWaterEvaporation: '提取器水蒸发',
    poutMmce: '出口压力 [毫米水柱]',
    waterRecallConsumption: '用水量回顾',
    waterPurgeLosses: '排污水损失 [千克/小时]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: '发电计算器',
    turbineVaporWithTaps: '带提取的蒸汽涡轮机',
    estimationPerformances: '性能估计',
    turbineConfiguration: '涡轮机配置',
    turbineType: '涡轮机类型',
    inletPressure: '进口压力 [巴]',
    inletTemperature: '进口温度 [°C]',
    outletPressure: '出口压力 [巴]',
    ambientTemperature: '环境温度 [°C]',
    efficiencyParameters: '效率参数',
    turbineEfficiency: '涡轮机效率 [%]',
    mechanicalEfficiency: '机械效率 [%]',
    generatorEfficiency: '发电机效率 [%]',
    pressureLevel1: '级别1(高压)',
    pressureLevel2: '级别2(中压)',
    pressureLevel3: '级别3(低压)',
    extraction1: '提取1',
    extraction2: '提取2',
    extraction3: '提取3',
    performanceResults: '性能结果',
    steamVaporProperties: '进口蒸汽性质',
    inletEnthalpy: '进口焓',
    inletEntropy: '进口熵',
    saturationTemperature: '饱和温度',
    superheating: '过热',
    electricPower: '电功率',
    mechanicalPower: '机械功率',
    specificWork: '比功',
    specificConsumption: '比耗',
    globalEfficiency: '总效率',
    expansionRatio: '膨胀比',
    carnotEfficiency: '卡诺效率',
    remainingFlow: '剩余流量',
    extractionDetails: '提取细节',
    performanceCurves: '性能曲线(根据流量)',
    bar: '巴',
    percent: '%',
    kW: '千瓦',
    MW: '兆瓦',
    kJperKg: '千焦/千克',
    kJperKgK: '千焦/千克·开',
    kgperKWh: '千克/千瓦时',
    degreeC: '°C',
    Nm3perH: '标准立方米/小时',
    tonperH: '吨/小时',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: '水管锅炉计算器',
    dimensioningEN12952: 'EN 12952-3标准设计',
    basicData: '基本数据',
    serviceTemperature: '工作温度 [°C]',
    servicePressure : '工作压力 [巴]',
    vaporFlow: '蒸汽流量 [千克/小时]',
    feedwaterTemp: '给水温度 [°C]',
    wasteHHV: '废物高位热值 [兆焦/千克]',
    combustionEfficiency: '燃烧效率 [%]',
    materialCharacteristics: '材料特性',
    material: '材料',
    admissibleStress: '许用应力 [牛/平方毫米]',
    weldingCoefficient: '焊接系数',
    corrosionAllowance: '腐蚀余量 [毫米]',
    bodyGeometry: '筒体几何',
    bodyInnerDiameter: '筒体内径 [毫米]',
    bodyLength: '筒体长度 [毫米]',
    tubeNumber: '管子数量',
    tubeOuterDiameter: '管子外径 [毫米]',
    tubeInnerDiameter: '管子内径 [毫米]',
    checks: '检查',
    mainResults: '主要结果',
    calculationPressure: '计算压力',
    bodyThickness: '筒体厚度',
    tubeThickness: '管子厚度',
    steamPower: '蒸汽功率',
    errorMessage: '错误: ',
    conformityCheck: '设计符合EN 12952-3要求',
    warningThickness: '筒体厚度 < 6毫米 - 检查最小厚度',
    warningFluxDensity: '热负荷密度高 - 结垢风险',
    errorVelocity: '速度过高 - 关键侵蚀风险',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: '余热锅炉配置',
    steamParameters: '蒸汽参数',
    flueGases: '烟气',
    steamValorization: '蒸汽利用',
    whbDesign: '余热锅炉设计',
    whbOpex: '余热锅炉运营成本',
    boilerDimensioning: '锅炉尺寸设计',
  },

  ja: {
    // ===== COMMUNES =====
    calculationParameters: '計算パラメータ',
    calculatedParameters: '計算されたパラメータ',
    resetValues: '値をリセット',
    resetDefaultValues: 'デフォルト値にリセット',
    clearMemory: 'メモリをクリア',
    export: 'エクスポート',
    backToFlow: 'フローに戻る',
    sendData: 'データを送信',
    title: '廃熱回収ボイラー設定',

    stepMM: '計算ステップ [mm]',
    chaleurRecuperee: '回収熱 [kW]',
    surfaceTotal: '総伝熱面積 [m²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'タービンなし',
    sansTurbineDesc: '蒸気特性計算のみ',
    contrepression: '背圧',
    contrepressionDesc: '固定圧力での抽気',
    deuxEtages: '2段',
    deuxEtagesDesc: '2段膨張タービン',
    troisEtages: '3段',
    troisEtagesDesc: '3段膨張タービン',
    condensationVide: 'コンデンサー(真空)',
    condensationVideDesc: '真空コンデンサー',
    pressureLevelsConfiguration: '圧力レベル設定',
    extractionConfiguration: '抽気設定',
    totalFlows: '総流量',
    quality: '乾き度',
    wetSteamWarning: '湿り蒸気 - 水滴の存在',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'ボイラー計算パラメータ',
    flueGasCalculation: '排ガス計算',
    feedWaterCalculation: '給水計算',
    steamCalculation: '蒸気計算',
    drumParameters: 'ドラムパラメータ',
    boilerOutletTemperature: 'ボイラー出口温度 [°C]',
    estimatedThermalLoss: '推定熱損失 [%]',
    feedwaterTemperature: '給水温度 [°C]',
    steamType: '蒸気の種類',
    superheatedSteamTemperature: '過熱蒸気温度 [°C]',
    boilerPressure: 'ボイラー圧力 [bar]',
    blowdownRate: 'ブロー率 [%]',
    saturated: '飽和',
    superheated: '過熱',
    flueGasTemperatureInlet: '排ガス入口温度 [°C]',
    flueGasEnthalpyIn: '排ガス入口エンタルピ [kJ/h]',
    flueGasEnthalpyOut: '排ガス出口エンタルピ [kJ/h]',
    flueGasEnthalpyDifference: '排ガスエンタルピ差 [kJ/h]',
    feedwaterFlow: '給水流量 [kg/h]',
    feedwaterPressure: '給水圧力 [bar]',
    blowdownMassFlow: 'ブロー質量流量 [kg/h]',
    enthalpyFeedwater: '給水エンタルピ [kW]',
    saturatedSteamTemperature: '飽和蒸気温度 [°C]',
    deltaEnthalpies: '排ガスエンタルピ差 [kJ/h]',
    steamEnthalpy: '蒸気エンタルピ [kJ/h]',
    steamFlow: '蒸気流量 [kg/h]',
    ventFlashSteamDrum: 'ベント/フラッシュドラム [kJ/h]',
    liquidRejected: '液体排出 [kg/h]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: '排ガス出口温度 [°C]',
    ambiantAirTemperature: '環境空気温度 [°C]',
    volumeAirIngrease: '空気供給量 [Nm³/h]',
    temperatureInletWHB: '廃熱ボイラー入口温度 [°C]',
    temperatureOutletWHB: '廃熱ボイラー出口温度 [°C]',
    flueGasComposition: '排ガス組成',
    flueGasInlet: '入口排ガス',
    flueGasOutlet: '出口排ガス',
    airIngrease: '環境空気供給',
    flueGasOutletConsideringAirIngrease: '空気供給を考慮した出口排ガス',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: '汚染物質排出',
    flyAshesContentOutlet: '飛灰含有量 [g/Nm³]',
    siccityBottomAsh: '底灰乾燥度 [%]',
    o2Ref: 'O2参照 [%]',
    wasteFlow: '廃棄物流量 [kg/h]',
    flueGasFlowWet: '排ガス流量(湿) [Nm³/h]',
    flueGasFlowDry: '排ガス流量(乾) [Nm³/h]',
    o2Calculated: 'O2計算値 [%]',
    inputFlueGas: '入力排ガス',
    outputFlueGas: '出力排ガス',
    residuesCalculated: '計算残渣',
    boilerAsh: 'ボイラー灰 [kg/h]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: '空気力学的圧力損失',
    thermicalLossParameters: '熱損失パラメータ',
    rotaryKilnDesign: '回転炉設計',
    lanceEstimation: 'ランス推定',
    facadeCooling: 'ファサード冷却',
    facadeThermicalLosses: 'ファサード熱損失',
    shellCooling: 'シェル冷却',
    sccDimensioning: 'SCC寸法設計',
    sccBurners: 'SCCバーナー',
    sccThermicalLosses: 'SCC熱損失',
    extractorConsumption: 'エクストラクター消費',
    combustionAirFan: '燃焼空気ファン',
    extractorWaterEvaporation: 'エクストラクター水蒸発',
    poutMmce: '出口圧力 [mmH2O]',
    waterRecallConsumption: '水消費量回顧',
    waterPurgeLosses: 'ブロー水損失 [kg/h]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: '発電計算機',
    turbineVaporWithTaps: '抽気付き蒸気タービン',
    estimationPerformances: '性能推定',
    turbineConfiguration: 'タービン設定',
    turbineType: 'タービンタイプ',
    inletPressure: '入口圧力 [bar]',
    inletTemperature: '入口温度 [°C]',
    outletPressure: '出口圧力 [bar]',
    ambientTemperature: '環境温度 [°C]',
    efficiencyParameters: '効率パラメータ',
    turbineEfficiency: 'タービン効率 [%]',
    mechanicalEfficiency: '機械効率 [%]',
    generatorEfficiency: '発電機効率 [%]',
    pressureLevel1: 'レベル1 (高圧)',
    pressureLevel2: 'レベル2 (中圧)',
    pressureLevel3: 'レベル3 (低圧)',
    extraction1: '抽気1',
    extraction2: '抽気2',
    extraction3: '抽気3',
    performanceResults: '性能結果',
    steamVaporProperties: '入口蒸気特性',
    inletEnthalpy: '入口エンタルピ',
    inletEntropy: '入口エントロピ',
    saturationTemperature: '飽和温度',
    superheating: '過熱度',
    electricPower: '電気出力',
    mechanicalPower: '機械出力',
    specificWork: '比仕事',
    specificConsumption: '比蒸気消費量',
    globalEfficiency: '総合効率',
    expansionRatio: '膨張比',
    carnotEfficiency: 'カルノー効率',
    remainingFlow: '残流量',
    extractionDetails: '抽気詳細',
    performanceCurves: '流量による性能曲線',
    bar: 'bar',
    percent: '%',
    kW: 'kW',
    MW: 'MW',
    kJperKg: 'kJ/kg',
    kJperKgK: 'kJ/kg·K',
    kgperKWh: 'kg/kWh',
    degreeC: '°C',
    Nm3perH: 'Nm³/h',
    tonperH: 't/h',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: '水管ボイラー計算機',
    dimensioningEN12952: 'EN 12952-3に基づく設計',
    basicData: '基本データ',
    serviceTemperature: '使用温度 [°C]',
    servicePressure : '使用圧力 [bar]',
    vaporFlow: '蒸気流量 [kg/h]',
    feedwaterTemp: '給水温度 [°C]',
    wasteHHV: '廃棄物高位発熱量 [MJ/kg]',
    combustionEfficiency: '燃焼効率 [%]',
    materialCharacteristics: '材料特性',
    material: '材料',
    admissibleStress: '許容応力 [N/mm²]',
    weldingCoefficient: '溶接係数',
    corrosionAllowance: '腐食余裕 [mm]',
    bodyGeometry: 'ボディ形状',
    bodyInnerDiameter: 'ボディ内径 [mm]',
    bodyLength: 'ボディ長さ [mm]',
    tubeNumber: 'チューブ数',
    tubeOuterDiameter: 'チューブ外径 [mm]',
    tubeInnerDiameter: 'チューブ内径 [mm]',
    checks: 'チェック',
    mainResults: '主要結果',
    calculationPressure: '計算圧力',
    bodyThickness: 'ボディ厚さ',
    tubeThickness: 'チューブ厚さ',
    steamPower: '蒸気出力',
    errorMessage: 'エラー: ',
    conformityCheck: 'EN 12952-3要件に準拠した設計',
    warningThickness: 'ボディ厚さ < 6 mm - 最小厚さを確認',
    warningFluxDensity: '高熱流密度 - スケーリングのリスク',
    errorVelocity: '過度な速度 - 臨界侵食のリスク',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: '廃熱回収ボイラー設定',
    steamParameters: '蒸気パラメータ',
    flueGases: '排ガス',
    steamValorization: '蒸気利用',
    whbDesign: '廃熱ボイラー設計',
    whbOpex: '廃熱ボイラー運用費',
    boilerDimensioning: 'ボイラー寸法設計',
  },

  ar: {
    // ===== COMMUNES =====
    calculationParameters: 'معاملات الحساب',
    calculatedParameters: 'المعاملات المحسوبة',
    resetValues: 'إعادة تعيين القيم',
    resetDefaultValues: 'إعادة تعيين إلى القيم الافتراضية',
    clearMemory: 'مسح الذاكرة',
    export: 'تصدير',
    backToFlow: 'العودة إلى التدفق',
    sendData: 'إرسال البيانات',
    title: 'إعدادات غلاية استعادة الحرارة',

    stepMM: 'خطوة الحساب [ملم]',
    chaleurRecuperee: 'الحرارة المستعادة [كيلوواط]',
    surfaceTotal: 'إجمالي مساحة التبادل [م²]',

    // ===== VALORISATION VAPEUR =====
    sansTurbine: 'بدون توربين',
    sansTurbineDesc: 'حساب خصائص البخار فقط',
    contrepression: 'الضغط المعاكس',
    contrepressionDesc: 'الاستخراج عند ضغط ثابت',
    deuxEtages: 'مرحلتان',
    deuxEtagesDesc: 'توربين ذو مرحلتي توسع',
    troisEtages: 'ثلاث مراحل',
    troisEtagesDesc: 'توربين ذو ثلاث مراحل توسع',
    condensationVide: 'التكثيف (فراغ)',
    condensationVideDesc: 'التكثيف تحت الفراغ',
    pressureLevelsConfiguration: 'إعدادات مستويات الضغط',
    extractionConfiguration: 'إعدادات الاستخراج',
    totalFlows: 'إجمالي التدفقات',
    quality: 'جودة',
    wetSteamWarning: 'بخار رطب - وجود قطرات ماء',

    // ===== 1_WHB_PARAMETERS =====
    boilerCalculationParameters: 'معاملات حساب الغلاية',
    flueGasCalculation: 'حساب غازات المداخن',
    feedWaterCalculation: 'حساب ماء التغذية',
    steamCalculation: 'حساب البخار',
    drumParameters: 'معاملات الأسطوانة',
    boilerOutletTemperature: 'درجة حرارة مخرج الغلاية [°C]',
    estimatedThermalLoss: 'الخسائر الحرارية المقدرة [%]',
    feedwaterTemperature: 'درجة حرارة ماء التغذية [°C]',
    steamType: 'نوع البخار',
    superheatedSteamTemperature: 'درجة حرارة البخار الجاف [°C]',
    boilerPressure: 'ضغط الغلاية [بار]',
    blowdownRate: 'معدل النفخ [%]',
    saturated: 'مشبع',
    superheated: 'جاف',
    flueGasTemperatureInlet: 'درجة حرارة غازات المداخن عند المدخل [°C]',
    flueGasEnthalpyIn: 'الإنثالبيا في المدخل [كيلوجول/ساعة]',
    flueGasEnthalpyOut: 'الإنثالبيا في المخرج [كيلوجول/ساعة]',
    flueGasEnthalpyDifference: 'فرق الإنثالبيا [كيلوجول/ساعة]',
    feedwaterFlow: 'تدفق ماء التغذية [كجم/ساعة]',
    feedwaterPressure: 'ضغط ماء التغذية [بار]',
    blowdownMassFlow: 'معدل التدفق الكتلي للنفخ [كجم/ساعة]',
    enthalpyFeedwater: 'إنثالبيا ماء التغذية [كيلوواط]',
    saturatedSteamTemperature: 'درجة حرارة البخار المشبع [°C]',
    deltaEnthalpies: 'دلتا الإنثالبيا [كيلوجول/ساعة]',
    steamEnthalpy: 'إنثالبيا البخار [كيلوجول/ساعة]',
    steamFlow: 'تدفق البخار [كجم/ساعة]',
    ventFlashSteamDrum: 'تنفيس/وميض الأسطوانة [كيلوجول/ساعة]',
    liquidRejected: 'السائل المرفوض [كجم/ساعة]',

    // ===== 2_WHB_FLUE_GAS =====
    flueGasTemperatureOutlet: 'درجة حرارة غازات المداخن عند المخرج [°C]',
    ambiantAirTemperature: 'درجة حرارة الهواء المحيط [°C]',
    volumeAirIngrease: 'حجم إمداد الهواء [متر مكعب قياسي/ساعة]',
    temperatureInletWHB: 'درجة الحرارة عند مدخل غلاية استعادة الحرارة [°C]',
    temperatureOutletWHB: 'درجة الحرارة عند مخرج غلاية استعادة الحرارة [°C]',
    flueGasComposition: 'تركيب غازات المداخن',
    flueGasInlet: 'غازات المداخن عند المدخل',
    flueGasOutlet: 'غازات المداخن عند المخرج',
    airIngrease: 'إمداد الهواء المحيط',
    flueGasOutletConsideringAirIngrease: 'غازات المداخن مع مراعاة إمداد الهواء',

    // ===== 3_WHB_POLLUTANT_EMISSION =====
    pollutantEmissions: 'انبعاثات الملوثات',
    flyAshesContentOutlet: 'محتوى الرماد الطائر [غرام/متر مكعب قياسي]',
    siccityBottomAsh: 'جفاف الرماد الثقيل [%]',
    o2Ref: 'O2 المرجعي [%]',
    wasteFlow: 'تدفق النفايات [كجم/ساعة]',
    flueGasFlowWet: 'تدفق غازات المداخن (رطب) [متر مكعب قياسي/ساعة]',
    flueGasFlowDry: 'تدفق غازات المداخن (جاف) [متر مكعب قياسي/ساعة]',
    o2Calculated: 'O2 المحسوب [%]',
    inputFlueGas: 'غازات المداخن المدخلة',
    outputFlueGas: 'غازات المداخن المخرجة',
    residuesCalculated: 'البقايا المحسوبة',
    boilerAsh: 'رماد الغلاية [كجم/ساعة]',

    // ===== 4_WHB_DESIGN =====
    aeraulicPressureLoss: 'فقدان الضغط الديناميكي الهوائي',
    thermicalLossParameters: 'معاملات الخسائر الحرارية',
    rotaryKilnDesign: 'تصميم الفرن الدوار',
    lanceEstimation: 'تقدير الرماح',
    facadeCooling: 'تبريد الواجهة',
    facadeThermicalLosses: 'الخسائر الحرارية للواجهة',
    shellCooling: 'تبريد الجسم',
    sccDimensioning: 'تحديد حجم SCC',
    sccBurners: 'موارد SCC',
    sccThermicalLosses: 'الخسائر الحرارية SCC',
    extractorConsumption: 'استهلاك المستخلص',
    combustionAirFan: 'مروحة هواء الاحتراق',
    extractorWaterEvaporation: 'تبخر ماء المستخلص',
    poutMmce: 'ضغط المخرج [ملم من الماء]',
    waterRecallConsumption: 'استدعاء استهلاك المياه',
    waterPurgeLosses: 'فقدان ماء النفخ [كجم/ساعة]',

    // ===== 5_TURBINE_CALCULATOR =====
    electricalProductionCalculator: 'حاسبة الإنتاج الكهربائي',
    turbineVaporWithTaps: 'توربين بخار مع استخراجات',
    estimationPerformances: 'تقدير الأداء',
    turbineConfiguration: 'إعدادات التوربين',
    turbineType: 'نوع التوربين',
    inletPressure: 'ضغط المدخل [بار]',
    inletTemperature: 'درجة حرارة المدخل [°C]',
    outletPressure: 'ضغط المخرج [بار]',
    ambientTemperature: 'درجة حرارة المحيط [°C]',
    efficiencyParameters: 'معاملات الكفاءة',
    turbineEfficiency: 'كفاءة التوربين [%]',
    mechanicalEfficiency: 'الكفاءة الميكانيكية [%]',
    generatorEfficiency: 'كفاءة المولد [%]',
    pressureLevel1: 'المستوى 1 (ضغط عالي)',
    pressureLevel2: 'المستوى 2 (ضغط متوسط)',
    pressureLevel3: 'المستوى 3 (ضغط منخفض)',
    extraction1: 'الاستخراج 1',
    extraction2: 'الاستخراج 2',
    extraction3: 'الاستخراج 3',
    performanceResults: 'نتائج الأداء',
    steamVaporProperties: 'خصائص البخار عند المدخل',
    inletEnthalpy: 'الإنثالبيا عند المدخل',
    inletEntropy: 'الإنتروبيا عند المدخل',
    saturationTemperature: 'درجة حرارة التشبع',
    superheating: 'التجفيف',
    electricPower: 'القوة الكهربائية',
    mechanicalPower: 'القوة الميكانيكية',
    specificWork: 'العمل النوعي',
    specificConsumption: 'الاستهلاك النوعي',
    globalEfficiency: 'الكفاءة الإجمالية',
    expansionRatio: 'نسبة التوسع',
    carnotEfficiency: 'كفاءة كارنو',
    remainingFlow: 'التدفق المتبقي',
    extractionDetails: 'تفاصيل الاستخراج',
    performanceCurves: 'منحنيات الأداء حسب معدل التدفق',
    bar: 'بار',
    percent: '%',
    kW: 'كيلوواط',
    MW: 'ميجاواط',
    kJperKg: 'كيلوجول/كيلوجرام',
    kJperKgK: 'كيلوجول/كيلوجرام·كلفن',
    kgperKWh: 'كيلوجرام/كيلوواط ساعة',
    degreeC: '°C',
    Nm3perH: 'متر مكعب قياسي/ساعة',
    tonperH: 'طن/ساعة',

    // ===== 6_BOILER_CALCULATOR =====
    boilerTubesCalculator: 'حاسبة غلاية الأنابيب المائية',
    dimensioningEN12952: 'التحديد وفقاً لـ EN 12952-3',
    basicData: 'البيانات الأساسية',
    serviceTemperature: 'درجة حرارة الخدمة [°C]',
    servicePressure : 'ضغط الخدمة [بار]',
    vaporFlow: 'تدفق البخار [كجم/ساعة]',
    feedwaterTemp: 'درجة حرارة ماء التغذية [°C]',
    wasteHHV: 'القيمة الحرارية العليا للنفايات [ميجاجول/كيلوجرام]',
    combustionEfficiency: 'كفاءة الاحتراق [%]',
    materialCharacteristics: 'خصائص المواد',
    material: 'المادة',
    admissibleStress: 'الإجهاد المسموح به [نيوتن/ملم²]',
    weldingCoefficient: 'معامل اللحام',
    corrosionAllowance: 'بدل التآكل [ملم]',
    bodyGeometry: 'هندسة الجسم',
    bodyInnerDiameter: 'القطر الداخلي للجسم [ملم]',
    bodyLength: 'طول الجسم [ملم]',
    tubeNumber: 'عدد الأنابيب',
    tubeOuterDiameter: 'القطر الخارجي للأنابيب [ملم]',
    tubeInnerDiameter: 'القطر الداخلي للأنابيب [ملم]',
    checks: 'الفحوصات',
    mainResults: 'النتائج الرئيسية',
    calculationPressure: 'ضغط الحساب',
    bodyThickness: 'سمك الجسم',
    tubeThickness: 'سمك الأنابيب',
    steamPower: 'قوة البخار',
    errorMessage: 'خطأ: ',
    conformityCheck: 'التحديد متطابق مع متطلبات EN 12952-3',
    warningThickness: 'سمك الجسم < 6 ملم - التحقق من الحد الأدنى للسمك',
    warningFluxDensity: 'كثافة التدفق عالية - خطر التصلب',
    errorVelocity: 'السرعة الزائدة - خطر التآكل الحرج',

    // ===== 7_WHB_MAIN_PAGE =====
    wasteHeatBoilerConfiguration: 'إعدادات غلاية استعادة الحرارة',
    steamParameters: 'معاملات البخار',
    flueGases: 'غازات المداخن',
    steamValorization: 'استخدام البخار',
    whbDesign: 'تصميم غلاية استعادة الحرارة',
    whbOpex: 'تكاليف التشغيل لغلاية استعادة الحرارة',
    boilerDimensioning: 'تحديد حجم الغلاية',
  },

};
