export const translations = {
  // ========================================
  // FRANÇAIS
  // ========================================
  fr: {
    // === Common / Commun ===
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Clear memory': 'Effacer la mémoire',
    'Flue gas composition': 'Composition des fumées',
    'Input flue gas': 'Fumées en entrée',
    'Output flue gas': 'Fumées en sortie',
    'Residues calculated': 'Résidus calculés',

    // === Equipment Configuration / Configuration des équipements ===
    'Equipment Configuration': 'Configuration des équipements',
    'Fan Type': 'Type de ventilateur',
    'Motor Type': 'Type de moteur',
    'Transmission Type': 'Type de transmission',

    // === Fan Types / Types de ventilateurs ===
    'Optimized centrifugal fan': 'Ventilateur centrifuge optimisé',
    'Standard centrifugal fan': 'Ventilateur centrifuge standard',
    'Optimized axial fan': 'Ventilateur axial optimisé',
    'Standard axial fan': 'Ventilateur axial standard',

    // === Motor Types / Types de moteurs ===
    'High efficiency motor (IE3/IE4)': 'Moteur haute efficacité (IE3/IE4)',
    'Standard motor (IE2)': 'Moteur standard (IE2)',

    // === Transmission Types / Types de transmission ===
    'Direct transmission': 'Transmission directe',
    'Belt transmission': 'Transmission par courroies',
    'Gear reducer': 'Réducteur à engrenages',

    // === Input Parameters / Paramètres d'entrée ===
    'Electrical yield [%]': 'Rendement électrique [%]',
    'Radiative losses [%]': 'Pertes radiatives [%]',
    'Outlet pressure [mmCE]': 'Pression de sortie [mmCE]',
    'Ambient air temperature [°C]': 'Température de l\'air ambiant [°C]',
    'Safety factor [-]': 'Facteur de sécurité [-]',
    'Fly ashes content outlet [g/Nm3]': 'Teneur en cendres volantes sortie [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité des mâchefers [%]',
    'O2 ref [%]': 'O2 référence [%]',

    // === Calculated Values / Valeurs calculées ===
    'Flow rate [m³/h at conditions]': 'Débit volumique [m³/h aux conditions]',
    'Total pressure drop [mmCE]': 'Perte de charge totale [mmCE]',
    'Aeraulic power [kW]': 'Puissance aéraulique [kW]',
    'Mechanical power [kW]': 'Puissance mécanique [kW]',
    'Electrical power (before safety) [kWe]': 'Puissance électrique (avant sécurité) [kWe]',
    'Electrical power (with safety) [kWe]': 'Puissance électrique (avec sécurité) [kWe]',
    'Fan efficiency [%]': 'Rendement ventilateur [%]',
    'Motor efficiency [%]': 'Rendement moteur [%]',
    'Transmission efficiency [%]': 'Rendement transmission [%]',
    'Global efficiency [%]': 'Rendement global [%]',
    'Temperature inlet IDFAN [°C]': 'Température entrée IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Température sortie IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Élévation de température (calculée) [°C]',
    'Power transmitted to flue gas [kW]': 'Puissance transmise aux fumées [kW]',
    'Power lost to ambient [kW]': 'Puissance perdue vers l\'ambiance [kW]',
    'Pressure inlet [mmCE]': 'Pression entrée [mmCE]',
    'Waste Flow [kg/h]': 'Débit de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit de fumées humides [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit de fumées sèches [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'Fly ash inlet [kg/h]': 'Cendres volantes entrée [kg/h]',
    'Fly ash outlet [kg/h]': 'Cendres volantes sortie [kg/h]',
    'IDFAN ash collected [kg/h]': 'Cendres collectées IDFAN [kg/h]',
    'Flue gas inlet at inlet temperature': 'Fumées en entrée à la température d\'entrée',
    'Flue gas outlet at outlet temperature': 'Fumées en sortie à la température de sortie',

    // === Help Page / Page d'aide ===
    'ID FAN (Induced Draft Fan)': 'ID FAN (Ventilateur de Tirage Induit)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Pour un ID FAN (ventilateur de tirage induit), le rendement global typique se situe entre 60% et 75%, selon la configuration et la qualité des équipements.',
    'Detail by component:': 'Détail par composant :',
    'Centrifugal fan': 'Ventilateur centrifuge',
    'Efficiency: 70-80% (optimized)': 'Rendement : 70-80% (optimisé)',
    'Efficiency: 60-75% (standard)': 'Rendement : 60-75% (standard)',
    'Electric motor': 'Moteur électrique',
    'Efficiency: 90-95% (high efficiency motor)': 'Rendement : 90-95% (moteur haute efficacité)',
    'Efficiency: 85-92% (standard motor)': 'Rendement : 85-92% (moteur standard)',
    'Transmission': 'Transmission',
    'Direct: 98-99%': 'Directe : 98-99%',
    'Belts: 94-96%': 'Courroies : 94-96%',
    'Gear reducer: 95-98%': 'Réducteur : 95-98%',
    'Overall efficiency calculation:': 'Calcul du rendement global :',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_ventilateur × η_moteur × η_transmission',
    'Optimal configuration:': 'Configuration optimale :',
    'Fan: 75%': 'Ventilateur : 75%',
    'Motor: 93%': 'Moteur : 93%',
    'Direct transmission: 98%': 'Transmission directe : 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Rendement global = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Configuration standard :',
    'Fan: 65%': 'Ventilateur : 65%',
    'Motor: 90%': 'Moteur : 90%',
    'Belt transmission: 95%': 'Transmission par courroies : 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Rendement global = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Recommandations pour votre code :',
    'For typical industrial applications, I recommend these default values:': 'Pour des applications industrielles typiques, je recommande ces valeurs par défaut :',
    'Realistic for a good fan': 'Réaliste pour un bon ventilateur',
    'Standard IE3 motor': 'Moteur IE3 standard',
    'Quality belt transmission': 'Transmission par courroies de qualité',
    'Standard safety factor': 'Facteur de sécurité standard',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Rendement global résultant : 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Facteurs d\'influence :',
    'Size: Large fans have better efficiencies': 'Taille : Les gros ventilateurs ont de meilleurs rendements',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Point de fonctionnement : Optimal près du BEP (Best Efficiency Point)',
    'Wear: Efficiency decreases with fouling': 'Usure : Le rendement diminue avec l\'encrassement',
    'Variable speed: Improves efficiency at partial load': 'Vitesse variable : Améliore l\'efficacité à charge partielle',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Un rendement global de 65% est une bonne valeur de référence pour un ID FAN bien dimensionné.',

    // === IDFAN_Report keys ===
    'Ventilateur d\'Extraction (ID Fan) — Rapport de synthèse': 'Ventilateur d\'Extraction (ID Fan) — Rapport de synthèse',
    '1. Gaz de combustion': '1. Gaz de combustion',
    'Température de sortie': 'Température de sortie',
    'O₂ mesuré (sec)': 'O₂ mesuré (sec)',
    'Débit humide total [kg/h]': 'Débit humide total [kg/h]',
    'Débit sec [Nm³/h]': 'Débit sec [Nm³/h]',
    'Débit humide [Nm³/h]': 'Débit humide [Nm³/h]',
    'Composition gaz de sortie': 'Composition gaz de sortie',
    '2. Émissions polluantes': '2. Émissions polluantes',
    'Gaz en entrée [kg/h]': 'Gaz en entrée [kg/h]',
    'Gaz en sortie [kg/h]': 'Gaz en sortie [kg/h]',
    '3. OPEX — Coûts horaires': '3. OPEX — Coûts horaires',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.': 'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.',
    'Total coût': 'Total coût',
    'Coût horaire': 'Coût horaire',
    'Coût annuel': 'Coût annuel',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ électricité',
    'Total CO₂': 'Total CO₂',
    'Électricité': 'Électricité',
    'Air': 'Air',
    'Rapport généré automatiquement': 'Rapport généré automatiquement',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Ventilateur d\'Extraction (ID Fan) — Rapport de synthèse',
    combustionGases: 'Gaz de combustion',
    outletTemp: 'Température de sortie',
    o2Dry: 'O₂ mesuré (sec)',
    wetFlowTotal: 'Débit humide total [kg/h]',
    dryFlowNm3h: 'Débit sec [Nm³/h]',
    wetFlowNm3h: 'Débit humide [Nm³/h]',
    outletGasComposition: 'Composition gaz de sortie',
    pollutantEmissions: 'Émissions polluantes',
    gasInlet: 'Gaz en entrée [kg/h]',
    gasOutlet: 'Gaz en sortie [kg/h]',
    opexHourlyCosts: 'OPEX — Coûts horaires',
    noOpexData: 'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.',
    totalCost: 'Total coût',
    hourlyCost: 'Coût horaire',
    annualCost: 'Coût annuel',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ électricité',
    totalCO2label: 'Total CO₂',
    electricityTag: 'Électricité',
    airTag: 'Air',
    autoReport: 'Rapport généré automatiquement',
    'IDFAN Configuration': 'Configuration IDFAN',
    'Flue gases': 'Gaz de fumée',
    'Pollutant Emissions': 'Émissions de polluants',
    'Opex': 'Opex',
    'Rapport': 'Rapport',
    'Back to Flow': 'Retour au flux',
  },

  // ========================================
  // ENGLISH
  // ========================================
  en: {
    // === Common ===
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Clear memory': 'Clear memory',
    'Flue gas composition': 'Flue gas composition',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',
    'Residues calculated': 'Residues calculated',

    // === Equipment Configuration ===
    'Equipment Configuration': 'Equipment Configuration',
    'Fan Type': 'Fan Type',
    'Motor Type': 'Motor Type',
    'Transmission Type': 'Transmission Type',

    // === Fan Types ===
    'Optimized centrifugal fan': 'Optimized centrifugal fan',
    'Standard centrifugal fan': 'Standard centrifugal fan',
    'Optimized axial fan': 'Optimized axial fan',
    'Standard axial fan': 'Standard axial fan',

    // === Motor Types ===
    'High efficiency motor (IE3/IE4)': 'High efficiency motor (IE3/IE4)',
    'Standard motor (IE2)': 'Standard motor (IE2)',

    // === Transmission Types ===
    'Direct transmission': 'Direct transmission',
    'Belt transmission': 'Belt transmission',
    'Gear reducer': 'Gear reducer',

    // === Input Parameters ===
    'Electrical yield [%]': 'Electrical yield [%]',
    'Radiative losses [%]': 'Radiative losses [%]',
    'Outlet pressure [mmCE]': 'Outlet pressure [mmWC]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Safety factor [-]': 'Safety factor [-]',
    'Fly ashes content outlet [g/Nm3]': 'Fly ashes content outlet [g/Nm3]',
    'siccity bottom ash [%]': 'Siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',

    // === Calculated Values ===
    'Flow rate [m³/h at conditions]': 'Flow rate [m³/h at conditions]',
    'Total pressure drop [mmCE]': 'Total pressure drop [mmWC]',
    'Aeraulic power [kW]': 'Aeraulic power [kW]',
    'Mechanical power [kW]': 'Mechanical power [kW]',
    'Electrical power (before safety) [kWe]': 'Electrical power (before safety) [kWe]',
    'Electrical power (with safety) [kWe]': 'Electrical power (with safety) [kWe]',
    'Fan efficiency [%]': 'Fan efficiency [%]',
    'Motor efficiency [%]': 'Motor efficiency [%]',
    'Transmission efficiency [%]': 'Transmission efficiency [%]',
    'Global efficiency [%]': 'Global efficiency [%]',
    'Temperature inlet IDFAN [°C]': 'Temperature inlet IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Temperature outlet IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Temperature rise (calculated) [°C]',
    'Power transmitted to flue gas [kW]': 'Power transmitted to flue gas [kW]',
    'Power lost to ambient [kW]': 'Power lost to ambient [kW]',
    'Pressure inlet [mmCE]': 'Pressure inlet [mmWC]',
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'Fly ash inlet [kg/h]': 'Fly ash inlet [kg/h]',
    'Fly ash outlet [kg/h]': 'Fly ash outlet [kg/h]',
    'IDFAN ash collected [kg/h]': 'IDFAN ash collected [kg/h]',
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',

    // === Help Page ===
    'ID FAN (Induced Draft Fan)': 'ID FAN (Induced Draft Fan)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.',
    'Detail by component:': 'Detail by component:',
    'Centrifugal fan': 'Centrifugal fan',
    'Efficiency: 70-80% (optimized)': 'Efficiency: 70-80% (optimized)',
    'Efficiency: 60-75% (standard)': 'Efficiency: 60-75% (standard)',
    'Electric motor': 'Electric motor',
    'Efficiency: 90-95% (high efficiency motor)': 'Efficiency: 90-95% (high efficiency motor)',
    'Efficiency: 85-92% (standard motor)': 'Efficiency: 85-92% (standard motor)',
    'Transmission': 'Transmission',
    'Direct: 98-99%': 'Direct: 98-99%',
    'Belts: 94-96%': 'Belts: 94-96%',
    'Gear reducer: 95-98%': 'Gear reducer: 95-98%',
    'Overall efficiency calculation:': 'Overall efficiency calculation:',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_fan × η_motor × η_transmission',
    'Optimal configuration:': 'Optimal configuration:',
    'Fan: 75%': 'Fan: 75%',
    'Motor: 93%': 'Motor: 93%',
    'Direct transmission: 98%': 'Direct transmission: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%',
    'Standard configuration:': 'Standard configuration:',
    'Fan: 65%': 'Fan: 65%',
    'Motor: 90%': 'Motor: 90%',
    'Belt transmission: 95%': 'Belt transmission: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%',
    'Recommendations for your code:': 'Recommendations for your code:',
    'For typical industrial applications, I recommend these default values:': 'For typical industrial applications, I recommend these default values:',
    'Realistic for a good fan': 'Realistic for a good fan',
    'Standard IE3 motor': 'Standard IE3 motor',
    'Quality belt transmission': 'Quality belt transmission',
    'Standard safety factor': 'Standard safety factor',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Resulting overall efficiency: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Influencing factors:',
    'Size: Large fans have better efficiencies': 'Size: Large fans have better efficiencies',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Operating point: Optimal near BEP (Best Efficiency Point)',
    'Wear: Efficiency decreases with fouling': 'Wear: Efficiency decreases with fouling',
    'Variable speed: Improves efficiency at partial load': 'Variable speed: Improves efficiency at partial load',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.',

    // === IDFAN_Report keys ===
    'Ventilateur d\'Extraction (ID Fan) — Rapport de synthèse': 'ID Fan (Induced Draft Fan) — Synthesis Report',
    '1. Gaz de combustion': '1. Flue Gas',
    'Température de sortie': 'Outlet temperature',
    'O₂ mesuré (sec)': 'O₂ measured (dry)',
    'Débit humide total [kg/h]': 'Total wet flow [kg/h]',
    'Débit sec [Nm³/h]': 'Dry flow [Nm³/h]',
    'Débit humide [Nm³/h]': 'Wet flow [Nm³/h]',
    'Composition gaz de sortie': 'Outlet gas composition',
    '2. Émissions polluantes': '2. Pollutant Emissions',
    'Gaz en entrée [kg/h]': 'Inlet gas [kg/h]',
    'Gaz en sortie [kg/h]': 'Outlet gas [kg/h]',
    '3. OPEX — Coûts horaires': '3. OPEX — Hourly costs',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.': 'OPEX costs unavailable — open Opex tab.',
    'Total coût': 'Total cost',
    'Coût horaire': 'Hourly cost',
    'Coût annuel': 'Annual cost',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricity',
    'Total CO₂': 'Total CO₂',
    'Électricité': 'Electricity',
    'Air': 'Air',
    'Rapport généré automatiquement': 'Automatically generated report',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'ID Fan (Induced Draft Fan) — Synthesis Report',
    combustionGases: 'Flue Gas',
    outletTemp: 'Outlet temperature',
    o2Dry: 'O₂ measured (dry)',
    wetFlowTotal: 'Total wet flow [kg/h]',
    dryFlowNm3h: 'Dry flow [Nm³/h]',
    wetFlowNm3h: 'Wet flow [Nm³/h]',
    outletGasComposition: 'Outlet gas composition',
    pollutantEmissions: 'Pollutant Emissions',
    gasInlet: 'Inlet gas [kg/h]',
    gasOutlet: 'Outlet gas [kg/h]',
    opexHourlyCosts: 'OPEX — Hourly costs',
    noOpexData: 'OPEX costs unavailable — open Opex tab.',
    totalCost: 'Total cost',
    hourlyCost: 'Hourly cost',
    annualCost: 'Annual cost',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricity',
    totalCO2label: 'Total CO₂',
    electricityTag: 'Electricity',
    airTag: 'Air',
    autoReport: 'Automatically generated report',
    'IDFAN Configuration': 'IDFAN Configuration',
    'Flue gases': 'Flue gases',
    'Pollutant Emissions': 'Pollutant Emissions',
    'Opex': 'Opex',
    'Rapport': 'Report',
    'Back to Flow': 'Back to Flow',
  },

  es: {
    'Calculation parameters': 'Parámetros de cálculo',
    'Calculated parameters': 'Parámetros calculados',
    'Clear memory': 'Borrar memoria',
    'Flue gas composition': 'Composición de gases de combustión',
    'Input flue gas': 'Gases de entrada',
    'Output flue gas': 'Gases de salida',
    'Residues calculated': 'Residuos calculados',
    'Equipment Configuration': 'Configuración de equipos',
    'Fan Type': 'Tipo de ventilador',
    'Motor Type': 'Tipo de motor',
    'Transmission Type': 'Tipo de transmisión',
    'Optimized centrifugal fan': 'Ventilador centrífugo optimizado',
    'Standard centrifugal fan': 'Ventilador centrífugo estándar',
    'Optimized axial fan': 'Ventilador axial optimizado',
    'Standard axial fan': 'Ventilador axial estándar',
    'High efficiency motor (IE3/IE4)': 'Motor de alta eficiencia (IE3/IE4)',
    'Standard motor (IE2)': 'Motor estándar (IE2)',
    'Direct transmission': 'Transmisión directa',
    'Belt transmission': 'Transmisión por correa',
    'Gear reducer': 'Reductor de engranajes',
    'Electrical yield [%]': 'Rendimiento eléctrico [%]',
    'Radiative losses [%]': 'Pérdidas radiativas [%]',
    'Outlet pressure [mmCE]': 'Presión de salida [mmCA]',
    'Ambient air temperature [°C]': 'Temperatura del aire ambiente [°C]',
    'Safety factor [-]': 'Factor de seguridad [-]',
    'Fly ashes content outlet [g/Nm3]': 'Contenido cenizas volantes salida [g/Nm3]',
    'siccity bottom ash [%]': 'Siccidad escorias [%]',
    'O2 ref [%]': 'O2 referencia [%]',
    'Flow rate [m³/h at conditions]': 'Caudal [m³/h en condiciones]',
    'Total pressure drop [mmCE]': 'Caída de presión total [mmCA]',
    'Aeraulic power [kW]': 'Potencia aeráulica [kW]',
    'Mechanical power [kW]': 'Potencia mecánica [kW]',
    'Electrical power (before safety) [kWe]': 'Potencia eléctrica (antes seguridad) [kWe]',
    'Electrical power (with safety) [kWe]': 'Potencia eléctrica (con seguridad) [kWe]',
    'Fan efficiency [%]': 'Rendimiento ventilador [%]',
    'Motor efficiency [%]': 'Rendimiento motor [%]',
    'Transmission efficiency [%]': 'Rendimiento transmisión [%]',
    'Global efficiency [%]': 'Rendimiento global [%]',
    'Temperature inlet IDFAN [°C]': 'Temperatura entrada IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Temperatura salida IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Elevación de temperatura (calculada) [°C]',
    'Power transmitted to flue gas [kW]': 'Potencia transmitida a gases [kW]',
    'Power lost to ambient [kW]': 'Potencia perdida al ambiente [kW]',
    'Pressure inlet [mmCE]': 'Presión entrada [mmCA]',
    'Waste Flow [kg/h]': 'Caudal de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Caudal gases húmedos [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Caudal gases secos [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'Fly ash inlet [kg/h]': 'Cenizas volantes entrada [kg/h]',
    'Fly ash outlet [kg/h]': 'Cenizas volantes salida [kg/h]',
    'IDFAN ash collected [kg/h]': 'Cenizas recolectadas IDFAN [kg/h]',
    'Flue gas inlet at inlet temperature': 'Gases en entrada a temperatura de entrada',
    'Flue gas outlet at outlet temperature': 'Gases en salida a temperatura de salida',
    'ID FAN (Induced Draft Fan)': 'ID FAN (Ventilador de Tiro Inducido)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Para un ID FAN, el rendimiento global típico está entre 60% y 75%.',
    'Detail by component:': 'Detalle por componente:',
    'Centrifugal fan': 'Ventilador centrífugo',
    'Efficiency: 70-80% (optimized)': 'Rendimiento: 70-80% (optimizado)',
    'Efficiency: 60-75% (standard)': 'Rendimiento: 60-75% (estándar)',
    'Electric motor': 'Motor eléctrico',
    'Efficiency: 90-95% (high efficiency motor)': 'Rendimiento: 90-95% (motor alta eficiencia)',
    'Efficiency: 85-92% (standard motor)': 'Rendimiento: 85-92% (motor estándar)',
    'Transmission': 'Transmisión',
    'Direct: 98-99%': 'Directa: 98-99%',
    'Belts: 94-96%': 'Correas: 94-96%',
    'Gear reducer: 95-98%': 'Reductor: 95-98%',
    'Overall efficiency calculation:': 'Cálculo del rendimiento global:',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_ventilador × η_motor × η_transmisión',
    'Optimal configuration:': 'Configuración óptima:',
    'Fan: 75%': 'Ventilador: 75%',
    'Motor: 93%': 'Motor: 93%',
    'Direct transmission: 98%': 'Transmisión directa: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Rendimiento global = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Configuración estándar:',
    'Fan: 65%': 'Ventilador: 65%',
    'Motor: 90%': 'Motor: 90%',
    'Belt transmission: 95%': 'Transmisión por correa: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Rendimiento global = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Recomendaciones:',
    'For typical industrial applications, I recommend these default values:': 'Para aplicaciones industriales típicas, se recomiendan estos valores por defecto:',
    'Realistic for a good fan': 'Realista para un buen ventilador',
    'Standard IE3 motor': 'Motor IE3 estándar',
    'Quality belt transmission': 'Transmisión por correa de calidad',
    'Standard safety factor': 'Factor de seguridad estándar',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Rendimiento global resultante: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Factores de influencia:',
    'Size: Large fans have better efficiencies': 'Tamaño: Los ventiladores grandes tienen mejores rendimientos',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Punto de operación: Óptimo cerca del BEP',
    'Wear: Efficiency decreases with fouling': 'Desgaste: El rendimiento disminuye con el ensuciamiento',
    'Variable speed: Improves efficiency at partial load': 'Velocidad variable: Mejora la eficiencia a carga parcial',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Un rendimiento global del 65% es un buen valor de referencia para un ID FAN bien dimensionado.',

    // === IDFAN_Report keys ===
    'Ventilateur d\'Extraction (ID Fan) — Rapport de synthèse': 'Ventilador de Extracción (ID Fan) — Informe de síntesis',
    '1. Gaz de combustion': '1. Gas de combustión',
    'Température de sortie': 'Temperatura de salida',
    'O₂ mesuré (sec)': 'O₂ medido (seco)',
    'Débit humide total [kg/h]': 'Caudal húmedo total [kg/h]',
    'Débit sec [Nm³/h]': 'Caudal seco [Nm³/h]',
    'Débit humide [Nm³/h]': 'Caudal húmedo [Nm³/h]',
    'Composition gaz de sortie': 'Composición gas de salida',
    '2. Émissions polluantes': '2. Emisiones contaminantes',
    'Gaz en entrée [kg/h]': 'Gas de entrada [kg/h]',
    'Gaz en sortie [kg/h]': 'Gas de salida [kg/h]',
    '3. OPEX — Coûts horaires': '3. OPEX — Costes horarios',
    'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.': 'Costes OPEX no disponibles — abrir pestaña Opex.',
    'Total coût': 'Coste total',
    'Coût horaire': 'Coste horario',
    'Coût annuel': 'Coste anual',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricidad',
    'Total CO₂': 'Total CO₂',
    'Électricité': 'Electricidad',
    'Air': 'Aire',
    'Rapport généré automatiquement': 'Informe generado automáticamente',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Ventilador de Tiro Inducido (ID Fan) — Informe de síntesis',
    combustionGases: 'Gases de combustión',
    outletTemp: 'Temperatura de salida',
    o2Dry: 'O₂ medido (seco)',
    wetFlowTotal: 'Caudal húmedo total [kg/h]',
    dryFlowNm3h: 'Caudal seco [Nm³/h]',
    wetFlowNm3h: 'Caudal húmedo [Nm³/h]',
    outletGasComposition: 'Composición del gas de salida',
    pollutantEmissions: 'Emisiones de contaminantes',
    gasInlet: 'Gas en entrada [kg/h]',
    gasOutlet: 'Gas en salida [kg/h]',
    opexHourlyCosts: 'OPEX — Costos horarios',
    noOpexData: 'Costos OPEX no disponibles — abrir pestaña Opex.',
    totalCost: 'Costo total',
    hourlyCost: 'Costo horario',
    annualCost: 'Costo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricidad',
    totalCO2label: 'Total CO₂',
    electricityTag: 'Electricidad',
    airTag: 'Aire',
    autoReport: 'Informe generado automáticamente',
    'IDFAN Configuration': 'Configuración IDFAN',
    'Flue gases': 'Gases de combustión',
    'Pollutant Emissions': 'Emisiones de contaminantes',
    'Opex': 'Opex',
    'Rapport': 'Informe',
    'Back to Flow': 'Volver al flujo',
  },

  de: {
    'Calculation parameters': 'Berechnungsparameter',
    'Calculated parameters': 'Berechnete Parameter',
    'Clear memory': 'Speicher löschen',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Input flue gas': 'Eingang Rauchgas',
    'Output flue gas': 'Ausgang Rauchgas',
    'Residues calculated': 'Berechnete Rückstände',
    'Equipment Configuration': 'Gerätekonfiguration',
    'Fan Type': 'Ventilatoryp',
    'Motor Type': 'Motortyp',
    'Transmission Type': 'Getriebetyp',
    'Optimized centrifugal fan': 'Optimierter Radialventilator',
    'Standard centrifugal fan': 'Standard-Radialventilator',
    'Optimized axial fan': 'Optimierter Axialventilator',
    'Standard axial fan': 'Standard-Axialventilator',
    'High efficiency motor (IE3/IE4)': 'Hocheffizienzmotor (IE3/IE4)',
    'Standard motor (IE2)': 'Standardmotor (IE2)',
    'Direct transmission': 'Direktantrieb',
    'Belt transmission': 'Riemenantrieb',
    'Gear reducer': 'Getriebereduzierer',
    'Electrical yield [%]': 'Elektrischer Wirkungsgrad [%]',
    'Radiative losses [%]': 'Strahlungsverluste [%]',
    'Outlet pressure [mmCE]': 'Ausgangsdruck [mmWS]',
    'Ambient air temperature [°C]': 'Umgebungslufttemperatur [°C]',
    'Safety factor [-]': 'Sicherheitsfaktor [-]',
    'Fly ashes content outlet [g/Nm3]': 'Flugaschegehalt Ausgang [g/Nm3]',
    'siccity bottom ash [%]': 'Restfeuchte Schlacke [%]',
    'O2 ref [%]': 'O2-Referenz [%]',
    'Flow rate [m³/h at conditions]': 'Volumenstrom [m³/h bei Betriebsbedingungen]',
    'Total pressure drop [mmCE]': 'Gesamtdruckverlust [mmWS]',
    'Aeraulic power [kW]': 'Aeraulische Leistung [kW]',
    'Mechanical power [kW]': 'Mechanische Leistung [kW]',
    'Electrical power (before safety) [kWe]': 'Elektrische Leistung (vor Sicherheit) [kWe]',
    'Electrical power (with safety) [kWe]': 'Elektrische Leistung (mit Sicherheit) [kWe]',
    'Fan efficiency [%]': 'Ventilatorwirkungsgrad [%]',
    'Motor efficiency [%]': 'Motorwirkungsgrad [%]',
    'Transmission efficiency [%]': 'Getriebewirkungsgrad [%]',
    'Global efficiency [%]': 'Gesamtwirkungsgrad [%]',
    'Temperature inlet IDFAN [°C]': 'Eintrittstemperatur IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Austrittstemperatur IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Temperaturerhöhung (berechnet) [°C]',
    'Power transmitted to flue gas [kW]': 'An Rauchgas übertragene Leistung [kW]',
    'Power lost to ambient [kW]': 'An Umgebung abgegebene Leistung [kW]',
    'Pressure inlet [mmCE]': 'Eintrittsdruck [mmWS]',
    'Waste Flow [kg/h]': 'Abfallstrom [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Feuchter Rauchgasstrom [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Trockener Rauchgasstrom [Nm3/h]',
    'O2 calculated [%]': 'O2 berechnet [%]',
    'Fly ash inlet [kg/h]': 'Flugasche Eingang [kg/h]',
    'Fly ash outlet [kg/h]': 'Flugasche Ausgang [kg/h]',
    'IDFAN ash collected [kg/h]': 'IDFAN gesammelte Asche [kg/h]',
    'Flue gas inlet at inlet temperature': 'Rauchgas am Eingang bei Eintrittstemperatur',
    'Flue gas outlet at outlet temperature': 'Rauchgas am Ausgang bei Austrittstemperatur',
    'ID FAN (Induced Draft Fan)': 'ID FAN (Saugzugventilator)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Für einen ID FAN liegt der typische Gesamtwirkungsgrad zwischen 60% und 75%.',
    'Detail by component:': 'Detail nach Komponente:',
    'Centrifugal fan': 'Radialventilator',
    'Efficiency: 70-80% (optimized)': 'Wirkungsgrad: 70-80% (optimiert)',
    'Efficiency: 60-75% (standard)': 'Wirkungsgrad: 60-75% (standard)',
    'Electric motor': 'Elektromotor',
    'Efficiency: 90-95% (high efficiency motor)': 'Wirkungsgrad: 90-95% (Hocheffizienzmotor)',
    'Efficiency: 85-92% (standard motor)': 'Wirkungsgrad: 85-92% (Standardmotor)',
    'Transmission': 'Getriebe',
    'Direct: 98-99%': 'Direkt: 98-99%',
    'Belts: 94-96%': 'Riemen: 94-96%',
    'Gear reducer: 95-98%': 'Getriebe: 95-98%',
    'Overall efficiency calculation:': 'Gesamtwirkungsgradberechnung:',
    'η_global = η_fan × η_motor × η_transmission': 'η_gesamt = η_Ventilator × η_Motor × η_Getriebe',
    'Optimal configuration:': 'Optimale Konfiguration:',
    'Fan: 75%': 'Ventilator: 75%',
    'Motor: 93%': 'Motor: 93%',
    'Direct transmission: 98%': 'Direktantrieb: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Gesamtwirkungsgrad = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Standardkonfiguration:',
    'Fan: 65%': 'Ventilator: 65%',
    'Motor: 90%': 'Motor: 90%',
    'Belt transmission: 95%': 'Riemenantrieb: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Gesamtwirkungsgrad = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Empfehlungen:',
    'For typical industrial applications, I recommend these default values:': 'Für typische Industrieanwendungen werden diese Standardwerte empfohlen:',
    'Realistic for a good fan': 'Realistisch für einen guten Ventilator',
    'Standard IE3 motor': 'Standard IE3-Motor',
    'Quality belt transmission': 'Qualitäts-Riemenantrieb',
    'Standard safety factor': 'Standard-Sicherheitsfaktor',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Resultierender Gesamtwirkungsgrad: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Einflussfaktoren:',
    'Size: Large fans have better efficiencies': 'Größe: Große Ventilatoren haben bessere Wirkungsgrade',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Betriebspunkt: Optimal nahe BEP',
    'Wear: Efficiency decreases with fouling': 'Verschleiß: Wirkungsgrad sinkt durch Verschmutzung',
    'Variable speed: Improves efficiency at partial load': 'Drehzahlregelung: Verbessert Effizienz bei Teillast',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Ein Gesamtwirkungsgrad von 65% ist ein guter Referenzwert für einen gut dimensionierten ID FAN.',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Saugzugventilator (ID Fan) — Synthesebericht',
    combustionGases: 'Rauchgase',
    outletTemp: 'Austrittstemperatur',
    o2Dry: 'O₂ gemessen (trocken)',
    wetFlowTotal: 'Gesamter Feuchtrauchgasstrom [kg/h]',
    dryFlowNm3h: 'Trockenstrom [Nm³/h]',
    wetFlowNm3h: 'Feuchtestrom [Nm³/h]',
    outletGasComposition: 'Ausgangsgaszusammensetzung',
    pollutantEmissions: 'Schadstoffemissionen',
    gasInlet: 'Eingangsgas [kg/h]',
    gasOutlet: 'Ausgangsgas [kg/h]',
    opexHourlyCosts: 'OPEX — Stündliche Kosten',
    noOpexData: 'OPEX-Kosten nicht verfügbar — Opex-Tab öffnen.',
    totalCost: 'Gesamtkosten',
    hourlyCost: 'Stundenkosten',
    annualCost: 'Jahreskosten',
    totalCO2: 'Gesamt-CO₂ [kg/h]',
    co2Electricity: 'CO₂ Elektrizität',
    totalCO2label: 'Gesamt-CO₂',
    electricityTag: 'Elektrizität',
    airTag: 'Luft',
    autoReport: 'Bericht automatisch erstellt',
    'IDFAN Configuration': 'IDFAN-Konfiguration',
    'Flue gases': 'Rauchgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Opex': 'Betriebskosten',
    'Rapport': 'Bericht',
    'Back to Flow': 'Zurück zum Fluss',
  },

  it: {
    'Calculation parameters': 'Parametri di calcolo',
    'Calculated parameters': 'Parametri calcolati',
    'Clear memory': 'Cancella memoria',
    'Flue gas composition': 'Composizione fumi',
    'Input flue gas': 'Fumi in ingresso',
    'Output flue gas': 'Fumi in uscita',
    'Residues calculated': 'Residui calcolati',
    'Equipment Configuration': 'Configurazione apparecchiature',
    'Fan Type': 'Tipo di ventilatore',
    'Motor Type': 'Tipo di motore',
    'Transmission Type': 'Tipo di trasmissione',
    'Optimized centrifugal fan': 'Ventilatore centrifugo ottimizzato',
    'Standard centrifugal fan': 'Ventilatore centrifugo standard',
    'Optimized axial fan': 'Ventilatore assiale ottimizzato',
    'Standard axial fan': 'Ventilatore assiale standard',
    'High efficiency motor (IE3/IE4)': 'Motore ad alta efficienza (IE3/IE4)',
    'Standard motor (IE2)': 'Motore standard (IE2)',
    'Direct transmission': 'Trasmissione diretta',
    'Belt transmission': 'Trasmissione a cinghia',
    'Gear reducer': 'Riduttore a ingranaggi',
    'Electrical yield [%]': 'Rendimento elettrico [%]',
    'Radiative losses [%]': 'Perdite radiative [%]',
    'Outlet pressure [mmCE]': 'Pressione di uscita [mmCA]',
    'Ambient air temperature [°C]': 'Temperatura aria ambiente [°C]',
    'Safety factor [-]': 'Fattore di sicurezza [-]',
    'Fly ashes content outlet [g/Nm3]': 'Contenuto ceneri volanti uscita [g/Nm3]',
    'siccity bottom ash [%]': 'Siccità scorie [%]',
    'O2 ref [%]': 'O2 riferimento [%]',
    'Flow rate [m³/h at conditions]': 'Portata [m³/h alle condizioni]',
    'Total pressure drop [mmCE]': 'Perdita di carico totale [mmCA]',
    'Aeraulic power [kW]': 'Potenza aeraulica [kW]',
    'Mechanical power [kW]': 'Potenza meccanica [kW]',
    'Electrical power (before safety) [kWe]': 'Potenza elettrica (prima sicurezza) [kWe]',
    'Electrical power (with safety) [kWe]': 'Potenza elettrica (con sicurezza) [kWe]',
    'Fan efficiency [%]': 'Rendimento ventilatore [%]',
    'Motor efficiency [%]': 'Rendimento motore [%]',
    'Transmission efficiency [%]': 'Rendimento trasmissione [%]',
    'Global efficiency [%]': 'Rendimento globale [%]',
    'Temperature inlet IDFAN [°C]': 'Temperatura ingresso IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Temperatura uscita IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Aumento di temperatura (calcolato) [°C]',
    'Power transmitted to flue gas [kW]': 'Potenza trasmessa ai fumi [kW]',
    'Power lost to ambient [kW]': 'Potenza dispersa in ambiente [kW]',
    'Pressure inlet [mmCE]': 'Pressione ingresso [mmCA]',
    'Waste Flow [kg/h]': 'Portata rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Portata fumi umidi [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Portata fumi secchi [Nm3/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',
    'Fly ash inlet [kg/h]': 'Ceneri volanti ingresso [kg/h]',
    'Fly ash outlet [kg/h]': 'Ceneri volanti uscita [kg/h]',
    'IDFAN ash collected [kg/h]': 'Ceneri raccolte IDFAN [kg/h]',
    'Flue gas inlet at inlet temperature': 'Fumi in ingresso alla temperatura di ingresso',
    'Flue gas outlet at outlet temperature': 'Fumi in uscita alla temperatura di uscita',
    'ID FAN (Induced Draft Fan)': 'ID FAN (Ventilatore a Tiraggio Indotto)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Per un ID FAN, il rendimento globale tipico è tra 60% e 75%.',
    'Detail by component:': 'Dettaglio per componente:',
    'Centrifugal fan': 'Ventilatore centrifugo',
    'Efficiency: 70-80% (optimized)': 'Rendimento: 70-80% (ottimizzato)',
    'Efficiency: 60-75% (standard)': 'Rendimento: 60-75% (standard)',
    'Electric motor': 'Motore elettrico',
    'Efficiency: 90-95% (high efficiency motor)': 'Rendimento: 90-95% (motore alta efficienza)',
    'Efficiency: 85-92% (standard motor)': 'Rendimento: 85-92% (motore standard)',
    'Transmission': 'Trasmissione',
    'Direct: 98-99%': 'Diretta: 98-99%',
    'Belts: 94-96%': 'Cinghie: 94-96%',
    'Gear reducer: 95-98%': 'Riduttore: 95-98%',
    'Overall efficiency calculation:': 'Calcolo del rendimento globale:',
    'η_global = η_fan × η_motor × η_transmission': 'η_globale = η_ventilatore × η_motore × η_trasmissione',
    'Optimal configuration:': 'Configurazione ottimale:',
    'Fan: 75%': 'Ventilatore: 75%',
    'Motor: 93%': 'Motore: 93%',
    'Direct transmission: 98%': 'Trasmissione diretta: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Rendimento globale = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Configurazione standard:',
    'Fan: 65%': 'Ventilatore: 65%',
    'Motor: 90%': 'Motore: 90%',
    'Belt transmission: 95%': 'Trasmissione a cinghia: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Rendimento globale = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Raccomandazioni:',
    'For typical industrial applications, I recommend these default values:': 'Per applicazioni industriali tipiche, si raccomandano questi valori predefiniti:',
    'Realistic for a good fan': 'Realistico per un buon ventilatore',
    'Standard IE3 motor': 'Motore IE3 standard',
    'Quality belt transmission': 'Trasmissione a cinghia di qualità',
    'Standard safety factor': 'Fattore di sicurezza standard',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Rendimento globale risultante: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Fattori di influenza:',
    'Size: Large fans have better efficiencies': 'Dimensione: I ventilatori grandi hanno migliori rendimenti',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Punto di funzionamento: Ottimale vicino al BEP',
    'Wear: Efficiency decreases with fouling': 'Usura: Il rendimento diminuisce con l\'incrostamento',
    'Variable speed: Improves efficiency at partial load': 'Velocità variabile: Migliora l\'efficienza a carico parziale',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Un rendimento globale del 65% è un buon valore di riferimento per un ID FAN ben dimensionato.',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Ventilatore di Tiraggio Indotto (ID Fan) — Rapporto di sintesi',
    combustionGases: 'Gas di combustione',
    outletTemp: 'Temperatura di uscita',
    o2Dry: 'O₂ misurato (secco)',
    wetFlowTotal: 'Portata umida totale [kg/h]',
    dryFlowNm3h: 'Portata secca [Nm³/h]',
    wetFlowNm3h: 'Portata umida [Nm³/h]',
    outletGasComposition: 'Composizione del gas in uscita',
    pollutantEmissions: 'Emissioni di inquinanti',
    gasInlet: 'Gas in ingresso [kg/h]',
    gasOutlet: 'Gas in uscita [kg/h]',
    opexHourlyCosts: 'OPEX — Costi orari',
    noOpexData: 'Costi OPEX non disponibili — aprire la scheda Opex.',
    totalCost: 'Costo totale',
    hourlyCost: 'Costo orario',
    annualCost: 'Costo annuale',
    totalCO2: 'Totale CO₂ [kg/h]',
    co2Electricity: 'CO₂ elettricità',
    totalCO2label: 'Totale CO₂',
    electricityTag: 'Elettricità',
    airTag: 'Aria',
    autoReport: 'Rapporto generato automaticamente',
    'IDFAN Configuration': 'Configurazione IDFAN',
    'Flue gases': 'Gas di combustione',
    'Pollutant Emissions': 'Emissioni di inquinanti',
    'Opex': 'Opex',
    'Rapport': 'Rapporto',
    'Back to Flow': 'Torna al flusso',
  },

  pt: {
    'Calculation parameters': 'Parâmetros de cálculo',
    'Calculated parameters': 'Parâmetros calculados',
    'Clear memory': 'Limpar memória',
    'Flue gas composition': 'Composição dos gases de combustão',
    'Input flue gas': 'Gases de entrada',
    'Output flue gas': 'Gases de saída',
    'Residues calculated': 'Resíduos calculados',
    'Equipment Configuration': 'Configuração de equipamentos',
    'Fan Type': 'Tipo de ventilador',
    'Motor Type': 'Tipo de motor',
    'Transmission Type': 'Tipo de transmissão',
    'Optimized centrifugal fan': 'Ventilador centrífugo otimizado',
    'Standard centrifugal fan': 'Ventilador centrífugo padrão',
    'Optimized axial fan': 'Ventilador axial otimizado',
    'Standard axial fan': 'Ventilador axial padrão',
    'High efficiency motor (IE3/IE4)': 'Motor de alta eficiência (IE3/IE4)',
    'Standard motor (IE2)': 'Motor padrão (IE2)',
    'Direct transmission': 'Transmissão direta',
    'Belt transmission': 'Transmissão por correia',
    'Gear reducer': 'Redutor de engrenagens',
    'Electrical yield [%]': 'Rendimento elétrico [%]',
    'Radiative losses [%]': 'Perdas radiativas [%]',
    'Outlet pressure [mmCE]': 'Pressão de saída [mmCA]',
    'Ambient air temperature [°C]': 'Temperatura do ar ambiente [°C]',
    'Safety factor [-]': 'Fator de segurança [-]',
    'Fly ashes content outlet [g/Nm3]': 'Teor de cinzas volantes saída [g/Nm3]',
    'siccity bottom ash [%]': 'Teor de umidade das escórias [%]',
    'O2 ref [%]': 'O2 referência [%]',
    'Flow rate [m³/h at conditions]': 'Vazão [m³/h nas condições]',
    'Total pressure drop [mmCE]': 'Queda de pressão total [mmCA]',
    'Aeraulic power [kW]': 'Potência aeráulica [kW]',
    'Mechanical power [kW]': 'Potência mecânica [kW]',
    'Electrical power (before safety) [kWe]': 'Potência elétrica (antes segurança) [kWe]',
    'Electrical power (with safety) [kWe]': 'Potência elétrica (com segurança) [kWe]',
    'Fan efficiency [%]': 'Rendimento do ventilador [%]',
    'Motor efficiency [%]': 'Rendimento do motor [%]',
    'Transmission efficiency [%]': 'Rendimento da transmissão [%]',
    'Global efficiency [%]': 'Rendimento global [%]',
    'Temperature inlet IDFAN [°C]': 'Temperatura entrada IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Temperatura saída IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Elevação de temperatura (calculada) [°C]',
    'Power transmitted to flue gas [kW]': 'Potência transmitida aos gases [kW]',
    'Power lost to ambient [kW]': 'Potência perdida para o ambiente [kW]',
    'Pressure inlet [mmCE]': 'Pressão entrada [mmCA]',
    'Waste Flow [kg/h]': 'Vazão de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Vazão gases úmidos [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Vazão gases secos [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'Fly ash inlet [kg/h]': 'Cinzas volantes entrada [kg/h]',
    'Fly ash outlet [kg/h]': 'Cinzas volantes saída [kg/h]',
    'IDFAN ash collected [kg/h]': 'Cinzas coletadas IDFAN [kg/h]',
    'Flue gas inlet at inlet temperature': 'Gases na entrada à temperatura de entrada',
    'Flue gas outlet at outlet temperature': 'Gases na saída à temperatura de saída',
    'ID FAN (Induced Draft Fan)': 'ID FAN (Ventilador de Tiragem Induzida)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Para um ID FAN, o rendimento global típico está entre 60% e 75%.',
    'Detail by component:': 'Detalhe por componente:',
    'Centrifugal fan': 'Ventilador centrífugo',
    'Efficiency: 70-80% (optimized)': 'Rendimento: 70-80% (otimizado)',
    'Efficiency: 60-75% (standard)': 'Rendimento: 60-75% (padrão)',
    'Electric motor': 'Motor elétrico',
    'Efficiency: 90-95% (high efficiency motor)': 'Rendimento: 90-95% (motor alta eficiência)',
    'Efficiency: 85-92% (standard motor)': 'Rendimento: 85-92% (motor padrão)',
    'Transmission': 'Transmissão',
    'Direct: 98-99%': 'Direta: 98-99%',
    'Belts: 94-96%': 'Correias: 94-96%',
    'Gear reducer: 95-98%': 'Redutor: 95-98%',
    'Overall efficiency calculation:': 'Cálculo do rendimento global:',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_ventilador × η_motor × η_transmissão',
    'Optimal configuration:': 'Configuração ótima:',
    'Fan: 75%': 'Ventilador: 75%',
    'Motor: 93%': 'Motor: 93%',
    'Direct transmission: 98%': 'Transmissão direta: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Rendimento global = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Configuração padrão:',
    'Fan: 65%': 'Ventilador: 65%',
    'Motor: 90%': 'Motor: 90%',
    'Belt transmission: 95%': 'Transmissão por correia: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Rendimento global = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Recomendações:',
    'For typical industrial applications, I recommend these default values:': 'Para aplicações industriais típicas, recomenda-se estes valores padrão:',
    'Realistic for a good fan': 'Realista para um bom ventilador',
    'Standard IE3 motor': 'Motor IE3 padrão',
    'Quality belt transmission': 'Transmissão por correia de qualidade',
    'Standard safety factor': 'Fator de segurança padrão',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Rendimento global resultante: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Fatores de influência:',
    'Size: Large fans have better efficiencies': 'Tamanho: Ventiladores grandes têm melhores rendimentos',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Ponto de operação: Ótimo perto do BEP',
    'Wear: Efficiency decreases with fouling': 'Desgaste: Rendimento diminui com o incrustamento',
    'Variable speed: Improves efficiency at partial load': 'Velocidade variável: Melhora a eficiência em carga parcial',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Um rendimento global de 65% é um bom valor de referência para um ID FAN bem dimensionado.',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Ventilador de Tiragem Induzida (ID Fan) — Relatório de síntese',
    combustionGases: 'Gases de combustão',
    outletTemp: 'Temperatura de saída',
    o2Dry: 'O₂ medido (seco)',
    wetFlowTotal: 'Vazão úmida total [kg/h]',
    dryFlowNm3h: 'Vazão seca [Nm³/h]',
    wetFlowNm3h: 'Vazão úmida [Nm³/h]',
    outletGasComposition: 'Composição do gás de saída',
    pollutantEmissions: 'Emissões de poluentes',
    gasInlet: 'Gás na entrada [kg/h]',
    gasOutlet: 'Gás na saída [kg/h]',
    opexHourlyCosts: 'OPEX — Custos horários',
    noOpexData: 'Custos OPEX não disponíveis — abrir aba Opex.',
    totalCost: 'Custo total',
    hourlyCost: 'Custo horário',
    annualCost: 'Custo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ eletricidade',
    totalCO2label: 'Total CO₂',
    electricityTag: 'Eletricidade',
    airTag: 'Ar',
    autoReport: 'Relatório gerado automaticamente',
    'IDFAN Configuration': 'Configuração IDFAN',
    'Flue gases': 'Gases de combustão',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Opex': 'Opex',
    'Rapport': 'Relatório',
    'Back to Flow': 'Voltar ao fluxo',
  },

  zh: {
    'Calculation parameters': '计算参数',
    'Calculated parameters': '计算结果',
    'Clear memory': '清除内存',
    'Flue gas composition': '烟气成分',
    'Input flue gas': '入口烟气',
    'Output flue gas': '出口烟气',
    'Residues calculated': '计算残留物',
    'Equipment Configuration': '设备配置',
    'Fan Type': '风机类型',
    'Motor Type': '电机类型',
    'Transmission Type': '传动类型',
    'Optimized centrifugal fan': '优化离心风机',
    'Standard centrifugal fan': '标准离心风机',
    'Optimized axial fan': '优化轴流风机',
    'Standard axial fan': '标准轴流风机',
    'High efficiency motor (IE3/IE4)': '高效电机 (IE3/IE4)',
    'Standard motor (IE2)': '标准电机 (IE2)',
    'Direct transmission': '直接传动',
    'Belt transmission': '皮带传动',
    'Gear reducer': '齿轮减速器',
    'Electrical yield [%]': '电气效率 [%]',
    'Radiative losses [%]': '辐射损失 [%]',
    'Outlet pressure [mmCE]': '出口压力 [mmWC]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Safety factor [-]': '安全系数 [-]',
    'Fly ashes content outlet [g/Nm3]': '出口飞灰含量 [g/Nm3]',
    'siccity bottom ash [%]': '底灰含水率 [%]',
    'O2 ref [%]': 'O2参考值 [%]',
    'Flow rate [m³/h at conditions]': '体积流量 [m³/h 工况]',
    'Total pressure drop [mmCE]': '总压降 [mmWC]',
    'Aeraulic power [kW]': '气动功率 [kW]',
    'Mechanical power [kW]': '机械功率 [kW]',
    'Electrical power (before safety) [kWe]': '电功率（安全前）[kWe]',
    'Electrical power (with safety) [kWe]': '电功率（含安全）[kWe]',
    'Fan efficiency [%]': '风机效率 [%]',
    'Motor efficiency [%]': '电机效率 [%]',
    'Transmission efficiency [%]': '传动效率 [%]',
    'Global efficiency [%]': '综合效率 [%]',
    'Temperature inlet IDFAN [°C]': 'IDFAN入口温度 [°C]',
    'Temperature outlet IDFAN [°C]': 'IDFAN出口温度 [°C]',
    'Temperature rise (calculated) [°C]': '温升（计算值）[°C]',
    'Power transmitted to flue gas [kW]': '传给烟气的功率 [kW]',
    'Power lost to ambient [kW]': '散失到环境的功率 [kW]',
    'Pressure inlet [mmCE]': '入口压力 [mmWC]',
    'Waste Flow [kg/h]': '废物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流量 [Nm3/h]',
    'O2 calculated [%]': '计算O2 [%]',
    'Fly ash inlet [kg/h]': '飞灰入口 [kg/h]',
    'Fly ash outlet [kg/h]': '飞灰出口 [kg/h]',
    'IDFAN ash collected [kg/h]': 'IDFAN收集灰 [kg/h]',
    'Flue gas inlet at inlet temperature': '入口温度下的入口烟气',
    'Flue gas outlet at outlet temperature': '出口温度下的出口烟气',
    'ID FAN (Induced Draft Fan)': 'ID FAN（引风机）',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': '引风机的典型综合效率在60%至75%之间。',
    'Detail by component:': '按组件详述：',
    'Centrifugal fan': '离心风机',
    'Efficiency: 70-80% (optimized)': '效率：70-80%（优化）',
    'Efficiency: 60-75% (standard)': '效率：60-75%（标准）',
    'Electric motor': '电动机',
    'Efficiency: 90-95% (high efficiency motor)': '效率：90-95%（高效电机）',
    'Efficiency: 85-92% (standard motor)': '效率：85-92%（标准电机）',
    'Transmission': '传动',
    'Direct: 98-99%': '直接：98-99%',
    'Belts: 94-96%': '皮带：94-96%',
    'Gear reducer: 95-98%': '齿轮减速器：95-98%',
    'Overall efficiency calculation:': '综合效率计算：',
    'η_global = η_fan × η_motor × η_transmission': 'η综合 = η风机 × η电机 × η传动',
    'Optimal configuration:': '最优配置：',
    'Fan: 75%': '风机：75%',
    'Motor: 93%': '电机：93%',
    'Direct transmission: 98%': '直接传动：98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': '综合效率 = 0.75 × 0.93 × 0.98 = 68%',
    'Standard configuration:': '标准配置：',
    'Fan: 65%': '风机：65%',
    'Motor: 90%': '电机：90%',
    'Belt transmission: 95%': '皮带传动：95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': '综合效率 = 0.65 × 0.90 × 0.95 = 56%',
    'Recommendations for your code:': '建议：',
    'For typical industrial applications, I recommend these default values:': '对于典型工业应用，建议使用以下默认值：',
    'Realistic for a good fan': '对于良好风机的实际值',
    'Standard IE3 motor': '标准IE3电机',
    'Quality belt transmission': '优质皮带传动',
    'Standard safety factor': '标准安全系数',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': '综合效率：72% × 91% × 97% = 63%',
    'Influencing factors:': '影响因素：',
    'Size: Large fans have better efficiencies': '尺寸：大型风机效率更高',
    'Operating point: Optimal near BEP (Best Efficiency Point)': '工作点：最优点附近效率最高',
    'Wear: Efficiency decreases with fouling': '磨损：积垢会降低效率',
    'Variable speed: Improves efficiency at partial load': '变速：改善部分负荷效率',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': '65%的综合效率是合理设计的引风机的良好参考值。',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: '引风机 (ID Fan) — 综合报告',
    combustionGases: '燃烧气体',
    outletTemp: '出口温度',
    o2Dry: 'O₂ 测量（干）',
    wetFlowTotal: '总湿流量 [kg/h]',
    dryFlowNm3h: '干流量 [Nm³/h]',
    wetFlowNm3h: '湿流量 [Nm³/h]',
    outletGasComposition: '出口气体成分',
    pollutantEmissions: '污染物排放',
    gasInlet: '入口气体 [kg/h]',
    gasOutlet: '出口气体 [kg/h]',
    opexHourlyCosts: 'OPEX — 每小时成本',
    noOpexData: 'OPEX成本不可用 — 请打开Opex选项卡。',
    totalCost: '总成本',
    hourlyCost: '小时成本',
    annualCost: '年度成本',
    totalCO2: '总CO₂ [kg/h]',
    co2Electricity: 'CO₂ 电力',
    totalCO2label: '总CO₂',
    electricityTag: '电力',
    airTag: '空气',
    autoReport: '自动生成报告',
    'IDFAN Configuration': '引风机配置',
    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Opex': '运营成本',
    'Rapport': '报告',
    'Back to Flow': '返回流程',
  },

  ja: {
    'Calculation parameters': '計算パラメータ',
    'Calculated parameters': '計算結果',
    'Clear memory': 'メモリをクリア',
    'Flue gas composition': '排ガス組成',
    'Input flue gas': '入口排ガス',
    'Output flue gas': '出口排ガス',
    'Residues calculated': '計算された残留物',
    'Equipment Configuration': '設備構成',
    'Fan Type': 'ファンタイプ',
    'Motor Type': 'モータータイプ',
    'Transmission Type': '伝動タイプ',
    'Optimized centrifugal fan': '最適化遠心ファン',
    'Standard centrifugal fan': '標準遠心ファン',
    'Optimized axial fan': '最適化軸流ファン',
    'Standard axial fan': '標準軸流ファン',
    'High efficiency motor (IE3/IE4)': '高効率モーター (IE3/IE4)',
    'Standard motor (IE2)': '標準モーター (IE2)',
    'Direct transmission': '直接伝動',
    'Belt transmission': 'ベルト伝動',
    'Gear reducer': '歯車減速機',
    'Electrical yield [%]': '電気効率 [%]',
    'Radiative losses [%]': '放射損失 [%]',
    'Outlet pressure [mmCE]': '出口圧力 [mmWC]',
    'Ambient air temperature [°C]': '周囲空気温度 [°C]',
    'Safety factor [-]': '安全率 [-]',
    'Fly ashes content outlet [g/Nm3]': '出口飛灰含有量 [g/Nm3]',
    'siccity bottom ash [%]': '底灰含水率 [%]',
    'O2 ref [%]': 'O2基準値 [%]',
    'Flow rate [m³/h at conditions]': '体積流量 [m³/h 条件下]',
    'Total pressure drop [mmCE]': '全圧力損失 [mmWC]',
    'Aeraulic power [kW]': '空力動力 [kW]',
    'Mechanical power [kW]': '機械動力 [kW]',
    'Electrical power (before safety) [kWe]': '電力（安全前）[kWe]',
    'Electrical power (with safety) [kWe]': '電力（安全込み）[kWe]',
    'Fan efficiency [%]': 'ファン効率 [%]',
    'Motor efficiency [%]': 'モーター効率 [%]',
    'Transmission efficiency [%]': '伝動効率 [%]',
    'Global efficiency [%]': '総合効率 [%]',
    'Temperature inlet IDFAN [°C]': 'IDFAN入口温度 [°C]',
    'Temperature outlet IDFAN [°C]': 'IDFAN出口温度 [°C]',
    'Temperature rise (calculated) [°C]': '温度上昇（計算値）[°C]',
    'Power transmitted to flue gas [kW]': '排ガスに伝達される動力 [kW]',
    'Power lost to ambient [kW]': '周囲への散逸動力 [kW]',
    'Pressure inlet [mmCE]': '入口圧力 [mmWC]',
    'Waste Flow [kg/h]': '廃棄物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿り排ガス流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾燥排ガス流量 [Nm3/h]',
    'O2 calculated [%]': '計算O2 [%]',
    'Fly ash inlet [kg/h]': '飛灰入口 [kg/h]',
    'Fly ash outlet [kg/h]': '飛灰出口 [kg/h]',
    'IDFAN ash collected [kg/h]': 'IDFAN回収灰 [kg/h]',
    'Flue gas inlet at inlet temperature': '入口温度における入口排ガス',
    'Flue gas outlet at outlet temperature': '出口温度における出口排ガス',
    'ID FAN (Induced Draft Fan)': 'ID FAN（誘引通風機）',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': '誘引通風機の典型的な総合効率は60%〜75%です。',
    'Detail by component:': 'コンポーネント別詳細：',
    'Centrifugal fan': '遠心ファン',
    'Efficiency: 70-80% (optimized)': '効率：70-80%（最適化）',
    'Efficiency: 60-75% (standard)': '効率：60-75%（標準）',
    'Electric motor': '電動モーター',
    'Efficiency: 90-95% (high efficiency motor)': '効率：90-95%（高効率モーター）',
    'Efficiency: 85-92% (standard motor)': '効率：85-92%（標準モーター）',
    'Transmission': '伝動',
    'Direct: 98-99%': '直結：98-99%',
    'Belts: 94-96%': 'ベルト：94-96%',
    'Gear reducer: 95-98%': '減速機：95-98%',
    'Overall efficiency calculation:': '総合効率の計算：',
    'η_global = η_fan × η_motor × η_transmission': 'η総合 = ηファン × ηモーター × η伝動',
    'Optimal configuration:': '最適構成：',
    'Fan: 75%': 'ファン：75%',
    'Motor: 93%': 'モーター：93%',
    'Direct transmission: 98%': '直結伝動：98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': '総合効率 = 0.75 × 0.93 × 0.98 = 68%',
    'Standard configuration:': '標準構成：',
    'Fan: 65%': 'ファン：65%',
    'Motor: 90%': 'モーター：90%',
    'Belt transmission: 95%': 'ベルト伝動：95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': '総合効率 = 0.65 × 0.90 × 0.95 = 56%',
    'Recommendations for your code:': '推奨事項：',
    'For typical industrial applications, I recommend these default values:': '一般的な産業用途には、以下のデフォルト値を推奨します：',
    'Realistic for a good fan': '良好なファンの現実的な値',
    'Standard IE3 motor': '標準IE3モーター',
    'Quality belt transmission': '高品質ベルト伝動',
    'Standard safety factor': '標準安全率',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': '結果の総合効率：72% × 91% × 97% = 63%',
    'Influencing factors:': '影響要因：',
    'Size: Large fans have better efficiencies': 'サイズ：大型ファンはより高い効率を持つ',
    'Operating point: Optimal near BEP (Best Efficiency Point)': '動作点：BEP付近で最適',
    'Wear: Efficiency decreases with fouling': '摩耗：汚れにより効率が低下',
    'Variable speed: Improves efficiency at partial load': '可変速度：部分負荷での効率向上',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': '総合効率65%は、適切に設計されたIDファンの良好な参考値です。',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: '誘引通風機 (ID Fan) — 総合報告書',
    combustionGases: '燃焼ガス',
    outletTemp: '出口温度',
    o2Dry: 'O₂ 測定（乾燥）',
    wetFlowTotal: '総湿流量 [kg/h]',
    dryFlowNm3h: '乾燥流量 [Nm³/h]',
    wetFlowNm3h: '湿流量 [Nm³/h]',
    outletGasComposition: '出口ガス組成',
    pollutantEmissions: '汚染物質排出',
    gasInlet: '入口ガス [kg/h]',
    gasOutlet: '出口ガス [kg/h]',
    opexHourlyCosts: 'OPEX — 時間コスト',
    noOpexData: 'OPEXコスト不可 — Opexタブを開いてください。',
    totalCost: '総コスト',
    hourlyCost: '時間コスト',
    annualCost: '年間コスト',
    totalCO2: '総CO₂ [kg/h]',
    co2Electricity: 'CO₂ 電力',
    totalCO2label: '総CO₂',
    electricityTag: '電力',
    airTag: '空気',
    autoReport: '自動生成されたレポート',
    'IDFAN Configuration': '誘引通風機構成',
    'Flue gases': '排気ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Opex': 'Opex',
    'Rapport': 'レポート',
    'Back to Flow': 'フローに戻る',
  },

  ru: {
    'Calculation parameters': 'Параметры расчёта',
    'Calculated parameters': 'Рассчитанные параметры',
    'Clear memory': 'Очистить память',
    'Flue gas composition': 'Состав дымовых газов',
    'Input flue gas': 'Входные дымовые газы',
    'Output flue gas': 'Выходные дымовые газы',
    'Residues calculated': 'Рассчитанные остатки',
    'Equipment Configuration': 'Конфигурация оборудования',
    'Fan Type': 'Тип вентилятора',
    'Motor Type': 'Тип двигателя',
    'Transmission Type': 'Тип передачи',
    'Optimized centrifugal fan': 'Оптимизированный центробежный вентилятор',
    'Standard centrifugal fan': 'Стандартный центробежный вентилятор',
    'Optimized axial fan': 'Оптимизированный осевой вентилятор',
    'Standard axial fan': 'Стандартный осевой вентилятор',
    'High efficiency motor (IE3/IE4)': 'Высокоэффективный двигатель (IE3/IE4)',
    'Standard motor (IE2)': 'Стандартный двигатель (IE2)',
    'Direct transmission': 'Прямая передача',
    'Belt transmission': 'Ременная передача',
    'Gear reducer': 'Редуктор',
    'Electrical yield [%]': 'КПД электрический [%]',
    'Radiative losses [%]': 'Радиационные потери [%]',
    'Outlet pressure [mmCE]': 'Давление на выходе [мм вод. ст.]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Safety factor [-]': 'Коэффициент запаса [-]',
    'Fly ashes content outlet [g/Nm3]': 'Содержание летучей золы на выходе [г/Нм3]',
    'siccity bottom ash [%]': 'Влажность шлака [%]',
    'O2 ref [%]': 'O2 референсный [%]',
    'Flow rate [m³/h at conditions]': 'Объёмный расход [м³/ч при условиях]',
    'Total pressure drop [mmCE]': 'Общее гидравлическое сопротивление [мм вод. ст.]',
    'Aeraulic power [kW]': 'Аэродинамическая мощность [кВт]',
    'Mechanical power [kW]': 'Механическая мощность [кВт]',
    'Electrical power (before safety) [kWe]': 'Электрическая мощность (до запаса) [кВт]',
    'Electrical power (with safety) [kWe]': 'Электрическая мощность (с запасом) [кВт]',
    'Fan efficiency [%]': 'КПД вентилятора [%]',
    'Motor efficiency [%]': 'КПД двигателя [%]',
    'Transmission efficiency [%]': 'КПД передачи [%]',
    'Global efficiency [%]': 'Общий КПД [%]',
    'Temperature inlet IDFAN [°C]': 'Температура на входе IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Температура на выходе IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Повышение температуры (расчётное) [°C]',
    'Power transmitted to flue gas [kW]': 'Мощность, передаваемая дымовым газам [кВт]',
    'Power lost to ambient [kW]': 'Мощность, рассеиваемая в окружающую среду [кВт]',
    'Pressure inlet [mmCE]': 'Давление на входе [мм вод. ст.]',
    'Waste Flow [kg/h]': 'Расход отходов [кг/ч]',
    'Flue gas Flow Wet [Nm3/h]': 'Расход влажных дымовых газов [Нм3/ч]',
    'Flue gas Flow Dry [Nm3/h]': 'Расход сухих дымовых газов [Нм3/ч]',
    'O2 calculated [%]': 'O2 расчётный [%]',
    'Fly ash inlet [kg/h]': 'Летучая зола на входе [кг/ч]',
    'Fly ash outlet [kg/h]': 'Летучая зола на выходе [кг/ч]',
    'IDFAN ash collected [kg/h]': 'Зола, собранная IDFAN [кг/ч]',
    'Flue gas inlet at inlet temperature': 'Дымовые газы на входе при температуре входа',
    'Flue gas outlet at outlet temperature': 'Дымовые газы на выходе при температуре выхода',
    'ID FAN (Induced Draft Fan)': 'ID FAN (Вентилятор дымососа)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Для дымососа типичный общий КПД составляет 60–75%.',
    'Detail by component:': 'Детализация по компонентам:',
    'Centrifugal fan': 'Центробежный вентилятор',
    'Efficiency: 70-80% (optimized)': 'КПД: 70-80% (оптимизированный)',
    'Efficiency: 60-75% (standard)': 'КПД: 60-75% (стандартный)',
    'Electric motor': 'Электродвигатель',
    'Efficiency: 90-95% (high efficiency motor)': 'КПД: 90-95% (высокоэффективный двигатель)',
    'Efficiency: 85-92% (standard motor)': 'КПД: 85-92% (стандартный двигатель)',
    'Transmission': 'Передача',
    'Direct: 98-99%': 'Прямая: 98-99%',
    'Belts: 94-96%': 'Ремни: 94-96%',
    'Gear reducer: 95-98%': 'Редуктор: 95-98%',
    'Overall efficiency calculation:': 'Расчёт общего КПД:',
    'η_global = η_fan × η_motor × η_transmission': 'η_общий = η_вентилятор × η_двигатель × η_передача',
    'Optimal configuration:': 'Оптимальная конфигурация:',
    'Fan: 75%': 'Вентилятор: 75%',
    'Motor: 93%': 'Двигатель: 93%',
    'Direct transmission: 98%': 'Прямая передача: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Общий КПД = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Стандартная конфигурация:',
    'Fan: 65%': 'Вентилятор: 65%',
    'Motor: 90%': 'Двигатель: 90%',
    'Belt transmission: 95%': 'Ременная передача: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Общий КПД = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Рекомендации:',
    'For typical industrial applications, I recommend these default values:': 'Для типичных промышленных применений рекомендуются следующие значения по умолчанию:',
    'Realistic for a good fan': 'Реалистично для хорошего вентилятора',
    'Standard IE3 motor': 'Стандартный двигатель IE3',
    'Quality belt transmission': 'Качественная ременная передача',
    'Standard safety factor': 'Стандартный коэффициент запаса',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Итоговый общий КПД: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Влияющие факторы:',
    'Size: Large fans have better efficiencies': 'Размер: Крупные вентиляторы имеют лучший КПД',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Рабочая точка: Оптимальна вблизи BEP',
    'Wear: Efficiency decreases with fouling': 'Износ: КПД снижается при загрязнении',
    'Variable speed: Improves efficiency at partial load': 'Переменная скорость: Улучшает КПД при частичной нагрузке',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Общий КПД 65% — хорошее референсное значение для правильно подобранного дымососа.',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'Дымосос (ID Fan) — Сводный отчет',
    combustionGases: 'Дымовые газы',
    outletTemp: 'Температура на выходе',
    o2Dry: 'O₂ измеренный (сухой)',
    wetFlowTotal: 'Суммарный влажный расход [кг/ч]',
    dryFlowNm3h: 'Сухой расход [Нм³/ч]',
    wetFlowNm3h: 'Влажный расход [Нм³/ч]',
    outletGasComposition: 'Состав выходящего газа',
    pollutantEmissions: 'Выбросы загрязнителей',
    gasInlet: 'Входящий газ [кг/ч]',
    gasOutlet: 'Исходящий газ [кг/ч]',
    opexHourlyCosts: 'OPEX — Почасовые затраты',
    noOpexData: 'Затраты OPEX недоступны — откройте вкладку Opex.',
    totalCost: 'Общие затраты',
    hourlyCost: 'Почасовые затраты',
    annualCost: 'Годовые затраты',
    totalCO2: 'Итого CO₂ [кг/ч]',
    co2Electricity: 'CO₂ электричество',
    totalCO2label: 'Итого CO₂',
    electricityTag: 'Электричество',
    airTag: 'Воздух',
    autoReport: 'Отчет сгенерирован автоматически',
    'IDFAN Configuration': 'Конфигурация дымососа',
    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязнителей',
    'Opex': 'Опex',
    'Rapport': 'Отчет',
    'Back to Flow': 'Вернуться к потоку',
  },

  ar: {
    'Calculation parameters': 'معاملات الحساب',
    'Calculated parameters': 'المعاملات المحسوبة',
    'Clear memory': 'مسح الذاكرة',
    'Flue gas composition': 'تركيب غازات المداخن',
    'Input flue gas': 'غازات المداخن الداخلة',
    'Output flue gas': 'غازات المداخن الخارجة',
    'Residues calculated': 'المخلفات المحسوبة',
    'Equipment Configuration': 'تكوين المعدات',
    'Fan Type': 'نوع المروحة',
    'Motor Type': 'نوع المحرك',
    'Transmission Type': 'نوع ناقل الحركة',
    'Optimized centrifugal fan': 'مروحة طاردة مركزية محسّنة',
    'Standard centrifugal fan': 'مروحة طاردة مركزية قياسية',
    'Optimized axial fan': 'مروحة محورية محسّنة',
    'Standard axial fan': 'مروحة محورية قياسية',
    'High efficiency motor (IE3/IE4)': 'محرك عالي الكفاءة (IE3/IE4)',
    'Standard motor (IE2)': 'محرك قياسي (IE2)',
    'Direct transmission': 'ناقل مباشر',
    'Belt transmission': 'ناقل بالحزام',
    'Gear reducer': 'مخفض التروس',
    'Electrical yield [%]': 'المردود الكهربائي [%]',
    'Radiative losses [%]': 'الفقد الإشعاعي [%]',
    'Outlet pressure [mmCE]': 'ضغط الخروج [ملم عمود ماء]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Safety factor [-]': 'معامل الأمان [-]',
    'Fly ashes content outlet [g/Nm3]': 'محتوى الرماد الطائر عند الخروج [g/Nm3]',
    'siccity bottom ash [%]': 'رطوبة رماد القاع [%]',
    'O2 ref [%]': 'O2 مرجعي [%]',
    'Flow rate [m³/h at conditions]': 'معدل التدفق [م³/ساعة في الظروف]',
    'Total pressure drop [mmCE]': 'إجمالي فقد الضغط [ملم عمود ماء]',
    'Aeraulic power [kW]': 'القدرة الهوائية [كيلوواط]',
    'Mechanical power [kW]': 'القدرة الميكانيكية [كيلوواط]',
    'Electrical power (before safety) [kWe]': 'القدرة الكهربائية (قبل الأمان) [كيلوواط]',
    'Electrical power (with safety) [kWe]': 'القدرة الكهربائية (مع الأمان) [كيلوواط]',
    'Fan efficiency [%]': 'كفاءة المروحة [%]',
    'Motor efficiency [%]': 'كفاءة المحرك [%]',
    'Transmission efficiency [%]': 'كفاءة ناقل الحركة [%]',
    'Global efficiency [%]': 'الكفاءة الإجمالية [%]',
    'Temperature inlet IDFAN [°C]': 'درجة حرارة مدخل IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'درجة حرارة مخرج IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'ارتفاع درجة الحرارة (محسوب) [°C]',
    'Power transmitted to flue gas [kW]': 'القدرة المنقولة إلى غازات المداخن [كيلوواط]',
    'Power lost to ambient [kW]': 'القدرة المفقودة للمحيط [كيلوواط]',
    'Pressure inlet [mmCE]': 'ضغط المدخل [ملم عمود ماء]',
    'Waste Flow [kg/h]': 'تدفق النفايات [كج/ساعة]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق الغازات الرطبة [نم³/ساعة]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق الغازات الجافة [نم³/ساعة]',
    'O2 calculated [%]': 'O2 محسوب [%]',
    'Fly ash inlet [kg/h]': 'رماد طائر عند المدخل [كج/ساعة]',
    'Fly ash outlet [kg/h]': 'رماد طائر عند المخرج [كج/ساعة]',
    'IDFAN ash collected [kg/h]': 'رماد محصود IDFAN [كج/ساعة]',
    'Flue gas inlet at inlet temperature': 'غازات المداخن عند المدخل بدرجة حرارة الدخول',
    'Flue gas outlet at outlet temperature': 'غازات المداخن عند المخرج بدرجة حرارة الخروج',
    'ID FAN (Induced Draft Fan)': 'مروحة سحب مستحث (ID FAN)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'للمروحة ذات السحب المستحث، تتراوح الكفاءة الإجمالية النموذجية بين 60% و75%.',
    'Detail by component:': 'التفصيل حسب المكون:',
    'Centrifugal fan': 'مروحة طاردة مركزية',
    'Efficiency: 70-80% (optimized)': 'الكفاءة: 70-80% (محسّن)',
    'Efficiency: 60-75% (standard)': 'الكفاءة: 60-75% (قياسي)',
    'Electric motor': 'محرك كهربائي',
    'Efficiency: 90-95% (high efficiency motor)': 'الكفاءة: 90-95% (محرك عالي الكفاءة)',
    'Efficiency: 85-92% (standard motor)': 'الكفاءة: 85-92% (محرك قياسي)',
    'Transmission': 'ناقل الحركة',
    'Direct: 98-99%': 'مباشر: 98-99%',
    'Belts: 94-96%': 'أحزمة: 94-96%',
    'Gear reducer: 95-98%': 'مخفض تروس: 95-98%',
    'Overall efficiency calculation:': 'حساب الكفاءة الإجمالية:',
    'η_global = η_fan × η_motor × η_transmission': 'η_إجمالي = η_مروحة × η_محرك × η_ناقل',
    'Optimal configuration:': 'التكوين الأمثل:',
    'Fan: 75%': 'المروحة: 75%',
    'Motor: 93%': 'المحرك: 93%',
    'Direct transmission: 98%': 'ناقل مباشر: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'الكفاءة الإجمالية = 0.75 × 0.93 × 0.98 = 68%',
    'Standard configuration:': 'التكوين القياسي:',
    'Fan: 65%': 'المروحة: 65%',
    'Motor: 90%': 'المحرك: 90%',
    'Belt transmission: 95%': 'ناقل الحزام: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'الكفاءة الإجمالية = 0.65 × 0.90 × 0.95 = 56%',
    'Recommendations for your code:': 'التوصيات:',
    'For typical industrial applications, I recommend these default values:': 'للتطبيقات الصناعية النموذجية، يُوصى بهذه القيم الافتراضية:',
    'Realistic for a good fan': 'واقعي لمروحة جيدة',
    'Standard IE3 motor': 'محرك IE3 قياسي',
    'Quality belt transmission': 'ناقل حزام عالي الجودة',
    'Standard safety factor': 'معامل أمان قياسي',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'الكفاءة الإجمالية الناتجة: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'العوامل المؤثرة:',
    'Size: Large fans have better efficiencies': 'الحجم: المراوح الكبيرة لها كفاءات أفضل',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'نقطة التشغيل: مثلى بالقرب من BEP',
    'Wear: Efficiency decreases with fouling': 'التآكل: تنخفض الكفاءة مع التلوث',
    'Variable speed: Improves efficiency at partial load': 'السرعة المتغيرة: تحسّن الكفاءة عند الحمل الجزئي',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'كفاءة إجمالية 65% قيمة مرجعية جيدة للمروحة المصممة جيداً.',

    // === camelCase keys for IDFAN_Report ===
    reportTitle_IDFAN: 'مروحة السحب الناجم (ID Fan) — تقرير تركيبي',
    combustionGases: 'غازات الاحتراق',
    outletTemp: 'درجة حرارة الخروج',
    o2Dry: 'O₂ مقاس (جاف)',
    wetFlowTotal: 'إجمالي التدفق الرطب [kg/h]',
    dryFlowNm3h: 'التدفق الجاف [Nm³/h]',
    wetFlowNm3h: 'التدفق الرطب [Nm³/h]',
    outletGasComposition: 'تركيبة غاز الخروج',
    pollutantEmissions: 'انبعاثات الملوثات',
    gasInlet: 'غاز الدخول [kg/h]',
    gasOutlet: 'غاز الخروج [kg/h]',
    opexHourlyCosts: 'OPEX — التكاليف بالساعة',
    noOpexData: 'تكاليف OPEX غير متاحة — افتح علامة التبويب Opex.',
    totalCost: 'التكلفة الإجمالية',
    hourlyCost: 'التكلفة بالساعة',
    annualCost: 'التكلفة السنوية',
    totalCO2: 'إجمالي CO₂ [kg/h]',
    co2Electricity: 'CO₂ الكهرباء',
    totalCO2label: 'إجمالي CO₂',
    electricityTag: 'الكهرباء',
    airTag: 'الهواء',
    autoReport: 'تقرير مُنشأ تلقائيًا',
    'IDFAN Configuration': 'تكوين مروحة السحب',
    'Flue gases': 'غازات الاحتراق',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Opex': 'Opex',
    'Rapport': 'تقرير',
    'Back to Flow': 'العودة إلى التدفق',
  },
};