export const translations = {
  fr: {
    // Onglet paramètres
    'TubeShell Parameters': 'Paramètres échangeur tube-calandre',
    'Clear memory': 'Effacer la mémoire',
    'Rapport': 'Rapport',
    // Onglet rapport
    'Rapport de synthèse': 'Rapport de synthèse',
    'Bilan thermique fumées': 'Bilan thermique côté fumées',
    'Températures et pressions': 'Températures et pressions',
    'Enthalpies': 'Enthalpies',
    'Température fumées entrée': 'Température fumées entrée',
    'Température fumées sortie': 'Température fumées sortie',
    'Pression entrée': 'Pression entrée',
    'Perte de charge': 'Perte de charge',
    'Pression sortie': 'Pression sortie',
    'Enthalpie fumées entrée': 'Enthalpie fumées entrée',
    'Enthalpie fumées sortie': 'Enthalpie fumées sortie',
    'Enthalpie cédée fumées': 'Enthalpie cédée par les fumées',
    'Bilan côté fluide': 'Bilan côté fluide',
    'Enthalpie transmise au fluide': 'Enthalpie transmise au fluide',
    'Température moyenne fluide': 'Température moyenne fluide',
    'cp fluide à T_moy': 'cp fluide à T_moy',
    'Débit fluide calculé': 'Débit fluide calculé',
    'Dimensionnement thermique': 'Dimensionnement thermique',
    'ΔT logarithmique moyen': 'ΔT logarithmique moyen',
    'Facteur UA': 'Facteur UA',
    "Surface d'échange": "Surface d'échange",
    'Composition des fumées': 'Composition des fumées',
    'Débits fumées': 'Débits fumées',
    'Débit humide': 'Débit humide',
    'Débit sec': 'Débit sec',
    'Composition sortie': 'Composition sortie',
    'Rapport généré automatiquement': 'Rapport généré automatiquement',
  },
  en: {
    'TubeShell Parameters': 'Tube & Shell Heat Exchanger Parameters',
    'Clear memory': 'Clear memory',
    'Rapport': 'Report',
    'Rapport de synthèse': 'Summary Report',
    'Bilan thermique fumées': 'Flue Gas Thermal Balance',
    'Températures et pressions': 'Temperatures & Pressures',
    'Enthalpies': 'Enthalpies',
    'Température fumées entrée': 'Flue gas inlet temperature',
    'Température fumées sortie': 'Flue gas outlet temperature',
    'Pression entrée': 'Inlet pressure',
    'Perte de charge': 'Pressure drop',
    'Pression sortie': 'Outlet pressure',
    'Enthalpie fumées entrée': 'Flue gas inlet enthalpy',
    'Enthalpie fumées sortie': 'Flue gas outlet enthalpy',
    'Enthalpie cédée fumées': 'Heat released by flue gas',
    'Bilan côté fluide': 'Secondary Fluid Balance',
    'Enthalpie transmise au fluide': 'Heat transferred to fluid',
    'Température moyenne fluide': 'Mean fluid temperature',
    'cp fluide à T_moy': 'cp fluid at T_avg',
    'Débit fluide calculé': 'Calculated fluid flow rate',
    'Dimensionnement thermique': 'Thermal Sizing',
    'ΔT logarithmique moyen': 'Log mean temperature difference',
    'Facteur UA': 'UA factor',
    "Surface d'échange": 'Heat exchange surface',
    'Composition des fumées': 'Flue Gas Composition',
    'Débits fumées': 'Flue gas flow rates',
    'Débit humide': 'Wet flow rate',
    'Débit sec': 'Dry flow rate',
    'Composition sortie': 'Outlet composition',
    'Rapport généré automatiquement': 'Automatically generated report',
  },
  es: {
    'TubeShell Parameters': 'Parámetros intercambiador de carcasa y tubos',
    'Clear memory': 'Borrar memoria',
    'Rapport': 'Informe',
    'Rapport de synthèse': 'Informe de síntesis',
    'Bilan thermique fumées': 'Balance térmico gases de combustión',
    'Températures et pressions': 'Temperaturas y presiones',
    'Enthalpies': 'Entalpías',
    'Température fumées entrée': 'Temperatura gases entrada',
    'Température fumées sortie': 'Temperatura gases salida',
    'Pression entrée': 'Presión entrada',
    'Perte de charge': 'Pérdida de carga',
    'Pression sortie': 'Presión salida',
    'Enthalpie fumées entrée': 'Entalpía gases entrada',
    'Enthalpie fumées sortie': 'Entalpía gases salida',
    'Enthalpie cédée fumées': 'Calor cedido por los gases',
    'Bilan côté fluide': 'Balance lado fluido',
    'Enthalpie transmise au fluide': 'Calor transferido al fluido',
    'Température moyenne fluide': 'Temperatura media fluido',
    'cp fluide à T_moy': 'cp fluido en T_med',
    'Débit fluide calculé': 'Caudal fluido calculado',
    'Dimensionnement thermique': 'Dimensionamiento térmico',
    'ΔT logarithmique moyen': 'DTLM (diferencia de temperatura logarítmica)',
    'Facteur UA': 'Factor UA',
    "Surface d'échange": 'Superficie de intercambio',
    'Composition des fumées': 'Composición de los gases',
    'Débits fumées': 'Caudales de gases',
    'Débit humide': 'Caudal húmedo',
    'Débit sec': 'Caudal seco',
    'Composition sortie': 'Composición salida',
    'Rapport généré automatiquement': 'Informe generado automáticamente',
  },
  de: {
    'TubeShell Parameters': 'Rohr-Mantel-Wärmetauscher-Parameter',
    'Clear memory': 'Speicher löschen',
    'Rapport': 'Bericht',
    'Rapport de synthèse': 'Synthesebericht',
    'Bilan thermique fumées': 'Thermische Bilanz Rauchgas',
    'Températures et pressions': 'Temperaturen & Drücke',
    'Enthalpies': 'Enthalpien',
    'Température fumées entrée': 'Rauchgas-Eingangstemperatur',
    'Température fumées sortie': 'Rauchgas-Ausgangstemperatur',
    'Pression entrée': 'Eingangsdruck',
    'Perte de charge': 'Druckverlust',
    'Pression sortie': 'Ausgangsdruck',
    'Enthalpie fumées entrée': 'Rauchgasenthalpie Eingang',
    'Enthalpie fumées sortie': 'Rauchgasenthalpie Ausgang',
    'Enthalpie cédée fumées': 'Abgegebene Wärme Rauchgas',
    'Bilan côté fluide': 'Bilanz Sekundärfluid',
    'Enthalpie transmise au fluide': 'Übertragene Wärme auf Fluid',
    'Température moyenne fluide': 'Mittlere Fluidtemperatur',
    'cp fluide à T_moy': 'cp Fluid bei T_mitt',
    'Débit fluide calculé': 'Berechneter Fluiddurchsatz',
    'Dimensionnement thermique': 'Thermische Auslegung',
    'ΔT logarithmique moyen': 'Logarithmische Temperaturdifferenz',
    'Facteur UA': 'UA-Faktor',
    "Surface d'échange": 'Wärmeübertragungsfläche',
    'Composition des fumées': 'Rauchgaszusammensetzung',
    'Débits fumées': 'Rauchgasmengen',
    'Débit humide': 'Feuchter Volumenstrom',
    'Débit sec': 'Trockener Volumenstrom',
    'Composition sortie': 'Zusammensetzung Ausgang',
    'Rapport généré automatiquement': 'Automatisch generierter Bericht',
  },
  it: {
    'TubeShell Parameters': 'Parametri scambiatore a fascio tubiero',
    'Clear memory': 'Cancella memoria',
    'Rapport': 'Rapporto',
    'Rapport de synthèse': 'Rapporto di sintesi',
    'Bilan thermique fumées': 'Bilancio termico fumi',
    'Températures et pressions': 'Temperature e pressioni',
    'Enthalpies': 'Entalpie',
    'Température fumées entrée': 'Temperatura fumi ingresso',
    'Température fumées sortie': 'Temperatura fumi uscita',
    'Pression entrée': 'Pressione ingresso',
    'Perte de charge': 'Perdita di carico',
    'Pression sortie': 'Pressione uscita',
    'Enthalpie fumées entrée': 'Entalpia fumi ingresso',
    'Enthalpie fumées sortie': 'Entalpia fumi uscita',
    'Enthalpie cédée fumées': 'Calore ceduto dai fumi',
    'Bilan côté fluide': 'Bilancio lato fluido',
    'Enthalpie transmise au fluide': 'Calore trasmesso al fluido',
    'Température moyenne fluide': 'Temperatura media fluido',
    'cp fluide à T_moy': 'cp fluido a T_med',
    'Débit fluide calculé': 'Portata fluido calcolata',
    'Dimensionnement thermique': 'Dimensionamento termico',
    'ΔT logarithmique moyen': 'Differenza di temperatura logaritmica media',
    'Facteur UA': 'Fattore UA',
    "Surface d'échange": 'Superficie di scambio',
    'Composition des fumées': 'Composizione dei fumi',
    'Débits fumées': 'Portate fumi',
    'Débit humide': 'Portata umida',
    'Débit sec': 'Portata secca',
    'Composition sortie': 'Composizione uscita',
    'Rapport généré automatiquement': 'Rapporto generato automaticamente',
  },
  pt: {
    'TubeShell Parameters': 'Parâmetros trocador casco e tubo',
    'Clear memory': 'Limpar memória',
    'Rapport': 'Relatório',
    'Rapport de synthèse': 'Relatório de síntese',
    'Bilan thermique fumées': 'Balanço térmico gases de combustão',
    'Températures et pressions': 'Temperaturas e pressões',
    'Enthalpies': 'Entalpias',
    'Température fumées entrée': 'Temperatura gases entrada',
    'Température fumées sortie': 'Temperatura gases saída',
    'Pression entrée': 'Pressão entrada',
    'Perte de charge': 'Perda de carga',
    'Pression sortie': 'Pressão saída',
    'Enthalpie fumées entrée': 'Entalpia gases entrada',
    'Enthalpie fumées sortie': 'Entalpia gases saída',
    'Enthalpie cédée fumées': 'Calor cedido pelos gases',
    'Bilan côté fluide': 'Balanço lado fluido',
    'Enthalpie transmise au fluide': 'Calor transferido ao fluido',
    'Température moyenne fluide': 'Temperatura média fluido',
    'cp fluide à T_moy': 'cp fluido em T_méd',
    'Débit fluide calculé': 'Vazão fluido calculada',
    'Dimensionnement thermique': 'Dimensionamento térmico',
    'ΔT logarithmique moyen': 'Diferença de temperatura logarítmica média',
    'Facteur UA': 'Fator UA',
    "Surface d'échange": 'Superfície de troca',
    'Composition des fumées': 'Composição dos gases',
    'Débits fumées': 'Vazões de gases',
    'Débit humide': 'Vazão úmida',
    'Débit sec': 'Vazão seca',
    'Composition sortie': 'Composição saída',
    'Rapport généré automatiquement': 'Relatório gerado automaticamente',
  },
  zh: {
    'TubeShell Parameters': '管壳式换热器参数',
    'Clear memory': '清除内存',
    'Rapport': '报告',
    'Rapport de synthèse': '综合报告',
    'Bilan thermique fumées': '烟气热平衡',
    'Températures et pressions': '温度与压力',
    'Enthalpies': '焓值',
    'Température fumées entrée': '烟气入口温度',
    'Température fumées sortie': '烟气出口温度',
    'Pression entrée': '入口压力',
    'Perte de charge': '压降',
    'Pression sortie': '出口压力',
    'Enthalpie fumées entrée': '烟气入口焓',
    'Enthalpie fumées sortie': '烟气出口焓',
    'Enthalpie cédée fumées': '烟气放热量',
    'Bilan côté fluide': '流体侧热平衡',
    'Enthalpie transmise au fluide': '传递给流体的热量',
    'Température moyenne fluide': '流体平均温度',
    'cp fluide à T_moy': '平均温度下流体比热',
    'Débit fluide calculé': '计算流体流量',
    'Dimensionnement thermique': '热工设计',
    'ΔT logarithmique moyen': '对数平均温差',
    'Facteur UA': 'UA因子',
    "Surface d'échange": '换热面积',
    'Composition des fumées': '烟气成分',
    'Débits fumées': '烟气流量',
    'Débit humide': '湿烟气流量',
    'Débit sec': '干烟气流量',
    'Composition sortie': '出口成分',
    'Rapport généré automatiquement': '自动生成报告',
  },
  ja: {
    'TubeShell Parameters': 'チューブ・シェル式熱交換器パラメータ',
    'Clear memory': 'メモリをクリア',
    'Rapport': 'レポート',
    'Rapport de synthèse': '総合レポート',
    'Bilan thermique fumées': '排ガス熱収支',
    'Températures et pressions': '温度と圧力',
    'Enthalpies': 'エンタルピー',
    'Température fumées entrée': '排ガス入口温度',
    'Température fumées sortie': '排ガス出口温度',
    'Pression entrée': '入口圧力',
    'Perte de charge': '圧力損失',
    'Pression sortie': '出口圧力',
    'Enthalpie fumées entrée': '排ガス入口エンタルピー',
    'Enthalpie fumées sortie': '排ガス出口エンタルピー',
    'Enthalpie cédée fumées': '排ガス放熱量',
    'Bilan côté fluide': '流体側熱収支',
    'Enthalpie transmise au fluide': '流体への伝熱量',
    'Température moyenne fluide': '流体平均温度',
    'cp fluide à T_moy': '平均温度での流体比熱',
    'Débit fluide calculé': '計算流体流量',
    'Dimensionnement thermique': '熱設計',
    'ΔT logarithmique moyen': '対数平均温度差',
    'Facteur UA': 'UA係数',
    "Surface d'échange": '伝熱面積',
    'Composition des fumées': '排ガス組成',
    'Débits fumées': '排ガス流量',
    'Débit humide': '湿り排ガス流量',
    'Débit sec': '乾き排ガス流量',
    'Composition sortie': '出口組成',
    'Rapport généré automatiquement': '自動生成レポート',
  },
  ru: {
    'TubeShell Parameters': 'Параметры кожухотрубного теплообменника',
    'Clear memory': 'Очистить память',
    'Rapport': 'Отчёт',
    'Rapport de synthèse': 'Сводный отчёт',
    'Bilan thermique fumées': 'Тепловой баланс дымовых газов',
    'Températures et pressions': 'Температуры и давления',
    'Enthalpies': 'Энтальпии',
    'Température fumées entrée': 'Температура газов на входе',
    'Température fumées sortie': 'Температура газов на выходе',
    'Pression entrée': 'Давление на входе',
    'Perte de charge': 'Потеря давления',
    'Pression sortie': 'Давление на выходе',
    'Enthalpie fumées entrée': 'Энтальпия газов на входе',
    'Enthalpie fumées sortie': 'Энтальпия газов на выходе',
    'Enthalpie cédée fumées': 'Теплота, отданная газами',
    'Bilan côté fluide': 'Баланс на стороне теплоносителя',
    'Enthalpie transmise au fluide': 'Теплота, переданная теплоносителю',
    'Température moyenne fluide': 'Средняя температура теплоносителя',
    'cp fluide à T_moy': 'cp теплоносителя при T_ср',
    'Débit fluide calculé': 'Расчётный расход теплоносителя',
    'Dimensionnement thermique': 'Тепловое проектирование',
    'ΔT logarithmique moyen': 'Среднелогарифмическая разность температур',
    'Facteur UA': 'Коэффициент UA',
    "Surface d'échange": 'Поверхность теплообмена',
    'Composition des fumées': 'Состав дымовых газов',
    'Débits fumées': 'Расходы дымовых газов',
    'Débit humide': 'Влажный расход',
    'Débit sec': 'Сухой расход',
    'Composition sortie': 'Состав на выходе',
    'Rapport généré automatiquement': 'Отчёт создан автоматически',
  },
  ar: {
    'TubeShell Parameters': 'معاملات مبادل الأنابيب والغلاف',
    'Clear memory': 'مسح الذاكرة',
    'Rapport': 'تقرير',
    'Rapport de synthèse': 'تقرير موجز',
    'Bilan thermique fumées': 'الميزان الحراري لغازات العادم',
    'Températures et pressions': 'درجات الحرارة والضغوط',
    'Enthalpies': 'الإنثالبيات',
    'Température fumées entrée': 'درجة حرارة الغازات عند الدخول',
    'Température fumées sortie': 'درجة حرارة الغازات عند الخروج',
    'Pression entrée': 'ضغط الدخول',
    'Perte de charge': 'فقد الضغط',
    'Pression sortie': 'ضغط الخروج',
    'Enthalpie fumées entrée': 'إنثالبي الغازات عند الدخول',
    'Enthalpie fumées sortie': 'إنثالبي الغازات عند الخروج',
    'Enthalpie cédée fumées': 'الحرارة المنبعثة من الغازات',
    'Bilan côté fluide': 'ميزان جانب السائل',
    'Enthalpie transmise au fluide': 'الحرارة المنقولة إلى السائل',
    'Température moyenne fluide': 'متوسط درجة حرارة السائل',
    'cp fluide à T_moy': 'cp السائل عند T_متوسط',
    'Débit fluide calculé': 'تدفق السائل المحسوب',
    'Dimensionnement thermique': 'التصميم الحراري',
    'ΔT logarithmique moyen': 'متوسط فرق درجة الحرارة اللوغاريتمي',
    'Facteur UA': 'معامل UA',
    "Surface d'échange": 'سطح التبادل الحراري',
    'Composition des fumées': 'تركيب غازات العادم',
    'Débits fumées': 'تدفقات غازات العادم',
    'Débit humide': 'التدفق الرطب',
    'Débit sec': 'التدفق الجاف',
    'Composition sortie': 'تركيب عند الخروج',
    'Rapport généré automatiquement': 'تقرير مُنشأ تلقائياً',
  },
};

export const getLinearGraphTranslations = (language = 'fr') => {
  return translations[language] || translations.fr;
};
