export const translations = {
  fr: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'Configuration DENOX',
    'Back to Flow': 'Retour au schéma',
    'Flue gases': 'Gaz de combustion',
    'Pollutant Emissions': 'Émissions polluantes',
    'Design': 'Dimensionnement',
    'Opex': 'Opex',
    'Rapport': 'Rapport',

    // === DENOXFlueGasParameters - Paramètres d'émission ===
    'Calculation parameters': 'Paramètres de calcul',
    'Clear memory': 'Effacer la mémoire',
    'Flue gas temperature before reheating [°C]': 'Température gaz avant réchauffage [°C]',
    'Flue gas temperature after reheating [°C]': 'Température gaz après réchauffage [°C]',
    'Ambient air temperature [°C]': 'Température air ambiant [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume infiltration air [Nm3/h]',
    'Thermal losses [%]': 'Pertes thermiques [%]',
    'Cooling water temperature [°C]': 'Température eau refroidissement [°C]',
    'Water injection': 'Injection d\'eau',
    'Gas type': 'Type de gaz',
    'Water type': 'Type d\'eau',
    'OUI': 'OUI',
    'NON': 'NON',

    // === Résultats calculés ===
    'Calculated parameters': 'Paramètres calculés',
    'Temperature inlet DENOX [°C]': 'Température entrée DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta enthalpies [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Eau de refroidissement/pulvérisation [kg/h]',
    'Total humid flue gas output [m³/h]': 'Débit total gaz humides sortie [m³/h]',
    'Temperature before reheating [°C]': 'Température avant réchauffage [°C]',
    'Temperature after reheating [°C]': 'Température après réchauffage [°C]',
    'Adiabatic flame temperature [°C]': 'Température adiabatique de flamme [°C]',
    'Air factor [-]': 'Facteur d\'air [-]',
    'Combustion air volume [m³/h]': 'Débit air combustion [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Débit gaz combustion [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Débit gaz pour réchauffage [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Température de mélange calculée [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Attention : Le calcul de combustion n\'a pas convergé correctement',
    'Warning: Reheating calculation did not converge after': '⚠️ Attention : Le calcul de réchauffage n\'a pas convergé après',
    'iterations': 'itérations',
    'No reheating required: outlet temperature is already above target': 'ℹ️ Aucun réchauffage requis : la température de sortie dépasse déjà la cible',
    'Flue gas composition': 'Composition des gaz de combustion',
    'Flue gas inlet at inlet temperature': 'Gaz de combustion à l\'entrée',
    'Flue gas outlet at temperature before reheating': 'Gaz de combustion avant réchauffage',
    'Flue gas outlet at temperature after reheating': 'Gaz de combustion après réchauffage',

    // === FlueGasPollutantEmission - Paramètres principaux ===
    'Fly ashes content [g/Nm3]': 'Teneur en poussières volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité cendres fond [%]',
    'O2 ref [%]': 'O2 référence [%]',
    'SCR enabled': 'SCR activé',
    'NOx limit [mg/Nm3]': 'Limite NOx [mg/Nm3]',
    'Stoichiometry': 'Stœchiométrie',
    'SOx reactif': 'Réactif SOx',
    'HCl reactif': 'Réactif HCl',
    'HF reactif': 'Réactif HF',
    'efficacite_SOx': 'Efficacité SOx [%]',
    'HCl efficacité': 'Efficacité HCl [%]',
    'HF efficacité': 'Efficacité HF [%]',
    'SOx stoechiométrie': 'Stœchiométrie SOx',
    'HCl stoechiométrie': 'Stœchiométrie HCl',
    'HF stoechiométrie': 'Stœchiométrie HF',
    'Reset to Default Values': 'Réinitialiser aux valeurs par défaut',

    // === Paramètres polluants ===
    'Waste Flow [kg/h]': 'Flux déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit gaz humides [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit gaz secs [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'inert mass [kg/h]': 'Masse inerte [kg/h]',
    'Input flue gas': 'Gaz de combustion en entrée',
    'SCR (Selective Catalytic Reduction)': 'SCR (Réduction catalytique sélective)',
    'SCR enabled:': 'SCR activé :',
    'NOx limit [mg/Nm3]:': 'Limite NOx [mg/Nm3] :',
    'Stoichiometry:': 'Stœchiométrie :',
    'NH3 consumption [kg/h]:': 'Consommation NH₃ [kg/h] :',
    'NOx input [mg/Nm3]:': 'NOx entrée [mg/Nm3] :',
    'NOx reduced [kg/h]:': 'NOx réduit [kg/h] :',
    'Pollutant Treatment Table': 'Tableau de traitement des polluants',
    'Polluant': 'Polluant',
    'Réactif': 'Réactif',
    'Masse (kg/h)': 'Masse (kg/h)',
    'Efficacité (%)': 'Efficacité (%)',
    'Coeff. Stoech': 'Coeff. Stoech',
    'Masse sortie': 'Masse sortie',
    'Masse résidu': 'Masse résidu',
    'Masse réactif': 'Masse réactif',
    'Masse abattue': 'Masse abattue',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Aucun',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 sec',
    'CaOH2wet': 'CaOH2 humide',
    'CAP': 'CAP',
    'Ammonia': 'Ammoniac',
    'Output flue gas': 'Gaz de combustion en sortie',
    'Bottom ashes calculated': 'Cendres fond calculées',
    'Bottom ash [kg/h]': 'Cendres fond [kg/h]',
    'Bottom ash wet [kg/h]': 'Cendres fond humides [kg/h]',
    'Fly ash [kg/h]': 'Cendres volantes [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'Technologie SCR',
    'Plaques catalytiques': 'Plaques catalytiques',
    'Nid d\'abeilles': 'Nid d\'abeilles',
    'Lit fixe': 'Lit fixe',
    'Paramètres SCR': 'Paramètres SCR',
    'Paramètres FAM': 'Paramètres FAM',
    'Débit de gaz [Nm³/h]': 'Débit de gaz [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'Concentration NOx entrée [mg/Nm³]',
    'Taux de réduction NOx [%]': 'Taux de réduction NOx [%]',
    'Température des gaz [°C]': 'Température des gaz [°C]',
    'Vitesse spatiale [h⁻¹]': 'Vitesse spatiale [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Vitesse superficielle [m/s]',
    'Rendement de capture [%]': 'Rendement de capture [%]',
    'Vitesse de filtration [m/h]': 'Vitesse de filtration [m/h]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Volume catalyseur requis [m³]': 'Volume catalyseur requis [m³]',
    'Section transversale [m²]': 'Section transversale [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'Concentration NOx sortie [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'Consommation NH₃ [kg/h]',
    'Perte de charge [Pa]': 'Perte de charge [Pa]',
    'Surface des manches [m²]': 'Surface des manches [m²]',
    'Pression de sortie [mmCE]': 'Pression de sortie [mmCE]',
    'Paramètres Calculés Généraux': 'Paramètres Calculés Généraux',
    'Dimensionnement Spécifique': 'Dimensionnement Spécifique',
    'Résumé des paramètres principaux': 'Résumé des paramètres principaux',
    'Technologie': 'Technologie',
    'Volume catalyseur [m³]': 'Volume catalyseur [m³]',
    'Nombre de plaques': 'Nombre de plaques',
    'Nombre de couches': 'Nombre de couches',
    'Plaques par couche': 'Plaques par couche',
    'Hauteur réacteur [m]': 'Hauteur réacteur [m]',
    'Largeur réacteur [m]': 'Largeur réacteur [m]',
    'Longueur réacteur [m]': 'Longueur réacteur [m]',
    'Volume total plaques [m³]': 'Volume total plaques [m³]',
    'Nombre d\'éléments': 'Nombre d\'éléments',
    'Éléments par rangée': 'Éléments par rangée',
    'Nombre de rangées': 'Nombre de rangées',
    'Densité cellulaire [cpsi]': 'Densité cellulaire [cpsi]',
    'Volume total éléments [m³]': 'Volume total éléments [m³]',
    'Volume lit total [m³]': 'Volume lit total [m³]',
    'Hauteur du lit [m]': 'Hauteur du lit [m]',
    'Diamètre réacteur [m]': 'Diamètre réacteur [m]',
    'Section du lit [m²]': 'Section du lit [m²]',
    'Porosité du lit [%]': 'Porosité du lit [%]',
    'Masse catalyseur [kg]': 'Masse catalyseur [kg]',
    'Densité apparente [kg/m³]': 'Densité apparente [kg/m³]',
    'Résultats': 'Résultats',
  },
  en: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'DENOX Configuration',
    'Back to Flow': 'Back to Flow',
    'Flue gases': 'Flue gases',
    'Pollutant Emissions': 'Pollutant Emissions',
    'Design': 'Design',
    'Opex': 'Opex',

    // === DENOXFlueGasParameters - Emission parameters ===
    'Calculation parameters': 'Calculation parameters',
    'Clear memory': 'Clear memory',
    'Flue gas temperature before reheating [°C]': 'Flue gas temperature before reheating [°C]',
    'Flue gas temperature after reheating [°C]': 'Flue gas temperature after reheating [°C]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume of air ingress [Nm3/h]',
    'Thermal losses [%]': 'Thermal losses [%]',
    'Cooling water temperature [°C]': 'Cooling water temperature [°C]',
    'Water injection': 'Water injection',
    'Gas type': 'Gas type',
    'Water type': 'Water type',
    'OUI': 'YES',
    'NON': 'NO',

    // === Calculated results ===
    'Calculated parameters': 'Calculated parameters',
    'Temperature inlet DENOX [°C]': 'Temperature inlet DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta enthalpies [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Sprayed/cooling water [kg/h]',
    'Total humid flue gas output [m³/h]': 'Total humid flue gas output [m³/h]',
    'Temperature before reheating [°C]': 'Temperature before reheating [°C]',
    'Temperature after reheating [°C]': 'Temperature after reheating [°C]',
    'Adiabatic flame temperature [°C]': 'Adiabatic flame temperature [°C]',
    'Air factor [-]': 'Air factor [-]',
    'Combustion air volume [m³/h]': 'Combustion air volume [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Combustion flue gas volume [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Gas flow rate for reheating [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Calculated mixing temperature [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Warning: Combustion calculation did not converge properly',
    'Warning: Reheating calculation did not converge after': '⚠️ Warning: Reheating calculation did not converge after',
    'iterations': 'iterations',
    'No reheating required: outlet temperature is already above target': 'ℹ️ No reheating required: outlet temperature is already above target',
    'Flue gas composition': 'Flue gas composition',
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Flue gas outlet at temperature before reheating': 'Flue gas outlet at temperature before reheating',
    'Flue gas outlet at temperature after reheating': 'Flue gas outlet at temperature after reheating',

    // === FlueGasPollutantEmission - Main parameters ===
    'Fly ashes content [g/Nm3]': 'Fly ashes content [g/Nm3]',
    'siccity bottom ash [%]': 'Siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SCR enabled': 'SCR enabled',
    'NOx limit [mg/Nm3]': 'NOx limit [mg/Nm3]',
    'Stoichiometry': 'Stoichiometry',
    'SOx reactif': 'SOx reactant',
    'HCl reactif': 'HCl reactant',
    'HF reactif': 'HF reactant',
    'efficacite_SOx': 'SOx efficiency [%]',
    'HCl efficacité': 'HCl efficiency [%]',
    'HF efficacité': 'HF efficiency [%]',
    'SOx stoechiométrie': 'SOx stoichiometry',
    'HCl stoechiométrie': 'HCl stoichiometry',
    'HF stoechiométrie': 'HF stoichiometry',
    'Reset to Default Values': 'Reset to Default Values',

    // === Pollutant parameters ===
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'inert mass [kg/h]': 'inert mass [kg/h]',
    'Input flue gas': 'Input flue gas',
    'SCR (Selective Catalytic Reduction)': 'SCR (Selective Catalytic Reduction)',
    'SCR enabled:': 'SCR enabled:',
    'NOx limit [mg/Nm3]:': 'NOx limit [mg/Nm3]:',
    'Stoichiometry:': 'Stoichiometry:',
    'NH3 consumption [kg/h]:': 'NH3 consumption [kg/h]:',
    'NOx input [mg/Nm3]:': 'NOx input [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'NOx reduced [kg/h]:',
    'Pollutant Treatment Table': 'Pollutant Treatment Table',
    'Polluant': 'Pollutant',
    'Réactif': 'Reactant',
    'Masse (kg/h)': 'Mass (kg/h)',
    'Efficacité (%)': 'Efficiency (%)',
    'Coeff. Stoech': 'Stoich. Coeff',
    'Masse sortie': 'Output mass',
    'Masse résidu': 'Residue mass',
    'Masse réactif': 'Reactant mass',
    'Masse abattue': 'Abated mass',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'None',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 dry',
    'CaOH2wet': 'CaOH2 wet',
    'CAP': 'CAP',
    'Ammonia': 'Ammonia',
    'Output flue gas': 'Output flue gas',
    'Bottom ashes calculated': 'Bottom ashes calculated',
    'Bottom ash [kg/h]': 'Bottom ash [kg/h]',
    'Bottom ash wet [kg/h]': 'Bottom ash wet [kg/h]',
    'Fly ash [kg/h]': 'Fly ash [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'SCR Technology',
    'Plaques catalytiques': 'Catalytic Plates',
    'Nid d\'abeilles': 'Honeycomb',
    'Lit fixe': 'Fixed Bed',
    'Paramètres SCR': 'SCR Parameters',
    'Paramètres FAM': 'FAM Parameters',
    'Débit de gaz [Nm³/h]': 'Gas Flow Rate [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'NOx Inlet Concentration [mg/Nm³]',
    'Taux de réduction NOx [%]': 'NOx Reduction Rate [%]',
    'Température des gaz [°C]': 'Gas Temperature [°C]',
    'Vitesse spatiale [h⁻¹]': 'Space Velocity [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Superficial Velocity [m/s]',
    'Rendement de capture [%]': 'Collection Efficiency [%]',
    'Vitesse de filtration [m/h]': 'Filtration Velocity [m/h]',
    'PDC [mmCE]': 'Pressure Drop [mmCE]',
    'Volume catalyseur requis [m³]': 'Required Catalyst Volume [m³]',
    'Section transversale [m²]': 'Cross-sectional Area [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'NOx Outlet Concentration [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'NH₃ Consumption [kg/h]',
    'Perte de charge [Pa]': 'Pressure Drop [Pa]',
    'Surface des manches [m²]': 'Bag Surface Area [m²]',
    'Pression de sortie [mmCE]': 'Outlet Pressure [mmCE]',
    'Paramètres Calculés Généraux': 'General Calculated Parameters',
    'Dimensionnement Spécifique': 'Specific Design',
    'Résumé des paramètres principaux': 'Summary of Main Parameters',
    'Technologie': 'Technology',
    'Volume catalyseur [m³]': 'Catalyst Volume [m³]',
    'Nombre de plaques': 'Number of Plates',
    'Nombre de couches': 'Number of Layers',
    'Plaques par couche': 'Plates per Layer',
    'Hauteur réacteur [m]': 'Reactor Height [m]',
    'Largeur réacteur [m]': 'Reactor Width [m]',
    'Longueur réacteur [m]': 'Reactor Length [m]',
    'Volume total plaques [m³]': 'Total Plate Volume [m³]',
    'Nombre d\'éléments': 'Number of Elements',
    'Éléments par rangée': 'Elements per Row',
    'Nombre de rangées': 'Number of Rows',
    'Densité cellulaire [cpsi]': 'Cell Density [cpsi]',
    'Volume total éléments [m³]': 'Total Elements Volume [m³]',
    'Volume lit total [m³]': 'Total Bed Volume [m³]',
    'Hauteur du lit [m]': 'Bed Height [m]',
    'Diamètre réacteur [m]': 'Reactor Diameter [m]',
    'Section du lit [m²]': 'Bed Section [m²]',
    'Porosité du lit [%]': 'Bed Porosity [%]',
    'Masse catalyseur [kg]': 'Catalyst Mass [kg]',
    'Densité apparente [kg/m³]': 'Bulk Density [kg/m³]',
    'Résultats': 'Results',
  },
  de: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'DENOX-Konfiguration',
    'Back to Flow': 'Zurück zum Fluss',
    'Flue gases': 'Rauchgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Design': 'Entwurf',
    'Opex': 'Opex',

    // === DENOXFlueGasParameters - Emissionsparameter ===
    'Calculation parameters': 'Berechnungsparameter',
    'Clear memory': 'Speicher löschen',
    'Flue gas temperature before reheating [°C]': 'Rauchgastemperatur vor Wiederaufheizung [°C]',
    'Flue gas temperature after reheating [°C]': 'Rauchgastemperatur nach Wiederaufheizung [°C]',
    'Ambient air temperature [°C]': 'Umgebungslufttemperatur [°C]',
    'Volume of air ingress [Nm3/h]': 'Lufteinlass-Volumen [Nm3/h]',
    'Thermal losses [%]': 'Wärmeverluste [%]',
    'Cooling water temperature [°C]': 'Kühlwassertemperatur [°C]',
    'Water injection': 'Wassereinspritzung',
    'Gas type': 'Gastyp',
    'Water type': 'Wassertyp',
    'OUI': 'JA',
    'NON': 'NEIN',

    // === Berechnete Ergebnisse ===
    'Calculated parameters': 'Berechnete Parameter',
    'Temperature inlet DENOX [°C]': 'Temperatur Einlass DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta-Enthalpien [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Besprühtes/Kühlwasser [kg/h]',
    'Total humid flue gas output [m³/h]': 'Gesamtfeuchte Rauchgasabgabe [m³/h]',
    'Temperature before reheating [°C]': 'Temperatur vor Wiederaufheizung [°C]',
    'Temperature after reheating [°C]': 'Temperatur nach Wiederaufheizung [°C]',
    'Adiabatic flame temperature [°C]': 'Adiabatische Flammentemperatur [°C]',
    'Air factor [-]': 'Luftfaktor [-]',
    'Combustion air volume [m³/h]': 'Verbrennungsluftstrom [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Rauchgasvolumen bei Verbrennung [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Gasstrom zum Wiederaufheizen [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Berechnete Mischtemperatur [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Warnung: Verbrennungsberechnung konvergierte nicht richtig',
    'Warning: Reheating calculation did not converge after': '⚠️ Warnung: Wiederaufheizungsberechnung konvergierte nicht nach',
    'iterations': 'Iterationen',
    'No reheating required: outlet temperature is already above target': 'ℹ️ Keine Wiederaufheizung erforderlich: Auslasstemperatur liegt bereits über dem Ziel',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Flue gas inlet at inlet temperature': 'Rauchgaseinlass bei Einlasstemperatur',
    'Flue gas outlet at temperature before reheating': 'Rauchgasauslass vor Wiederaufheizung',
    'Flue gas outlet at temperature after reheating': 'Rauchgasauslass nach Wiederaufheizung',

    // === FlueGasPollutantEmission - Hauptparameter ===
    'Fly ashes content [g/Nm3]': 'Flugaschegehalt [g/Nm3]',
    'siccity bottom ash [%]': 'Trockenheit der Bodenasche [%]',
    'O2 ref [%]': 'O2-Referenz [%]',
    'SCR enabled': 'SCR aktiviert',
    'NOx limit [mg/Nm3]': 'NOx-Grenzwert [mg/Nm3]',
    'Stoichiometry': 'Stöchiometrie',
    'SOx reactif': 'SOx-Reaktant',
    'HCl reactif': 'HCl-Reaktant',
    'HF reactif': 'HF-Reaktant',
    'efficacite_SOx': 'SOx-Effizienz [%]',
    'HCl efficacité': 'HCl-Effizienz [%]',
    'HF efficacité': 'HF-Effizienz [%]',
    'SOx stoechiométrie': 'SOx-Stöchiometrie',
    'HCl stoechiométrie': 'HCl-Stöchiometrie',
    'HF stoechiométrie': 'HF-Stöchiometrie',
    'Reset to Default Values': 'Auf Standardwerte zurücksetzen',

    // === Schadstoffparameter ===
    'Waste Flow [kg/h]': 'Abfallstrom [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Feuchter Rauchgasstrom [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Trockener Rauchgasstrom [Nm3/h]',
    'O2 calculated [%]': 'O2 berechnet [%]',
    'inert mass [kg/h]': 'Inertmasse [kg/h]',
    'Input flue gas': 'Eingangsrauchgas',
    'SCR (Selective Catalytic Reduction)': 'SCR (Selektive katalytische Reduktion)',
    'SCR enabled:': 'SCR aktiviert:',
    'NOx limit [mg/Nm3]:': 'NOx-Grenzwert [mg/Nm3]:',
    'Stoichiometry:': 'Stöchiometrie:',
    'NH3 consumption [kg/h]:': 'NH₃-Verbrauch [kg/h]:',
    'NOx input [mg/Nm3]:': 'NOx-Eingang [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'NOx-Reduktion [kg/h]:',
    'Pollutant Treatment Table': 'Schadstoffbehandlungstabelle',
    'Polluant': 'Schadstoff',
    'Réactif': 'Reaktant',
    'Masse (kg/h)': 'Masse (kg/h)',
    'Efficacité (%)': 'Effizienz (%)',
    'Coeff. Stoech': 'Stoich. Koeff.',
    'Masse sortie': 'Ausgangsmasse',
    'Masse résidu': 'Restmasse',
    'Masse réactif': 'Reaktantmasse',
    'Masse abattue': 'Abgebaute Masse',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Keine',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 trocken',
    'CaOH2wet': 'CaOH2 nass',
    'CAP': 'CAP',
    'Ammonia': 'Ammoniak',
    'Output flue gas': 'Ausgangsrauchgas',
    'Bottom ashes calculated': 'Bodenaschenberechnung',
    'Bottom ash [kg/h]': 'Bodenasche [kg/h]',
    'Bottom ash wet [kg/h]': 'Feuchte Bodenasche [kg/h]',
    'Fly ash [kg/h]': 'Flugasche [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'SCR-Technologie',
    'Plaques catalytiques': 'Katalytische Platten',
    'Nid d\'abeilles': 'Wabenkörper',
    'Lit fixe': 'Festbett',
    'Paramètres SCR': 'SCR-Parameter',
    'Paramètres FAM': 'FAM-Parameter',
    'Débit de gaz [Nm³/h]': 'Gasstrom [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'NOx-Eingangskonzentration [mg/Nm³]',
    'Taux de réduction NOx [%]': 'NOx-Reduktionsrate [%]',
    'Température des gaz [°C]': 'Gastemperatur [°C]',
    'Vitesse spatiale [h⁻¹]': 'Raumgeschwindigkeit [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Oberflächengeschwindigkeit [m/s]',
    'Rendement de capture [%]': 'Abscheideeffizienz [%]',
    'Vitesse de filtration [m/h]': 'Filtergeschwindigkeit [m/h]',
    'PDC [mmCE]': 'Druckverlust [mmCE]',
    'Volume catalyseur requis [m³]': 'Erforderliches Katalysatorvolumen [m³]',
    'Section transversale [m²]': 'Querschnittsfläche [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'NOx-Ausgangskonzentration [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'NH₃-Verbrauch [kg/h]',
    'Perte de charge [Pa]': 'Druckverlust [Pa]',
    'Surface des manches [m²]': 'Schlauchoberfläche [m²]',
    'Pression de sortie [mmCE]': 'Ausgangsdruck [mmCE]',
    'Paramètres Calculés Généraux': 'Allgemeine berechnete Parameter',
    'Dimensionnement Spécifique': 'Spezifisches Design',
    'Résumé des paramètres principaux': 'Zusammenfassung der Hauptparameter',
    'Technologie': 'Technologie',
    'Volume catalyseur [m³]': 'Katalysatorvolumen [m³]',
    'Nombre de plaques': 'Anzahl der Platten',
    'Nombre de couches': 'Anzahl der Schichten',
    'Plaques par couche': 'Platten pro Schicht',
    'Hauteur réacteur [m]': 'Reaktorhöhe [m]',
    'Largeur réacteur [m]': 'Reaktorbreite [m]',
    'Longueur réacteur [m]': 'Reaktorlänge [m]',
    'Volume total plaques [m³]': 'Gesamtplattenvolumen [m³]',
    'Nombre d\'éléments': 'Anzahl der Elemente',
    'Éléments par rangée': 'Elemente pro Reihe',
    'Nombre de rangées': 'Anzahl der Reihen',
    'Densité cellulaire [cpsi]': 'Zelldichte [cpsi]',
    'Volume total éléments [m³]': 'Gesamtelementvolumen [m³]',
    'Volume lit total [m³]': 'Gesamtbettvolumen [m³]',
    'Hauteur du lit [m]': 'Betthöhe [m]',
    'Diamètre réacteur [m]': 'Reaktordurchmesser [m]',
    'Section du lit [m²]': 'Bettfläche [m²]',
    'Porosité du lit [%]': 'Bettporenraum [%]',
    'Masse catalyseur [kg]': 'Katalysatormasse [kg]',
    'Densité apparente [kg/m³]': 'Schüttdichte [kg/m³]',
    'Résultats': 'Ergebnisse',
  },
  it: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'Configurazione DENOX',
    'Back to Flow': 'Torna al flusso',
    'Flue gases': 'Gas di combustione',
    'Pollutant Emissions': 'Emissioni inquinanti',
    'Design': 'Progettazione',
    'Opex': 'Opex',

    // === DENOXFlueGasParameters - Parametri di emissione ===
    'Calculation parameters': 'Parametri di calcolo',
    'Clear memory': 'Cancella memoria',
    'Flue gas temperature before reheating [°C]': 'Temperatura gas di scarico prima del riscaldamento [°C]',
    'Flue gas temperature after reheating [°C]': 'Temperatura gas di scarico dopo il riscaldamento [°C]',
    'Ambient air temperature [°C]': 'Temperatura dell\'aria ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume di immissione d\'aria [Nm3/h]',
    'Thermal losses [%]': 'Perdite termiche [%]',
    'Cooling water temperature [°C]': 'Temperatura acqua di raffreddamento [°C]',
    'Water injection': 'Iniezione d\'acqua',
    'Gas type': 'Tipo di gas',
    'Water type': 'Tipo di acqua',
    'OUI': 'SÌ',
    'NON': 'NO',

    // === Risultati calcolati ===
    'Calculated parameters': 'Parametri calcolati',
    'Temperature inlet DENOX [°C]': 'Temperatura ingresso DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta entalpie [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Acqua spruzzata/raffreddata [kg/h]',
    'Total humid flue gas output [m³/h]': 'Portata totale gas di scarico umido [m³/h]',
    'Temperature before reheating [°C]': 'Temperatura prima del riscaldamento [°C]',
    'Temperature after reheating [°C]': 'Temperatura dopo il riscaldamento [°C]',
    'Adiabatic flame temperature [°C]': 'Temperatura adiabatica della fiamma [°C]',
    'Air factor [-]': 'Fattore aria [-]',
    'Combustion air volume [m³/h]': 'Volume aria di combustione [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Volume gas di scarico di combustione [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Portata gas per riscaldamento [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Temperatura di miscelazione calcolata [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Avvertenza: Il calcolo della combustione non ha convergito correttamente',
    'Warning: Reheating calculation did not converge after': '⚠️ Avvertenza: Il calcolo del riscaldamento non ha convergito dopo',
    'iterations': 'iterazioni',
    'No reheating required: outlet temperature is already above target': 'ℹ️ Nessun riscaldamento richiesto: la temperatura di uscita è già al di sopra del target',
    'Flue gas composition': 'Composizione gas di scarico',
    'Flue gas inlet at inlet temperature': 'Ingresso gas di scarico alla temperatura di ingresso',
    'Flue gas outlet at temperature before reheating': 'Uscita gas di scarico prima del riscaldamento',
    'Flue gas outlet at temperature after reheating': 'Uscita gas di scarico dopo il riscaldamento',

    // === FlueGasPollutantEmission - Parametri principali ===
    'Fly ashes content [g/Nm3]': 'Contenuto ceneri volatili [g/Nm3]',
    'siccity bottom ash [%]': 'Siccità ceneri di fondo [%]',
    'O2 ref [%]': 'O2 riferimento [%]',
    'SCR enabled': 'SCR abilitato',
    'NOx limit [mg/Nm3]': 'Limite NOx [mg/Nm3]',
    'Stoichiometry': 'Stechiometria',
    'SOx reactif': 'Reattivo SOx',
    'HCl reactif': 'Reattivo HCl',
    'HF reactif': 'Reattivo HF',
    'efficacite_SOx': 'Efficienza SOx [%]',
    'HCl efficacité': 'Efficienza HCl [%]',
    'HF efficacité': 'Efficienza HF [%]',
    'SOx stoechiométrie': 'Stechiometria SOx',
    'HCl stoechiométrie': 'Stechiometria HCl',
    'HF stoechiométrie': 'Stechiometria HF',
    'Reset to Default Values': 'Ripristina valori predefiniti',

    // === Parametri inquinanti ===
    'Waste Flow [kg/h]': 'Flusso rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flusso gas di scarico umido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flusso gas di scarico secco [Nm3/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Input flue gas': 'Gas di scarico in ingresso',
    'SCR (Selective Catalytic Reduction)': 'SCR (Riduzione Catalitica Selettiva)',
    'SCR enabled:': 'SCR abilitato:',
    'NOx limit [mg/Nm3]:': 'Limite NOx [mg/Nm3]:',
    'Stoichiometry:': 'Stechiometria:',
    'NH3 consumption [kg/h]:': 'Consumo NH₃ [kg/h]:',
    'NOx input [mg/Nm3]:': 'Ingresso NOx [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'Riduzione NOx [kg/h]:',
    'Pollutant Treatment Table': 'Tabella di trattamento degli inquinanti',
    'Polluant': 'Inquinante',
    'Réactif': 'Reattivo',
    'Masse (kg/h)': 'Massa (kg/h)',
    'Efficacité (%)': 'Efficienza (%)',
    'Coeff. Stoech': 'Coeff. Stechim.',
    'Masse sortie': 'Massa di uscita',
    'Masse résidu': 'Massa residua',
    'Masse réactif': 'Massa reattiva',
    'Masse abattue': 'Massa abbattuta',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Nessuno',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 secco',
    'CaOH2wet': 'CaOH2 bagnato',
    'CAP': 'CAP',
    'Ammonia': 'Ammoniaca',
    'Output flue gas': 'Gas di scarico in uscita',
    'Bottom ashes calculated': 'Ceneri di fondo calcolate',
    'Bottom ash [kg/h]': 'Ceneri di fondo [kg/h]',
    'Bottom ash wet [kg/h]': 'Ceneri di fondo bagnate [kg/h]',
    'Fly ash [kg/h]': 'Ceneri volatili [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'Tecnologia SCR',
    'Plaques catalytiques': 'Piatti catalitici',
    'Nid d\'abeilles': 'Favo',
    'Lit fixe': 'Letto fisso',
    'Paramètres SCR': 'Parametri SCR',
    'Paramètres FAM': 'Parametri FAM',
    'Débit de gaz [Nm³/h]': 'Portata gas [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'Concentrazione NOx in ingresso [mg/Nm³]',
    'Taux de réduction NOx [%]': 'Tasso di riduzione NOx [%]',
    'Température des gaz [°C]': 'Temperatura del gas [°C]',
    'Vitesse spatiale [h⁻¹]': 'Velocità spaziale [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Velocità superficiale [m/s]',
    'Rendement de capture [%]': 'Efficienza di raccolta [%]',
    'Vitesse de filtration [m/h]': 'Velocità di filtrazione [m/h]',
    'PDC [mmCE]': 'Caduta di pressione [mmCE]',
    'Volume catalyseur requis [m³]': 'Volume catalizzatore richiesto [m³]',
    'Section transversale [m²]': 'Area della sezione trasversale [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'Concentrazione NOx in uscita [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'Consumo NH₃ [kg/h]',
    'Perte de charge [Pa]': 'Caduta di pressione [Pa]',
    'Surface des manches [m²]': 'Superficie dei mandrini [m²]',
    'Pression de sortie [mmCE]': 'Pressione di uscita [mmCE]',
    'Paramètres Calculés Généraux': 'Parametri calcolati generali',
    'Dimensionnement Spécifique': 'Progettazione specifica',
    'Résumé des paramètres principaux': 'Riepilogo dei parametri principali',
    'Technologie': 'Tecnologia',
    'Volume catalyseur [m³]': 'Volume catalizzatore [m³]',
    'Nombre de plaques': 'Numero di piatti',
    'Nombre de couches': 'Numero di strati',
    'Plaques par couche': 'Piatti per strato',
    'Hauteur réacteur [m]': 'Altezza reattore [m]',
    'Largeur réacteur [m]': 'Larghezza reattore [m]',
    'Longueur réacteur [m]': 'Lunghezza reattore [m]',
    'Volume total plaques [m³]': 'Volume totale piatti [m³]',
    'Nombre d\'éléments': 'Numero di elementi',
    'Éléments par rangée': 'Elementi per riga',
    'Nombre de rangées': 'Numero di righe',
    'Densité cellulaire [cpsi]': 'Densità cellulare [cpsi]',
    'Volume total éléments [m³]': 'Volume totale elementi [m³]',
    'Volume lit total [m³]': 'Volume letto totale [m³]',
    'Hauteur du lit [m]': 'Altezza del letto [m]',
    'Diamètre réacteur [m]': 'Diametro reattore [m]',
    'Section du lit [m²]': 'Sezione del letto [m²]',
    'Porosité du lit [%]': 'Porosità del letto [%]',
    'Masse catalyseur [kg]': 'Massa catalizzatore [kg]',
    'Densité apparente [kg/m³]': 'Densità apparente [kg/m³]',
    'Résultats': 'Risultati',
  },
  es: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'Configuración DENOX',
    'Back to Flow': 'Volver al flujo',
    'Flue gases': 'Gases de combustión',
    'Pollutant Emissions': 'Emisiones de contaminantes',
    'Design': 'Diseño',
    'Opex': 'Opex',

    // === DENOXFlueGasParameters - Parámetros de emisión ===
    'Calculation parameters': 'Parámetros de cálculo',
    'Clear memory': 'Limpiar memoria',
    'Flue gas temperature before reheating [°C]': 'Temperatura del gas de combustión antes del recalentamiento [°C]',
    'Flue gas temperature after reheating [°C]': 'Temperatura del gas de combustión después del recalentamiento [°C]',
    'Ambient air temperature [°C]': 'Temperatura del aire ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volumen de entrada de aire [Nm3/h]',
    'Thermal losses [%]': 'Pérdidas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura del agua de enfriamiento [°C]',
    'Water injection': 'Inyección de agua',
    'Gas type': 'Tipo de gas',
    'Water type': 'Tipo de agua',
    'OUI': 'SÍ',
    'NON': 'NO',

    // === Resultados calculados ===
    'Calculated parameters': 'Parámetros calculados',
    'Temperature inlet DENOX [°C]': 'Temperatura de entrada DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta entalpías [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Agua pulverizada/enfriada [kg/h]',
    'Total humid flue gas output [m³/h]': 'Caudal total de gas de combustión húmedo [m³/h]',
    'Temperature before reheating [°C]': 'Temperatura antes del recalentamiento [°C]',
    'Temperature after reheating [°C]': 'Temperatura después del recalentamiento [°C]',
    'Adiabatic flame temperature [°C]': 'Temperatura adiabática de la llama [°C]',
    'Air factor [-]': 'Factor de aire [-]',
    'Combustion air volume [m³/h]': 'Volumen de aire de combustión [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Volumen de gas de combustión [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Caudal de gas para recalentamiento [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Temperatura de mezcla calculada [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Advertencia: El cálculo de combustión no convergió correctamente',
    'Warning: Reheating calculation did not converge after': '⚠️ Advertencia: El cálculo de recalentamiento no convergió después',
    'iterations': 'iteraciones',
    'No reheating required: outlet temperature is already above target': 'ℹ️ No se requiere recalentamiento: la temperatura de salida ya está por encima del objetivo',
    'Flue gas composition': 'Composición del gas de combustión',
    'Flue gas inlet at inlet temperature': 'Entrada de gas de combustión a temperatura de entrada',
    'Flue gas outlet at temperature before reheating': 'Salida de gas de combustión antes del recalentamiento',
    'Flue gas outlet at temperature after reheating': 'Salida de gas de combustión después del recalentamiento',

    // === FlueGasPollutantEmission - Parámetros principales ===
    'Fly ashes content [g/Nm3]': 'Contenido de cenizas volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Sequedad de cenizas de fondo [%]',
    'O2 ref [%]': 'O2 referencia [%]',
    'SCR enabled': 'SCR habilitado',
    'NOx limit [mg/Nm3]': 'Límite de NOx [mg/Nm3]',
    'Stoichiometry': 'Estequiometría',
    'SOx reactif': 'Reactivo SOx',
    'HCl reactif': 'Reactivo HCl',
    'HF reactif': 'Reactivo HF',
    'efficacite_SOx': 'Eficiencia SOx [%]',
    'HCl efficacité': 'Eficiencia HCl [%]',
    'HF efficacité': 'Eficiencia HF [%]',
    'SOx stoechiométrie': 'Estequiometría SOx',
    'HCl stoechiométrie': 'Estequiometría HCl',
    'HF stoechiométrie': 'Estequiometría HF',
    'Reset to Default Values': 'Restaurar valores predeterminados',

    // === Parámetros contaminantes ===
    'Waste Flow [kg/h]': 'Caudal de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Caudal de gas de combustión húmedo [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Caudal de gas de combustión seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Masa inerte [kg/h]',
    'Input flue gas': 'Gas de combustión de entrada',
    'SCR (Selective Catalytic Reduction)': 'SCR (Reducción Catalítica Selectiva)',
    'SCR enabled:': 'SCR habilitado:',
    'NOx limit [mg/Nm3]:': 'Límite de NOx [mg/Nm3]:',
    'Stoichiometry:': 'Estequiometría:',
    'NH3 consumption [kg/h]:': 'Consumo de NH₃ [kg/h]:',
    'NOx input [mg/Nm3]:': 'Entrada de NOx [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'Reducción de NOx [kg/h]:',
    'Pollutant Treatment Table': 'Tabla de tratamiento de contaminantes',
    'Polluant': 'Contaminante',
    'Réactif': 'Reactivo',
    'Masse (kg/h)': 'Masa (kg/h)',
    'Efficacité (%)': 'Eficiencia (%)',
    'Coeff. Stoech': 'Coef. Estequio.',
    'Masse sortie': 'Masa de salida',
    'Masse résidu': 'Masa residual',
    'Masse réactif': 'Masa reactiva',
    'Masse abattue': 'Masa reducida',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Ninguno',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 seco',
    'CaOH2wet': 'CaOH2 húmedo',
    'CAP': 'CAP',
    'Ammonia': 'Amoníaco',
    'Output flue gas': 'Gas de combustión de salida',
    'Bottom ashes calculated': 'Cenizas de fondo calculadas',
    'Bottom ash [kg/h]': 'Cenizas de fondo [kg/h]',
    'Bottom ash wet [kg/h]': 'Cenizas de fondo húmedas [kg/h]',
    'Fly ash [kg/h]': 'Cenizas volantes [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'Tecnología SCR',
    'Plaques catalytiques': 'Placas catalíticas',
    'Nid d\'abeilles': 'Panal',
    'Lit fixe': 'Lecho fijo',
    'Paramètres SCR': 'Parámetros SCR',
    'Paramètres FAM': 'Parámetros FAM',
    'Débit de gaz [Nm³/h]': 'Caudal de gas [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'Concentración de NOx de entrada [mg/Nm³]',
    'Taux de réduction NOx [%]': 'Tasa de reducción de NOx [%]',
    'Température des gaz [°C]': 'Temperatura del gas [°C]',
    'Vitesse spatiale [h⁻¹]': 'Velocidad espacial [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Velocidad superficial [m/s]',
    'Rendement de capture [%]': 'Eficiencia de recolección [%]',
    'Vitesse de filtration [m/h]': 'Velocidad de filtración [m/h]',
    'PDC [mmCE]': 'Caída de presión [mmCE]',
    'Volume catalyseur requis [m³]': 'Volumen de catalizador requerido [m³]',
    'Section transversale [m²]': 'Área de sección transversal [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'Concentración de NOx de salida [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'Consumo de NH₃ [kg/h]',
    'Perte de charge [Pa]': 'Caída de presión [Pa]',
    'Surface des manches [m²]': 'Superficie de mangas [m²]',
    'Pression de sortie [mmCE]': 'Presión de salida [mmCE]',
    'Paramètres Calculés Généraux': 'Parámetros calculados generales',
    'Dimensionnement Spécifique': 'Dimensionamiento específico',
    'Résumé des paramètres principaux': 'Resumen de parámetros principales',
    'Technologie': 'Tecnología',
    'Volume catalyseur [m³]': 'Volumen del catalizador [m³]',
    'Nombre de plaques': 'Número de placas',
    'Nombre de couches': 'Número de capas',
    'Plaques par couche': 'Placas por capa',
    'Hauteur réacteur [m]': 'Altura del reactor [m]',
    'Largeur réacteur [m]': 'Ancho del reactor [m]',
    'Longueur réacteur [m]': 'Longitud del reactor [m]',
    'Volume total plaques [m³]': 'Volumen total de placas [m³]',
    'Nombre d\'éléments': 'Número de elementos',
    'Éléments par rangée': 'Elementos por fila',
    'Nombre de rangées': 'Número de filas',
    'Densité cellulaire [cpsi]': 'Densidad celular [cpsi]',
    'Volume total éléments [m³]': 'Volumen total de elementos [m³]',
    'Volume lit total [m³]': 'Volumen total del lecho [m³]',
    'Hauteur du lit [m]': 'Altura del lecho [m]',
    'Diamètre réacteur [m]': 'Diámetro del reactor [m]',
    'Section du lit [m²]': 'Sección del lecho [m²]',
    'Porosité du lit [%]': 'Porosidad del lecho [%]',
    'Masse catalyseur [kg]': 'Masa del catalizador [kg]',
    'Densité apparente [kg/m³]': 'Densidad aparente [kg/m³]',
    'Résultats': 'Resultados',
  },
  pt: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'Configuração DENOX',
    'Back to Flow': 'Voltar ao fluxo',
    'Flue gases': 'Gases de combustão',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Design': 'Projeto',
    'Opex': 'Opex',

    // === DENOXFlueGasParameters - Parâmetros de emissão ===
    'Calculation parameters': 'Parâmetros de cálculo',
    'Clear memory': 'Limpar memória',
    'Flue gas temperature before reheating [°C]': 'Temperatura do gás de combustão antes do reaquecimento [°C]',
    'Flue gas temperature after reheating [°C]': 'Temperatura do gás de combustão após o reaquecimento [°C]',
    'Ambient air temperature [°C]': 'Temperatura do ar ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume de entrada de ar [Nm3/h]',
    'Thermal losses [%]': 'Perdas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura da água de resfriamento [°C]',
    'Water injection': 'Injeção de água',
    'Gas type': 'Tipo de gás',
    'Water type': 'Tipo de água',
    'OUI': 'SIM',
    'NON': 'NÃO',

    // === Resultados calculados ===
    'Calculated parameters': 'Parâmetros calculados',
    'Temperature inlet DENOX [°C]': 'Temperatura de entrada DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Delta entalpias [kJ/h]',
    'Sprayed/cooling water [kg/h]': 'Água pulverizada/resfriada [kg/h]',
    'Total humid flue gas output [m³/h]': 'Vazão total de gás de combustão úmido [m³/h]',
    'Temperature before reheating [°C]': 'Temperatura antes do reaquecimento [°C]',
    'Temperature after reheating [°C]': 'Temperatura após o reaquecimento [°C]',
    'Adiabatic flame temperature [°C]': 'Temperatura adiabática da chama [°C]',
    'Air factor [-]': 'Fator de ar [-]',
    'Combustion air volume [m³/h]': 'Volume de ar de combustão [m³/h]',
    'Combustion flue gas volume [m³/h]': 'Volume de gás de combustão [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': 'Vazão de gás para reaquecimento [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Temperatura de mistura calculada [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Aviso: O cálculo de combustão não convergiu corretamente',
    'Warning: Reheating calculation did not converge after': '⚠️ Aviso: O cálculo de reaquecimento não convergiu após',
    'iterations': 'iterações',
    'No reheating required: outlet temperature is already above target': 'ℹ️ Nenhum reaquecimento necessário: a temperatura de saída já está acima do alvo',
    'Flue gas composition': 'Composição do gás de combustão',
    'Flue gas inlet at inlet temperature': 'Entrada de gás de combustão na temperatura de entrada',
    'Flue gas outlet at temperature before reheating': 'Saída de gás de combustão antes do reaquecimento',
    'Flue gas outlet at temperature after reheating': 'Saída de gás de combustão após o reaquecimento',

    // === FlueGasPollutantEmission - Parâmetros principais ===
    'Fly ashes content [g/Nm3]': 'Conteúdo de cinzas volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Secura de cinzas de fundo [%]',
    'O2 ref [%]': 'O2 referência [%]',
    'SCR enabled': 'SCR habilitado',
    'NOx limit [mg/Nm3]': 'Limite de NOx [mg/Nm3]',
    'Stoichiometry': 'Estequiometria',
    'SOx reactif': 'Reagente SOx',
    'HCl reactif': 'Reagente HCl',
    'HF reactif': 'Reagente HF',
    'efficacite_SOx': 'Eficiência SOx [%]',
    'HCl efficacité': 'Eficiência HCl [%]',
    'HF efficacité': 'Eficiência HF [%]',
    'SOx stoechiométrie': 'Estequiometria SOx',
    'HCl stoechiométrie': 'Estequiometria HCl',
    'HF stoechiométrie': 'Estequiometria HF',
    'Reset to Default Values': 'Restaurar valores padrão',

    // === Parâmetros de poluentes ===
    'Waste Flow [kg/h]': 'Vazão de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Vazão de gás de combustão úmido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Vazão de gás de combustão seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Input flue gas': 'Gás de combustão de entrada',
    'SCR (Selective Catalytic Reduction)': 'SCR (Redução Catalítica Seletiva)',
    'SCR enabled:': 'SCR habilitado:',
    'NOx limit [mg/Nm3]:': 'Limite de NOx [mg/Nm3]:',
    'Stoichiometry:': 'Estequiometria:',
    'NH3 consumption [kg/h]:': 'Consumo de NH₃ [kg/h]:',
    'NOx input [mg/Nm3]:': 'Entrada de NOx [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'Redução de NOx [kg/h]:',
    'Pollutant Treatment Table': 'Tabela de tratamento de poluentes',
    'Polluant': 'Poluente',
    'Réactif': 'Reagente',
    'Masse (kg/h)': 'Massa (kg/h)',
    'Efficacité (%)': 'Eficiência (%)',
    'Coeff. Stoech': 'Coef. Estequio.',
    'Masse sortie': 'Massa de saída',
    'Masse résidu': 'Massa residual',
    'Masse réactif': 'Massa reativa',
    'Masse abattue': 'Massa reduzida',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Nenhum',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 seco',
    'CaOH2wet': 'CaOH2 úmido',
    'CAP': 'CAP',
    'Ammonia': 'Amônia',
    'Output flue gas': 'Gás de combustão de saída',
    'Bottom ashes calculated': 'Cinzas de fundo calculadas',
    'Bottom ash [kg/h]': 'Cinzas de fundo [kg/h]',
    'Bottom ash wet [kg/h]': 'Cinzas de fundo úmidas [kg/h]',
    'Fly ash [kg/h]': 'Cinzas volantes [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'Tecnologia SCR',
    'Plaques catalytiques': 'Placas catalíticas',
    'Nid d\'abeilles': 'Favo',
    'Lit fixe': 'Leito fixo',
    'Paramètres SCR': 'Parâmetros SCR',
    'Paramètres FAM': 'Parâmetros FAM',
    'Débit de gaz [Nm³/h]': 'Vazão de gás [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'Concentração de NOx de entrada [mg/Nm³]',
    'Taux de réduction NOx [%]': 'Taxa de redução de NOx [%]',
    'Température des gaz [°C]': 'Temperatura do gás [°C]',
    'Vitesse spatiale [h⁻¹]': 'Velocidade espacial [h⁻¹]',
    'Vitesse superficielle [m/s]': 'Velocidade superficial [m/s]',
    'Rendement de capture [%]': 'Eficiência de coleta [%]',
    'Vitesse de filtration [m/h]': 'Velocidade de filtração [m/h]',
    'PDC [mmCE]': 'Queda de pressão [mmCE]',
    'Volume catalyseur requis [m³]': 'Volume de catalisador necessário [m³]',
    'Section transversale [m²]': 'Área da seção transversal [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'Concentração de NOx de saída [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'Consumo de NH₃ [kg/h]',
    'Perte de charge [Pa]': 'Queda de pressão [Pa]',
    'Surface des manches [m²]': 'Área das mangas [m²]',
    'Pression de sortie [mmCE]': 'Pressão de saída [mmCE]',
    'Paramètres Calculés Généraux': 'Parâmetros calculados gerais',
    'Dimensionnement Spécifique': 'Dimensionamento específico',
    'Résumé des paramètres principaux': 'Resumo dos parâmetros principais',
    'Technologie': 'Tecnologia',
    'Volume catalyseur [m³]': 'Volume de catalisador [m³]',
    'Nombre de plaques': 'Número de placas',
    'Nombre de couches': 'Número de camadas',
    'Plaques par couche': 'Placas por camada',
    'Hauteur réacteur [m]': 'Altura do reator [m]',
    'Largeur réacteur [m]': 'Largura do reator [m]',
    'Longueur réacteur [m]': 'Comprimento do reator [m]',
    'Volume total plaques [m³]': 'Volume total de placas [m³]',
    'Nombre d\'éléments': 'Número de elementos',
    'Éléments par rangée': 'Elementos por fileira',
    'Nombre de rangées': 'Número de fileiras',
    'Densité cellulaire [cpsi]': 'Densidade celular [cpsi]',
    'Volume total éléments [m³]': 'Volume total de elementos [m³]',
    'Volume lit total [m³]': 'Volume total do leito [m³]',
    'Hauteur du lit [m]': 'Altura do leito [m]',
    'Diamètre réacteur [m]': 'Diâmetro do reator [m]',
    'Section du lit [m²]': 'Seção do leito [m²]',
    'Porosité du lit [%]': 'Porosidade do leito [%]',
    'Masse catalyseur [kg]': 'Massa do catalisador [kg]',
    'Densité apparente [kg/m³]': 'Densidade aparente [kg/m³]',
    'Résultats': 'Resultados',
  },
  zh: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'DENOX 配置',
    'Back to Flow': '返回流程',
    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Design': '设计',
    'Opex': '运营支出',

    // === DENOXFlueGasParameters - 排放参数 ===
    'Calculation parameters': '计算参数',
    'Clear memory': '清除内存',
    'Flue gas temperature before reheating [°C]': '再热前烟气温度 [°C]',
    'Flue gas temperature after reheating [°C]': '再热后烟气温度 [°C]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空气进入体积 [Nm3/h]',
    'Thermal losses [%]': '热损失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Water injection': '水喷射',
    'Gas type': '气体类型',
    'Water type': '水类型',
    'OUI': '是',
    'NON': '否',

    // === 计算结果 ===
    'Calculated parameters': '计算参数',
    'Temperature inlet DENOX [°C]': 'DENOX 入口温度 [°C]',
    'Delta enthalpies [kJ/h]': '焓差 [kJ/h]',
    'Sprayed/cooling water [kg/h]': '喷射/冷却水 [kg/h]',
    'Total humid flue gas output [m³/h]': '总湿烟气输出 [m³/h]',
    'Temperature before reheating [°C]': '再热前温度 [°C]',
    'Temperature after reheating [°C]': '再热后温度 [°C]',
    'Adiabatic flame temperature [°C]': '绝热火焰温度 [°C]',
    'Air factor [-]': '空气系数 [-]',
    'Combustion air volume [m³/h]': '燃烧空气体积 [m³/h]',
    'Combustion flue gas volume [m³/h]': '燃烧烟气体积 [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': '再热气体流速 [Nm³/h]',
    'Calculated mixing temperature [°C]': '计算混合温度 [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ 警告：燃烧计算未正确收敛',
    'Warning: Reheating calculation did not converge after': '⚠️ 警告：再热计算未收敛后',
    'iterations': '迭代',
    'No reheating required: outlet temperature is already above target': 'ℹ️ 不需要再热：出口温度已经高于目标',
    'Flue gas composition': '烟气成分',
    'Flue gas inlet at inlet temperature': '入口处烟气入口',
    'Flue gas outlet at temperature before reheating': '再热前烟气出口',
    'Flue gas outlet at temperature after reheating': '再热后烟气出口',

    // === FlueGasPollutantEmission - 主要参数 ===
    'Fly ashes content [g/Nm3]': '飞灰含量 [g/Nm3]',
    'siccity bottom ash [%]': '底灰干度 [%]',
    'O2 ref [%]': 'O2 参考 [%]',
    'SCR enabled': 'SCR 启用',
    'NOx limit [mg/Nm3]': 'NOx 限制 [mg/Nm3]',
    'Stoichiometry': '化学计量学',
    'SOx reactif': 'SOx 反应剂',
    'HCl reactif': 'HCl 反应剂',
    'HF reactif': 'HF 反应剂',
    'efficacite_SOx': 'SOx 效率 [%]',
    'HCl efficacité': 'HCl 效率 [%]',
    'HF efficacité': 'HF 效率 [%]',
    'SOx stoechiométrie': 'SOx 化学计量学',
    'HCl stoechiométrie': 'HCl 化学计量学',
    'HF stoechiométrie': 'HF 化学计量学',
    'Reset to Default Values': '重置为默认值',

    // === 污染物参数 ===
    'Waste Flow [kg/h]': '废物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流量 [Nm3/h]',
    'O2 calculated [%]': 'O2 计算 [%]',
    'inert mass [kg/h]': '惰性质量 [kg/h]',
    'Input flue gas': '输入烟气',
    'SCR (Selective Catalytic Reduction)': 'SCR (选择性催化还原)',
    'SCR enabled:': 'SCR 启用：',
    'NOx limit [mg/Nm3]:': 'NOx 限制 [mg/Nm3]：',
    'Stoichiometry:': '化学计量学：',
    'NH3 consumption [kg/h]:': 'NH₃ 消耗 [kg/h]：',
    'NOx input [mg/Nm3]:': 'NOx 输入 [mg/Nm3]：',
    'NOx reduced [kg/h]:': 'NOx 还原 [kg/h]：',
    'Pollutant Treatment Table': '污染物处理表',
    'Polluant': '污染物',
    'Réactif': '反应剂',
    'Masse (kg/h)': '质量 (kg/h)',
    'Efficacité (%)': '效率 (%)',
    'Coeff. Stoech': '化学计量系数',
    'Masse sortie': '输出质量',
    'Masse résidu': '残留质量',
    'Masse réactif': '反应剂质量',
    'Masse abattue': '减少的质量',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': '无',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 干',
    'CaOH2wet': 'CaOH2 湿',
    'CAP': 'CAP',
    'Ammonia': '氨',
    'Output flue gas': '输出烟气',
    'Bottom ashes calculated': '计算的底灰',
    'Bottom ash [kg/h]': '底灰 [kg/h]',
    'Bottom ash wet [kg/h]': '湿底灰 [kg/h]',
    'Fly ash [kg/h]': '飞灰 [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'SCR 技术',
    'Plaques catalytiques': '催化剂板',
    'Nid d\'abeilles': '蜂窝',
    'Lit fixe': '固定床',
    'Paramètres SCR': 'SCR 参数',
    'Paramètres FAM': 'FAM 参数',
    'Débit de gaz [Nm³/h]': '气体流速 [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'NOx 入口浓度 [mg/Nm³]',
    'Taux de réduction NOx [%]': 'NOx 还原率 [%]',
    'Température des gaz [°C]': '气体温度 [°C]',
    'Vitesse spatiale [h⁻¹]': '空间速度 [h⁻¹]',
    'Vitesse superficielle [m/s]': '表观速度 [m/s]',
    'Rendement de capture [%]': '捕集效率 [%]',
    'Vitesse de filtration [m/h]': '过滤速度 [m/h]',
    'PDC [mmCE]': '压降 [mmCE]',
    'Volume catalyseur requis [m³]': '所需催化剂体积 [m³]',
    'Section transversale [m²]': '横截面积 [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'NOx 出口浓度 [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'NH₃ 消耗 [kg/h]',
    'Perte de charge [Pa]': '压降 [Pa]',
    'Surface des manches [m²]': '滤袋表面积 [m²]',
    'Pression de sortie [mmCE]': '出口压力 [mmCE]',
    'Paramètres Calculés Généraux': '一般计算参数',
    'Dimensionnement Spécifique': '具体尺寸设计',
    'Résumé des paramètres principaux': '主要参数摘要',
    'Technologie': '技术',
    'Volume catalyseur [m³]': '催化剂体积 [m³]',
    'Nombre de plaques': '板数',
    'Nombre de couches': '层数',
    'Plaques par couche': '每层板数',
    'Hauteur réacteur [m]': '反应器高度 [m]',
    'Largeur réacteur [m]': '反应器宽度 [m]',
    'Longueur réacteur [m]': '反应器长度 [m]',
    'Volume total plaques [m³]': '总板体积 [m³]',
    'Nombre d\'éléments': '元素数量',
    'Éléments par rangée': '每行元素数',
    'Nombre de rangées': '行数',
    'Densité cellulaire [cpsi]': '单元密度 [cpsi]',
    'Volume total éléments [m³]': '总元素体积 [m³]',
    'Volume lit total [m³]': '总床体积 [m³]',
    'Hauteur du lit [m]': '床高 [m]',
    'Diamètre réacteur [m]': '反应器直径 [m]',
    'Section du lit [m²]': '床截面 [m²]',
    'Porosité du lit [%]': '床孔隙率 [%]',
    'Masse catalyseur [kg]': '催化剂质量 [kg]',
    'Densité apparente [kg/m³]': '表观密度 [kg/m³]',
    'Résultats': '结果',
  },
  ja: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'DENOX設定',
    'Back to Flow': 'フローに戻る',
    'Flue gases': '排ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Design': '設計',
    'Opex': '運営支出',

    // === DENOXFlueGasParameters - 排出パラメータ ===
    'Calculation parameters': '計算パラメータ',
    'Clear memory': 'メモリをクリア',
    'Flue gas temperature before reheating [°C]': '再加熱前の排ガス温度 [°C]',
    'Flue gas temperature after reheating [°C]': '再加熱後の排ガス温度 [°C]',
    'Ambient air temperature [°C]': '周囲空気温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空気流入量 [Nm3/h]',
    'Thermal losses [%]': '熱損失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Water injection': '水注入',
    'Gas type': 'ガスタイプ',
    'Water type': '水のタイプ',
    'OUI': 'はい',
    'NON': 'いいえ',

    // === 計算結果 ===
    'Calculated parameters': '計算されたパラメータ',
    'Temperature inlet DENOX [°C]': 'DENOX入口温度 [°C]',
    'Delta enthalpies [kJ/h]': 'デルタエンタルピ [kJ/h]',
    'Sprayed/cooling water [kg/h]': '噴霧/冷却水 [kg/h]',
    'Total humid flue gas output [m³/h]': '総湿排ガス出力 [m³/h]',
    'Temperature before reheating [°C]': '再加熱前の温度 [°C]',
    'Temperature after reheating [°C]': '再加熱後の温度 [°C]',
    'Adiabatic flame temperature [°C]': '断熱火焔温度 [°C]',
    'Air factor [-]': '空気係数 [-]',
    'Combustion air volume [m³/h]': '燃焼空気体積 [m³/h]',
    'Combustion flue gas volume [m³/h]': '燃焼排ガス体積 [m³/h]',
    'Gas flow rate for reheating [Nm³/h]': '再加熱用ガス流速 [Nm³/h]',
    'Calculated mixing temperature [°C]': '計算された混合温度 [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ 警告: 燃焼計算が正しく収束しませんでした',
    'Warning: Reheating calculation did not converge after': '⚠️ 警告: 再加熱計算が収束しませんでした',
    'iterations': 'イテレーション',
    'No reheating required: outlet temperature is already above target': 'ℹ️ 再加熱は必要ありません: 出口温度は既にターゲットを上回っています',
    'Flue gas composition': '排ガス組成',
    'Flue gas inlet at inlet temperature': '入口温度での排ガス入口',
    'Flue gas outlet at temperature before reheating': '再加熱前の排ガス出口',
    'Flue gas outlet at temperature after reheating': '再加熱後の排ガス出口',

    // === FlueGasPollutantEmission - 主要パラメータ ===
    'Fly ashes content [g/Nm3]': 'フライアッシュ含有量 [g/Nm3]',
    'siccity bottom ash [%]': 'ボトムアッシュ乾燥度 [%]',
    'O2 ref [%]': 'O2参照 [%]',
    'SCR enabled': 'SCR有効',
    'NOx limit [mg/Nm3]': 'NOx制限 [mg/Nm3]',
    'Stoichiometry': '化学量論',
    'SOx reactif': 'SOx反応剤',
    'HCl reactif': 'HCl反応剤',
    'HF reactif': 'HF反応剤',
    'efficacite_SOx': 'SOx効率 [%]',
    'HCl efficacité': 'HCl効率 [%]',
    'HF efficacité': 'HF効率 [%]',
    'SOx stoechiométrie': 'SOx化学量論',
    'HCl stoechiométrie': 'HCl化学量論',
    'HF stoechiométrie': 'HF化学量論',
    'Reset to Default Values': 'デフォルト値にリセット',

    // === 汚染物質パラメータ ===
    'Waste Flow [kg/h]': '廃棄物流 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿排ガス流 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾排ガス流 [Nm3/h]',
    'O2 calculated [%]': 'O2計算 [%]',
    'inert mass [kg/h]': '不活性物質 [kg/h]',
    'Input flue gas': '入力排ガス',
    'SCR (Selective Catalytic Reduction)': 'SCR (選択的触媒還元)',
    'SCR enabled:': 'SCR有効:',
    'NOx limit [mg/Nm3]:': 'NOx制限 [mg/Nm3]:',
    'Stoichiometry:': '化学量論:',
    'NH3 consumption [kg/h]:': 'NH₃消費 [kg/h]:',
    'NOx input [mg/Nm3]:': 'NOx入力 [mg/Nm3]:',
    'NOx reduced [kg/h]:': 'NOx削減 [kg/h]:',
    'Pollutant Treatment Table': '汚染物質処理表',
    'Polluant': '汚染物質',
    'Réactif': '反応剤',
    'Masse (kg/h)': '質量 (kg/h)',
    'Efficacité (%)': '効率 (%)',
    'Coeff. Stoech': '化学量論係数',
    'Masse sortie': '出力質量',
    'Masse résidu': '残留質量',
    'Masse réactif': '反応剤質量',
    'Masse abattue': '削減質量',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'なし',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2乾',
    'CaOH2wet': 'CaOH2湿',
    'CAP': 'CAP',
    'Ammonia': 'アンモニア',
    'Output flue gas': '出力排ガス',
    'Bottom ashes calculated': '計算されたボトムアッシュ',
    'Bottom ash [kg/h]': 'ボトムアッシュ [kg/h]',
    'Bottom ash wet [kg/h]': '湿ボトムアッシュ [kg/h]',
    'Fly ash [kg/h]': 'フライアッシュ [kg/h]',

    // === DENOXDesign ===
    'Technologie SCR': 'SCR技術',
    'Plaques catalytiques': '触媒プレート',
    'Nid d\'abeilles': 'ハニカム',
    'Lit fixe': '固定床',
    'Paramètres SCR': 'SCRパラメータ',
    'Paramètres FAM': 'FAMパラメータ',
    'Débit de gaz [Nm³/h]': 'ガス流速 [Nm³/h]',
    'Concentration NOx entrée [mg/Nm³]': 'NOx入口濃度 [mg/Nm³]',
    'Taux de réduction NOx [%]': 'NOx削減率 [%]',
    'Température des gaz [°C]': 'ガス温度 [°C]',
    'Vitesse spatiale [h⁻¹]': '空間速度 [h⁻¹]',
    'Vitesse superficielle [m/s]': '表面速度 [m/s]',
    'Rendement de capture [%]': '集塵効率 [%]',
    'Vitesse de filtration [m/h]': 'ろ過速度 [m/h]',
    'PDC [mmCE]': '圧力損失 [mmCE]',
    'Volume catalyseur requis [m³]': '必要な触媒体積 [m³]',
    'Section transversale [m²]': '断面積 [m²]',
    'Concentration NOx sortie [mg/Nm³]': 'NOx出口濃度 [mg/Nm³]',
    'Consommation NH₃ [kg/h]': 'NH₃消費 [kg/h]',
    'Perte de charge [Pa]': '圧力損失 [Pa]',
    'Surface des manches [m²]': 'フィルターバッグ表面積 [m²]',
    'Pression de sortie [mmCE]': '出口圧力 [mmCE]',
    'Paramètres Calculés Généraux': '一般計算パラメータ',
    'Dimensionnement Spécifique': '特定設計',
    'Résumé des paramètres principaux': '主要パラメータの概要',
    'Technologie': 'テクノロジー',
    'Volume catalyseur [m³]': '触媒体積 [m³]',
    'Nombre de plaques': 'プレート数',
    'Nombre de couches': 'レイヤー数',
    'Plaques par couche': 'レイヤーあたりのプレート数',
    'Hauteur réacteur [m]': 'リアクター高さ [m]',
    'Largeur réacteur [m]': 'リアクター幅 [m]',
    'Longueur réacteur [m]': 'リアクター長さ [m]',
    'Volume total plaques [m³]': '総プレート体積 [m³]',
    'Nombre d\'éléments': '要素数',
    'Éléments par rangée': '行あたりの要素数',
    'Nombre de rangées': '行数',
    'Densité cellulaire [cpsi]': 'セル密度 [cpsi]',
    'Volume total éléments [m³]': '総要素体積 [m³]',
    'Volume lit total [m³]': '総床体積 [m³]',
    'Hauteur du lit [m]': 'ベッド高さ [m]',
    'Diamètre réacteur [m]': 'リアクター直径 [m]',
    'Section du lit [m²]': 'ベッド断面 [m²]',
    'Porosité du lit [%]': 'ベッド孔隙率 [%]',
    'Masse catalyseur [kg]': '触媒質量 [kg]',
    'Densité apparente [kg/m³]': '嵩密度 [kg/m³]',
    'Résultats': '結果',
  },

  ru: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'Конфигурация DENOX',
    'Back to Flow': 'Вернуться к потоку',
    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязняющих веществ',
    'Design': 'Проектирование',
    'Opex': 'Опекс',

    // === DENOXFlueGasParameters - Параметры выбросов ===
    'Calculation parameters': 'Параметры расчета',
    'Clear memory': 'Очистить память',
    'Flue gas temperature before reheating [°C]': 'Температура дымовых газов перед повторным нагревом [°C]',
    'Flue gas temperature after reheating [°C]': 'Температура дымовых газов после повторного нагрева [°C]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Volume of air ingress [Nm3/h]': 'Объем поступающего воздуха [Nm3/h]',
    'Thermal losses [%]': 'Тепловые потери [%]',
    'Cooling water temperature [°C]': 'Температура охлаждающей воды [°C]',
    'Water injection': 'Впрыск воды',
    'Gas type': 'Тип газа',
    'Water type': 'Тип воды',
    'OUI': 'ДА',
    'NON': 'НЕТ',

    // === Рассчитанные результаты ===
    'Calculated parameters': 'Рассчитанные параметры',
    'Temperature inlet DENOX [°C]': 'Температура входа DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'Дельта энтальпий [кДж/ч]',
    'Sprayed/cooling water [kg/h]': 'Распыленная/охлаждающая вода [кг/ч]',
    'Total humid flue gas output [m³/h]': 'Полный выход влажного дымового газа [м³/ч]',
    'Temperature before reheating [°C]': 'Температура перед повторным нагревом [°C]',
    'Temperature after reheating [°C]': 'Температура после повторного нагрева [°C]',
    'Adiabatic flame temperature [°C]': 'Адиабатическая температура пламени [°C]',
    'Air factor [-]': 'Коэффициент воздуха [-]',
    'Combustion air volume [m³/h]': 'Объем воздуха горения [м³/ч]',
    'Combustion flue gas volume [m³/h]': 'Объем дымовых газов горения [м³/ч]',
    'Gas flow rate for reheating [Nm³/h]': 'Скорость потока газа для повторного нагрева [Nm³/h]',
    'Calculated mixing temperature [°C]': 'Рассчитанная температура смешивания [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ Предупреждение: расчет горения не сходился должным образом',
    'Warning: Reheating calculation did not converge after': '⚠️ Предупреждение: расчет повторного нагрева не сошелся после',
    'iterations': 'итераций',
    'No reheating required: outlet temperature is already above target': 'ℹ️ Повторный нагрев не требуется: температура на выходе уже превышает целевую',
    'Flue gas composition': 'Состав дымовых газов',
    'Flue gas inlet at inlet temperature': 'Вход дымовых газов при температуре входа',
    'Flue gas outlet at temperature before reheating': 'Выход дымовых газов перед повторным нагревом',
    'Flue gas outlet at temperature after reheating': 'Выход дымовых газов после повторного нагрева',

    // === FlueGasPollutantEmission - Основные параметры ===
    'Fly ashes content [g/Nm3]': 'Содержание летучей золы [г/Nm3]',
    'siccity bottom ash [%]': 'Сухость золы [%]',
    'O2 ref [%]': 'O2 ориентир [%]',
    'SCR enabled': 'SCR включен',
    'NOx limit [mg/Nm3]': 'Предел NOx [мг/Nm3]',
    'Stoichiometry': 'Стехиометрия',
    'SOx reactif': 'Реагент SOx',
    'HCl reactif': 'Реагент HCl',
    'HF reactif': 'Реагент HF',
    'efficacite_SOx': 'Эффективность SOx [%]',
    'HCl efficacité': 'Эффективность HCl [%]',
    'HF efficacité': 'Эффективность HF [%]',
    'SOx stoechiométrie': 'Стехиометрия SOx',
    'HCl stoechiométrie': 'Стехиометрия HCl',
    'HF stoechiométrie': 'Стехиометрия HF',
    'Reset to Default Values': 'Восстановить значения по умолчанию',

    // === Параметры загрязняющих веществ ===
    'Waste Flow [kg/h]': 'Поток отходов [кг/ч]',
    'Flue gas Flow Wet [Nm3/h]': 'Поток влажного дымового газа [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Поток сухого дымового газа [Nm3/h]',
    'O2 calculated [%]': 'O2 рассчитанный [%]',
    'inert mass [kg/h]': 'Масса инертная [кг/ч]',
    'Input flue gas': 'Входящий дымовой газ',
    'SCR (Selective Catalytic Reduction)': 'SCR (Селективное каталитическое восстановление)',
    'SCR enabled:': 'SCR включен:',
    'NOx limit [mg/Nm3]:': 'Предел NOx [мг/Nm3]:',
    'Stoichiometry:': 'Стехиометрия:',
    'NH3 consumption [kg/h]:': 'Потребление NH₃ [кг/ч]:',
    'NOx input [mg/Nm3]:': 'Вход NOx [мг/Nm3]:',
    'NOx reduced [kg/h]:': 'NOx восстановлен [кг/ч]:',
    'Pollutant Treatment Table': 'Таблица обработки загрязняющих веществ',
    'Polluant': 'Загрязняющее вещество',
    'Réactif': 'Реагент',
    'Masse (kg/h)': 'Масса (кг/ч)',
    'Efficacité (%)': 'Эффективность (%)',
    'Coeff. Stoech': 'Коэф. Стехиометр.',
    'Masse sortie': 'Выходная масса',
    'Masse résidu': 'Остаток массы',
    'Masse réactif': 'Масса реагента',
    'Masse abattue': 'Уменьшенная масса',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'Нет',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 сухой',
    'CaOH2wet': 'CaOH2 влажный',
    'CAP': 'CAP',
    'Ammonia': 'Аммиак',
    'Output flue gas': 'Выходящий дымовой газ',
    'Bottom ashes calculated': 'Рассчитанная зола',
    'Bottom ash [kg/h]': 'Золы [кг/ч]',
    'Bottom ash wet [kg/h]': 'Влажная зола [кг/ч]',
    'Fly ash [kg/h]': 'Летучая зола [кг/ч]',

    // === DENOXDesign ===
    'Technologie SCR': 'Технология SCR',
    'Plaques catalytiques': 'Каталитические пластины',
    'Nid d\'abeilles': 'Сотовая структура',
    'Lit fixe': 'Неподвижный слой',
    'Paramètres SCR': 'Параметры SCR',
    'Paramètres FAM': 'Параметры FAM',
    'Débit de gaz [Nm³/h]': 'Расход газа [Nm³/ч]',
    'Concentration NOx entrée [mg/Nm³]': 'Концентрация NOx на входе [мг/Nm³]',
    'Taux de réduction NOx [%]': 'Скорость снижения NOx [%]',
    'Température des gaz [°C]': 'Температура газа [°C]',
    'Vitesse spatiale [h⁻¹]': 'Пространственная скорость [ч⁻¹]',
    'Vitesse superficielle [m/s]': 'Поверхностная скорость [м/с]',
    'Rendement de capture [%]': 'Эффективность захвата [%]',
    'Vitesse de filtration [m/h]': 'Скорость фильтрации [м/ч]',
    'PDC [mmCE]': 'Перепад давления [mmCE]',
    'Volume catalyseur requis [m³]': 'Требуемый объем катализатора [м³]',
    'Section transversale [m²]': 'Площадь поперечного сечения [м²]',
    'Concentration NOx sortie [mg/Nm³]': 'Концентрация NOx на выходе [мг/Nm³]',
    'Consommation NH₃ [kg/h]': 'Потребление NH₃ [кг/ч]',
    'Perte de charge [Pa]': 'Перепад давления [Па]',
    'Surface des manches [m²]': 'Площадь фильтровальных рукавов [м²]',
    'Pression de sortie [mmCE]': 'Давление на выходе [mmCE]',
    'Paramètres Calculés Généraux': 'Общие рассчитанные параметры',
    'Dimensionnement Spécifique': 'Специальное проектирование',
    'Résumé des paramètres principaux': 'Резюме основных параметров',
    'Technologie': 'Технология',
    'Volume catalyseur [m³]': 'Объем катализатора [м³]',
    'Nombre de plaques': 'Количество пластин',
    'Nombre de couches': 'Количество слоев',
    'Plaques par couche': 'Пластин на слой',
    'Hauteur réacteur [m]': 'Высота реактора [м]',
    'Largeur réacteur [m]': 'Ширина реактора [м]',
    'Longueur réacteur [m]': 'Длина реактора [м]',
    'Volume total plaques [m³]': 'Общий объем пластин [м³]',
    'Nombre d\'éléments': 'Количество элементов',
    'Éléments par rangée': 'Элементов в ряду',
    'Nombre de rangées': 'Количество рядов',
    'Densité cellulaire [cpsi]': 'Плотность ячеек [cpsi]',
    'Volume total éléments [m³]': 'Общий объем элементов [м³]',
    'Volume lit total [m³]': 'Общий объем слоя [м³]',
    'Hauteur du lit [m]': 'Высота слоя [м]',
    'Diamètre réacteur [m]': 'Диаметр реактора [м]',
    'Section du lit [m²]': 'Сечение слоя [м²]',
    'Porosité du lit [%]': 'Пористость слоя [%]',
    'Masse catalyseur [kg]': 'Масса катализатора [кг]',
    'Densité apparente [kg/m³]': 'Кажущаяся плотность [кг/м³]',
    'Résultats': 'Результаты',
  },
  ar: {
    // === DENOX Main Page ===
    'DENOX Configuration': 'تكوين DENOX',
    'Back to Flow': 'العودة إلى التدفق',
    'Flue gases': 'غازات المداخن',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Design': 'التصميم',
    'Opex': 'التكاليف التشغيلية',

    // === DENOXFlueGasParameters - معاملات الانبعاثات ===
    'Calculation parameters': 'معاملات الحساب',
    'Clear memory': 'مسح الذاكرة',
    'Flue gas temperature before reheating [°C]': 'درجة حرارة غاز المداخن قبل إعادة التسخين [°C]',
    'Flue gas temperature after reheating [°C]': 'درجة حرارة غاز المداخن بعد إعادة التسخين [°C]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Volume of air ingress [Nm3/h]': 'حجم دخول الهواء [Nm3/h]',
    'Thermal losses [%]': 'الفقد الحراري [%]',
    'Cooling water temperature [°C]': 'درجة حرارة ماء التبريد [°C]',
    'Water injection': 'حقن الماء',
    'Gas type': 'نوع الغاز',
    'Water type': 'نوع الماء',
    'OUI': 'نعم',
    'NON': 'لا',

    // === النتائج المحسوبة ===
    'Calculated parameters': 'المعاملات المحسوبة',
    'Temperature inlet DENOX [°C]': 'درجة حرارة مدخل DENOX [°C]',
    'Delta enthalpies [kJ/h]': 'دلتا الإنثالبيا [كيلوجول/س]',
    'Sprayed/cooling water [kg/h]': 'الماء المرشوش/المبرد [كجم/س]',
    'Total humid flue gas output [m³/h]': 'إجمالي مخرجات غاز المداخن الرطب [م³/س]',
    'Temperature before reheating [°C]': 'درجة الحرارة قبل إعادة التسخين [°C]',
    'Temperature after reheating [°C]': 'درجة الحرارة بعد إعادة التسخين [°C]',
    'Adiabatic flame temperature [°C]': 'درجة حرارة اللهب الثابتة [°C]',
    'Air factor [-]': 'معامل الهواء [-]',
    'Combustion air volume [m³/h]': 'حجم هواء الاحتراق [م³/س]',
    'Combustion flue gas volume [m³/h]': 'حجم غاز مداخن الاحتراق [م³/س]',
    'Gas flow rate for reheating [Nm³/h]': 'معدل تدفق الغاز لإعادة التسخين [Nm³/h]',
    'Calculated mixing temperature [°C]': 'درجة حرارة الخلط المحسوبة [°C]',
    'Warning: Combustion calculation did not converge properly': '⚠️ تحذير: حساب الاحتراق لم يتقارب بشكل صحيح',
    'Warning: Reheating calculation did not converge after': '⚠️ تحذير: حساب إعادة التسخين لم يتقارب بعد',
    'iterations': 'تكرارات',
    'No reheating required: outlet temperature is already above target': 'ℹ️ لا حاجة لإعادة التسخين: درجة حرارة المخرج أعلى بالفعل من الهدف',
    'Flue gas composition': 'تركيب غاز المداخن',
    'Flue gas inlet at inlet temperature': 'مدخل غاز المداخن عند درجة حرارة الدخول',
    'Flue gas outlet at temperature before reheating': 'مخرج غاز المداخن قبل إعادة التسخين',
    'Flue gas outlet at temperature after reheating': 'مخرج غاز المداخن بعد إعادة التسخين',

    // === FlueGasPollutantEmission - المعاملات الرئيسية ===
    'Fly ashes content [g/Nm3]': 'محتوى الرماد الطائر [جم/Nm3]',
    'siccity bottom ash [%]': 'جفاف الرماد السفلي [%]',
    'O2 ref [%]': 'مرجع O2 [%]',
    'SCR enabled': 'تم تفعيل SCR',
    'NOx limit [mg/Nm3]': 'حد NOx [ملغ/Nm3]',
    'Stoichiometry': 'القياس المتكافئ',
    'SOx reactif': 'كاشف SOx',
    'HCl reactif': 'كاشف HCl',
    'HF reactif': 'كاشف HF',
    'efficacite_SOx': 'كفاءة SOx [%]',
    'HCl efficacité': 'كفاءة HCl [%]',
    'HF efficacité': 'كفاءة HF [%]',
    'SOx stoechiométrie': 'القياس المتكافئ SOx',
    'HCl stoechiométrie': 'القياس المتكافئ HCl',
    'HF stoechiométrie': 'القياس المتكافئ HF',
    'Reset to Default Values': 'إعادة تعيين إلى القيم الافتراضية',

    // === معاملات الملوثات ===
    'Waste Flow [kg/h]': 'تدفق النفايات [كجم/س]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق غاز المداخن الرطب [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق غاز المداخن الجاف [Nm3/h]',
    'O2 calculated [%]': 'O2 المحسوب [%]',
    'inert mass [kg/h]': 'الكتلة الخاملة [كجم/س]',
    'Input flue gas': 'غاز المداخن المدخل',
    'SCR (Selective Catalytic Reduction)': 'SCR (الاختزال الحفزي الانتقائي)',
    'SCR enabled:': 'تم تفعيل SCR:',
    'NOx limit [mg/Nm3]:': 'حد NOx [ملغ/Nm3]:',
    'Stoichiometry:': 'القياس المتكافئ:',
    'NH3 consumption [kg/h]:': 'استهلاك NH₃ [كجم/س]:',
    'NOx input [mg/Nm3]:': 'مدخل NOx [ملغ/Nm3]:',
    'NOx reduced [kg/h]:': 'تقليل NOx [كجم/س]:',
    'Pollutant Treatment Table': 'جدول معالجة الملوثات',
    'Polluant': 'الملوث',
    'Réactif': 'الكاشف',
    'Masse (kg/h)': 'الكتلة (كجم/س)',
    'Efficacité (%)': 'الكفاءة (%)',
    'Coeff. Stoech': 'المعامل القياسي',
    'Masse sortie': 'كتلة المخرج',
    'Masse résidu': 'كتلة البقايا',
    'Masse réactif': 'كتلة الكاشف',
    'Masse abattue': 'الكتلة المختزلة',
    'SOx': 'SOx',
    'HCl': 'HCl',
    'HF': 'HF',
    'None': 'لا شيء',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 جاف',
    'CaOH2wet': 'CaOH2 رطب',
    'CAP': 'CAP',
    'Ammonia': 'الأمونيا',
    'Output flue gas': 'غاز المداخن المخرج',
    'Bottom ashes calculated': 'الرماد السفلي المحسوب',
    'Bottom ash [kg/h]': 'الرماد السفلي [كجم/س]',
    'Bottom ash wet [kg/h]': 'الرماد السفلي الرطب [كجم/س]',
    'Fly ash [kg/h]': 'الرماد الطائر [كجم/س]',

    // === DENOXDesign ===
    'Technologie SCR': 'تقنية SCR',
    'Plaques catalytiques': 'الصفائح الحفزية',
    'Nid d\'abeilles': 'الخلايا السداسية',
    'Lit fixe': 'السرير الثابت',
    'Paramètres SCR': 'معاملات SCR',
    'Paramètres FAM': 'معاملات FAM',
    'Débit de gaz [Nm³/h]': 'معدل تدفق الغاز [Nm³/س]',
    'Concentration NOx entrée [mg/Nm³]': 'تركيز NOx المدخل [ملغ/Nm³]',
    'Taux de réduction NOx [%]': 'معدل تقليل NOx [%]',
    'Température des gaz [°C]': 'درجة حرارة الغاز [°C]',
    'Vitesse spatiale [h⁻¹]': 'السرعة المكانية [ح⁻¹]',
    'Vitesse superficielle [m/s]': 'السرعة السطحية [م/س]',
    'Rendement de capture [%]': 'كفاءة التجميع [%]',
    'Vitesse de filtration [m/h]': 'سرعة الترشيح [م/س]',
    'PDC [mmCE]': 'فقدان الضغط [mmCE]',
    'Volume catalyseur requis [m³]': 'حجم الحفاز المطلوب [م³]',
    'Section transversale [m²]': 'المقطع العرضي [م²]',
    'Concentration NOx sortie [mg/Nm³]': 'تركيز NOx المخرج [ملغ/Nm³]',
    'Consommation NH₃ [kg/h]': 'استهلاك NH₃ [كجم/س]',
    'Perte de charge [Pa]': 'فقدان الضغط [Pa]',
    'Surface des manches [m²]': 'مساحة الأكياس [م²]',
    'Pression de sortie [mmCE]': 'ضغط المخرج [mmCE]',
    'Paramètres Calculés Généraux': 'المعاملات المحسوبة العامة',
    'Dimensionnement Spécifique': 'التصميم المحدد',
    'Résumé des paramètres principaux': 'ملخص المعاملات الرئيسية',
    'Technologie': 'التقنية',
    'Volume catalyseur [m³]': 'حجم الحفاز [م³]',
    'Nombre de plaques': 'عدد الصفائح',
    'Nombre de couches': 'عدد الطبقات',
    'Plaques par couche': 'الصفائح لكل طبقة',
    'Hauteur réacteur [m]': 'ارتفاع المفاعل [م]',
    'Largeur réacteur [m]': 'عرض المفاعل [م]',
    'Longueur réacteur [m]': 'طول المفاعل [م]',
    'Volume total plaques [m³]': 'الحجم الإجمالي للصفائح [م³]',
    'Nombre d\'éléments': 'عدد العناصر',
    'Éléments par rangée': 'العناصر لكل صف',
    'Nombre de rangées': 'عدد الصفوف',
    'Densité cellulaire [cpsi]': 'كثافة الخلايا [cpsi]',
    'Volume total éléments [m³]': 'الحجم الإجمالي للعناصر [م³]',
    'Volume lit total [m³]': 'الحجم الإجمالي للسرير [م³]',
    'Hauteur du lit [m]': 'ارتفاع السرير [م]',
    'Diamètre réacteur [m]': 'قطر المفاعل [م]',
    'Section du lit [m²]': 'قسم السرير [م²]',
    'Porosité du lit [%]': 'مسامية السرير [%]',
    'Masse catalyseur [kg]': 'كتلة الحفاز [كجم]',
    'Densité apparente [kg/m³]': 'الكثافة الظاهرية [كجم/م³]',
    'Résultats': 'النتائج',
  }
};
