export const translations = {
  fr: {
    // FlueGasParameters (RK)
    calculationParameters: 'Paramètres de calcul',
    resetValues: 'Réinitialiser les valeurs',
    calculatedParameters: 'Paramètres calculés',
    airStoechio: 'Air stoechiométrique [kmol]',
    calculatedTemperature: 'Température calculée [°C]',
    waterContent: 'Teneur en eau [kg/Nm³]',
    hSystem: 'Enthalpie système [kJ/h]',
    airFactorCalculated: 'Facteur air calculé',
    combustionAirComposition: 'Composition de l\'air de combustion',
    atStoichiometry: 'À la stoechiométrie',
    atAdiabaticity: 'À l\'adiabaticité',
    combustionAirTotal: 'Air de combustion total',
    flueGasComposition: 'Composition des gaz de fumée',
    flueGasAtStoichiometry: 'Gaz de fumée à la stoechiométrie',
    outputFlueGasWithoutWater: 'Gaz de fumée en sortie sans eau',
    outputFlueGasWithWater: 'Gaz de fumée en sortie avec eau',
    export: 'Exporter',

    // STACKFlueGasParameters
    flueGasInletAtTemperature: 'Gaz de fumée en entrée à la température',
    clearMemory: 'Effacer la mémoire',

    // STACKFlueGasPollutantEmission
    flueGasCompositionInput: 'Composition des gaz de fumée',
    inputFlueGas: 'Gaz de fumée en entrée',
    O2RefPercent: 'O2 référence [%]',
    flyAshContent: 'Teneur en cendres volantes [g/Nm³]',

    // STACKdesign
    stackTheoreticHeight: 'Hauteur théorique de la cheminée indépendante',
    pollutantType: 'Type de polluant',
    gas: 'Gaz',
    dust: 'Poussière',
    zone: 'Zone',
    zoneDescription1: 'Zone peu polluée',
    zoneDescription2: 'Zone moyennement urbanisée ou industrialisée',
    zoneDescription3: 'Zone très urbanisée ou industrialisée',
    gasType: 'Type de gaz',
    calculatedResults: 'Résultats calculés',
    pollutantConcentration: 'Concentration des polluants [mg/Nm³]',
    minimumStackHeight: 'Hauteur minimale de cheminée [m]',
    multiStackConfiguration: 'Configuration multi-cheminées',
    multiStackCorrection: 'Résultat : correction multi-cheminées',
    correctedStackHeight: 'Hauteur cheminée corrigée [m]',
    heightDifferenceInitial: 'Différence avec hauteur initiale [m]',
    obstacleCalculation: 'Calcul avec obstacles',
    obstacleCorrection: 'Résultat : correction avec obstacles',
    stackHeightWithObstacles: 'Hauteur cheminée avec obstacles [m]',
    heightDifferenceMultiStack: 'Différence avec hauteur multi-stack [m]',
    regulatoryCompliance: 'Conformité réglementaire',
    emissionLimit: 'Valeur limite d\'émission',
    calculatedConcentration: 'Concentration calculée',
    status: 'Statut',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    note: 'Note',
    secondaryStackHeightNote: 'La hauteur minimale de la cheminée secondaire doit être calculée en fonction de la hauteur de la cheminée principale et de la distance entre les deux installations.',
    obstacleNoteText: 'La présence d\'obstacles à proximité de la cheminée peut affecter la dispersion des polluants et nécessiter un ajustement de hauteur.',
    
    // Input field labels
    wetFlueGasFlow: 'Débit des fumées humides [kg/h]',
    pollutantFlow: 'Débit de polluant [kg/h]',
    outletTemperature: 'Température de sortie [°C]',
    temperatureDifference: 'Delta Température sortie-air [°C]',
    distanceBetweenStacks: 'Distance entre cheminées [m]',
    secondaryStackHeight: 'Hauteur cheminée secondaire [m]',
    secondaryStackDiameter: 'Diamètre cheminée secondaire [m]',
    secondaryStackFlow: 'Débit des fumées cheminée secondaire [Nm³/h]',
    secondaryStackTemperature: 'Température cheminée secondaire [°C]',
    obstacleDistance: 'Distance de l\'obstacle [m]',
    obstacleHeight: 'Hauteur de l\'obstacle [m]',
    obstacleWidth: 'Largeur de l\'obstacle [m]',
    obstacleAngle: 'Angle de l\'obstacle [°]',

    // STACKMainPage
    stackConfiguration: 'Configuration de la CHEMINÉE',
    backToFlow: 'Retour au flux',
    flueGases: 'Gaz de fumée',
    design: 'Design',
    opex: 'Opex',
    rapport: 'Rapport',

    // STACK_Report keys
    reportTitle_STACK: 'Cheminée (Stack) — Rapport de synthèse',
    combustionGases: 'Gaz de combustion',
    stackInletTemp: 'Température entrée cheminée [°C]',
    o2Dry: 'O₂ (sec)',
    wetFlowTotal: 'Débit humide total [kg/h]',
    dryFlowNm3h: 'Débit sec [Nm³/h]',
    wetFlowNm3h: 'Débit humide [Nm³/h]',
    gasComposition: 'Composition gaz',
    pollutantEmissions: 'Émissions polluantes',
    pollutantsInput: 'Polluants en entrée [kg/h]',
    pollutantsOutput: 'Polluants en sortie [kg/h]',
    stackDesignTitle: 'Design — Dimensionnement cheminée',
    noDesignData: 'Données non disponibles — ouvrir l\'onglet Design.',
    gasFlows: 'Débits gaz',
    wetMassFlow: 'Débit massique humide [kg/h]',
    dryVolume: 'Volume sec [Nm³/h]',
    realVolAtTemp: 'Volume réel à T sortie [m³/h]',
    referencePolluant: 'Polluant de référence',
    typeLabel: 'Type',
    regulatoryZone: 'Zone réglementaire',
    calculatedHeightsM: 'Hauteurs calculées [m]',
    minTheoreticalHeight: 'Hauteur min. théorique',
    correctedMultiStack: 'Hauteur corrigée multi-stack',
    correctedObstacles: 'Hauteur corrigée obstacles',
    calculatedConcentrationMg: 'Concentration calculée [mg/Nm³]',
    emissionLimitVLE: 'Limite d\'émission VLE [mg/Nm³]',
    percentVLE: '% de la VLE',
    statusLabel: 'Statut',
    compliantStatus: 'Conforme',
    nonCompliantStatus: 'Non conforme',
    electricalConsumption: 'Consommations électriques',
    consumer: 'Consommateur',
    total: 'Total',
    opexHourlyCosts: 'OPEX — Coûts horaires',
    noOpexData: 'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.',
    electricityTag: 'Électricité',
    totalCost: 'Total coût',
    hourlyCost: 'Coût horaire',
    annualCost: 'Coût annuel',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ électricité',
    totalCO2label: 'Total CO₂',
    autoReport: 'Rapport généré automatiquement',

    // Design - Existing keys
    pressionAeraulique: 'Pression aéraulique [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    diametreInterne: 'Diamètre interne du four [m]',
    diametreExterne: 'Diamètre externe du four [m]',
    longueur: 'Longueur du four [m]',
    pente: 'Pente du four [°]',
    beta: 'Beta',
    nombreTours: 'Nombre de tours [rpm]',
    hauteurDechets: 'Hauteur des déchets [m]',
    masseVolumiqueDechets: 'Masse volumique des déchets [kg/m3]',
    debitDechetsSolides: 'Débit déchets solides [kg/h]',
    debitDechetsLiquides: 'Débit déchets liquides [kg/h]',
    typeCombustible: 'Type de combustible',
    typeAtomisation: 'Type d\'atomisation',
    typeEau: 'Type d\'eau',
    debitEau: 'Débit eau [m3/h]',
    temperatureEntree: 'Température entrée [°C]',
    temperatureSortie: 'Température sortie [°C]',
    epaisseurRefractaire: 'Épaisseur réfractaire [m]',
    temperaturePeau: 'Température de peau moyenne [°C]',
    dtRefroidissement: 'DT de refroidissement [°C]',
    debitHumideFumees: 'Débit humide des fumées [Nm3/h]',
    temperatureSCC: 'Température SCC [°C]',
    diametreSCC: 'Diamètre interne SCC [m]',
    tempsSejourDesire: 'Temps de séjour désiré [s]',
    typeCombustibleSCC: 'Type de combustible SCC',
    typeAtomisationSCC: 'Type d\'atomisation déchets SCC',
    nbTrappes: 'Actionner les vérins : nb de trappes',
    puissanceUnite: 'Puissance électrique par unité [kW/u]',
    masseImbrulees: 'Masse des imbrûlées [kg/h]',
    typeCamion: 'Type de camion',
    distance: 'Distance [km]',
    debitVentilateur: 'Débit du ventilateur de combustion [Nm3/h]',
    rendementVentilateur: 'Rendement du ventilateur de combustion [%]',
    h2oPourcent: 'H2O [%]',
    co2Pourcent: 'CO2 [%]',
    tfumProvisoire: 'Température fumées provisoire [°C]',
    emissiviteFume: 'Émissivité fumées',
    teauExtracteur: 'Température eau extracteur [°C]',
  },

  de: {
    // Fluent calculations
    calculationParameters: 'Berechnungsparameter',
    resetValues: 'Werte zurücksetzen',
    calculatedParameters: 'Berechnete Parameter',
    airStoechio: 'Stöchiometrische Luft [kmol]',
    calculatedTemperature: 'Berechnete Temperatur [°C]',
    waterContent: 'Wassergehalt [kg/Nm³]',
    hSystem: 'Systementhalpie [kJ/h]',
    airFactorCalculated: 'Berechneter Luftfaktor',
    combustionAirComposition: 'Zusammensetzung der Verbrennungsluft',
    atStoichiometry: 'Bei Stöchiometrie',
    atAdiabaticity: 'Bei Adiabatizität',
    combustionAirTotal: 'Gesamte Verbrennungsluft',
    flueGasComposition: 'Zusammensetzung der Rauchgase',
    flueGasAtStoichiometry: 'Rauchgase bei Stöchiometrie',
    outputFlueGasWithoutWater: 'Ausgangsrauchgas ohne Wasser',
    outputFlueGasWithWater: 'Ausgangsrauchgas mit Wasser',
    export: 'Exportieren',

    flueGasInletAtTemperature: 'Rauchgaseintritt bei Temperatur',
    clearMemory: 'Speicher löschen',

    flueGasCompositionInput: 'Rauchgaszusammensetzung',
    inputFlueGas: 'Eingangsrauchgas',
    O2RefPercent: 'O2 Referenz [%]',
    flyAshContent: 'Flugaschegehalt [g/Nm³]',

    stackTheoreticHeight: 'Theoretische Höhe des unabhängigen Schornsteins',
    pollutantType: 'Schadstofftyp',
    gas: 'Gas',
    dust: 'Staub',
    zone: 'Zone',
    zoneDescription1: 'Gering verschmutzte Zone',
    zoneDescription2: 'Mäßig urbanisiertes oder industrialisiertes Gebiet',
    zoneDescription3: 'Stark urbanisiertes oder industrialisiertes Gebiet',
    gasType: 'Gastyp',
    calculatedResults: 'Berechnete Ergebnisse',
    pollutantConcentration: 'Schadstoffkonzentration [mg/Nm³]',
    minimumStackHeight: 'Mindestschornsteinhöhe [m]',
    multiStackConfiguration: 'Multi-Stack-Konfiguration',
    multiStackCorrection: 'Ergebnis: Multi-Stack-Korrektur',
    correctedStackHeight: 'Korrigierte Schornsteinhohe [m]',
    heightDifferenceInitial: 'Unterschied zur Anfangshöhe [m]',
    obstacleCalculation: 'Berechnung mit Hindernissen',
    obstacleCorrection: 'Ergebnis: Korrektur mit Hindernissen',
    stackHeightWithObstacles: 'Schornsteinhohe mit Hindernissen [m]',
    heightDifferenceMultiStack: 'Unterschied zur Multi-Stack-Höhe [m]',
    regulatoryCompliance: 'Behördliche Einhaltung',
    emissionLimit: 'Emissionsgrenzwert',
    calculatedConcentration: 'Berechnete Konzentration',
    status: 'Status',
    compliant: 'Konform',
    nonCompliant: 'Nicht konform',
    note: 'Hinweis',
    secondaryStackHeightNote: 'Die Mindesthohe des Sekundärschornsteins sollte auf der Grundlage der Hohe des Primärschornsteins und des Abstands zwischen den beiden Anlagen berechnet werden.',
    obstacleNoteText: 'Das Vorhandensein von Hindernissen in der Nähe des Schornsteins kann die Schadstoffausbreitung beeinflussen und eine Höhennanpassung erfordern.',
    
    wetFlueGasFlow: 'Feuchter Rauchgasdurchsatz [kg/h]',
    pollutantFlow: 'Schadstoffdurchsatz [kg/h]',
    outletTemperature: 'Ausgangstemperatur [°C]',
    temperatureDifference: 'Temperaturunterschied Ausgang-Luft [°C]',
    distanceBetweenStacks: 'Abstand zwischen Schornsteinen [m]',
    secondaryStackHeight: 'Höhe des Sekundärschornsteins [m]',
    secondaryStackDiameter: 'Durchmesser des Sekundärschornsteins [m]',
    secondaryStackFlow: 'Rauchgasdurchsatz Sekundärschornstein [Nm³/h]',
    secondaryStackTemperature: 'Temperatur des Sekundärschornsteins [°C]',
    obstacleDistance: 'Hindernisabstand [m]',
    obstacleHeight: 'Hindernishshöhe [m]',
    obstacleWidth: 'Hindernisbreite [m]',
    obstacleAngle: 'Hinderniswinkel [°]',

    stackConfiguration: 'SCHORNSTEIN-Konfiguration',
    backToFlow: 'Zurück zu Fluss',
    flueGases: 'Rauchgase',
    design: 'Design',
    opex: 'Betriebskosten',
    rapport: 'Bericht',

    // STACK_Report keys
    reportTitle_STACK: 'Schornstein (Stack) — Synthesebericht',
    combustionGases: 'Rauchgase',
    stackInletTemp: 'Eingangstemperatur Schornstein [°C]',
    o2Dry: 'O₂ (trocken)',
    wetFlowTotal: 'Gesamter Feuchtrauchgasstrom [kg/h]',
    dryFlowNm3h: 'Trockenstrom [Nm³/h]',
    wetFlowNm3h: 'Feuchtestrom [Nm³/h]',
    gasComposition: 'Gaszusammensetzung',
    pollutantEmissions: 'Schadstoffemissionen',
    pollutantsInput: 'Eingangsschadstoffe [kg/h]',
    pollutantsOutput: 'Ausgangsschadstoffe [kg/h]',
    stackDesignTitle: 'Design — Schornsteinauslegung',
    noDesignData: 'Daten nicht verfügbar — Design-Tab öffnen.',
    gasFlows: 'Gasströme',
    wetMassFlow: 'Feuchter Massenstrom [kg/h]',
    dryVolume: 'Trockenvolumen [Nm³/h]',
    realVolAtTemp: 'Tatsächliches Volumen bei T Austritt [m³/h]',
    referencePolluant: 'Referenzschadstoff',
    typeLabel: 'Typ',
    regulatoryZone: 'Regulierungszone',
    calculatedHeightsM: 'Berechnete Höhen [m]',
    minTheoreticalHeight: 'Theoretische Mindesthöhe',
    correctedMultiStack: 'Korrigierte Multi-Stack-Höhe',
    correctedObstacles: 'Höhe mit Hinderniskorrektur',
    calculatedConcentrationMg: 'Berechnete Konzentration [mg/Nm³]',
    emissionLimitVLE: 'Emissionsgrenzwert VLE [mg/Nm³]',
    percentVLE: '% des VLE',
    statusLabel: 'Status',
    compliantStatus: 'Konform',
    nonCompliantStatus: 'Nicht konform',
    electricalConsumption: 'Stromverbrauch',
    consumer: 'Verbraucher',
    total: 'Gesamt',
    opexHourlyCosts: 'OPEX — Stündliche Kosten',
    noOpexData: 'OPEX-Kosten nicht verfügbar — Design- und Opex-Tabs öffnen.',
    electricityTag: 'Elektrizität',
    totalCost: 'Gesamtkosten',
    hourlyCost: 'Stundenkosten',
    annualCost: 'Jahreskosten',
    totalCO2: 'Gesamt-CO₂ [kg/h]',
    co2Electricity: 'CO₂ Elektrizität',
    totalCO2label: 'Gesamt-CO₂',
    autoReport: 'Bericht automatisch erstellt',
  },

  es: {
    calculationParameters: 'Parámetros de cálculo',
    resetValues: 'Restablecer valores',
    calculatedParameters: 'Parámetros calculados',
    airStoechio: 'Aire estequiométrico [kmol]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Contenido de agua [kg/Nm³]',
    hSystem: 'Entalpía del sistema [kJ/h]',
    airFactorCalculated: 'Factor de aire calculado',
    combustionAirComposition: 'Composición del aire de combustión',
    atStoichiometry: 'En estequiometría',
    atAdiabaticity: 'En adiabaticidad',
    combustionAirTotal: 'Aire de combustión total',
    flueGasComposition: 'Composición del gas de escape',
    flueGasAtStoichiometry: 'Gas de escape en estequiometría',
    outputFlueGasWithoutWater: 'Gas de escape sin agua',
    outputFlueGasWithWater: 'Gas de escape con agua',
    export: 'Exportar',

    flueGasInletAtTemperature: 'Entrada de gas de escape a temperatura',
    clearMemory: 'Limpiar memoria',

    flueGasCompositionInput: 'Composición del gas de escape',
    inputFlueGas: 'Gas de escape de entrada',
    O2RefPercent: 'Referencia O2 [%]',
    flyAshContent: 'Contenido de ceniza volante [g/Nm³]',

    stackTheoreticHeight: 'Altura teórica de la chimenea independiente',
    pollutantType: 'Tipo de contaminante',
    gas: 'Gas',
    dust: 'Polvo',
    zone: 'Zona',
    zoneDescription1: 'Zona poco contaminada',
    zoneDescription2: 'Zona moderadamente urbanizada o industrializada',
    zoneDescription3: 'Zona altamente urbanizada o industrializada',
    gasType: 'Tipo de gas',
    calculatedResults: 'Resultados calculados',
    pollutantConcentration: 'Concentración de contaminantes [mg/Nm³]',
    minimumStackHeight: 'Altura mínima de la chimenea [m]',
    multiStackConfiguration: 'Configuración multi-chimenea',
    multiStackCorrection: 'Resultado: corrección multi-chimenea',
    correctedStackHeight: 'Altura de chimenea corregida [m]',
    heightDifferenceInitial: 'Diferencia de altura inicial [m]',
    obstacleCalculation: 'Cálculo con obstáculos',
    obstacleCorrection: 'Resultado: corrección con obstáculos',
    stackHeightWithObstacles: 'Altura de chimenea con obstáculos [m]',
    heightDifferenceMultiStack: 'Diferencia de altura multi-chimenea [m]',
    regulatoryCompliance: 'Cumplimiento regulatorio',
    emissionLimit: 'Límite de emisión',
    calculatedConcentration: 'Concentración calculada',
    status: 'Estado',
    compliant: 'Conforme',
    nonCompliant: 'No conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'La altura mínima de la chimenea secundaria debe calcularse en función de la altura de la chimenea principal y la distancia entre las dos instalaciones.',
    obstacleNoteText: 'La presencia de obstáculos cerca de la chimenea puede afectar la dispersión de contaminantes y requerir un ajuste de altura.',
    
    wetFlueGasFlow: 'Caudal de gas de escape húmedo [kg/h]',
    pollutantFlow: 'Caudal de contaminante [kg/h]',
    outletTemperature: 'Temperatura de salida [°C]',
    temperatureDifference: 'Diferencia de temperatura salida-aire [°C]',
    distanceBetweenStacks: 'Distancia entre chimeneas [m]',
    secondaryStackHeight: 'Altura de chimenea secundaria [m]',
    secondaryStackDiameter: 'Diámetro de chimenea secundaria [m]',
    secondaryStackFlow: 'Caudal de gas chimenea secundaria [Nm³/h]',
    secondaryStackTemperature: 'Temperatura chimenea secundaria [°C]',
    obstacleDistance: 'Distancia del obstáculo [m]',
    obstacleHeight: 'Altura del obstáculo [m]',
    obstacleWidth: 'Ancho del obstáculo [m]',
    obstacleAngle: 'Ángulo del obstáculo [°]',

    stackConfiguration: 'Configuración de CHIMENEA',
    backToFlow: 'Volver al flujo',
    flueGases: 'Gases de escape',
    design: 'Diseño',
    opex: 'Opex',
    rapport: 'Informe',

    // STACK_Report keys
    reportTitle_STACK: 'Chimenea (Stack) — Informe de síntesis',
    combustionGases: 'Gases de combustión',
    stackInletTemp: 'Temperatura entrada chimenea [°C]',
    o2Dry: 'O₂ (seco)',
    wetFlowTotal: 'Caudal húmedo total [kg/h]',
    dryFlowNm3h: 'Caudal seco [Nm³/h]',
    wetFlowNm3h: 'Caudal húmedo [Nm³/h]',
    gasComposition: 'Composición del gas',
    pollutantEmissions: 'Emisiones de contaminantes',
    pollutantsInput: 'Contaminantes en entrada [kg/h]',
    pollutantsOutput: 'Contaminantes en salida [kg/h]',
    stackDesignTitle: 'Design — Dimensionamiento chimenea',
    noDesignData: 'Datos no disponibles — abrir la pestaña Design.',
    gasFlows: 'Caudales de gas',
    wetMassFlow: 'Caudal másico húmedo [kg/h]',
    dryVolume: 'Volumen seco [Nm³/h]',
    realVolAtTemp: 'Volumen real a T salida [m³/h]',
    referencePolluant: 'Contaminante de referencia',
    typeLabel: 'Tipo',
    regulatoryZone: 'Zona regulatoria',
    calculatedHeightsM: 'Alturas calculadas [m]',
    minTheoreticalHeight: 'Altura mín. teórica',
    correctedMultiStack: 'Altura corregida multi-chimenea',
    correctedObstacles: 'Altura corregida obstáculos',
    calculatedConcentrationMg: 'Concentración calculada [mg/Nm³]',
    emissionLimitVLE: 'Límite de emisión VLE [mg/Nm³]',
    percentVLE: '% del VLE',
    statusLabel: 'Estado',
    compliantStatus: 'Conforme',
    nonCompliantStatus: 'No conforme',
    electricalConsumption: 'Consumos eléctricos',
    consumer: 'Consumidor',
    total: 'Total',
    opexHourlyCosts: 'OPEX — Costos horarios',
    noOpexData: 'Costos OPEX no disponibles — abrir las pestañas Design y Opex.',
    electricityTag: 'Electricidad',
    totalCost: 'Costo total',
    hourlyCost: 'Costo horario',
    annualCost: 'Costo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricidad',
    totalCO2label: 'Total CO₂',
    autoReport: 'Informe generado automáticamente',
  },

  it: {
    calculationParameters: 'Parametri di calcolo',
    resetValues: 'Ripristina valori',
    calculatedParameters: 'Parametri calcolati',
    airStoechio: 'Aria stechiometrica [kmol]',
    calculatedTemperature: 'Temperatura calcolata [°C]',
    waterContent: 'Contenuto di acqua [kg/Nm³]',
    hSystem: 'Entalpia del sistema [kJ/h]',
    airFactorCalculated: 'Fattore aria calcolato',
    combustionAirComposition: 'Composizione dell\'aria di combustione',
    atStoichiometry: 'A stechiometria',
    atAdiabaticity: 'Ad adiabaticità',
    combustionAirTotal: 'Aria di combustione totale',
    flueGasComposition: 'Composizione dei gas di scarico',
    flueGasAtStoichiometry: 'Gas di scarico a stechiometria',
    outputFlueGasWithoutWater: 'Gas di scarico senza acqua',
    outputFlueGasWithWater: 'Gas di scarico con acqua',
    export: 'Esporta',

    flueGasInletAtTemperature: 'Ingresso gas di scarico alla temperatura',
    clearMemory: 'Cancella memoria',

    flueGasCompositionInput: 'Composizione gas di scarico',
    inputFlueGas: 'Gas di scarico in ingresso',
    O2RefPercent: 'Riferimento O2 [%]',
    flyAshContent: 'Contenuto di cenere volante [g/Nm³]',

    stackTheoreticHeight: 'Altezza teorica del camino indipendente',
    pollutantType: 'Tipo di inquinante',
    gas: 'Gas',
    dust: 'Polvere',
    zone: 'Zona',
    zoneDescription1: 'Zona poco inquinata',
    zoneDescription2: 'Area moderatamente urbanizzata o industrializzata',
    zoneDescription3: 'Area altamente urbanizzata o industrializzata',
    gasType: 'Tipo di gas',
    calculatedResults: 'Risultati calcolati',
    pollutantConcentration: 'Concentrazione di inquinanti [mg/Nm³]',
    minimumStackHeight: 'Altezza minima del camino [m]',
    multiStackConfiguration: 'Configurazione multi-camino',
    multiStackCorrection: 'Risultato: correzione multi-camino',
    correctedStackHeight: 'Altezza camino corretta [m]',
    heightDifferenceInitial: 'Differenza dall\'altezza iniziale [m]',
    obstacleCalculation: 'Calcolo con ostacoli',
    obstacleCorrection: 'Risultato: correzione con ostacoli',
    stackHeightWithObstacles: 'Altezza camino con ostacoli [m]',
    heightDifferenceMultiStack: 'Differenza dall\'altezza multi-camino [m]',
    regulatoryCompliance: 'Conformità normativa',
    emissionLimit: 'Limite di emissione',
    calculatedConcentration: 'Concentrazione calcolata',
    status: 'Stato',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'L\'altezza minima del camino secondario deve essere calcolata in base all\'altezza del camino primario e alla distanza tra i due impianti.',
    obstacleNoteText: 'La presenza di ostacoli vicino al camino può influenzare la dispersione degli inquinanti e potrebbe richiedere un adeguamento dell\'altezza.',
    
    wetFlueGasFlow: 'Portata gas di scarico umido [kg/h]',
    pollutantFlow: 'Portata di inquinante [kg/h]',
    outletTemperature: 'Temperatura di uscita [°C]',
    temperatureDifference: 'Differenza di temperatura uscita-aria [°C]',
    distanceBetweenStacks: 'Distanza tra camini [m]',
    secondaryStackHeight: 'Altezza camino secondario [m]',
    secondaryStackDiameter: 'Diametro camino secondario [m]',
    secondaryStackFlow: 'Portata gas camino secondario [Nm³/h]',
    secondaryStackTemperature: 'Temperatura camino secondario [°C]',
    obstacleDistance: 'Distanza ostacolo [m]',
    obstacleHeight: 'Altezza ostacolo [m]',
    obstacleWidth: 'Larghezza ostacolo [m]',
    obstacleAngle: 'Angolo ostacolo [°]',

    stackConfiguration: 'Configurazione CAMINO',
    backToFlow: 'Torna al flusso',
    flueGases: 'Gas di scarico',
    design: 'Design',
    opex: 'Opex',
    rapport: 'Rapporto',

    // STACK_Report keys
    reportTitle_STACK: 'Camino (Stack) — Rapporto di sintesi',
    combustionGases: 'Gas di combustione',
    stackInletTemp: 'Temperatura ingresso camino [°C]',
    o2Dry: 'O₂ (secco)',
    wetFlowTotal: 'Portata umida totale [kg/h]',
    dryFlowNm3h: 'Portata secca [Nm³/h]',
    wetFlowNm3h: 'Portata umida [Nm³/h]',
    gasComposition: 'Composizione del gas',
    pollutantEmissions: 'Emissioni di inquinanti',
    pollutantsInput: 'Inquinanti in ingresso [kg/h]',
    pollutantsOutput: 'Inquinanti in uscita [kg/h]',
    stackDesignTitle: 'Design — Dimensionamento camino',
    noDesignData: 'Dati non disponibili — aprire la scheda Design.',
    gasFlows: 'Portate di gas',
    wetMassFlow: 'Portata massica umida [kg/h]',
    dryVolume: 'Volume secco [Nm³/h]',
    realVolAtTemp: 'Volume reale a T uscita [m³/h]',
    referencePolluant: 'Inquinante di riferimento',
    typeLabel: 'Tipo',
    regulatoryZone: 'Zona normativa',
    calculatedHeightsM: 'Altezze calcolate [m]',
    minTheoreticalHeight: 'Altezza min. teorica',
    correctedMultiStack: 'Altezza corretta multi-camino',
    correctedObstacles: 'Altezza corretta ostacoli',
    calculatedConcentrationMg: 'Concentrazione calcolata [mg/Nm³]',
    emissionLimitVLE: 'Limite di emissione VLE [mg/Nm³]',
    percentVLE: '% del VLE',
    statusLabel: 'Stato',
    compliantStatus: 'Conforme',
    nonCompliantStatus: 'Non conforme',
    electricalConsumption: 'Consumi elettrici',
    consumer: 'Consumatore',
    total: 'Totale',
    opexHourlyCosts: 'OPEX — Costi orari',
    noOpexData: 'Costi OPEX non disponibili — aprire le schede Design e Opex.',
    electricityTag: 'Elettricità',
    totalCost: 'Costo totale',
    hourlyCost: 'Costo orario',
    annualCost: 'Costo annuale',
    totalCO2: 'Totale CO₂ [kg/h]',
    co2Electricity: 'CO₂ elettricità',
    totalCO2label: 'Totale CO₂',
    autoReport: 'Rapporto generato automaticamente',
  },

  pt: {
    calculationParameters: 'Parâmetros de cálculo',
    resetValues: 'Redefinir valores',
    calculatedParameters: 'Parâmetros calculados',
    airStoechio: 'Ar estequiométrico [kmol]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Conteúdo de água [kg/Nm³]',
    hSystem: 'Entalpia do sistema [kJ/h]',
    airFactorCalculated: 'Fator de ar calculado',
    combustionAirComposition: 'Composição do ar de combustão',
    atStoichiometry: 'Na estequiometria',
    atAdiabaticity: 'Na adiabaticidade',
    combustionAirTotal: 'Ar de combustão total',
    flueGasComposition: 'Composição dos gases de escape',
    flueGasAtStoichiometry: 'Gases de escape na estequiometria',
    outputFlueGasWithoutWater: 'Gases de escape sem água',
    outputFlueGasWithWater: 'Gases de escape com água',
    export: 'Exportar',

    flueGasInletAtTemperature: 'Entrada de gás de escape à temperatura',
    clearMemory: 'Limpar memória',

    flueGasCompositionInput: 'Composição de gases de escape',
    inputFlueGas: 'Gás de escape de entrada',
    O2RefPercent: 'Referência O2 [%]',
    flyAshContent: 'Conteúdo de cinza volante [g/Nm³]',

    stackTheoreticHeight: 'Altura teórica da chaminé independente',
    pollutantType: 'Tipo de poluente',
    gas: 'Gás',
    dust: 'Poeira',
    zone: 'Zona',
    zoneDescription1: 'Zona pouco poluída',
    zoneDescription2: 'Área moderadamente urbanizada ou industrializada',
    zoneDescription3: 'Área altamente urbanizada ou industrializada',
    gasType: 'Tipo de gás',
    calculatedResults: 'Resultados calculados',
    pollutantConcentration: 'Concentração de poluentes [mg/Nm³]',
    minimumStackHeight: 'Altura mínima da chaminé [m]',
    multiStackConfiguration: 'Configuração multi-chaminé',
    multiStackCorrection: 'Resultado: correção multi-chaminé',
    correctedStackHeight: 'Altura de chaminé corrigida [m]',
    heightDifferenceInitial: 'Diferença da altura inicial [m]',
    obstacleCalculation: 'Cálculo com obstáculos',
    obstacleCorrection: 'Resultado: correção com obstáculos',
    stackHeightWithObstacles: 'Altura de chaminé com obstáculos [m]',
    heightDifferenceMultiStack: 'Diferença da altura multi-chaminé [m]',
    regulatoryCompliance: 'Conformidade regulatória',
    emissionLimit: 'Limite de emissão',
    calculatedConcentration: 'Concentração calculada',
    status: 'Status',
    compliant: 'Conforme',
    nonCompliant: 'Não conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'A altura mínima da chaminé secundária deve ser calculada com base na altura da chaminé primária e na distância entre as duas instalações.',
    obstacleNoteText: 'A presença de obstáculos perto da chaminé pode afetar a dispersão de poluentes e pode exigir um ajuste de altura.',
    
    wetFlueGasFlow: 'Vazão de gás de escape úmido [kg/h]',
    pollutantFlow: 'Vazão de poluente [kg/h]',
    outletTemperature: 'Temperatura de saída [°C]',
    temperatureDifference: 'Diferença de temperatura saída-ar [°C]',
    distanceBetweenStacks: 'Distância entre chaminés [m]',
    secondaryStackHeight: 'Altura de chaminé secundária [m]',
    secondaryStackDiameter: 'Diâmetro de chaminé secundária [m]',
    secondaryStackFlow: 'Vazão de gás chaminé secundária [Nm³/h]',
    secondaryStackTemperature: 'Temperatura chaminé secundária [°C]',
    obstacleDistance: 'Distância do obstáculo [m]',
    obstacleHeight: 'Altura do obstáculo [m]',
    obstacleWidth: 'Largura do obstáculo [m]',
    obstacleAngle: 'Ângulo do obstáculo [°]',

    stackConfiguration: 'Configuração de CHAMINÉ',
    backToFlow: 'Voltar ao fluxo',
    flueGases: 'Gases de escape',
    design: 'Design',
    opex: 'Opex',
    rapport: 'Relatório',

    // STACK_Report keys
    reportTitle_STACK: 'Chaminé (Stack) — Relatório de síntese',
    combustionGases: 'Gases de combustão',
    stackInletTemp: 'Temperatura entrada chaminé [°C]',
    o2Dry: 'O₂ (seco)',
    wetFlowTotal: 'Vazão úmida total [kg/h]',
    dryFlowNm3h: 'Vazão seca [Nm³/h]',
    wetFlowNm3h: 'Vazão úmida [Nm³/h]',
    gasComposition: 'Composição do gás',
    pollutantEmissions: 'Emissões de poluentes',
    pollutantsInput: 'Poluentes na entrada [kg/h]',
    pollutantsOutput: 'Poluentes na saída [kg/h]',
    stackDesignTitle: 'Design — Dimensionamento chaminé',
    noDesignData: 'Dados não disponíveis — abrir a aba Design.',
    gasFlows: 'Vazões de gás',
    wetMassFlow: 'Vazão mássica úmida [kg/h]',
    dryVolume: 'Volume seco [Nm³/h]',
    realVolAtTemp: 'Volume real à T saída [m³/h]',
    referencePolluant: 'Poluente de referência',
    typeLabel: 'Tipo',
    regulatoryZone: 'Zona regulatória',
    calculatedHeightsM: 'Alturas calculadas [m]',
    minTheoreticalHeight: 'Altura mín. teórica',
    correctedMultiStack: 'Altura corrigida multi-chaminé',
    correctedObstacles: 'Altura corrigida obstáculos',
    calculatedConcentrationMg: 'Concentração calculada [mg/Nm³]',
    emissionLimitVLE: 'Limite de emissão VLE [mg/Nm³]',
    percentVLE: '% do VLE',
    statusLabel: 'Status',
    compliantStatus: 'Conforme',
    nonCompliantStatus: 'Não conforme',
    electricalConsumption: 'Consumos elétricos',
    consumer: 'Consumidor',
    total: 'Total',
    opexHourlyCosts: 'OPEX — Custos horários',
    noOpexData: 'Custos OPEX não disponíveis — abrir as abas Design e Opex.',
    electricityTag: 'Eletricidade',
    totalCost: 'Custo total',
    hourlyCost: 'Custo horário',
    annualCost: 'Custo anual',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ eletricidade',
    totalCO2label: 'Total CO₂',
    autoReport: 'Relatório gerado automaticamente',
  },

  ru: {
    calculationParameters: 'Параметры расчета',
    resetValues: 'Сбросить значения',
    calculatedParameters: 'Рассчитанные параметры',
    airStoechio: 'Стехиометрический воздух [кмоль]',
    calculatedTemperature: 'Рассчитанная температура [°C]',
    waterContent: 'Содержание воды [кг/Nm³]',
    hSystem: 'Энтальпия системы [кДж/ч]',
    airFactorCalculated: 'Рассчитанный коэффициент воздуха',
    combustionAirComposition: 'Состав воздуха сгорания',
    atStoichiometry: 'При стехиометрии',
    atAdiabaticity: 'При адиабатичности',
    combustionAirTotal: 'Общий воздух сгорания',
    flueGasComposition: 'Состав дымовых газов',
    flueGasAtStoichiometry: 'Дымовые газы при стехиометрии',
    outputFlueGasWithoutWater: 'Выходящие дымовые газы без воды',
    outputFlueGasWithWater: 'Выходящие дымовые газы с водой',
    export: 'Экспорт',

    flueGasInletAtTemperature: 'Вход дымовых газов при температуре',
    clearMemory: 'Очистить память',

    flueGasCompositionInput: 'Состав дымовых газов',
    inputFlueGas: 'Входящие дымовые газы',
    O2RefPercent: 'Эталон O2 [%]',
    flyAshContent: 'Содержание летучей золы [г/Nm³]',

    stackTheoreticHeight: 'Теоретическая высота независимой трубы',
    pollutantType: 'Тип загрязнителя',
    gas: 'Газ',
    dust: 'Пыль',
    zone: 'Зона',
    zoneDescription1: 'Слабо загрязненная зона',
    zoneDescription2: 'Умеренно урбанизированная или промышленная зона',
    zoneDescription3: 'Сильно урбанизированная или промышленная зона',
    gasType: 'Тип газа',
    calculatedResults: 'Рассчитанные результаты',
    pollutantConcentration: 'Концентрация загрязнителей [мг/Nm³]',
    minimumStackHeight: 'Минимальная высота трубы [м]',
    multiStackConfiguration: 'Конфигурация мульти-трубы',
    multiStackCorrection: 'Результат: коррекция мульти-трубы',
    correctedStackHeight: 'Скорректированная высота трубы [м]',
    heightDifferenceInitial: 'Разница с начальной высотой [м]',
    obstacleCalculation: 'Расчет с препятствиями',
    obstacleCorrection: 'Результат: коррекция с препятствиями',
    stackHeightWithObstacles: 'Высота трубы с препятствиями [м]',
    heightDifferenceMultiStack: 'Разница с высотой мульти-трубы [м]',
    regulatoryCompliance: 'Соответствие нормативам',
    emissionLimit: 'Предельное значение выбросов',
    calculatedConcentration: 'Рассчитанная концентрация',
    status: 'Статус',
    compliant: 'Соответствует',
    nonCompliant: 'Не соответствует',
    note: 'Примечание',
    secondaryStackHeightNote: 'Минимальная высота вторичной трубы должна рассчитываться на основе высоты первичной трубы и расстояния между двумя установками.',
    obstacleNoteText: 'Наличие препятствий рядом с трубой может повлиять на рассеивание загрязнителей и потребовать корректировки высоты.',
    
    wetFlueGasFlow: 'Расход влажных дымовых газов [кг/ч]',
    pollutantFlow: 'Расход загрязнителя [кг/ч]',
    outletTemperature: 'Температура на выходе [°C]',
    temperatureDifference: 'Разница температур выход-воздух [°C]',
    distanceBetweenStacks: 'Расстояние между трубами [м]',
    secondaryStackHeight: 'Высота вторичной трубы [м]',
    secondaryStackDiameter: 'Диаметр вторичной трубы [м]',
    secondaryStackFlow: 'Расход дымовых газов вторичной трубы [Nm³/ч]',
    secondaryStackTemperature: 'Температура вторичной трубы [°C]',
    obstacleDistance: 'Расстояние препятствия [м]',
    obstacleHeight: 'Высота препятствия [м]',
    obstacleWidth: 'Ширина препятствия [м]',
    obstacleAngle: 'Угол препятствия [°]',

    stackConfiguration: 'Конфигурация ТРУБЫ',
    backToFlow: 'Вернуться к потоку',
    flueGases: 'Дымовые газы',
    design: 'Проектирование',
    opex: 'Opex',
    rapport: 'Отчет',

    // STACK_Report keys
    reportTitle_STACK: 'Дымовая труба (Stack) — Сводный отчет',
    combustionGases: 'Дымовые газы',
    stackInletTemp: 'Температура входа в трубу [°C]',
    o2Dry: 'O₂ (сухой)',
    wetFlowTotal: 'Суммарный влажный расход [кг/ч]',
    dryFlowNm3h: 'Сухой расход [Нм³/ч]',
    wetFlowNm3h: 'Влажный расход [Нм³/ч]',
    gasComposition: 'Состав газа',
    pollutantEmissions: 'Выбросы загрязнителей',
    pollutantsInput: 'Входящие загрязнители [кг/ч]',
    pollutantsOutput: 'Исходящие загрязнители [кг/ч]',
    stackDesignTitle: 'Дизайн — Размерный расчет трубы',
    noDesignData: 'Данные недоступны — откройте вкладку Design.',
    gasFlows: 'Расходы газа',
    wetMassFlow: 'Влажный массовый расход [кг/ч]',
    dryVolume: 'Сухой объем [Нм³/ч]',
    realVolAtTemp: 'Реальный объем при T выхода [м³/ч]',
    referencePolluant: 'Эталонный загрязнитель',
    typeLabel: 'Тип',
    regulatoryZone: 'Регулятивная зона',
    calculatedHeightsM: 'Рассчитанные высоты [м]',
    minTheoreticalHeight: 'Мин. теоретическая высота',
    correctedMultiStack: 'Скорректированная мульти-труба',
    correctedObstacles: 'Скорректированная с препятствиями',
    calculatedConcentrationMg: 'Рассчитанная концентрация [мг/Нм³]',
    emissionLimitVLE: 'Предельное значение VLE [мг/Нм³]',
    percentVLE: '% от VLE',
    statusLabel: 'Статус',
    compliantStatus: 'Соответствует',
    nonCompliantStatus: 'Не соответствует',
    electricalConsumption: 'Потребление электроэнергии',
    consumer: 'Потребитель',
    total: 'Итого',
    opexHourlyCosts: 'ОПEX — Почасовые затраты',
    noOpexData: 'Затраты OPEX недоступны — откройте вкладки Design и Opex.',
    electricityTag: 'Электричество',
    totalCost: 'Общие затраты',
    hourlyCost: 'Почасовые затраты',
    annualCost: 'Годовые затраты',
    totalCO2: 'Итого CO₂ [кг/ч]',
    co2Electricity: 'CO₂ электричество',
    totalCO2label: 'Итого CO₂',
    autoReport: 'Отчет сгенерирован автоматически',
  },

  zh: {
    calculationParameters: '计算参数',
    resetValues: '重置值',
    calculatedParameters: '计算的参数',
    airStoechio: '化学计量空气 [kmol]',
    calculatedTemperature: '计算温度 [°C]',
    waterContent: '含水量 [kg/Nm³]',
    hSystem: '系统焓 [kJ/h]',
    airFactorCalculated: '计算的空气因子',
    combustionAirComposition: '燃烧空气成分',
    atStoichiometry: '在化学计量中',
    atAdiabaticity: '在绝热条件下',
    combustionAirTotal: '总燃烧空气',
    flueGasComposition: '烟气成分',
    flueGasAtStoichiometry: '化学计量烟气',
    outputFlueGasWithoutWater: '无水输出烟气',
    outputFlueGasWithWater: '含水输出烟气',
    export: '导出',

    flueGasInletAtTemperature: '烟气进口温度',
    clearMemory: '清除内存',

    flueGasCompositionInput: '烟气成分',
    inputFlueGas: '输入烟气',
    O2RefPercent: '氧气参考值 [%]',
    flyAshContent: '飞灰含量 [g/Nm³]',

    stackTheoreticHeight: '独立烟囱的理论高度',
    pollutantType: '污染物类型',
    gas: '气体',
    dust: '尘埃',
    zone: '区域',
    zoneDescription1: '污染较少的区域',
    zoneDescription2: '中等城市化或工业化地区',
    zoneDescription3: '高度城市化或工业化地区',
    gasType: '气体类型',
    calculatedResults: '计算结果',
    pollutantConcentration: '污染物浓度 [mg/Nm³]',
    minimumStackHeight: '最小烟囱高度 [m]',
    multiStackConfiguration: '多烟囱配置',
    multiStackCorrection: '结果：多烟囱修正',
    correctedStackHeight: '修正烟囱高度 [m]',
    heightDifferenceInitial: '与初始高度的差值 [m]',
    obstacleCalculation: '有障碍物的计算',
    obstacleCorrection: '结果：有障碍物的修正',
    stackHeightWithObstacles: '有障碍物的烟囱高度 [m]',
    heightDifferenceMultiStack: '与多烟囱高度的差值 [m]',
    regulatoryCompliance: '法规符合性',
    emissionLimit: '排放限制值',
    calculatedConcentration: '计算浓度',
    status: '状态',
    compliant: '符合',
    nonCompliant: '不符合',
    note: '注意',
    secondaryStackHeightNote: '应根据主烟囱的高度和两个装置之间的距离来计算二级烟囱的最小高度。',
    obstacleNoteText: '烟囱附近的障碍物可能影响污染物的散布，可能需要调整高度。',
    
    wetFlueGasFlow: '湿烟气流量 [kg/h]',
    pollutantFlow: '污染物流量 [kg/h]',
    outletTemperature: '出口温度 [°C]',
    temperatureDifference: '出口-空气温度差 [°C]',
    distanceBetweenStacks: '烟囱之间的距离 [m]',
    secondaryStackHeight: '次级烟囱高度 [m]',
    secondaryStackDiameter: '次级烟囱直径 [m]',
    secondaryStackFlow: '次级烟囱烟气流量 [Nm³/h]',
    secondaryStackTemperature: '次级烟囱温度 [°C]',
    obstacleDistance: '障碍物距离 [m]',
    obstacleHeight: '障碍物高度 [m]',
    obstacleWidth: '障碍物宽度 [m]',
    obstacleAngle: '障碍物角度 [°]',

    stackConfiguration: '烟囱配置',
    backToFlow: '返回流程',
    flueGases: '烟气',
    design: '设计',
    opex: '运营成本',
    rapport: '报告',

    // STACK_Report keys
    reportTitle_STACK: '烟囱 (Stack) — 综合报告',
    combustionGases: '燃烧气体',
    stackInletTemp: '烟囱入口温度 [°C]',
    o2Dry: 'O₂（干燥）',
    wetFlowTotal: '总湿流量 [kg/h]',
    dryFlowNm3h: '干流量 [Nm³/h]',
    wetFlowNm3h: '湿流量 [Nm³/h]',
    gasComposition: '气体成分',
    pollutantEmissions: '污染物排放',
    pollutantsInput: '入口污染物 [kg/h]',
    pollutantsOutput: '出口污染物 [kg/h]',
    stackDesignTitle: 'Design — 烟囱尺寸设计',
    noDesignData: '数据不可用 — 请打开Design选项卡。',
    gasFlows: '气体流量',
    wetMassFlow: '湿质量流量 [kg/h]',
    dryVolume: '干体积 [Nm³/h]',
    realVolAtTemp: '实际出口体积 [m³/h]',
    referencePolluant: '参考污染物',
    typeLabel: '类型',
    regulatoryZone: '监管区域',
    calculatedHeightsM: '计算高度 [m]',
    minTheoreticalHeight: '最小理论高度',
    correctedMultiStack: '多烟囱修正高度',
    correctedObstacles: '障碍物修正高度',
    calculatedConcentrationMg: '计算浓度 [mg/Nm³]',
    emissionLimitVLE: '排放限值 VLE [mg/Nm³]',
    percentVLE: 'VLE的百分比',
    statusLabel: '状态',
    compliantStatus: '符合',
    nonCompliantStatus: '不符合',
    electricalConsumption: '电力消耗',
    consumer: '消费者',
    total: '总计',
    opexHourlyCosts: 'OPEX — 每小时成本',
    noOpexData: 'OPEX成本不可用 — 请打开Design和Opex选项卡。',
    electricityTag: '电力',
    totalCost: '总成本',
    hourlyCost: '小时成本',
    annualCost: '年度成本',
    totalCO2: '总CO₂ [kg/h]',
    co2Electricity: 'CO₂ 电力',
    totalCO2label: '总CO₂',
    autoReport: '自动生成报告',
  },

  ja: {
    calculationParameters: '計算パラメータ',
    resetValues: '値をリセット',
    calculatedParameters: '計算されたパラメータ',
    airStoechio: '化学量論空気 [kmol]',
    calculatedTemperature: '計算温度 [°C]',
    waterContent: '含水量 [kg/Nm³]',
    hSystem: 'システムエンタルピー [kJ/h]',
    airFactorCalculated: '計算された空気係数',
    combustionAirComposition: '燃焼空気の組成',
    atStoichiometry: '化学量論で',
    atAdiabaticity: '断熱条件で',
    combustionAirTotal: '総燃焼空気',
    flueGasComposition: '排気ガスの組成',
    flueGasAtStoichiometry: '化学量論排気ガス',
    outputFlueGasWithoutWater: '無水排気ガス',
    outputFlueGasWithWater: '含水排気ガス',
    export: 'エクスポート',

    flueGasInletAtTemperature: '排気ガス入口温度',
    clearMemory: 'メモリをクリア',

    flueGasCompositionInput: '排気ガス組成',
    inputFlueGas: '入力排気ガス',
    O2RefPercent: '酸素参照値 [%]',
    flyAshContent: 'フライアッシュ含有量 [g/Nm³]',

    stackTheoreticHeight: '独立煙突の理論的高さ',
    pollutantType: '汚染物質の種類',
    gas: 'ガス',
    dust: 'ダスト',
    zone: 'ゾーン',
    zoneDescription1: '汚染の少ないゾーン',
    zoneDescription2: '中程度の都市化または産業化地域',
    zoneDescription3: '高度に都市化または産業化した地域',
    gasType: 'ガスの種類',
    calculatedResults: '計算結果',
    pollutantConcentration: '汚染物質濃度 [mg/Nm³]',
    minimumStackHeight: '最小煙突高さ [m]',
    multiStackConfiguration: 'マルチスタック構成',
    multiStackCorrection: '結果：マルチスタック補正',
    correctedStackHeight: '補正された煙突の高さ [m]',
    heightDifferenceInitial: '初期高さからの差 [m]',
    obstacleCalculation: '障害物のある計算',
    obstacleCorrection: '結果：障害物のある補正',
    stackHeightWithObstacles: '障害物のある煙突の高さ [m]',
    heightDifferenceMultiStack: 'マルチスタック高さからの差 [m]',
    regulatoryCompliance: '規制適合性',
    emissionLimit: '排出限界値',
    calculatedConcentration: '計算濃度',
    status: 'ステータス',
    compliant: '適合',
    nonCompliant: '不適合',
    note: '注意',
    secondaryStackHeightNote: 'セカンダリ煙突の最小高さは、プライマリ煙突の高さと2つの設備間の距離に基づいて計算する必要があります。',
    obstacleNoteText: '煙突の近くの障害物は汚染物質の拡散に影響を与え、高さの調整が必要な場合があります。',
    
    wetFlueGasFlow: '湿排気ガス流量 [kg/h]',
    pollutantFlow: '汚染物質流量 [kg/h]',
    outletTemperature: '出口温度 [°C]',
    temperatureDifference: '出口-空気温度差 [°C]',
    distanceBetweenStacks: '煙突間距離 [m]',
    secondaryStackHeight: 'セカンダリ煙突高さ [m]',
    secondaryStackDiameter: 'セカンダリ煙突直径 [m]',
    secondaryStackFlow: 'セカンダリ煙突排気ガス流量 [Nm³/h]',
    secondaryStackTemperature: 'セカンダリ煙突温度 [°C]',
    obstacleDistance: '障害物距離 [m]',
    obstacleHeight: '障害物の高さ [m]',
    obstacleWidth: '障害物幅 [m]',
    obstacleAngle: '障害物角度 [°]',

    stackConfiguration: '煙突構成',
    backToFlow: 'フローに戻る',
    flueGases: '排気ガス',
    design: 'デザイン',
    opex: 'Opex',
    rapport: 'レポート',

    // STACK_Report keys
    reportTitle_STACK: '煙突 (Stack) — 総合報告書',
    combustionGases: '燃焼ガス',
    stackInletTemp: '煙突入口温度 [°C]',
    o2Dry: 'O₂（乾燥）',
    wetFlowTotal: '総湿流量 [kg/h]',
    dryFlowNm3h: '乾燥流量 [Nm³/h]',
    wetFlowNm3h: '湿流量 [Nm³/h]',
    gasComposition: 'ガス組成',
    pollutantEmissions: '汚染物質排出',
    pollutantsInput: '入口汚染物質 [kg/h]',
    pollutantsOutput: '出口汚染物質 [kg/h]',
    stackDesignTitle: 'Design — 煙突サイジング',
    noDesignData: 'データ不可 — Designタブを開いてください。',
    gasFlows: 'ガス流量',
    wetMassFlow: '湿質量流量 [kg/h]',
    dryVolume: '乾燥体積 [Nm³/h]',
    realVolAtTemp: '出口実体積 [m³/h]',
    referencePolluant: '基準汚染物質',
    typeLabel: 'タイプ',
    regulatoryZone: '規制区域',
    calculatedHeightsM: '計算された高さ [m]',
    minTheoreticalHeight: '最小理論高さ',
    correctedMultiStack: 'マルチスタック修正高さ',
    correctedObstacles: '障害物修正高さ',
    calculatedConcentrationMg: '計算濃度 [mg/Nm³]',
    emissionLimitVLE: '排出限界値 VLE [mg/Nm³]',
    percentVLE: 'VLEの割合',
    statusLabel: 'ステータス',
    compliantStatus: '適合',
    nonCompliantStatus: '不適合',
    electricalConsumption: '電力消費',
    consumer: '消費者',
    total: '合計',
    opexHourlyCosts: 'OPEX — 時間コスト',
    noOpexData: 'OPEXコスト不可 — DesignとOpexタブを開いてください。',
    electricityTag: '電力',
    totalCost: '総コスト',
    hourlyCost: '時間コスト',
    annualCost: '年間コスト',
    totalCO2: '総CO₂ [kg/h]',
    co2Electricity: 'CO₂ 電力',
    totalCO2label: '総CO₂',
    autoReport: '自動生成されたレポート',
  },

  ar: {
    calculationParameters: 'معاملات الحساب',
    resetValues: 'إعادة تعيين القيم',
    calculatedParameters: 'المعاملات المحسوبة',
    airStoechio: 'الهواء المتكافئ [kmol]',
    calculatedTemperature: 'درجة الحرارة المحسوبة [°C]',
    waterContent: 'محتوى الماء [kg/Nm³]',
    hSystem: 'إنتالبيا النظام [kJ/h]',
    airFactorCalculated: 'معامل الهواء المحسوب',
    combustionAirComposition: 'تركيب الهواء الاحتراق',
    atStoichiometry: 'في التكافؤ',
    atAdiabaticity: 'في الحالة الثابتة حرارياً',
    combustionAirTotal: 'إجمالي الهواء الاحتراق',
    flueGasComposition: 'تركيب غاز العادم',
    flueGasAtStoichiometry: 'غاز العادم في التكافؤ',
    outputFlueGasWithoutWater: 'غاز العادم بدون ماء',
    outputFlueGasWithWater: 'غاز العادم مع الماء',
    export: 'تصدير',

    flueGasInletAtTemperature: 'مدخل غاز العادم عند درجة الحرارة',
    clearMemory: 'مسح الذاكرة',

    flueGasCompositionInput: 'تركيب غاز العادم',
    inputFlueGas: 'غاز العادم المدخل',
    O2RefPercent: 'مرجع الأكسجين [%]',
    flyAshContent: 'محتوى الرماد المتطاير [g/Nm³]',

    stackTheoreticHeight: 'الارتفاع النظري للمداخن المستقلة',
    pollutantType: 'نوع الملوث',
    gas: 'غاز',
    dust: 'غبار',
    zone: 'منطقة',
    zoneDescription1: 'منطقة ملوثة قليلاً',
    zoneDescription2: 'منطقة حضرية أو صناعية معتدلة',
    zoneDescription3: 'منطقة حضرية أو صناعية عالية',
    gasType: 'نوع الغاز',
    calculatedResults: 'النتائج المحسوبة',
    pollutantConcentration: 'تركيز الملوثات [mg/Nm³]',
    minimumStackHeight: 'الحد الأدنى لارتفاع المدخن [m]',
    multiStackConfiguration: 'تكوين المداخن المتعددة',
    multiStackCorrection: 'النتيجة: تصحيح المداخن المتعددة',
    correctedStackHeight: 'ارتفاع المدخن المصحح [m]',
    heightDifferenceInitial: 'الفرق عن الارتفاع الأولي [m]',
    obstacleCalculation: 'حساب مع العقبات',
    obstacleCorrection: 'النتيجة: تصحيح مع العقبات',
    stackHeightWithObstacles: 'ارتفاع المدخن مع العقبات [m]',
    heightDifferenceMultiStack: 'الفرق عن ارتفاع المداخن المتعددة [m]',
    regulatoryCompliance: 'الامتثال التنظيمي',
    emissionLimit: 'حد الانبعاثات',
    calculatedConcentration: 'التركيز المحسوب',
    status: 'الحالة',
    compliant: 'متوافق',
    nonCompliant: 'غير متوافق',
    note: 'ملاحظة',
    secondaryStackHeightNote: 'يجب حساب الحد الأدنى لارتفاع المدخن الثانوي على أساس ارتفاع المدخن الأساسي والمسافة بين المنشأتين.',
    obstacleNoteText: 'قد تؤثر العقبات القريبة من المدخن على تشتت الملوثات وقد تتطلب تعديلاً في الارتفاع.',
    
    wetFlueGasFlow: 'معدل تدفق غاز العادم الرطب [kg/h]',
    pollutantFlow: 'معدل تدفق الملوث [kg/h]',
    outletTemperature: 'درجة حرارة المخرج [°C]',
    temperatureDifference: 'فرق درجة الحرارة مخرج-الهواء [°C]',
    distanceBetweenStacks: 'المسافة بين المداخن [m]',
    secondaryStackHeight: 'ارتفاع المدخن الثانوي [m]',
    secondaryStackDiameter: 'قطر المدخن الثانوي [m]',
    secondaryStackFlow: 'معدل تدفق غاز العادم للمدخن الثانوي [Nm³/h]',
    secondaryStackTemperature: 'درجة حرارة المدخن الثانوي [°C]',
    obstacleDistance: 'مسافة العقبة [m]',
    obstacleHeight: 'ارتفاع العقبة [m]',
    obstacleWidth: 'عرض العقبة [m]',
    obstacleAngle: 'زاوية العقبة [°]',

    stackConfiguration: 'تكوين المدخن',
    backToFlow: 'العودة إلى التدفق',
    flueGases: 'غاز العادم',
    design: 'التصميم',
    opex: 'Opex',
    rapport: 'تقرير',

    // STACK_Report keys
    reportTitle_STACK: 'المدخن (Stack) — تقرير تركيبي',
    combustionGases: 'غازات الاحتراق',
    stackInletTemp: 'درجة حرارة مدخل المدخن [°C]',
    o2Dry: 'O₂ (جاف)',
    wetFlowTotal: 'إجمالي التدفق الرطب [kg/h]',
    dryFlowNm3h: 'التدفق الجاف [Nm³/h]',
    wetFlowNm3h: 'التدفق الرطب [Nm³/h]',
    gasComposition: 'تركيبة الغاز',
    pollutantEmissions: 'انبعاثات الملوثات',
    pollutantsInput: 'الملوثات في المدخل [kg/h]',
    pollutantsOutput: 'الملوثات في المخرج [kg/h]',
    stackDesignTitle: 'Design — تصميم المدخن',
    noDesignData: 'البيانات غير متاحة — افتح علامة التبويب Design.',
    gasFlows: 'تدفقات الغاز',
    wetMassFlow: 'التدفق الكتلي الرطب [kg/h]',
    dryVolume: 'الحجم الجاف [Nm³/h]',
    realVolAtTemp: 'الحجم الحقيقي عند T الخروج [m³/h]',
    referencePolluant: 'الملوث المرجعي',
    typeLabel: 'النوع',
    regulatoryZone: 'المنطقة التنظيمية',
    calculatedHeightsM: 'الارتفاعات المحسوبة [m]',
    minTheoreticalHeight: 'الحد الأدنى للارتفاع النظري',
    correctedMultiStack: 'الارتفاع المصحح متعدد المداخن',
    correctedObstacles: 'الارتفاع المصحح مع العقبات',
    calculatedConcentrationMg: 'التركيز المحسوب [mg/Nm³]',
    emissionLimitVLE: 'حد الانبعاثات VLE [mg/Nm³]',
    percentVLE: '% من VLE',
    statusLabel: 'الحالة',
    compliantStatus: 'متوافق',
    nonCompliantStatus: 'غير متوافق',
    electricalConsumption: 'الاستهلاك الكهربائي',
    consumer: 'المستهلك',
    total: 'المجموع',
    opexHourlyCosts: 'OPEX — التكاليف بالساعة',
    noOpexData: 'تكاليف OPEX غير متاحة — افتح علامات التبويب Design و Opex.',
    electricityTag: 'الكهرباء',
    totalCost: 'التكلفة الإجمالية',
    hourlyCost: 'التكلفة بالساعة',
    annualCost: 'التكلفة السنوية',
    totalCO2: 'إجمالي CO₂ [kg/h]',
    co2Electricity: 'CO₂ الكهرباء',
    totalCO2label: 'إجمالي CO₂',
    autoReport: 'تقرير مُنشأ تلقائيًا',
  },

  en: {
    calculationParameters: 'Calculation parameters',
    resetValues: 'Reset values',
    calculatedParameters: 'Calculated parameters',
    airStoechio: 'Stoichiometric air [kmol]',
    calculatedTemperature: 'Calculated temperature [°C]',
    waterContent: 'Water content [kg/Nm³]',
    hSystem: 'System enthalpy [kJ/h]',
    airFactorCalculated: 'Calculated air factor',
    combustionAirComposition: 'Combustion air composition',
    atStoichiometry: 'At stoichiometry',
    atAdiabaticity: 'At adiabaticity',
    combustionAirTotal: 'Total combustion air',
    flueGasComposition: 'Flue gas composition',
    flueGasAtStoichiometry: 'Flue gas at stoichiometry',
    outputFlueGasWithoutWater: 'Output flue gas without water',
    outputFlueGasWithWater: 'Output flue gas with water',
    export: 'Export',

    flueGasInletAtTemperature: 'Flue gas inlet at temperature',
    clearMemory: 'Clear memory',

    flueGasCompositionInput: 'Flue gas composition',
    inputFlueGas: 'Input flue gas',
    O2RefPercent: 'O2 reference [%]',
    flyAshContent: 'Fly ash content [g/Nm³]',

    stackTheoreticHeight: 'Theoretical height of independent stack',
    pollutantType: 'Pollutant type',
    gas: 'Gas',
    dust: 'Dust',
    zone: 'Zone',
    zoneDescription1: 'Low pollution zone',
    zoneDescription2: 'Moderately urbanized or industrialized area',
    zoneDescription3: 'Highly urbanized or industrialized area',
    gasType: 'Gas type',
    calculatedResults: 'Calculated results',
    pollutantConcentration: 'Pollutant concentration [mg/Nm³]',
    minimumStackHeight: 'Minimum stack height [m]',
    multiStackConfiguration: 'Multi-stack configuration',
    multiStackCorrection: 'Result: multi-stack correction',
    correctedStackHeight: 'Corrected stack height [m]',
    heightDifferenceInitial: 'Difference from initial height [m]',
    obstacleCalculation: 'Calculation with obstacles',
    obstacleCorrection: 'Result: correction with obstacles',
    stackHeightWithObstacles: 'Stack height with obstacles [m]',
    heightDifferenceMultiStack: 'Difference from multi-stack height [m]',
    regulatoryCompliance: 'Regulatory compliance',
    emissionLimit: 'Emission limit value',
    calculatedConcentration: 'Calculated concentration',
    status: 'Status',
    compliant: 'Compliant',
    nonCompliant: 'Non-compliant',
    note: 'Note',
    secondaryStackHeightNote: 'The minimum height of the secondary stack should be calculated based on the height of the primary stack and the distance between the two installations.',
    obstacleNoteText: 'The presence of obstacles near the stack can affect pollutant dispersion and may require height adjustment.',
    
    wetFlueGasFlow: 'Wet flue gas flow rate [kg/h]',
    pollutantFlow: 'Pollutant flow rate [kg/h]',
    outletTemperature: 'Outlet temperature [°C]',
    temperatureDifference: 'Temperature difference outlet-air [°C]',
    distanceBetweenStacks: 'Distance between stacks [m]',
    secondaryStackHeight: 'Secondary stack height [m]',
    secondaryStackDiameter: 'Secondary stack diameter [m]',
    secondaryStackFlow: 'Secondary stack flue gas flow rate [Nm³/h]',
    secondaryStackTemperature: 'Secondary stack temperature [°C]',
    obstacleDistance: 'Distance from obstacle [m]',
    obstacleHeight: 'Obstacle height [m]',
    obstacleWidth: 'Obstacle width [m]',
    obstacleAngle: 'Obstacle angle [°]',

    stackConfiguration: 'STACK Configuration',
    backToFlow: 'Back to Flow',
    flueGases: 'Flue gases',
    design: 'Design',
    opex: 'Opex',
    rapport: 'Report',

    // STACK_Report keys
    reportTitle_STACK: 'Stack (Chimney) — Synthesis Report',
    combustionGases: 'Combustion gases',
    stackInletTemp: 'Stack inlet temperature [°C]',
    o2Dry: 'O₂ (dry)',
    wetFlowTotal: 'Total wet flow [kg/h]',
    dryFlowNm3h: 'Dry flow [Nm³/h]',
    wetFlowNm3h: 'Wet flow [Nm³/h]',
    gasComposition: 'Gas composition',
    pollutantEmissions: 'Pollutant emissions',
    pollutantsInput: 'Inlet pollutants [kg/h]',
    pollutantsOutput: 'Outlet pollutants [kg/h]',
    stackDesignTitle: 'Design — Stack sizing',
    noDesignData: 'Data not available — open the Design tab.',
    gasFlows: 'Gas flows',
    wetMassFlow: 'Wet mass flow [kg/h]',
    dryVolume: 'Dry volume [Nm³/h]',
    realVolAtTemp: 'Real volume at T outlet [m³/h]',
    referencePolluant: 'Reference pollutant',
    typeLabel: 'Type',
    regulatoryZone: 'Regulatory zone',
    calculatedHeightsM: 'Calculated heights [m]',
    minTheoreticalHeight: 'Min. theoretical height',
    correctedMultiStack: 'Corrected multi-stack height',
    correctedObstacles: 'Height corrected for obstacles',
    calculatedConcentrationMg: 'Calculated concentration [mg/Nm³]',
    emissionLimitVLE: 'Emission limit VLE [mg/Nm³]',
    percentVLE: '% of VLE',
    statusLabel: 'Status',
    compliantStatus: 'Compliant',
    nonCompliantStatus: 'Non-compliant',
    electricalConsumption: 'Electrical consumption',
    consumer: 'Consumer',
    total: 'Total',
    opexHourlyCosts: 'OPEX — Hourly costs',
    noOpexData: 'OPEX costs not available — open the Design and Opex tabs.',
    electricityTag: 'Electricity',
    totalCost: 'Total cost',
    hourlyCost: 'Hourly cost',
    annualCost: 'Annual cost',
    totalCO2: 'Total CO₂ [kg/h]',
    co2Electricity: 'CO₂ electricity',
    totalCO2label: 'Total CO₂',
    autoReport: 'Report generated automatically',
  },
};