export const translations = {
  fr: {
    // Navigation et structure
    'AIR INJECTION Configuration': 'Configuration CYCLONE',
    'Flue gases': 'Gaz de combustion',
    'Pollutant Emissions': 'Émissions de polluants',
    'Design': 'Dimensionnement',
    'Opex': 'OPEX',
    'Rapport': 'Rapport',
    'Back to Flow': 'Retour au flux',
    'Clear memory': 'Effacer la mémoire',
    'Clear parameters': 'Effacer les paramètres',
    'Reset to Default Values': 'Réinitialiser aux valeurs par défaut',

    // Paramètres de gaz de combustion
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Flue gas composition': 'Composition des gaz de combustion',
    'Flue gas inlet at inlet temperature': 'Entrée gaz de combustion à la température d\'entrée',
    'Air ingress at ambient temperature': 'Entrée d\'air ambiant',
    'Flue gas outlet at outlet temperature': 'Sortie gaz de combustion à la température de sortie',
    'Input flue gas': 'Gaz de combustion en entrée',
    'Output flue gas': 'Gaz de combustion en sortie',
    'Residues calculated': 'Résidus calculés',

    // Paramètres spécifiques CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Température sortie gaz combustion [°C]',
    'Ambient air temperature [°C]': 'Température air ambiant [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume d\'entrée d\'air [Nm3/h]',
    'Thermal losses [%]': 'Pertes thermiques [%]',
    'Cooling water temperature [°C]': 'Température eau refroidissement [°C]',
    'Fly residus content outlet [g/Nm3]': 'Teneur en résidus volants sortie [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité cendres de fond [%]',
    'O2 ref [%]': 'O2 référence [%]',

    // Résultats calculés
    'Temperature inlet CYCLONE [°C]': 'Température entrée CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Eau pulvérisée/refroidissement [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gaz sortie [Nm3/h]',

    // Paramètres CYCLONE Design
    'Cyclone Model Selection': 'Sélection du modèle de cyclone',
    'Cyclone Design Parameters': 'Paramètres de conception du cyclone',
    'Select Model': 'Sélectionner le modèle',
    'Cyclone parameters': 'Paramètres du cyclone',
    'Input Parameters': 'Paramètres d\'entrée',
    'Calculated Dimensions': 'Dimensions calculées',
    'Pressure Drop Calculation': 'Calcul de la perte de charge',
    'Flue Gas Flow [Nm3/h]': 'Débit gaz de combustion [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Température gaz de combustion [°C]',
    'Velocity Target [m/s]': 'Vitesse cible [m/s]',
    'Pressure Drop Model': 'Modèle de perte de charge',
    'Head Losses': 'Pertes de charge',
    'Summary of Main Parameters': 'Résumé des paramètres principaux',

    // Dimensionnement et calculs
    'Surface des manches [m²]': 'Surface des manches [m²]',
    'Rendement de capture [%]': 'Rendement de capture [%]',
    'Vitesse de filtration [m/h]': 'Vitesse de filtration [m/h]',
    'Pression air comprimé [Bar]': 'Pression air comprimé [Bar]',
    'Consommation air comprimé [Nm3/h]': 'Consommation air comprimé [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consommation électrique air comprimé [kW]',
    'Residus du CYCLONE [kg/h]': 'Résidus CYCLONE [kg/h]',
    'Type de camion': 'Type de camion',
    'Distance [km]': 'Distance [km]',
    'CO2 transport total [kg]': 'CO2 transport total [kg]',
    'Coût transport total [€]': 'Coût transport total [€]',

    // Pertes de charge
    'Pertes de charge aéraulique': 'Pertes de charge aéraulique',
    'Pression de sortie [mmCE]': 'Pression de sortie [mmCE]',
    'Pression aéraulique [mmCE]': 'Pression aéraulique [mmCE]',
    'PDC [mmCE]': 'Perte de charge [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'Masse volumique [kg/m3]',
    'Pin [mmCE]': 'Pression entrée [mmCE]',
    'PDC [Pa]': 'Perte de charge [Pa]',
    'Pout [mmCE]': 'Pression sortie [mmCE]',

    // Flux et masses
    'Waste Flow [kg/h]': 'Débit de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit gaz humide [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit gaz sec [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'Fly ash [kg/h]': 'Cendres volantes [kg/h]',
    'Fly ash inlet [kg/h]': 'Cendres volantes entrée [kg/h]',
    'Cyclone residus [kg/h]': 'Résidus cyclone [kg/h]',
    'Dry residus [kg/h]': 'Résidus secs [kg/h]',
    'Wet residus [kg/h]': 'Résidus humides [kg/h]',
    'inert mass [kg/h]': 'Masse inerte [kg/h]',

    // Polluants
    'Pollutant': 'Polluant',
    'Reagent': 'Réactif',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Efficacité (%)',
    'Stoich. Coeff.': 'Coeff. stoechiométrique',
    'Output Mass': 'Masse sortie',
    'Residue Mass': 'Masse résidu',
    'Reagent Mass': 'Masse réactif',
    'Abated Mass': 'Masse réduite',
    'Pollutant Treatment Table': 'Tableau de traitement des polluants',

    // Réactifs
    'SOx reactif': 'Réactif SOx',
    'HCl reactif': 'Réactif HCl',
    'HF reactif': 'Réactif HF',
    'efficacite_SOx': 'Efficacité SOx',
    'HCl efficacité': 'Efficacité HCl',
    'HF efficacité': 'Efficacité HF',
    'SOx stoechiométrie': 'Stoechiométrie SOx',
    'HCl stoechiométrie': 'Stoechiométrie HCl',
    'HF stoechiométrie': 'Stoechiométrie HF',

    // Conception FAM
    'Dimensionnement du FAM': 'Dimensionnement du FAM',
    'Consommation électrique de la vis sans fin': 'Consommation électrique de la vis sans fin',
    'conso elec vis de transport [kW]': 'Consommation électrique vis transport [kW]',
    'Consommation d\'air comprimé': 'Consommation d\'air comprimé',
    'Nombre de cycles [Nb]': 'Nombre de cycles [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Air comprimé par cycle [Nm3/cycle]',
    'Évacuation des residus AIRINJECTION': 'Évacuation des résidus CYCLONE',

    // Résumé
    'Résultats': 'Résultats',
    'Résumé des paramètres principaux': 'Résumé des paramètres principaux',
    'Paramètres calculés détaillés': 'Paramètres calculés détaillés',
    'Model': 'Modèle',
    'Cyclone Diameter [m]': 'Diamètre cyclone [m]',
    'Velocity Section [m/s]': 'Vitesse section [m/s]',

    // Autres
    'None': 'Aucun',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 sec',
    'CaOH2wet': 'CaOH2 humide',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 tonnes',
    '20t': '20 tonnes',
    '25t': '25 tonnes',
    'Conveyor': 'Convoyeur',

    // === Rapport ===
    'AIR INJECTION — Rapport de synthèse': 'AIR INJECTION — Rapport de synthèse',
    '1. Gaz de combustion': '1. Gaz de combustion',
    'Température de sortie': 'Température de sortie',
    'O₂ mesuré (sec)': 'O₂ mesuré (sec)',
    'Débit humide total [kg/h]': 'Débit humide total [kg/h]',
    'Débit sec [Nm³/h]': 'Débit sec [Nm³/h]',
    'Débit humide [Nm³/h]': 'Débit humide [Nm³/h]',
    'Composition gaz de sortie': 'Composition gaz de sortie',
    '2. Émissions polluantes': '2. Émissions polluantes',
    'Gaz en entrée [kg/h]': 'Gaz en entrée [kg/h]',
    'Gaz en sortie [kg/h]': 'Gaz en sortie [kg/h]',
    'Cendres lourdes sèches [kg/h]': 'Cendres lourdes sèches [kg/h]',
    'Cendres lourdes humides [kg/h]': 'Cendres lourdes humides [kg/h]',
    'Cendres volantes [kg/h]': 'Cendres volantes [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Consommations électriques',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Données non disponibles (ouvrir l\'onglet Design)',
    'Consommation d\'eau': 'Consommation d\'eau',
    'Eau potable [m³/h]': 'Eau potable [m³/h]',
    'Eau de refroidissement [m³/h]': 'Eau de refroidissement [m³/h]',
    'Eau déminéralisée [m³/h]': 'Eau déminéralisée [m³/h]',
    'Énergie auxiliaire': 'Énergie auxiliaire',
    'Gaz haute valeur [MW]': 'Gaz haute valeur [MW]',
    'Fuel [MW]': 'Fuel [MW]',
    '4. OPEX — Coûts horaires': '4. OPEX — Coûts horaires',
    'Rapport généré automatiquement': 'Rapport généré automatiquement',
    'Consommateur': 'Consommateur',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.': 'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.',
    'Électricité': 'Électricité',
    'Eau': 'Eau',
    'Réactifs': 'Réactifs',
    'Énergie': 'Énergie',
    'Total coût': 'Total coût',
    'Coût horaire': 'Coût horaire',
    'Coût annuel': 'Coût annuel',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ électricité',
    'CO₂ énergie': 'CO₂ énergie',
    'CO₂ transport': 'CO₂ transport',
    'Total CO₂': 'Total CO₂',
  },
  en: {
    // Navigation et structure
    'AIR INJECTION Configuration': 'AIR INJECTION Configuration',
    'Flue gases': 'Flue gases',
    'Pollutant Emissions': 'Pollutant Emissions',
    'Design': 'Design',
    'Opex': 'Opex',
    'Back to Flow': 'Back to Flow',
    'Clear memory': 'Clear memory',
    'Clear parameters': 'Clear parameters',
    'Reset to Default Values': 'Reset to Default Values',

    // Paramètres de gaz de combustion
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Flue gas composition': 'Flue gas composition',
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Air ingress at ambient temperature': 'Air ingress at ambient temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',
    'Residues calculated': 'Residues calculated',

    // Paramètres spécifiques CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Flue gas temperature outlet [°C]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume of air ingress [Nm3/h]',
    'Thermal losses [%]': 'Thermal losses [%]',
    'Cooling water temperature [°C]': 'Cooling water temperature [°C]',
    'Fly residus content outlet [g/Nm3]': 'Fly residus content outlet [g/Nm3]',
    'siccity bottom ash [%]': 'siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',

    // Résultats calculés
    'Temperature inlet CYCLONE [°C]': 'Temperature inlet CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprayed/cooling water [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Outlet flue gas volume [Nm3/h]',

    // Paramètres CYCLONE Design
    'Cyclone Model Selection': 'Cyclone Model Selection',
    'Cyclone Design Parameters': 'Cyclone Design Parameters',
    'Select Model': 'Select Model',
    'Cyclone parameters': 'Cyclone parameters',
    'Input Parameters': 'Input Parameters',
    'Calculated Dimensions': 'Calculated Dimensions',
    'Pressure Drop Calculation': 'Pressure Drop Calculation',
    'Flue Gas Flow [Nm3/h]': 'Flue Gas Flow [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Temperature Flue Gas [°C]',
    'Velocity Target [m/s]': 'Velocity Target [m/s]',
    'Pressure Drop Model': 'Pressure Drop Model',
    'Head Losses': 'Head Losses',
    'Summary of Main Parameters': 'Summary of Main Parameters',

    // Dimensionnement et calculs
    'Surface des manches [m²]': 'Bag surface [m²]',
    'Rendement de capture [%]': 'Collection efficiency [%]',
    'Vitesse de filtration [m/h]': 'Filtration velocity [m/h]',
    'Pression air comprimé [Bar]': 'Compressed air pressure [Bar]',
    'Consommation air comprimé [Nm3/h]': 'Compressed air consumption [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Compressed air electric consumption [kW]',
    'Residus du CYCLONE [kg/h]': 'CYCLONE residues [kg/h]',
    'Type de camion': 'Truck type',
    'Distance [km]': 'Distance [km]',
    'CO2 transport total [kg]': 'Total transport CO2 [kg]',
    'Coût transport total [€]': 'Total transport cost [€]',

    // Pertes de charge
    'Pertes de charge aéraulique': 'Aeraulic pressure drop',
    'Pression de sortie [mmCE]': 'Outlet pressure [mmCE]',
    'Pression aéraulique [mmCE]': 'Aeraulic pressure [mmCE]',
    'PDC [mmCE]': 'Pressure drop [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'RHO [kg/m3]',
    'Pin [mmCE]': 'Inlet pressure [mmCE]',
    'PDC [Pa]': 'Pressure drop [Pa]',
    'Pout [mmCE]': 'Outlet pressure [mmCE]',

    // Flux et masses
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'Fly ash [kg/h]': 'Fly ash [kg/h]',
    'Fly ash inlet [kg/h]': 'Fly ash inlet [kg/h]',
    'Cyclone residus [kg/h]': 'Cyclone residues [kg/h]',
    'Dry residus [kg/h]': 'Dry residues [kg/h]',
    'Wet residus [kg/h]': 'Wet residues [kg/h]',
    'inert mass [kg/h]': 'inert mass [kg/h]',

    // Polluants
    'Pollutant': 'Pollutant',
    'Reagent': 'Reagent',
    'Mass (kg/h)': 'Mass (kg/h)',
    'Efficiency (%)': 'Efficiency (%)',
    'Stoich. Coeff.': 'Stoich. Coeff.',
    'Output Mass': 'Output Mass',
    'Residue Mass': 'Residue Mass',
    'Reagent Mass': 'Reagent Mass',
    'Abated Mass': 'Abated Mass',
    'Pollutant Treatment Table': 'Pollutant Treatment Table',

    // Réactifs
    'SOx reactif': 'SOx reagent',
    'HCl reactif': 'HCl reagent',
    'HF reactif': 'HF reagent',
    'efficacite_SOx': 'SOx efficiency',
    'HCl efficacité': 'HCl efficiency',
    'HF efficacité': 'HF efficiency',
    'SOx stoechiométrie': 'SOx stoichiometry',
    'HCl stoechiométrie': 'HCl stoichiometry',
    'HF stoechiométrie': 'HF stoichiometry',

    // Conception FAM
    'Dimensionnement du FAM': 'FAM dimensioning',
    'Consommation électrique de la vis sans fin': 'Screw conveyor electric consumption',
    'conso elec vis de transport [kW]': 'Screw conveyor electric consumption [kW]',
    'Consommation d\'air comprimé': 'Compressed air consumption',
    'Nombre de cycles [Nb]': 'Number of cycles [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Compressed air per cycle [Nm3/cycle]',
    'Évacuation des residus AIRINJECTION': 'CYCLONE residues evacuation',

    // Résumé
    'Résultats': 'Results',
    'Résumé des paramètres principaux': 'Summary of main parameters',
    'Paramètres calculés détaillés': 'Detailed calculated parameters',
    'Model': 'Model',
    'Cyclone Diameter [m]': 'Cyclone Diameter [m]',
    'Velocity Section [m/s]': 'Velocity Section [m/s]',

    // Autres
    'None': 'None',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 dry',
    'CaOH2wet': 'CaOH2 wet',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 tonnes',
    '20t': '20 tonnes',
    '25t': '25 tonnes',
    'Conveyor': 'Conveyor',

    // === Report ===
    'AIR INJECTION — Rapport de synthèse': 'Cyclone — Synthesis Report',
    '1. Gaz de combustion': '1. Flue gas',
    'Température de sortie': 'Outlet temperature',
    'O₂ mesuré (sec)': 'Measured O₂ (dry)',
    'Débit humide total [kg/h]': 'Total wet flow [kg/h]',
    'Débit sec [Nm³/h]': 'Dry flow [Nm³/h]',
    'Débit humide [Nm³/h]': 'Wet flow [Nm³/h]',
    'Composition gaz de sortie': 'Outlet gas composition',
    '2. Émissions polluantes': '2. Pollutant emissions',
    'Gaz en entrée [kg/h]': 'Inlet gas [kg/h]',
    'Gaz en sortie [kg/h]': 'Outlet gas [kg/h]',
    'Cendres lourdes sèches [kg/h]': 'Dry bottom ash [kg/h]',
    'Cendres lourdes humides [kg/h]': 'Wet bottom ash [kg/h]',
    'Cendres volantes [kg/h]': 'Fly ash [kg/h]',
    '3. Design': '3. Design',
    'Consommations électriques': 'Electrical consumptions',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Data unavailable (open Design tab)',
    'Consommation d\'eau': 'Water consumption',
    'Eau potable [m³/h]': 'Drinking water [m³/h]',
    'Eau de refroidissement [m³/h]': 'Cooling water [m³/h]',
    'Eau déminéralisée [m³/h]': 'Demineralised water [m³/h]',
    'Énergie auxiliaire': 'Auxiliary energy',
    'Gaz haute valeur [MW]': 'High-value gas [MW]',
    'Fuel [MW]': 'Fuel [MW]',
    '4. OPEX — Coûts horaires': '4. OPEX — Hourly costs',
    'Rapport généré automatiquement': 'Report automatically generated',
    'Consommateur': 'Consumer',
    'Total': 'Total',
    'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.': 'OPEX costs unavailable — open Design and Opex tabs.',
    'Électricité': 'Electricity',
    'Eau': 'Water',
    'Réactifs': 'Reagents',
    'Énergie': 'Energy',
    'Total coût': 'Total cost',
    'Coût horaire': 'Hourly cost',
    'Coût annuel': 'Annual cost',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricity',
    'CO₂ énergie': 'CO₂ energy',
    'CO₂ transport': 'CO₂ transport',
    'Total CO₂': 'Total CO₂',
  },

  de: {
    // Navigation und Struktur
    'AIR INJECTION Configuration': 'CYCLONE-Konfiguration',
    'Flue gases': 'Rauchgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Design': 'Auslegung',
    'Opex': 'OPEX',
    'Back to Flow': 'Zurück zum Fluss',
    'Clear memory': 'Speicher löschen',
    'Clear parameters': 'Parameter löschen',
    'Reset to Default Values': 'Auf Standardwerte zurücksetzen',
  
    // Rauchgasparameter
    'Calculation parameters': 'Berechnungsparameter',
    'Calculated parameters': 'Berechnete Parameter',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Flue gas inlet at inlet temperature': 'Rauchgaseintritt bei Eintrittstemperatur',
    'Air ingress at ambient temperature': 'Lufteintritt bei Umgebungstemperatur',
    'Flue gas outlet at outlet temperature': 'Rauchgasaustritt bei Austrittstemperatur',
    'Input flue gas': 'Eingabe Rauchgas',
    'Output flue gas': 'Ausgabe Rauchgas',
    'Residues calculated': 'Berechnete Rückstände',
  
    // Spezifische CYCLONE/CYCLONE-Parameter
    'Flue gas temperature outlet [°C]': 'Rauchgastemperatur Ausgang [°C]',
    'Ambient air temperature [°C]': 'Umgebungslufttemperatur [°C]',
    'Volume of air ingress [Nm3/h]': 'Lufteingangsvolumen [Nm3/h]',
    'Thermal losses [%]': 'Wärmeverluste [%]',
    'Cooling water temperature [°C]': 'Kühlwassertemperatur [°C]',
    'Fly residus content outlet [g/Nm3]': 'Flugaschegehalt Ausgang [g/Nm3]',
    'siccity bottom ash [%]': 'Trockenheit Bodenasche [%]',
    'O2 ref [%]': 'O2 Referenz [%]',
  
    // Berechnete Ergebnisse
    'Temperature inlet CYCLONE [°C]': 'Temperatur Eingang CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta Enthalpien [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Zerstäubtes/Kühlwasser [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Rauchgasvolumen Ausgang [Nm3/h]',
  
    // CYCLONE-Auslegungsparameter
    'Cyclone Model Selection': 'Zyklonmodellauswahl',
    'Cyclone Design Parameters': 'Zyklonauslegungsparameter',
    'Select Model': 'Modell auswählen',
    'Cyclone parameters': 'Zyklonparameter',
    'Input Parameters': 'Eingabeparameter',
    'Calculated Dimensions': 'Berechnete Abmessungen',
    'Pressure Drop Calculation': 'Druckverlustberechnung',
    'Flue Gas Flow [Nm3/h]': 'Rauchgasfluss [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Rauchgastemperatur [°C]',
    'Velocity Target [m/s]': 'Zielgeschwindigkeit [m/s]',
    'Pressure Drop Model': 'Druckverlustmodell',
    'Head Losses': 'Druckverluste',
    'Summary of Main Parameters': 'Zusammenfassung der Hauptparameter',
  
    // Dimensionierung und Berechnungen
    'Surface des manches [m²]': 'Schlauchoberfläche [m²]',
    'Rendement de capture [%]': 'Erfassungswirkungsgrad [%]',
    'Vitesse de filtration [m/h]': 'Filtergeschwindigkeit [m/h]',
    'Pression air comprimé [Bar]': 'Drucklufrdruck [bar]',
    'Consommation air comprimé [Nm3/h]': 'Drucklufverbrauch [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Stromverbrauch Druckluft [kW]',
    'Residus du CYCLONE [kg/h]': 'CYCLONE-Rückstände [kg/h]',
    'Type de camion': 'Lastwagen-Typ',
    'Distance [km]': 'Entfernung [km]',
    'CO2 transport total [kg]': 'Gesamtes Transport-CO2 [kg]',
    'Coût transport total [€]': 'Gesamttransportkosten [€]',
  
    // Druckverluste
    'Pertes de charge aéraulique': 'Aerodynamische Druckverluste',
    'Pression de sortie [mmCE]': 'Ausgangsdruck [mmCE]',
    'Pression aéraulique [mmCE]': 'Aerodynamischer Druck [mmCE]',
    'PDC [mmCE]': 'Druckverlust [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'Dichte [kg/m3]',
    'Pin [mmCE]': 'Eingangsdruck [mmCE]',
    'PDC [Pa]': 'Druckverlust [Pa]',
    'Pout [mmCE]': 'Ausgangsdruck [mmCE]',
  
    // Fluss und Massen
    'Waste Flow [kg/h]': 'Abfallstrom [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Rauchgasfluss feucht [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Rauchgasfluss trocken [Nm3/h]',
    'O2 calculated [%]': 'O2 berechnet [%]',
    'Fly ash [kg/h]': 'Flugasche [kg/h]',
    'Fly ash inlet [kg/h]': 'Flugasche Eingang [kg/h]',
    'Cyclone residus [kg/h]': 'Zyklonrückstände [kg/h]',
    'Dry residus [kg/h]': 'Trockene Rückstände [kg/h]',
    'Wet residus [kg/h]': 'Feuchte Rückstände [kg/h]',
    'inert mass [kg/h]': 'Inertmasse [kg/h]',
  
    // Schadstoffe
    'Pollutant': 'Schadstoff',
    'Reagent': 'Reagenz',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Wirkungsgrad (%)',
    'Stoich. Coeff.': 'Stöchiometrischer Koeffizient',
    'Output Mass': 'Ausgabemasse',
    'Residue Mass': 'Rückstandsmasse',
    'Reagent Mass': 'Regenzmasse',
    'Abated Mass': 'Verringerte Masse',
    'Pollutant Treatment Table': 'Schadstoffbehandlungstabelle',
  
    // Reagenzien
    'SOx reactif': 'SOx Reagenz',
    'HCl reactif': 'HCl Reagenz',
    'HF reactif': 'HF Reagenz',
    'efficacite_SOx': 'SOx Wirkungsgrad',
    'HCl efficacité': 'HCl Wirkungsgrad',
    'HF efficacité': 'HF Wirkungsgrad',
    'SOx stoechiométrie': 'SOx Stöchiometrie',
    'HCl stoechiométrie': 'HCl Stöchiometrie',
    'HF stoechiométrie': 'HF Stöchiometrie',
  
    // FAM-Auslegung
    'Dimensionnement du FAM': 'FAM-Dimensionierung',
    'Consommation électrique de la vis sans fin': 'Stromverbrauch der Schneckenförderer',
    'conso elec vis de transport [kW]': 'Stromverbrauch Transportschnecke [kW]',
    'Consommation d\'air comprimé': 'Drucklufverbrauch',
    'Nombre de cycles [Nb]': 'Anzahl der Zyklen [Anz.]',
    'Air comprime par cycle [Nm3/cycle]': 'Druckluft pro Zyklus [Nm3/Zyklus]',
    'Évacuation des residus AIRINJECTION': 'Entsorgung von CYCLONE-Rückständen',
  
    // Zusammenfassung
    'Résultats': 'Ergebnisse',
    'Résumé des paramètres principaux': 'Zusammenfassung der Hauptparameter',
    'Paramètres calculés détaillés': 'Detaillierte berechnete Parameter',
    'Model': 'Modell',
    'Cyclone Diameter [m]': 'Zyklondurchmesser [m]',
    'Velocity Section [m/s]': 'Geschwindigkeit Querschnitt [m/s]',
  
    // Sonstiges
    'None': 'Keine',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 trocken',
    'CaOH2wet': 'CaOH2 feucht',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 Tonnen',
    '20t': '20 Tonnen',
    '25t': '25 Tonnen',
    'Conveyor': 'Förderanlage',

    // === Bericht ===
    'AIR INJECTION — Rapport de synthèse': 'Zyklon — Synthesebericht',
    '1. Gaz de combustion': '1. Rauchgas',
    'Température de sortie': 'Austrittstemperatur',
    'O₂ mesuré (sec)': 'Gemessenes O₂ (trocken)',
    'Débit humide total [kg/h]': 'Gesamter Feuchtstrom [kg/h]',
    'Débit sec [Nm³/h]': 'Trockenstrom [Nm³/h]',
    'Débit humide [Nm³/h]': 'Feuchtestrom [Nm³/h]',
    'Composition gaz de sortie': 'Austrittsgaszusammensetzung',
    '2. Émissions polluantes': '2. Schadstoffemissionen',
    'Gaz en entrée [kg/h]': 'Eingangsgas [kg/h]',
    'Gaz en sortie [kg/h]': 'Ausgangsgas [kg/h]',
    'Cendres lourdes sèches [kg/h]': 'Trockene Bodenasche [kg/h]',
    'Cendres lourdes humides [kg/h]': 'Feuchte Bodenasche [kg/h]',
    'Cendres volantes [kg/h]': 'Flugasche [kg/h]',
    '3. Design': '3. Auslegung',
    'Consommations électriques': 'Stromverbräuche',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Daten nicht verfügbar (Auslegungs-Tab öffnen)',
    'Consommation d\'eau': 'Wasserverbrauch',
    'Eau potable [m³/h]': 'Trinkwasser [m³/h]',
    'Eau de refroidissement [m³/h]': 'Kühlwasser [m³/h]',
    'Eau déminéralisée [m³/h]': 'Demineralisiertes Wasser [m³/h]',
    'Énergie auxiliaire': 'Hilfsenergie',
    'Gaz haute valeur [MW]': 'Hochwertiges Gas [MW]',
    'Fuel [MW]': 'Brennstoff [MW]',
    '4. OPEX — Coûts horaires': '4. OPEX — Stundenkosten',
    'Rapport généré automatiquement': 'Automatisch generierter Bericht',
    'Consommateur': 'Verbraucher',
    'Total': 'Gesamt',
    'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.': 'OPEX-Kosten nicht verfügbar — Auslegungs- und OPEX-Tabs öffnen.',
    'Électricité': 'Strom',
    'Eau': 'Wasser',
    'Réactifs': 'Reagenzien',
    'Énergie': 'Energie',
    'Total coût': 'Gesamtkosten',
    'Coût horaire': 'Stundenkosten',
    'Coût annuel': 'Jahreskosten',
    'Total CO₂ [kg/h]': 'Gesamt CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ Strom',
    'CO₂ énergie': 'CO₂ Energie',
    'CO₂ transport': 'CO₂ Transport',
    'Total CO₂': 'Gesamt CO₂',
  },

  es: {
    // Navegación y estructura
    'AIR INJECTION Configuration': 'Configuración CYCLONE',
    'Flue gases': 'Gases de combustión',
    'Pollutant Emissions': 'Emisiones de contaminantes',
    'Design': 'Diseño',
    'Opex': 'OPEX',
    'Back to Flow': 'Volver al flujo',
    'Clear memory': 'Borrar memoria',
    'Clear parameters': 'Borrar parámetros',
    'Reset to Default Values': 'Restablecer valores predeterminados',
  
    // Parámetros de gases de combustión
    'Calculation parameters': 'Parámetros de cálculo',
    'Calculated parameters': 'Parámetros calculados',
    'Flue gas composition': 'Composición de gases de combustión',
    'Flue gas inlet at inlet temperature': 'Entrada de gases de combustión a temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de aire a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Salida de gases de combustión a temperatura de salida',
    'Input flue gas': 'Gases de combustión de entrada',
    'Output flue gas': 'Gases de combustión de salida',
    'Residues calculated': 'Residuos calculados',
  
    // Parámetros específicos CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Temperatura salida gases combustión [°C]',
    'Ambient air temperature [°C]': 'Temperatura aire ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volumen de entrada de aire [Nm3/h]',
    'Thermal losses [%]': 'Pérdidas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura agua de enfriamiento [°C]',
    'Fly residus content outlet [g/Nm3]': 'Contenido de cenizas volantes salida [g/Nm3]',
    'siccity bottom ash [%]': 'Sequedad cenizas de fondo [%]',
    'O2 ref [%]': 'O2 referencia [%]',
  
    // Resultados calculados
    'Temperature inlet CYCLONE [°C]': 'Temperatura entrada CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpías [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Agua pulverizada/enfriamiento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volumen gases salida [Nm3/h]',
  
    // Parámetros de diseño CYCLONE
    'Cyclone Model Selection': 'Selección de modelo de ciclón',
    'Cyclone Design Parameters': 'Parámetros de diseño del ciclón',
    'Select Model': 'Seleccionar modelo',
    'Cyclone parameters': 'Parámetros del ciclón',
    'Input Parameters': 'Parámetros de entrada',
    'Calculated Dimensions': 'Dimensiones calculadas',
    'Pressure Drop Calculation': 'Cálculo de caída de presión',
    'Flue Gas Flow [Nm3/h]': 'Flujo de gases de combustión [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Temperatura gases de combustión [°C]',
    'Velocity Target [m/s]': 'Velocidad objetivo [m/s]',
    'Pressure Drop Model': 'Modelo de caída de presión',
    'Head Losses': 'Pérdidas de carga',
    'Summary of Main Parameters': 'Resumen de parámetros principales',
  
    // Dimensionamiento y cálculos
    'Surface des manches [m²]': 'Superficie de mangas [m²]',
    'Rendement de capture [%]': 'Eficiencia de captura [%]',
    'Vitesse de filtration [m/h]': 'Velocidad de filtración [m/h]',
    'Pression air comprimé [Bar]': 'Presión aire comprimido [bar]',
    'Consommation air comprimé [Nm3/h]': 'Consumo aire comprimido [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo eléctrico aire comprimido [kW]',
    'Residus du CYCLONE [kg/h]': 'Residuos CYCLONE [kg/h]',
    'Type de camion': 'Tipo de camión',
    'Distance [km]': 'Distancia [km]',
    'CO2 transport total [kg]': 'CO2 transporte total [kg]',
    'Coût transport total [€]': 'Costo transporte total [€]',
  
    // Pérdidas de carga
    'Pertes de charge aéraulique': 'Pérdidas de carga aerodinámica',
    'Pression de sortie [mmCE]': 'Presión de salida [mmCE]',
    'Pression aéraulique [mmCE]': 'Presión aerodinámica [mmCE]',
    'PDC [mmCE]': 'Pérdida de carga [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'Densidad [kg/m3]',
    'Pin [mmCE]': 'Presión entrada [mmCE]',
    'PDC [Pa]': 'Pérdida de carga [Pa]',
    'Pout [mmCE]': 'Presión salida [mmCE]',
  
    // Flujos y masas
    'Waste Flow [kg/h]': 'Flujo de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flujo gases húmedo [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flujo gases seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'Fly ash [kg/h]': 'Cenizas volantes [kg/h]',
    'Fly ash inlet [kg/h]': 'Cenizas volantes entrada [kg/h]',
    'Cyclone residus [kg/h]': 'Residuos ciclón [kg/h]',
    'Dry residus [kg/h]': 'Residuos secos [kg/h]',
    'Wet residus [kg/h]': 'Residuos húmedos [kg/h]',
    'inert mass [kg/h]': 'Masa inerte [kg/h]',
  
    // Contaminantes
    'Pollutant': 'Contaminante',
    'Reagent': 'Reactivo',
    'Mass (kg/h)': 'Masa (kg/h)',
    'Efficiency (%)': 'Eficiencia (%)',
    'Stoich. Coeff.': 'Coef. estequiométrico',
    'Output Mass': 'Masa de salida',
    'Residue Mass': 'Masa de residuo',
    'Reagent Mass': 'Masa de reactivo',
    'Abated Mass': 'Masa reducida',
    'Pollutant Treatment Table': 'Tabla de tratamiento de contaminantes',
  
    // Reactivos
    'SOx reactif': 'Reactivo SOx',
    'HCl reactif': 'Reactivo HCl',
    'HF reactif': 'Reactivo HF',
    'efficacite_SOx': 'Eficiencia SOx',
    'HCl efficacité': 'Eficiencia HCl',
    'HF efficacité': 'Eficiencia HF',
    'SOx stoechiométrie': 'Estequiometría SOx',
    'HCl stoechiométrie': 'Estequiometría HCl',
    'HF stoechiométrie': 'Estequiometría HF',
  
    // Diseño FAM
    'Dimensionnement du FAM': 'Dimensionamiento del FAM',
    'Consommation électrique de la vis sans fin': 'Consumo eléctrico del tornillo sin fin',
    'conso elec vis de transport [kW]': 'Consumo eléctrico tornillo transporte [kW]',
    'Consommation d\'air comprimé': 'Consumo de aire comprimido',
    'Nombre de cycles [Nb]': 'Número de ciclos [Nº]',
    'Air comprime par cycle [Nm3/cycle]': 'Aire comprimido por ciclo [Nm3/ciclo]',
    'Évacuation des residus AIRINJECTION': 'Evacuación de residuos CYCLONE',
  
    // Resumen
    'Résultats': 'Resultados',
    'Résumé des paramètres principaux': 'Resumen de parámetros principales',
    'Paramètres calculés détaillés': 'Parámetros calculados detallados',
    'Model': 'Modelo',
    'Cyclone Diameter [m]': 'Diámetro ciclón [m]',
    'Velocity Section [m/s]': 'Velocidad sección [m/s]',
  
    // Otros
    'None': 'Ninguno',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 seco',
    'CaOH2wet': 'CaOH2 húmedo',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 toneladas',
    '20t': '20 toneladas',
    '25t': '25 toneladas',
    'Conveyor': 'Transportador',
  },

  it: {
    // Navigazione e struttura
    'AIR INJECTION Configuration': 'Configurazione CYCLONE',
    'Flue gases': 'Gas di combustione',
    'Pollutant Emissions': 'Emissioni di inquinanti',
    'Design': 'Progettazione',
    'Opex': 'OPEX',
    'Back to Flow': 'Ritorna al flusso',
    'Clear memory': 'Cancella memoria',
    'Clear parameters': 'Cancella parametri',
    'Reset to Default Values': 'Ripristina valori predefiniti',
  
    // Parametri dei gas di combustione
    'Calculation parameters': 'Parametri di calcolo',
    'Calculated parameters': 'Parametri calcolati',
    'Flue gas composition': 'Composizione dei gas di combustione',
    'Flue gas inlet at inlet temperature': 'Ingresso gas di combustione a temperatura di ingresso',
    'Air ingress at ambient temperature': 'Ingresso aria a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Uscita gas di combustione a temperatura di uscita',
    'Input flue gas': 'Gas di combustione in ingresso',
    'Output flue gas': 'Gas di combustione in uscita',
    'Residues calculated': 'Residui calcolati',
  
    // Parametri specifici CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Temperatura uscita gas combustione [°C]',
    'Ambient air temperature [°C]': 'Temperatura aria ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume di ingresso aria [Nm3/h]',
    'Thermal losses [%]': 'Perdite termiche [%]',
    'Cooling water temperature [°C]': 'Temperatura acqua di raffreddamento [°C]',
    'Fly residus content outlet [g/Nm3]': 'Contenuto ceneri volanti uscita [g/Nm3]',
    'siccity bottom ash [%]': 'Secchezza ceneri di fondo [%]',
    'O2 ref [%]': 'O2 riferimento [%]',
  
    // Risultati calcolati
    'Temperature inlet CYCLONE [°C]': 'Temperatura ingresso CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpie [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Acqua nebulizzata/raffreddamento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gas uscita [Nm3/h]',
  
    // Parametri di progettazione CYCLONE
    'Cyclone Model Selection': 'Selezione modello ciclone',
    'Cyclone Design Parameters': 'Parametri di progettazione del ciclone',
    'Select Model': 'Seleziona modello',
    'Cyclone parameters': 'Parametri del ciclone',
    'Input Parameters': 'Parametri di ingresso',
    'Calculated Dimensions': 'Dimensioni calcolate',
    'Pressure Drop Calculation': 'Calcolo della perdita di carico',
    'Flue Gas Flow [Nm3/h]': 'Portata gas di combustione [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Temperatura gas di combustione [°C]',
    'Velocity Target [m/s]': 'Velocità target [m/s]',
    'Pressure Drop Model': 'Modello di perdita di carico',
    'Head Losses': 'Perdite di carico',
    'Summary of Main Parameters': 'Riepilogo dei parametri principali',
  
    // Dimensionamento e calcoli
    'Surface des manches [m²]': 'Superficie delle maniche [m²]',
    'Rendement de capture [%]': 'Efficienza di cattura [%]',
    'Vitesse de filtration [m/h]': 'Velocità di filtrazione [m/h]',
    'Pression air comprimé [Bar]': 'Pressione aria compressa [bar]',
    'Consommation air comprimé [Nm3/h]': 'Consumo aria compressa [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo elettrico aria compressa [kW]',
    'Residus du CYCLONE [kg/h]': 'Residui CYCLONE [kg/h]',
    'Type de camion': 'Tipo di camion',
    'Distance [km]': 'Distanza [km]',
    'CO2 transport total [kg]': 'CO2 trasporto totale [kg]',
    'Coût transport total [€]': 'Costo trasporto totale [€]',
  
    // Perdite di carico
    'Pertes de charge aéraulique': 'Perdite di carico aerodinamiche',
    'Pression de sortie [mmCE]': 'Pressione di uscita [mmCE]',
    'Pression aéraulique [mmCE]': 'Pressione aerodinamica [mmCE]',
    'PDC [mmCE]': 'Perdita di carico [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'Densità [kg/m3]',
    'Pin [mmCE]': 'Pressione ingresso [mmCE]',
    'PDC [Pa]': 'Perdita di carico [Pa]',
    'Pout [mmCE]': 'Pressione uscita [mmCE]',
  
    // Flussi e masse
    'Waste Flow [kg/h]': 'Flusso di rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Portata gas umido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Portata gas secco [Nm3/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',
    'Fly ash [kg/h]': 'Ceneri volanti [kg/h]',
    'Fly ash inlet [kg/h]': 'Ceneri volanti ingresso [kg/h]',
    'Cyclone residus [kg/h]': 'Residui ciclone [kg/h]',
    'Dry residus [kg/h]': 'Residui secchi [kg/h]',
    'Wet residus [kg/h]': 'Residui umidi [kg/h]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
  
    // Inquinanti
    'Pollutant': 'Inquinante',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Efficienza (%)',
    'Stoich. Coeff.': 'Coeff. stechiometrico',
    'Output Mass': 'Massa di uscita',
    'Residue Mass': 'Massa residuo',
    'Reagent Mass': 'Massa reagente',
    'Abated Mass': 'Massa ridotta',
    'Pollutant Treatment Table': 'Tabella di trattamento degli inquinanti',
  
    // Reagenti
    'SOx reactif': 'Reagente SOx',
    'HCl reactif': 'Reagente HCl',
    'HF reactif': 'Reagente HF',
    'efficacite_SOx': 'Efficienza SOx',
    'HCl efficacité': 'Efficienza HCl',
    'HF efficacité': 'Efficienza HF',
    'SOx stoechiométrie': 'Stechiometria SOx',
    'HCl stoechiométrie': 'Stechiometria HCl',
    'HF stoechiométrie': 'Stechiometria HF',
  
    // Progettazione FAM
    'Dimensionnement du FAM': 'Dimensionamento FAM',
    'Consommation électrique de la vis sans fin': 'Consumo elettrico della vite senza fine',
    'conso elec vis de transport [kW]': 'Consumo elettrico vite di trasporto [kW]',
    'Consommation d\'air comprimé': 'Consumo di aria compressa',
    'Nombre de cycles [Nb]': 'Numero di cicli [N.]',
    'Air comprime par cycle [Nm3/cycle]': 'Aria compressa per ciclo [Nm3/ciclo]',
    'Évacuation des residus AIRINJECTION': 'Smaltimento dei residui CYCLONE',
  
    // Riepilogo
    'Résultats': 'Risultati',
    'Résumé des paramètres principaux': 'Riepilogo dei parametri principali',
    'Paramètres calculés détaillés': 'Parametri calcolati dettagliati',
    'Model': 'Modello',
    'Cyclone Diameter [m]': 'Diametro ciclone [m]',
    'Velocity Section [m/s]': 'Velocità sezione [m/s]',
  
    // Altro
    'None': 'Nessuno',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 secco',
    'CaOH2wet': 'CaOH2 umido',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 tonnellate',
    '20t': '20 tonnellate',
    '25t': '25 tonnellate',
    'Conveyor': 'Trasportatore',
  },

  pt: {
    // Navegação e estrutura
    'AIR INJECTION Configuration': 'Configuração CYCLONE',
    'Flue gases': 'Gases de combustão',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Design': 'Projeto',
    'Opex': 'OPEX',
    'Back to Flow': 'Voltar ao fluxo',
    'Clear memory': 'Limpar memória',
    'Clear parameters': 'Limpar parâmetros',
    'Reset to Default Values': 'Restaurar valores padrão',
  
    // Parâmetros de gases de combustão
    'Calculation parameters': 'Parâmetros de cálculo',
    'Calculated parameters': 'Parâmetros calculados',
    'Flue gas composition': 'Composição dos gases de combustão',
    'Flue gas inlet at inlet temperature': 'Entrada de gases de combustão à temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de ar à temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Saída de gases de combustão à temperatura de saída',
    'Input flue gas': 'Gases de combustão de entrada',
    'Output flue gas': 'Gases de combustão de saída',
    'Residues calculated': 'Resíduos calculados',
  
    // Parâmetros específicos CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Temperatura saída gases combustão [°C]',
    'Ambient air temperature [°C]': 'Temperatura ar ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume de entrada de ar [Nm3/h]',
    'Thermal losses [%]': 'Perdas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura água de resfriamento [°C]',
    'Fly residus content outlet [g/Nm3]': 'Teor de cinzas volantes saída [g/Nm3]',
    'siccity bottom ash [%]': 'Secura cinzas de fundo [%]',
    'O2 ref [%]': 'O2 referência [%]',
  
    // Resultados calculados
    'Temperature inlet CYCLONE [°C]': 'Temperatura entrada CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpias [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Água pulverizada/resfriamento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gases saída [Nm3/h]',
  
    // Parâmetros de projeto CYCLONE
    'Cyclone Model Selection': 'Seleção de modelo de ciclone',
    'Cyclone Design Parameters': 'Parâmetros de projeto do ciclone',
    'Select Model': 'Selecionar modelo',
    'Cyclone parameters': 'Parâmetros do ciclone',
    'Input Parameters': 'Parâmetros de entrada',
    'Calculated Dimensions': 'Dimensões calculadas',
    'Pressure Drop Calculation': 'Cálculo da queda de pressão',
    'Flue Gas Flow [Nm3/h]': 'Vazão de gases de combustão [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Temperatura gases de combustão [°C]',
    'Velocity Target [m/s]': 'Velocidade alvo [m/s]',
    'Pressure Drop Model': 'Modelo de queda de pressão',
    'Head Losses': 'Perdas de carga',
    'Summary of Main Parameters': 'Resumo dos parâmetros principais',
  
    // Dimensionamento e cálculos
    'Surface des manches [m²]': 'Superfície das mangas [m²]',
    'Rendement de capture [%]': 'Eficiência de captura [%]',
    'Vitesse de filtration [m/h]': 'Velocidade de filtração [m/h]',
    'Pression air comprimé [Bar]': 'Pressão ar comprimido [bar]',
    'Consommation air comprimé [Nm3/h]': 'Consumo ar comprimido [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Consumo elétrico ar comprimido [kW]',
    'Residus du CYCLONE [kg/h]': 'Resíduos CYCLONE [kg/h]',
    'Type de camion': 'Tipo de caminhão',
    'Distance [km]': 'Distância [km]',
    'CO2 transport total [kg]': 'CO2 transporte total [kg]',
    'Coût transport total [€]': 'Custo transporte total [€]',
  
    // Perdas de carga
    'Pertes de charge aéraulique': 'Perdas de carga aerodinâmica',
    'Pression de sortie [mmCE]': 'Pressão de saída [mmCE]',
    'Pression aéraulique [mmCE]': 'Pressão aerodinâmica [mmCE]',
    'PDC [mmCE]': 'Perda de carga [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': 'Densidade [kg/m3]',
    'Pin [mmCE]': 'Pressão entrada [mmCE]',
    'PDC [Pa]': 'Perda de carga [Pa]',
    'Pout [mmCE]': 'Pressão saída [mmCE]',
  
    // Fluxos e massas
    'Waste Flow [kg/h]': 'Vazão de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Vazão gases úmido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Vazão gases seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'Fly ash [kg/h]': 'Cinzas volantes [kg/h]',
    'Fly ash inlet [kg/h]': 'Cinzas volantes entrada [kg/h]',
    'Cyclone residus [kg/h]': 'Resíduos ciclone [kg/h]',
    'Dry residus [kg/h]': 'Resíduos secos [kg/h]',
    'Wet residus [kg/h]': 'Resíduos úmidos [kg/h]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
  
    // Poluentes
    'Pollutant': 'Poluente',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Eficiência (%)',
    'Stoich. Coeff.': 'Coef. estequiométrico',
    'Output Mass': 'Massa de saída',
    'Residue Mass': 'Massa de resíduo',
    'Reagent Mass': 'Massa de reagente',
    'Abated Mass': 'Massa reduzida',
    'Pollutant Treatment Table': 'Tabela de tratamento de poluentes',
  
    // Reagentes
    'SOx reactif': 'Reagente SOx',
    'HCl reactif': 'Reagente HCl',
    'HF reactif': 'Reagente HF',
    'efficacite_SOx': 'Eficiência SOx',
    'HCl efficacité': 'Eficiência HCl',
    'HF efficacité': 'Eficiência HF',
    'SOx stoechiométrie': 'Estequiometria SOx',
    'HCl stoechiométrie': 'Estequiometria HCl',
    'HF stoechiométrie': 'Estequiometria HF',
  
    // Projeto FAM
    'Dimensionnement du FAM': 'Dimensionamento FAM',
    'Consommation électrique de la vis sans fin': 'Consumo elétrico do parafuso sem fim',
    'conso elec vis de transport [kW]': 'Consumo elétrico parafuso transporte [kW]',
    'Consommation d\'air comprimé': 'Consumo de ar comprimido',
    'Nombre de cycles [Nb]': 'Número de ciclos [N.]',
    'Air comprime par cycle [Nm3/cycle]': 'Ar comprimido por ciclo [Nm3/ciclo]',
    'Évacuation des residus AIRINJECTION': 'Disposição de resíduos CYCLONE',
  
    // Resumo
    'Résultats': 'Resultados',
    'Résumé des paramètres principaux': 'Resumo dos parâmetros principais',
    'Paramètres calculés détaillés': 'Parâmetros calculados detalhados',
    'Model': 'Modelo',
    'Cyclone Diameter [m]': 'Diâmetro ciclone [m]',
    'Velocity Section [m/s]': 'Velocidade seção [m/s]',
  
    // Outros
    'None': 'Nenhum',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 seco',
    'CaOH2wet': 'CaOH2 úmido',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 toneladas',
    '20t': '20 toneladas',
    '25t': '25 toneladas',
    'Conveyor': 'Transportador',
  },

  zh: {
    // 导航和结构
    'AIR INJECTION Configuration': 'CYCLONE 配置',
    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Design': '设计',
    'Opex': '运营成本',
    'Back to Flow': '返回流量',
    'Clear memory': '清除内存',
    'Clear parameters': '清除参数',
    'Reset to Default Values': '恢复默认值',
  
    // 烟气参数
    'Calculation parameters': '计算参数',
    'Calculated parameters': '计算的参数',
    'Flue gas composition': '烟气成分',
    'Flue gas inlet at inlet temperature': '烟气入口于进口温度',
    'Air ingress at ambient temperature': '空气进入于环境温度',
    'Flue gas outlet at outlet temperature': '烟气出口于出口温度',
    'Input flue gas': '输入烟气',
    'Output flue gas': '输出烟气',
    'Residues calculated': '计算的残留物',
  
    // CYCLONE/CYCLONE 特定参数
    'Flue gas temperature outlet [°C]': '烟气出口温度 [°C]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空气进入体积 [Nm3/h]',
    'Thermal losses [%]': '热损失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Fly residus content outlet [g/Nm3]': '飞灰含量出口 [g/Nm3]',
    'siccity bottom ash [%]': '底灰干燥度 [%]',
    'O2 ref [%]': 'O2 参考 [%]',
  
    // 计算结果
    'Temperature inlet CYCLONE [°C]': 'CYCLONE 入口温度 [°C]',
    'Delta enthalpies [kJ/kg]': '焓差 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '喷雾/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '出口烟气体积 [Nm3/h]',
  
    // CYCLONE 设计参数
    'Cyclone Model Selection': '旋风分离器型号选择',
    'Cyclone Design Parameters': '旋风分离器设计参数',
    'Select Model': '选择型号',
    'Cyclone parameters': '旋风分离器参数',
    'Input Parameters': '输入参数',
    'Calculated Dimensions': '计算的尺寸',
    'Pressure Drop Calculation': '压降计算',
    'Flue Gas Flow [Nm3/h]': '烟气流量 [Nm3/h]',
    'Temperature Flue Gas [°C]': '烟气温度 [°C]',
    'Velocity Target [m/s]': '目标速度 [m/s]',
    'Pressure Drop Model': '压降模型',
    'Head Losses': '水头损失',
    'Summary of Main Parameters': '主要参数汇总',
  
    // 尺寸和计算
    'Surface des manches [m²]': '滤袋表面 [m²]',
    'Rendement de capture [%]': '捕集效率 [%]',
    'Vitesse de filtration [m/h]': '过滤速度 [m/h]',
    'Pression air comprimé [Bar]': '压缩空气压力 [bar]',
    'Consommation air comprimé [Nm3/h]': '压缩空气消耗 [Nm3/h]',
    'Conso élec air comprimé [kW]': '压缩空气用电 [kW]',
    'Residus du CYCLONE [kg/h]': 'CYCLONE 残留物 [kg/h]',
    'Type de camion': '卡车类型',
    'Distance [km]': '距离 [km]',
    'CO2 transport total [kg]': '总运输 CO2 [kg]',
    'Coût transport total [€]': '总运输成本 [€]',
  
    // 压降
    'Pertes de charge aéraulique': '气动压降',
    'Pression de sortie [mmCE]': '出口压力 [mmCE]',
    'Pression aéraulique [mmCE]': '气动压力 [mmCE]',
    'PDC [mmCE]': '压降 [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Dzeta',
    'RHO [kg/m3]': '密度 [kg/m3]',
    'Pin [mmCE]': '入口压力 [mmCE]',
    'PDC [Pa]': '压降 [Pa]',
    'Pout [mmCE]': '出口压力 [mmCE]',
  
    // 流量和质量
    'Waste Flow [kg/h]': '废物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流量 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流量 [Nm3/h]',
    'O2 calculated [%]': 'O2 计算值 [%]',
    'Fly ash [kg/h]': '飞灰 [kg/h]',
    'Fly ash inlet [kg/h]': '飞灰进口 [kg/h]',
    'Cyclone residus [kg/h]': '旋风分离器残留物 [kg/h]',
    'Dry residus [kg/h]': '干残留物 [kg/h]',
    'Wet residus [kg/h]': '湿残留物 [kg/h]',
    'inert mass [kg/h]': '惯性质量 [kg/h]',
  
    // 污染物
    'Pollutant': '污染物',
    'Reagent': '试剂',
    'Mass (kg/h)': '质量 (kg/h)',
    'Efficiency (%)': '效率 (%)',
    'Stoich. Coeff.': '化学计量系数',
    'Output Mass': '输出质量',
    'Residue Mass': '残留物质量',
    'Reagent Mass': '试剂质量',
    'Abated Mass': '减少的质量',
    'Pollutant Treatment Table': '污染物处理表',
  
    // 试剂
    'SOx reactif': 'SOx 试剂',
    'HCl reactif': 'HCl 试剂',
    'HF reactif': 'HF 试剂',
    'efficacite_SOx': 'SOx 效率',
    'HCl efficacité': 'HCl 效率',
    'HF efficacité': 'HF 效率',
    'SOx stoechiométrie': 'SOx 化学计量',
    'HCl stoechiométrie': 'HCl 化学计量',
    'HF stoechiométrie': 'HF 化学计量',
  
    // FAM 设计
    'Dimensionnement du FAM': 'FAM 尺寸设计',
    'Consommation électrique de la vis sans fin': '无轴螺旋输送机用电',
    'conso elec vis de transport [kW]': '输送螺旋用电 [kW]',
    'Consommation d\'air comprimé': '压缩空气消耗',
    'Nombre de cycles [Nb]': '循环数 [N.]',
    'Air comprime par cycle [Nm3/cycle]': '每个循环压缩空气 [Nm3/循环]',
    'Évacuation des residus AIRINJECTION': 'CYCLONE 残留物处置',
  
    // 汇总
    'Résultats': '结果',
    'Résumé des paramètres principaux': '主要参数汇总',
    'Paramètres calculés détaillés': '详细计算参数',
    'Model': '型号',
    'Cyclone Diameter [m]': '旋风分离器直径 [m]',
    'Velocity Section [m/s]': '速度截面 [m/s]',
  
    // 其他
    'None': '无',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 干燥',
    'CaOH2wet': 'CaOH2 湿润',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 吨',
    '20t': '20 吨',
    '25t': '25 吨',
    'Conveyor': '传送带',
  },

  ja: {
    // ナビゲーションと構造
    'AIR INJECTION Configuration': 'CYCLONE設定',
    'Flue gases': '煙道ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Design': '設計',
    'Opex': '運用コスト',
    'Back to Flow': 'フローに戻る',
    'Clear memory': 'メモリをクリア',
    'Clear parameters': 'パラメータをクリア',
    'Reset to Default Values': 'デフォルト値にリセット',
  
    // 煙道ガスパラメータ
    'Calculation parameters': '計算パラメータ',
    'Calculated parameters': '計算されたパラメータ',
    'Flue gas composition': '煙道ガス組成',
    'Flue gas inlet at inlet temperature': '入口温度での煙道ガス入口',
    'Air ingress at ambient temperature': '環境温度での空気流入',
    'Flue gas outlet at outlet temperature': '出口温度での煙道ガス出口',
    'Input flue gas': '入力煙道ガス',
    'Output flue gas': '出力煙道ガス',
    'Residues calculated': '計算された残留物',
  
    // CYCLONE/CYCLONE特定パラメータ
    'Flue gas temperature outlet [°C]': '煙道ガス出口温度 [°C]',
    'Ambient air temperature [°C]': '環境空気温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空気流入量 [Nm3/h]',
    'Thermal losses [%]': '熱損失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Fly residus content outlet [g/Nm3]': 'フライアッシュ含有量出口 [g/Nm3]',
    'siccity bottom ash [%]': 'ボトムアッシュ乾燥度 [%]',
    'O2 ref [%]': 'O2参照値 [%]',
  
    // 計算結果
    'Temperature inlet CYCLONE [°C]': 'CYCLONE入口温度 [°C]',
    'Delta enthalpies [kJ/kg]': 'エンタルピー差 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '噴霧/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '出口煙道ガス量 [Nm3/h]',
  
    // CYCLONE設計パラメータ
    'Cyclone Model Selection': 'サイクロンモデル選択',
    'Cyclone Design Parameters': 'サイクロン設計パラメータ',
    'Select Model': 'モデルを選択',
    'Cyclone parameters': 'サイクロンパラメータ',
    'Input Parameters': '入力パラメータ',
    'Calculated Dimensions': '計算された寸法',
    'Pressure Drop Calculation': '圧力損失計算',
    'Flue Gas Flow [Nm3/h]': '煙道ガスフロー [Nm3/h]',
    'Temperature Flue Gas [°C]': '煙道ガス温度 [°C]',
    'Velocity Target [m/s]': '目標速度 [m/s]',
    'Pressure Drop Model': '圧力損失モデル',
    'Head Losses': 'ヘッド損失',
    'Summary of Main Parameters': '主要パラメータの概要',
  
    // 寸法と計算
    'Surface des manches [m²]': 'フィルタバッグ表面 [m²]',
    'Rendement de capture [%]': '捕集効率 [%]',
    'Vitesse de filtration [m/h]': 'ろ過速度 [m/h]',
    'Pression air comprimé [Bar]': '圧縮空気圧力 [bar]',
    'Consommation air comprimé [Nm3/h]': '圧縮空気消費量 [Nm3/h]',
    'Conso élec air comprimé [kW]': '圧縮空気電力消費 [kW]',
    'Residus du CYCLONE [kg/h]': 'CYCLONE残留物 [kg/h]',
    'Type de camion': 'トラックタイプ',
    'Distance [km]': '距離 [km]',
    'CO2 transport total [kg]': '総輸送CO2 [kg]',
    'Coût transport total [€]': '総輸送コスト [€]',
  
    // 圧力損失
    'Pertes de charge aéraulique': '空気力学的圧力損失',
    'Pression de sortie [mmCE]': '出口圧力 [mmCE]',
    'Pression aéraulique [mmCE]': '空気力学的圧力 [mmCE]',
    'PDC [mmCE]': '圧力損失 [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'ゼータ',
    'RHO [kg/m3]': '密度 [kg/m3]',
    'Pin [mmCE]': '入口圧力 [mmCE]',
    'PDC [Pa]': '圧力損失 [Pa]',
    'Pout [mmCE]': '出口圧力 [mmCE]',
  
    // フローと質量
    'Waste Flow [kg/h]': '廃棄物流量 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿式煙道ガスフロー [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾式煙道ガスフロー [Nm3/h]',
    'O2 calculated [%]': 'O2計算値 [%]',
    'Fly ash [kg/h]': 'フライアッシュ [kg/h]',
    'Fly ash inlet [kg/h]': 'フライアッシュ入口 [kg/h]',
    'Cyclone residus [kg/h]': 'サイクロン残留物 [kg/h]',
    'Dry residus [kg/h]': '乾式残留物 [kg/h]',
    'Wet residus [kg/h]': '湿式残留物 [kg/h]',
    'inert mass [kg/h]': '不活性質量 [kg/h]',
  
    // 汚染物質
    'Pollutant': '汚染物質',
    'Reagent': '試薬',
    'Mass (kg/h)': '質量 (kg/h)',
    'Efficiency (%)': '効率 (%)',
    'Stoich. Coeff.': '化学量論係数',
    'Output Mass': '出力質量',
    'Residue Mass': '残留物質量',
    'Reagent Mass': '試薬質量',
    'Abated Mass': '低減質量',
    'Pollutant Treatment Table': '汚染物質処理表',
  
    // 試薬
    'SOx reactif': 'SOx試薬',
    'HCl reactif': 'HCl試薬',
    'HF reactif': 'HF試薬',
    'efficacite_SOx': 'SOx効率',
    'HCl efficacité': 'HCl効率',
    'HF efficacité': 'HF効率',
    'SOx stoechiométrie': 'SOx化学量論',
    'HCl stoechiométrie': 'HCl化学量論',
    'HF stoechiométrie': 'HF化学量論',
  
    // FAM設計
    'Dimensionnement du FAM': 'FAM寸法設計',
    'Consommation électrique de la vis sans fin': '無軸スクリューコンベア電力消費',
    'conso elec vis de transport [kW]': '輸送スクリュー電力消費 [kW]',
    'Consommation d\'air comprimé': '圧縮空気消費量',
    'Nombre de cycles [Nb]': 'サイクル数 [N.]',
    'Air comprime par cycle [Nm3/cycle]': 'サイクル当たり圧縮空気 [Nm3/サイクル]',
    'Évacuation des residus AIRINJECTION': 'CYCLONE残留物の処分',
  
    // 概要
    'Résultats': '結果',
    'Résumé des paramètres principaux': '主要パラメータの概要',
    'Paramètres calculés détaillés': '詳細な計算パラメータ',
    'Model': 'モデル',
    'Cyclone Diameter [m]': 'サイクロン直径 [m]',
    'Velocity Section [m/s]': '速度セクション [m/s]',
  
    // その他
    'None': 'なし',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2乾燥',
    'CaOH2wet': 'CaOH2湿潤',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15トン',
    '20t': '20トン',
    '25t': '25トン',
    'Conveyor': 'コンベア',
  },

  ru: {
    // Навигация и структура
    'AIR INJECTION Configuration': 'Конфигурация CYCLONE',
    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязняющих веществ',
    'Design': 'Конструкция',
    'Opex': 'OPEX',
    'Back to Flow': 'Вернуться к потоку',
    'Clear memory': 'Очистить память',
    'Clear parameters': 'Очистить параметры',
    'Reset to Default Values': 'Восстановить значения по умолчанию',
  
    // Параметры дымовых газов
    'Calculation parameters': 'Параметры расчета',
    'Calculated parameters': 'Рассчитанные параметры',
    'Flue gas composition': 'Состав дымовых газов',
    'Flue gas inlet at inlet temperature': 'Входящие дымовые газы при температуре входа',
    'Air ingress at ambient temperature': 'Поступление воздуха при температуре окружающей среды',
    'Flue gas outlet at outlet temperature': 'Выходящие дымовые газы при температуре выхода',
    'Input flue gas': 'Входящие дымовые газы',
    'Output flue gas': 'Выходящие дымовые газы',
    'Residues calculated': 'Рассчитанные остатки',
  
    // Специфические параметры CYCLONE/CYCLONE
    'Flue gas temperature outlet [°C]': 'Температура выхода дымовых газов [°C]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Volume of air ingress [Nm3/h]': 'Объем поступления воздуха [Nm3/h]',
    'Thermal losses [%]': 'Тепловые потери [%]',
    'Cooling water temperature [°C]': 'Температура охлаждающей воды [°C]',
    'Fly residus content outlet [g/Nm3]': 'Содержание летучей золы на выходе [g/Nm3]',
    'siccity bottom ash [%]': 'Сухость шлака [%]',
    'O2 ref [%]': 'O2 эталон [%]',
  
    // Рассчитанные результаты
    'Temperature inlet CYCLONE [°C]': 'Температура входа CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'Разность энтальпий [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Распыляемая/охлаждающая вода [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Объем выходящих дымовых газов [Nm3/h]',
  
    // Параметры конструкции CYCLONE
    'Cyclone Model Selection': 'Выбор модели циклона',
    'Cyclone Design Parameters': 'Параметры конструкции циклона',
    'Select Model': 'Выбрать модель',
    'Cyclone parameters': 'Параметры циклона',
    'Input Parameters': 'Входные параметры',
    'Calculated Dimensions': 'Рассчитанные размеры',
    'Pressure Drop Calculation': 'Расчет перепада давления',
    'Flue Gas Flow [Nm3/h]': 'Поток дымовых газов [Nm3/h]',
    'Temperature Flue Gas [°C]': 'Температура дымовых газов [°C]',
    'Velocity Target [m/s]': 'Целевая скорость [m/s]',
    'Pressure Drop Model': 'Модель перепада давления',
    'Head Losses': 'Потери напора',
    'Summary of Main Parameters': 'Сводка основных параметров',
  
    // Размеры и расчеты
    'Surface des manches [m²]': 'Поверхность фильтровальных рукавов [m²]',
    'Rendement de capture [%]': 'Эффективность захвата [%]',
    'Vitesse de filtration [m/h]': 'Скорость фильтрации [m/h]',
    'Pression air comprimé [Bar]': 'Давление сжатого воздуха [bar]',
    'Consommation air comprimé [Nm3/h]': 'Расход сжатого воздуха [Nm3/h]',
    'Conso élec air comprimé [kW]': 'Электропотребление сжатого воздуха [kW]',
    'Residus du CYCLONE [kg/h]': 'Остатки CYCLONE [kg/h]',
    'Type de camion': 'Тип грузовика',
    'Distance [km]': 'Расстояние [km]',
    'CO2 transport total [kg]': 'Общий CO2 при транспортировке [kg]',
    'Coût transport total [€]': 'Общая стоимость транспортировки [€]',
  
    // Потери давления
    'Pertes de charge aéraulique': 'Аэродинамические потери давления',
    'Pression de sortie [mmCE]': 'Давление на выходе [mmCE]',
    'Pression aéraulique [mmCE]': 'Аэродинамическое давление [mmCE]',
    'PDC [mmCE]': 'Перепад давления [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'Дзета',
    'RHO [kg/m3]': 'Плотность [kg/m3]',
    'Pin [mmCE]': 'Давление входа [mmCE]',
    'PDC [Pa]': 'Перепад давления [Pa]',
    'Pout [mmCE]': 'Давление на выходе [mmCE]',
  
    // Потоки и массы
    'Waste Flow [kg/h]': 'Поток отходов [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Поток влажных дымовых газов [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Поток сухих дымовых газов [Nm3/h]',
    'O2 calculated [%]': 'O2 рассчитанный [%]',
    'Fly ash [kg/h]': 'Летучая зола [kg/h]',
    'Fly ash inlet [kg/h]': 'Летучая зола на входе [kg/h]',
    'Cyclone residus [kg/h]': 'Остатки циклона [kg/h]',
    'Dry residus [kg/h]': 'Сухие остатки [kg/h]',
    'Wet residus [kg/h]': 'Влажные остатки [kg/h]',
    'inert mass [kg/h]': 'Инертная масса [kg/h]',
  
    // Загрязняющие вещества
    'Pollutant': 'Загрязняющее вещество',
    'Reagent': 'Реагент',
    'Mass (kg/h)': 'Масса (kg/h)',
    'Efficiency (%)': 'Эффективность (%)',
    'Stoich. Coeff.': 'Стехиометрический коэффициент',
    'Output Mass': 'Выходная масса',
    'Residue Mass': 'Масса остатка',
    'Reagent Mass': 'Масса реагента',
    'Abated Mass': 'Сокращенная масса',
    'Pollutant Treatment Table': 'Таблица обработки загрязняющих веществ',
  
    // Реагенты
    'SOx reactif': 'Реагент SOx',
    'HCl reactif': 'Реагент HCl',
    'HF reactif': 'Реагент HF',
    'efficacite_SOx': 'Эффективность SOx',
    'HCl efficacité': 'Эффективность HCl',
    'HF efficacité': 'Эффективность HF',
    'SOx stoechiométrie': 'Стехиометрия SOx',
    'HCl stoechiométrie': 'Стехиометрия HCl',
    'HF stoechiométrie': 'Стехиометрия HF',
  
    // Конструкция FAM
    'Dimensionnement du FAM': 'Расчет размеров FAM',
    'Consommation électrique de la vis sans fin': 'Электропотребление шнекового конвейера',
    'conso elec vis de transport [kW]': 'Электропотребление шнека транспортировки [kW]',
    'Consommation d\'air comprimé': 'Расход сжатого воздуха',
    'Nombre de cycles [Nb]': 'Количество циклов [N.]',
    'Air comprime par cycle [Nm3/cycle]': 'Сжатый воздух за цикл [Nm3/цикл]',
    'Évacuation des residus AIRINJECTION': 'Утилизация остатков CYCLONE',
  
    // Резюме
    'Résultats': 'Результаты',
    'Résumé des paramètres principaux': 'Сводка основных параметров',
    'Paramètres calculés détaillés': 'Подробные рассчитанные параметры',
    'Model': 'Модель',
    'Cyclone Diameter [m]': 'Диаметр циклона [m]',
    'Velocity Section [m/s]': 'Скорость в сечении [m/s]',
  
    // Другое
    'None': 'Нет',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 сухой',
    'CaOH2wet': 'CaOH2 влажный',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 тонн',
    '20t': '20 тонн',
    '25t': '25 тонн',
    'Conveyor': 'Конвейер',
  },

  ar: {
    // الملاحة والهيكل
    'AIR INJECTION Configuration': 'تكوين CYCLONE',
    'Flue gases': 'غازات العادم',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Design': 'التصميم',
    'Opex': 'تكاليف التشغيل',
    'Back to Flow': 'العودة إلى التدفق',
    'Clear memory': 'مسح الذاكرة',
    'Clear parameters': 'مسح المعاملات',
    'Reset to Default Values': 'إعادة تعيين القيم الافتراضية',
  
    // معاملات غازات العادم
    'Calculation parameters': 'معاملات الحساب',
    'Calculated parameters': 'المعاملات المحسوبة',
    'Flue gas composition': 'تكوين غازات العادم',
    'Flue gas inlet at inlet temperature': 'مدخل غازات العادم عند درجة حرارة الدخول',
    'Air ingress at ambient temperature': 'دخول الهواء عند درجة حرارة محيطة',
    'Flue gas outlet at outlet temperature': 'مخرج غازات العادم عند درجة حرارة الخروج',
    'Input flue gas': 'غازات العادم المدخلة',
    'Output flue gas': 'غازات العادم المخرجة',
    'Residues calculated': 'البقايا المحسوبة',
  
    // معاملات CYCLONE/CYCLONE المحددة
    'Flue gas temperature outlet [°C]': 'درجة حرارة خروج غازات العادم [°C]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Volume of air ingress [Nm3/h]': 'حجم دخول الهواء [Nm3/h]',
    'Thermal losses [%]': 'الخسائر الحرارية [%]',
    'Cooling water temperature [°C]': 'درجة حرارة ماء التبريد [°C]',
    'Fly residus content outlet [g/Nm3]': 'محتوى الرماد المتطاير في المخرج [g/Nm3]',
    'siccity bottom ash [%]': 'جفاف رماد القاع [%]',
    'O2 ref [%]': 'مرجع O2 [%]',
  
    // النتائج المحسوبة
    'Temperature inlet CYCLONE [°C]': 'درجة حرارة مدخل CYCLONE [°C]',
    'Delta enthalpies [kJ/kg]': 'الفرق في الإنثالبيا [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'الماء المرشوش/التبريد [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'حجم غازات العادم المخرجة [Nm3/h]',
  
    // معاملات تصميم CYCLONE
    'Cyclone Model Selection': 'اختيار نموذج الدوامة',
    'Cyclone Design Parameters': 'معاملات تصميم الدوامة',
    'Select Model': 'اختر النموذج',
    'Cyclone parameters': 'معاملات الدوامة',
    'Input Parameters': 'معاملات الإدخال',
    'Calculated Dimensions': 'الأبعاد المحسوبة',
    'Pressure Drop Calculation': 'حساب انخفاض الضغط',
    'Flue Gas Flow [Nm3/h]': 'تدفق غازات العادم [Nm3/h]',
    'Temperature Flue Gas [°C]': 'درجة حرارة غازات العادم [°C]',
    'Velocity Target [m/s]': 'السرعة المستهدفة [m/s]',
    'Pressure Drop Model': 'نموذج انخفاض الضغط',
    'Head Losses': 'خسائر رأس الضغط',
    'Summary of Main Parameters': 'ملخص المعاملات الرئيسية',
  
    // الأبعاد والحسابات
    'Surface des manches [m²]': 'سطح أكياس الترشيح [m²]',
    'Rendement de capture [%]': 'كفاءة الالتقاط [%]',
    'Vitesse de filtration [m/h]': 'سرعة الترشيح [m/h]',
    'Pression air comprimé [Bar]': 'ضغط الهواء المضغوط [bar]',
    'Consommation air comprimé [Nm3/h]': 'استهلاك الهواء المضغوط [Nm3/h]',
    'Conso élec air comprimé [kW]': 'استهلاك الكهرباء للهواء المضغوط [kW]',
    'Residus du CYCLONE [kg/h]': 'بقايا CYCLONE [kg/h]',
    'Type de camion': 'نوع الشاحنة',
    'Distance [km]': 'المسافة [km]',
    'CO2 transport total [kg]': 'إجمالي CO2 للنقل [kg]',
    'Coût transport total [€]': 'إجمالي تكلفة النقل [€]',
  
    // خسائر الضغط
    'Pertes de charge aéraulique': 'خسائر الضغط الديناميكية الهوائية',
    'Pression de sortie [mmCE]': 'ضغط المخرج [mmCE]',
    'Pression aéraulique [mmCE]': 'الضغط الديناميكي الهوائي [mmCE]',
    'PDC [mmCE]': 'انخفاض الضغط [mmCE]',
    'a x b / d^2': 'a x b / d^2',
    'Dzeta': 'زيتا',
    'RHO [kg/m3]': 'الكثافة [kg/m3]',
    'Pin [mmCE]': 'ضغط المدخل [mmCE]',
    'PDC [Pa]': 'انخفاض الضغط [Pa]',
    'Pout [mmCE]': 'ضغط المخرج [mmCE]',
  
    // التدفقات والكتل
    'Waste Flow [kg/h]': 'تدفق النفايات [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق غازات العادم الرطب [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق غازات العادم الجاف [Nm3/h]',
    'O2 calculated [%]': 'O2 المحسوب [%]',
    'Fly ash [kg/h]': 'الرماد المتطاير [kg/h]',
    'Fly ash inlet [kg/h]': 'الرماد المتطاير في المدخل [kg/h]',
    'Cyclone residus [kg/h]': 'بقايا الدوامة [kg/h]',
    'Dry residus [kg/h]': 'البقايا الجافة [kg/h]',
    'Wet residus [kg/h]': 'البقايا الرطبة [kg/h]',
    'inert mass [kg/h]': 'الكتلة الخاملة [kg/h]',
  
    // الملوثات
    'Pollutant': 'ملوث',
    'Reagent': 'كاشف',
    'Mass (kg/h)': 'الكتلة (kg/h)',
    'Efficiency (%)': 'الكفاءة (%)',
    'Stoich. Coeff.': 'معامل ستويتشيومتري',
    'Output Mass': 'كتلة المخرج',
    'Residue Mass': 'كتلة البقايا',
    'Reagent Mass': 'كتلة الكاشف',
    'Abated Mass': 'الكتلة المخففة',
    'Pollutant Treatment Table': 'جدول معالجة الملوثات',
  
    // الكواشف
    'SOx reactif': 'كاشف SOx',
    'HCl reactif': 'كاشف HCl',
    'HF reactif': 'كاشف HF',
    'efficacite_SOx': 'كفاءة SOx',
    'HCl efficacité': 'كفاءة HCl',
    'HF efficacité': 'كفاءة HF',
    'SOx stoechiométrie': 'ستويتشيومتري SOx',
    'HCl stoechiométrie': 'ستويتشيومتري HCl',
    'HF stoechiométrie': 'ستويتشيومتري HF',
  
    // تصميم FAM
    'Dimensionnement du FAM': 'تحديد أبعاد FAM',
    'Consommation électrique de la vis sans fin': 'استهلاك الكهرباء للمسمار اللانهائي',
    'conso elec vis de transport [kW]': 'استهلاك الكهرباء لمسمار النقل [kW]',
    'Consommation d\'air comprimé': 'استهلاك الهواء المضغوط',
    'Nombre de cycles [Nb]': 'عدد الدورات [N.]',
    'Air comprime par cycle [Nm3/cycle]': 'الهواء المضغوط لكل دورة [Nm3/دورة]',
    'Évacuation des residus AIRINJECTION': 'التخلص من بقايا CYCLONE',
  
    // الملخص
    'Résultats': 'النتائج',
    'Résumé des paramètres principaux': 'ملخص المعاملات الرئيسية',
    'Paramètres calculés détaillés': 'المعاملات المحسوبة التفصيلية',
    'Model': 'النموذج',
    'Cyclone Diameter [m]': 'قطر الدوامة [m]',
    'Velocity Section [m/s]': 'سرعة القسم [m/s]',
  
    // آخر
    'None': 'لا شيء',
    'CaCO3': 'CaCO3',
    'CaO': 'CaO',
    'CaOH2dry': 'CaOH2 جاف',
    'CaOH2wet': 'CaOH2 رطب',
    'CAP': 'CAP',
    'NaOH': 'NaOH',
    'NaOHCO3': 'NaOHCO3',
    '15t': '15 طن',
    '20t': '20 طن',
    '25t': '25 طن',
    'Conveyor': 'ناقل',
  },

};