export const translations = {
  fr: {
    // ========== SECTIONS PRINCIPALES ==========
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Flue gas composition': 'Composition des gaz de combustion',
    'Pollutant Treatment Table': 'Tableau de traitement des polluants',
    'Résultats': 'Résultats',
    'Résumé des paramètres principaux': 'Résumé des paramètres principaux',
    'Paramètres calculés détaillés': 'Paramètres calculés détaillés',

    // ========== BOUTONS ==========
    'Clear memory': 'Effacer la mémoire',
    'Reset to Default Values': 'Réinitialiser aux valeurs par défaut',
    'Export': 'Exporter',

    // ========== PARAMETRES GENERIQUES ==========
    'Flue gas inlet at inlet temperature': 'Gaz de combustion à l\'entrée à température d\'entrée',
    'Air ingress at ambient temperature': 'Entrée d\'air à température ambiante',
    'Flue gas outlet at outlet temperature': 'Gaz de combustion à la sortie à température de sortie',
    'Input flue gas': 'Gaz de combustion d\'entrée',
    'Output flue gas': 'Gaz de combustion de sortie',

    // ========== CLÉS CRITIQUES - CHAMPS FORMULAIRE ==========
    'Flue gas temperature outlet [°C]': 'Température de sortie des gaz [°C]',
    'Ambient air temperature [°C]': 'Température de l\'air ambiant [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume d\'entrée d\'air [Nm3/h]',
    'Thermal losses [%]': 'Pertes thermiques [%]',
    'Cooling water temperature [°C]': 'Température de l\'eau de refroidissement [°C]',

    // ========== PARAMETRES AFFICHES ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Température d\'entrée QUENCH [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Température de sortie WATER INJECTION [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Eau pulvérisée/refroidissement [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume des gaz de sortie [Nm3/h]',

    // ========== MESSAGES DE VALIDATION ==========
    'Valeur invalide': 'Valeur invalide',
    'Veuillez entrer une valeur numérique': 'Veuillez entrer une valeur numérique',
    'Valeur hors limites': 'Valeur hors limites (0-10000)',

    // ========== PARAMETRES POLLUTANTS ==========
    'Fly ashes content [g/Nm3]': 'Teneur en cendres volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité des cendres de fond [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SOx reactif': 'Réactif SOx',
    'HCl reactif': 'Réactif HCl',
    'HF reactif': 'Réactif HF',
    'efficacite_SOx': 'Efficacité SOx [%]',
    'HCl efficacité': 'Efficacité HCl [%]',
    'HF efficacité': 'Efficacité HF [%]',
    'SOx stoechiométrie': 'Stoechiométrie SOx',
    'HCl stoechiométrie': 'Stoechiométrie HCl',
    'HF stoechiométrie': 'Stoechiométrie HF',
    'Pollutant': 'Polluant',
    'Reagent': 'Réactif',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Efficacité (%)',
    'Stoich. Coeff.': 'Coeff. Stoech.',
    'Output Mass': 'Masse de sortie',
    'Residue Mass': 'Masse de résidu',
    'Reagent Mass': 'Masse de réactif',
    'Abated Mass': 'Masse abattue',

    // ========== PARAMETRES DESIGN QUENCH ==========
    'Pertes de charge aéraulique': 'Pertes de charge aéraulique',
    'Pression aéraulique [mmCE]': 'Pression aéraulique [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Pression de sortie [mmCE]': 'Pression de sortie [mmCE]',
    'Dimensionnement du Quench': 'Dimensionnement du Quench',
    'Quench diameter [m]': 'Diamètre du Quench [m]',
    'Pression pulverisation [bar]': 'Pression de pulvérisation [bar]',
    'Type de buse': 'Type de buse',
    'Type d\'eau': 'Type d\'eau',
    'Consommation électrique de la pompe': 'Consommation électrique de la pompe',
    'Puissance pompe [kW]': 'Puissance pompe [kW]',
    'Rendement pompe [%]': 'Rendement pompe [%]',
    'Puissance pompe nominale [kW]': 'Puissance pompe nominale [kW]',
    'Consommation réelle [kW]': 'Consommation réelle [kW]',

    // ========== TYPES DE BUSES ==========
    'cone creux': 'Cône creux',
    'cone plein': 'Cône plein',
    'jet plat': 'Jet plat',
    'spirale': 'Spirale',
    'Distribution étroite, bon pour uniformité': 'Distribution étroite, bon pour l\'uniformité',
    'Distribution plus large, meilleure couverture': 'Distribution plus large, meilleure couverture',
    'Distribution large, bon pour surfaces': 'Distribution large, bon pour les surfaces',
    'Distribution très étroite, excellente atomisation': 'Distribution très étroite, excellente atomisation',

    // ========== TYPES D'EAU ==========
    'Eau potable': 'Eau potable',
    'Eau de refroidissement': 'Eau de refroidissement',
    'Eau déminéralisée': 'Eau déminéralisée',
    'Eau adoucie': 'Eau adoucie',
    'Eau de rivière': 'Eau de rivière',

    // ========== CARACTERISTIQUES SPRAY ==========
    'Résultats du Quench': 'Résultats du Quench',
    'Hauteur minimale du quench [m]': 'Hauteur minimale du Quench [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter Mean Diameter) [µm]',
    'Vitesse des gouttes [m/s]': 'Vitesse des gouttes [m/s]',
    'Angle du spray [°]': 'Angle du spray [°]',
    'Qualité du spray - Atomisation': 'Qualité du spray - Atomisation',
    'Qualité du spray - Uniformité': 'Qualité du spray - Uniformité',
    'Qualité du spray - Couverture': 'Qualité du spray - Couverture',
    'Type de buse - Description': 'Type de buse - Description',
    'Paramètre n (distribution)': 'Paramètre n (distribution)',
    'Taille moyenne des gouttes [µm]': 'Taille moyenne des gouttes [µm]',

    // ========== QUALITES SPRAY ==========
    'Excellente': 'Excellente',
    'Bonne': 'Bonne',
    'Moyenne': 'Moyenne',
    'Très uniforme': 'Très uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Moins uniforme',
    'Large couverture': 'Large couverture',
    'Couverture moyenne': 'Couverture moyenne',
    'Couverture concentrée': 'Couverture concentrée',

    // ========== CARACTERISTIQUES FLUE GAS ==========
    'Inlet temperature [K]': 'Température d\'entrée [K]',
    'Outlet temperature [K]': 'Température de sortie [K]',
    'Flue gas flow rate [m3/h]': 'Débit des gaz de combustion [m3/h]',
    'Water vapor in flue gas [m3/h]': 'Vapeur d\'eau dans les gaz de combustion [m3/h]',
    'Quench surface area [m2]': 'Surface du Quench [m2]',
    'Spray pressure [bar]': 'Pression du spray [bar]',
    'Débit eau [L/min]': 'Débit eau [L/min]',
    'Vitesse des gaz [m/s]': 'Vitesse des gaz [m/s]',
    'Prix de l\'eau [€/m³]': 'Prix de l\'eau [€/m³]',
    'Coût eau par heure [€/h]': 'Coût eau par heure [€/h]',

    // ========== RESIDUS ==========
    'Residus calculated': 'Résidus calculés',
    'Dry residus [kg/h]': 'Résidus secs [kg/h]',
    'Wet residus [kg/h]': 'Résidus humides [kg/h]',
    'Fly ash [kg/h]': 'Cendres volantes [kg/h]',
    'Bottom ash [kg/h]': 'Cendres de fond [kg/h]',
    'Bottom ash wet [kg/h]': 'Cendres de fond humides [kg/h]',
    'inert mass [kg/h]': 'Masse inerte [kg/h]',
    'Waste Flow [kg/h]': 'Débit de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit des gaz humides [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit des gaz secs [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',

    // ========== RESUME ==========
    'Diamètre quench': 'Diamètre du Quench',
    'Pression pulvérisation': 'Pression de pulvérisation',
    'Surface quench [m²]': 'Surface du Quench [m²]',
    'Hauteur quench [m]': 'Hauteur du Quench [m]',
    'Puissance pompe': 'Puissance de la pompe',
    'Consommation eau': 'Consommation d\'eau',
    'Surface des manches [m²]': 'Surface des manches [m²]',
    'Consommation air comprimé [Nm3/h]': 'Consommation air comprimé [Nm3/h]',
    'Pression air comprimé [Bar]': 'Pression air comprimé [Bar]',
    'Residus du BHF [kg/h]': 'Résidus du BHF [kg/h]',
    'CO2 transport total [kg]': 'CO2 transport total [kg]',
    'Coût transport total [€]': 'Coût transport total [€]',

    // ========== POMPE ET CONSOMMATION ==========
    'pompe quench': 'Pompe quench',
    'Nombre de cycles [Nb]': 'Nombre de cycles [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Air comprimé par cycle [Nm3/cycle]',
    'Conso élec air comprimé [kW]': 'Conso élec air comprimé [kW]',
    'conso elec vis de transport [kW]': 'Consommation électrique vis de transport [kW]',
  },

  en: {
    // ========== MAIN SECTIONS ==========
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Flue gas composition': 'Flue gas composition',
    'Pollutant Treatment Table': 'Pollutant Treatment Table',
    'Résultats': 'Results',
    'Résumé des paramètres principaux': 'Summary of main parameters',
    'Paramètres calculés détaillés': 'Detailed calculated parameters',

    // ========== BUTTONS ==========
    'Clear memory': 'Clear memory',
    'Reset to Default Values': 'Reset to Default Values',
    'Export': 'Export',

    // ========== GENERIC PARAMETERS ==========
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Air ingress at ambient temperature': 'Air ingress at ambient temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',

    // ========== CRITICAL KEYS - FORM FIELDS ==========
    'Flue gas temperature outlet [°C]': 'Flue gas temperature outlet [°C]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume of air ingress [Nm3/h]',
    'Thermal losses [%]': 'Thermal losses [%]',
    'Cooling water temperature [°C]': 'Cooling water temperature [°C]',

    // ========== DISPLAYED PARAMETERS ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Temperature inlet WATER_INJECTION [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Temperature outlet WATER_INJECTION [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprayed/cooling water [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Outlet flue gas volume [Nm3/h]',

    // ========== VALIDATION MESSAGES ==========
    'Valeur invalide': 'Invalid value',
    'Veuillez entrer une valeur numérique': 'Please enter a numeric value',
    'Valeur hors limites': 'Value out of range (0-10000)',

    // ========== POLLUTANTS PARAMETERS ==========
    'Fly ashes content [g/Nm3]': 'Fly ashes content [g/Nm3]',
    'siccity bottom ash [%]': 'Siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SOx reactif': 'SOx reactif',
    'HCl reactif': 'HCl reactif',
    'HF reactif': 'HF reactif',
    'efficacite_SOx': 'SOx efficiency [%]',
    'HCl efficacité': 'HCl efficiency [%]',
    'HF efficacité': 'HF efficiency [%]',
    'SOx stoechiométrie': 'SOx stoichiometry',
    'HCl stoechiométrie': 'HCl stoichiometry',
    'HF stoechiométrie': 'HF stoichiometry',
    'Pollutant': 'Pollutant',
    'Reagent': 'Reagent',
    'Mass (kg/h)': 'Mass (kg/h)',
    'Efficiency (%)': 'Efficiency (%)',
    'Stoich. Coeff.': 'Stoich. Coeff.',
    'Output Mass': 'Output Mass',
    'Residue Mass': 'Residue Mass',
    'Reagent Mass': 'Reagent Mass',
    'Abated Mass': 'Abated Mass',

    // ========== DESIGN PARAMETERS ==========
    'Pertes de charge aéraulique': 'Aeraulic pressure drop',
    'Pression aéraulique [mmCE]': 'Aeraulic pressure [mmCE]',
    'PDC [mmCE]': 'Pressure drop [mmCE]',
    'Pression de sortie [mmCE]': 'Outlet pressure [mmCE]',
    'Dimensionnement du Quench': 'Quench dimensioning',
    'Quench diameter [m]': 'Quench diameter [m]',
    'Pression pulverisation [bar]': 'Spray pressure [bar]',
    'Type de buse': 'Nozzle type',
    'Type d\'eau': 'Water type',
    'Consommation électrique de la pompe': 'Pump electrical consumption',
    'Puissance pompe [kW]': 'Pump power [kW]',
    'Rendement pompe [%]': 'Pump efficiency [%]',
    'Puissance pompe nominale [kW]': 'Nominal pump power [kW]',
    'Consommation réelle [kW]': 'Actual consumption [kW]',

    // ========== NOZZLE TYPES ==========
    'cone creux': 'Hollow cone',
    'cone plein': 'Full cone',
    'jet plat': 'Flat jet',
    'spirale': 'Spiral',
    'Distribution étroite, bon pour uniformité': 'Narrow distribution, good for uniformity',
    'Distribution plus large, meilleure couverture': 'Wider distribution, better coverage',
    'Distribution large, bon pour surfaces': 'Wide distribution, good for large surfaces',
    'Distribution très étroite, excellente atomisation': 'Very narrow distribution, excellent atomization',

    // ========== WATER TYPES ==========
    'Eau potable': 'Drinking water',
    'Eau de refroidissement': 'Cooling water',
    'Eau déminéralisée': 'Demineralized water',
    'Eau adoucie': 'Softened water',
    'Eau de rivière': 'River water',

    // ========== SPRAY CHARACTERISTICS ==========
    'Résultats du Quench': 'Quench Results',
    'Hauteur minimale du quench [m]': 'Minimum quench height [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter Mean Diameter) [µm]',
    'Vitesse des gouttes [m/s]': 'Droplet velocity [m/s]',
    'Angle du spray [°]': 'Spray angle [°]',
    'Qualité du spray - Atomisation': 'Spray quality - Atomization',
    'Qualité du spray - Uniformité': 'Spray quality - Uniformity',
    'Qualité du spray - Couverture': 'Spray quality - Coverage',
    'Type de buse - Description': 'Nozzle type - Description',
    'Paramètre n (distribution)': 'Parameter n (distribution)',
    'Taille moyenne des gouttes [µm]': 'Average droplet size [µm]',

    // ========== SPRAY QUALITIES ==========
    'Excellente': 'Excellent',
    'Bonne': 'Good',
    'Moyenne': 'Average',
    'Très uniforme': 'Very uniform',
    'Uniforme': 'Uniform',
    'Moins uniforme': 'Less uniform',
    'Large couverture': 'Wide coverage',
    'Couverture moyenne': 'Average coverage',
    'Couverture concentrée': 'Concentrated coverage',

    // ========== FLUE GAS CHARACTERISTICS ==========
    'Inlet temperature [K]': 'Inlet temperature [K]',
    'Outlet temperature [K]': 'Outlet temperature [K]',
    'Flue gas flow rate [m3/h]': 'Flue gas flow rate [m3/h]',
    'Water vapor in flue gas [m3/h]': 'Water vapor in flue gas [m3/h]',
    'Quench surface area [m2]': 'Quench surface area [m2]',
    'Spray pressure [bar]': 'Spray pressure [bar]',
    'Débit eau [L/min]': 'Water flow [L/min]',
    'Vitesse des gaz [m/s]': 'Gas velocity [m/s]',
    'Prix de l\'eau [€/m³]': 'Water price [€/m³]',
    'Coût eau par heure [€/h]': 'Water cost per hour [€/h]',

    // ========== RESIDUES ==========
    'Residus calculated': 'Residues calculated',
    'Dry residus [kg/h]': 'Dry residues [kg/h]',
    'Wet residus [kg/h]': 'Wet residues [kg/h]',
    'Fly ash [kg/h]': 'Fly ash [kg/h]',
    'Bottom ash [kg/h]': 'Bottom ash [kg/h]',
    'Bottom ash wet [kg/h]': 'Wet bottom ash [kg/h]',
    'inert mass [kg/h]': 'Inert mass [kg/h]',
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Wet flue gas flow [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Dry flue gas flow [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',

    // ========== SUMMARY ==========
    'Diamètre quench': 'Quench diameter',
    'Pression pulvérisation': 'Spray pressure',
    'Surface quench [m²]': 'Quench surface [m²]',
    'Hauteur quench [m]': 'Quench height [m]',
    'Puissance pompe': 'Pump power',
    'Consommation eau': 'Water consumption',
    'Surface des manches [m²]': 'Sleeve surface [m²]',
    'Consommation air comprimé [Nm3/h]': 'Compressed air consumption [Nm3/h]',
    'Pression air comprimé [Bar]': 'Compressed air pressure [Bar]',
    'Residus du BHF [kg/h]': 'BHF residues [kg/h]',
    'CO2 transport total [kg]': 'Total transport CO2 [kg]',
    'Coût transport total [€]': 'Total transport cost [€]',

    // ========== PUMP AND CONSUMPTION ==========
    'pompe quench': 'Quench pump',
    'Nombre de cycles [Nb]': 'Number of cycles [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Compressed air per cycle [Nm3/cycle]',
    'Conso élec air comprimé [kW]': 'Compressed air electrical consumption [kW]',
    'conso elec vis de transport [kW]': 'Transport screw electrical consumption [kW]',
  },


  de: {
    // ========== HAUPTABSCHNITTE ==========
    'Calculation parameters': 'Berechnungsparameter',
    'Calculated parameters': 'Berechnete Parameter',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Quench Configuration': 'QUENCH-Konfiguration',
    'Back to Flow': 'Zurück zum Fluss',
    'Flue gases': 'Rauchgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Design': 'Design',
    'Opex': 'Opex',
    'Pollutant Treatment Table': 'Schadstoffbehandlungstabelle',
    'Résultats': 'Ergebnisse',
    'Résumé des paramètres principaux': 'Zusammenfassung der Hauptparameter',
    'Paramètres calculés détaillés': 'Detaillierte berechnete Parameter',

    // ========== SCHALTFLÄCHEN ==========
    'Clear memory': 'Speicher löschen',
    'Reset to Default Values': 'Auf Standardwerte zurücksetzen',
    'Export': 'Exportieren',

    // ========== GENERISCHE PARAMETER ==========
    'Flue gas inlet at inlet temperature': 'Rauchgaseintritt bei Eintrittstemperatur',
    'Air ingress at ambient temperature': 'Lufteintritt bei Umgebungstemperatur',
    'Flue gas outlet at outlet temperature': 'Rauchgasaustritt bei Austrittstemperatur',
    'Input flue gas': 'Eingangsrauchgas',
    'Output flue gas': 'Ausgangsrauchgas',

    // ========== KRITISCHE SCHLÜSSEL - FORMULAREINGABEN ==========
    'Flue gas temperature outlet [°C]': 'Rauchgasaustrittstemperatur [°C]',
    'Ambient air temperature [°C]': 'Umgebungslufttemperatur [°C]',
    'Volume of air ingress [Nm3/h]': 'Lufteinlassvolumen [Nm³/h]',
    'Thermal losses [%]': 'Wärmeverluste [%]',
    'Cooling water temperature [°C]': 'Kühlwassertemperatur [°C]',

    // ========== ANGEZEIGTE PARAMETER ==========
    'Temperature inlet WATER_INJECTION [°C]': 'WATER INJECTION-Eintrittstemperatur [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'WATER INJECTION-Austrittstemperatur [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta-Enthalpien [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprühwasser/Kühlwasser [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Rauchgasaustrittsvolumen [Nm³/h]',

    // ========== VALIDIERUNGSMELDUNGEN ==========
    'Valeur invalide': 'Ungültiger Wert',
    'Veuillez entrer une valeur numérique': 'Bitte geben Sie einen numerischen Wert ein',
    'Valeur hors limites': 'Wert außerhalb des Bereichs (0-10000)',

    // ========== SCHADSTOFFPARAMETER ==========
    'Fly ashes content [g/Nm3]': 'Flugaschegehalt [g/Nm³]',
    'siccity bottom ash [%]': 'Trockengehalt der Bodenasche [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SOx reactif': 'SOx-Reaktionsmittel',
    'HCl reactif': 'HCl-Reaktionsmittel',
    'HF reactif': 'HF-Reaktionsmittel',
    'efficacite_SOx': 'SOx-Effizienz [%]',
    'HCl efficacité': 'HCl-Effizienz [%]',
    'HF efficacité': 'HF-Effizienz [%]',
    'SOx stoechiométrie': 'SOx-Stöchiometrie',
    'HCl stoechiométrie': 'HCl-Stöchiometrie',
    'HF stoechiométrie': 'HF-Stöchiometrie',
    'Pollutant': 'Schadstoff',
    'Reagent': 'Reaktionsmittel',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Effizienz (%)',
    'Stoich. Coeff.': 'Stoich. Koeff.',
    'Output Mass': 'Ausgangsmasse',
    'Residue Mass': 'Rückstandsmasse',
    'Reagent Mass': 'Reaktionsmittelmasse',
    'Abated Mass': 'Reduzierte Masse',

    // ========== QUENCH-DESIGNPARAMETER ==========
    'Pertes de charge aéraulique': 'Aerodynamischer Druckabfall',
    'Pression aéraulique [mmCE]': 'Aerodynamischer Druck [mmCE]',
    'PDC [mmCE]': 'Druckabfall [mmCE]',
    'Pression de sortie [mmCE]': 'Auslassdruck [mmCE]',
    'Dimensionnement du Quench': 'QUENCH-Dimensionierung',
    'Quench diameter [m]': 'QUENCH-Durchmesser [m]',
    'Pression pulverisation [bar]': 'Sprühdrück [bar]',
    'Type de buse': 'Düsentyp',
    'Type d\'eau': 'Wassertyp',
    'Consommation électrique de la pompe': 'Stromverbrauch der Pumpe',
    'Puissance pompe [kW]': 'Pumpenleistung [kW]',
    'Rendement pompe [%]': 'Pumpenwirkungsgrad [%]',
    'Puissance pompe nominale [kW]': 'Nennpumpenleistung [kW]',
    'Consommation réelle [kW]': 'Tatsächlicher Verbrauch [kW]',

    // ========== DÜSENTYPEN ==========
    'cone creux': 'Hohlkegel',
    'cone plein': 'Vollkegel',
    'jet plat': 'Flachstrahl',
    'spirale': 'Spirale',
    'Distribution étroite, bon pour uniformité': 'Enge Verteilung, gut für Gleichmäßigkeit',
    'Distribution plus large, meilleure couverture': 'Breitere Verteilung, bessere Abdeckung',
    'Distribution large, bon pour surfaces': 'Breite Verteilung, gut für Oberflächen',
    'Distribution très étroite, excellente atomisation': 'Sehr enge Verteilung, hervorragende Zerstäubung',

    // ========== WASSERTYPEN ==========
    'Eau potable': 'Trinkwasser',
    'Eau de refroidissement': 'Kühlwasser',
    'Eau déminéralisée': 'Demineralisiertes Wasser',
    'Eau adoucie': 'Enthärtetes Wasser',
    'Eau de rivière': 'Flusswasser',

    // ========== SPRAYMERKALE ==========
    'Résultats du Quench': 'QUENCH-Ergebnisse',
    'Hauteur minimale du quench [m]': 'Minimale QUENCH-Höhe [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter Mean Diameter) [µm]',
    'Vitesse des gouttes [m/s]': 'Tropfengeschwindigkeit [m/s]',
    'Angle du spray [°]': 'Sprühwinkel [°]',
    'Qualité du spray - Atomisation': 'Sprühqualität - Zerstäubung',
    'Qualité du spray - Uniformité': 'Sprühqualität - Gleichmäßigkeit',
    'Qualité du spray - Couverture': 'Sprühqualität - Abdeckung',
    'Type de buse - Description': 'Düsentyp - Beschreibung',
    'Paramètre n (distribution)': 'Parameter n (Verteilung)',
    'Taille moyenne des gouttes [µm]': 'Mittlere Tropfengröße [µm]',

    // ========== SPRÜHQUALITÄTEN ==========
    'Excellente': 'Hervorragend',
    'Bonne': 'Gut',
    'Moyenne': 'Durchschnittlich',
    'Très uniforme': 'Sehr gleichmäßig',
    'Uniforme': 'Gleichmäßig',
    'Moins uniforme': 'Weniger gleichmäßig',
    'Large couverture': 'Breite Abdeckung',
    'Couverture moyenne': 'Mittlere Abdeckung',
    'Couverture concentrée': 'Konzentrierte Abdeckung',

    // ========== RAUCHGASMERKALE ==========
    'Inlet temperature [K]': 'Eintrittstemperatur [K]',
    'Outlet temperature [K]': 'Austrittstemperatur [K]',
    'Flue gas flow rate [m3/h]': 'Rauchgasdurchsatz [m³/h]',
    'Water vapor in flue gas [m3/h]': 'Wasserdampf in Rauchgas [m³/h]',
    'Quench surface area [m2]': 'QUENCH-Oberfläche [m²]',
    'Spray pressure [bar]': 'Sprühdruck [bar]',
    'Débit eau [L/min]': 'Wasserdurchfluss [L/min]',
    'Vitesse des gaz [m/s]': 'Gasgeschwindigkeit [m/s]',
    'Prix de l\'eau [€/m³]': 'Wasserpreis [€/m³]',
    'Coût eau par heure [€/h]': 'Wasserkosten pro Stunde [€/h]',

    // ========== RÜCKSTÄNDE ==========
    'Residus calculated': 'Berechnete Rückstände',
    'Dry residus [kg/h]': 'Trockene Rückstände [kg/h]',
    'Wet residus [kg/h]': 'Nasse Rückstände [kg/h]',
    'Fly ash [kg/h]': 'Flugasche [kg/h]',
    'Bottom ash [kg/h]': 'Bodenasche [kg/h]',
    'Bottom ash wet [kg/h]': 'Feuchte Bodenasche [kg/h]',
    'inert mass [kg/h]': 'Inerte Masse [kg/h]',
    'Waste Flow [kg/h]': 'Abfallstrom [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Feuchter Rauchgasstrom [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Trockener Rauchgasstrom [Nm³/h]',
    'O2 calculated [%]': 'Berechnetes O2 [%]',

    // ========== ZUSAMMENFASSUNG ==========
    'Diamètre quench': 'QUENCH-Durchmesser',
    'Pression pulvérisation': 'Sprühdruck',
    'Surface quench [m²]': 'QUENCH-Oberfläche [m²]',
    'Hauteur quench [m]': 'QUENCH-Höhe [m]',
    'Puissance pompe': 'Pumpenleistung',
    'Consommation eau': 'Wasserverbrauch',
    'Surface des manches [m²]': 'Schlauchfläche [m²]',
    'Consommation air comprimé [Nm3/h]': 'Druckluftverbrauch [Nm³/h]',
    'Pression air comprimé [Bar]': 'Drucklufttdruck [Bar]',
    'Residus du BHF [kg/h]': 'BHF-Rückstände [kg/h]',
    'CO2 transport total [kg]': 'Gesamt-CO2-Transport [kg]',
    'Coût transport total [€]': 'Gesamttransportkosten [€]',

    // ========== PUMPE UND VERBRAUCH ==========
    'pompe quench': 'QUENCH-Pumpe',
    'Nombre de cycles [Nb]': 'Anzahl der Zyklen [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Druckluft pro Zyklus [Nm³/Zyklus]',
    'Conso élec air comprimé [kW]': 'Stromverbrauch Druckluft [kW]',
    'conso elec vis de transport [kW]': 'Stromverbrauch Transportschraube [kW]',
  },

  it: {
    // ========== SEZIONI PRINCIPALI ==========
    'Calculation parameters': 'Parametri di calcolo',
    'Calculated parameters': 'Parametri calcolati',
    'Flue gas composition': 'Composizione dei gas di combustione',
    'Quench Configuration': 'Configurazione QUENCH',
    'Back to Flow': 'Torna al flusso',
    'Flue gases': 'Gas di combustione',
    'Pollutant Emissions': 'Emissioni di inquinanti',
    'Design': 'Progettazione',
    'Opex': 'Opex',
    'Pollutant Treatment Table': 'Tabella trattamento inquinanti',
    'Résultats': 'Risultati',
    'Résumé des paramètres principaux': 'Riassunto dei parametri principali',
    'Paramètres calculés détaillés': 'Parametri calcolati dettagliati',

    // ========== PULSANTI ==========
    'Clear memory': 'Cancella memoria',
    'Reset to Default Values': 'Ripristina valori predefiniti',
    'Export': 'Esporta',

    // ========== PARAMETRI GENERICI ==========
    'Flue gas inlet at inlet temperature': 'Ingresso gas di combustione a temperatura di ingresso',
    'Air ingress at ambient temperature': 'Ingresso aria a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Uscita gas di combustione a temperatura di uscita',
    'Input flue gas': 'Gas di combustione in ingresso',
    'Output flue gas': 'Gas di combustione in uscita',

    // ========== CHIAVI CRITICHE - CAMPI MODULO ==========
    'Flue gas temperature outlet [°C]': 'Temperatura uscita gas di combustione [°C]',
    'Ambient air temperature [°C]': 'Temperatura aria ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume ingresso aria [Nm³/h]',
    'Thermal losses [%]': 'Perdite termiche [%]',
    'Cooling water temperature [°C]': 'Temperatura acqua di raffreddamento [°C]',

    // ========== PARAMETRI VISUALIZZATI ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Temperatura ingresso WATER INJECTION [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Temperatura uscita WATER INJECTION [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpie [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Acqua nebulizzata/raffreddamento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gas di combustione in uscita [Nm³/h]',

    // ========== MESSAGGI DI VALIDAZIONE ==========
    'Valeur invalide': 'Valore non valido',
    'Veuillez entrer une valeur numérique': 'Si prega di immettere un valore numerico',
    'Valeur hors limites': 'Valore fuori intervallo (0-10000)',

    // ========== PARAMETRI INQUINANTI ==========
    'Fly ashes content [g/Nm3]': 'Contenuto ceneri volanti [g/Nm³]',
    'siccity bottom ash [%]': 'Secchezza ceneri sul fondo [%]',
    'O2 ref [%]': 'O2 rif [%]',
    'SOx reactif': 'Reattivo SOx',
    'HCl reactif': 'Reattivo HCl',
    'HF reactif': 'Reattivo HF',
    'efficacite_SOx': 'Efficienza SOx [%]',
    'HCl efficacité': 'Efficienza HCl [%]',
    'HF efficacité': 'Efficienza HF [%]',
    'SOx stoechiométrie': 'Stechiometria SOx',
    'HCl stoechiométrie': 'Stechiometria HCl',
    'HF stoechiométrie': 'Stechiometria HF',
    'Pollutant': 'Inquinante',
    'Reagent': 'Reattivo',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Efficienza (%)',
    'Stoich. Coeff.': 'Coeff. Stechim.',
    'Output Mass': 'Massa in uscita',
    'Residue Mass': 'Massa residua',
    'Reagent Mass': 'Massa reattivo',
    'Abated Mass': 'Massa ridotta',

    // ========== PARAMETRI PROGETTAZIONE QUENCH ==========
    'Pertes de charge aéraulique': 'Perdita di carico aerodinamica',
    'Pression aéraulique [mmCE]': 'Pressione aerodinamica [mmCE]',
    'PDC [mmCE]': 'Perdita carico [mmCE]',
    'Pression de sortie [mmCE]': 'Pressione uscita [mmCE]',
    'Dimensionnement du Quench': 'Dimensionamento QUENCH',
    'Quench diameter [m]': 'Diametro QUENCH [m]',
    'Pression pulverisation [bar]': 'Pressione nebulizzazione [bar]',
    'Type de buse': 'Tipo ugello',
    'Type d\'eau': 'Tipo acqua',
    'Consommation électrique de la pompe': 'Consumo elettrico pompa',
    'Puissance pompe [kW]': 'Potenza pompa [kW]',
    'Rendement pompe [%]': 'Rendimento pompa [%]',
    'Puissance pompe nominale [kW]': 'Potenza pompa nominale [kW]',
    'Consommation réelle [kW]': 'Consumo effettivo [kW]',

    // ========== TIPI DI UGELLI ==========
    'cone creux': 'Cono cavo',
    'cone plein': 'Cono pieno',
    'jet plat': 'Getto piatto',
    'spirale': 'Spirale',
    'Distribution étroite, bon pour uniformité': 'Distribuzione stretta, buona per uniformità',
    'Distribution plus large, meilleure couverture': 'Distribuzione più ampia, migliore copertura',
    'Distribution large, bon pour surfaces': 'Distribuzione ampia, buona per superfici',
    'Distribution très étroite, excellente atomisation': 'Distribuzione molto stretta, eccellente atomizzazione',

    // ========== TIPI DI ACQUA ==========
    'Eau potable': 'Acqua potabile',
    'Eau de refroidissement': 'Acqua di raffreddamento',
    'Eau déminéralisée': 'Acqua demineralizzata',
    'Eau adoucie': 'Acqua addolcita',
    'Eau de rivière': 'Acqua di fiume',

    // ========== CARATTERISTICHE SPRAY ==========
    'Résultats du Quench': 'Risultati QUENCH',
    'Hauteur minimale du quench [m]': 'Altezza minima QUENCH [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter Mean Diameter) [µm]',
    'Vitesse des gouttes [m/s]': 'Velocità goccioline [m/s]',
    'Angle du spray [°]': 'Angolo spray [°]',
    'Qualité du spray - Atomisation': 'Qualità spray - Atomizzazione',
    'Qualité du spray - Uniformité': 'Qualità spray - Uniformità',
    'Qualité du spray - Couverture': 'Qualità spray - Copertura',
    'Type de buse - Description': 'Tipo ugello - Descrizione',
    'Paramètre n (distribution)': 'Parametro n (distribuzione)',
    'Taille moyenne des gouttes [µm]': 'Dimensione media goccioline [µm]',

    // ========== QUALITÀ SPRAY ==========
    'Excellente': 'Eccellente',
    'Bonne': 'Buona',
    'Moyenne': 'Media',
    'Très uniforme': 'Molto uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Meno uniforme',
    'Large couverture': 'Copertura ampia',
    'Couverture moyenne': 'Copertura media',
    'Couverture concentrée': 'Copertura concentrata',

    // ========== CARATTERISTICHE GAS DI COMBUSTIONE ==========
    'Inlet temperature [K]': 'Temperatura ingresso [K]',
    'Outlet temperature [K]': 'Temperatura uscita [K]',
    'Flue gas flow rate [m3/h]': 'Portata gas di combustione [m³/h]',
    'Water vapor in flue gas [m3/h]': 'Vapore acqueo in gas di combustione [m³/h]',
    'Quench surface area [m2]': 'Area superficiale QUENCH [m²]',
    'Spray pressure [bar]': 'Pressione spray [bar]',
    'Débit eau [L/min]': 'Portata acqua [L/min]',
    'Vitesse des gaz [m/s]': 'Velocità gas [m/s]',
    'Prix de l\'eau [€/m³]': 'Prezzo acqua [€/m³]',
    'Coût eau par heure [€/h]': 'Costo acqua per ora [€/h]',

    // ========== RESIDUI ==========
    'Residus calculated': 'Residui calcolati',
    'Dry residus [kg/h]': 'Residui secchi [kg/h]',
    'Wet residus [kg/h]': 'Residui umidi [kg/h]',
    'Fly ash [kg/h]': 'Ceneri volanti [kg/h]',
    'Bottom ash [kg/h]': 'Ceneri sul fondo [kg/h]',
    'Bottom ash wet [kg/h]': 'Ceneri sul fondo umide [kg/h]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Waste Flow [kg/h]': 'Flusso rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flusso gas umido [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flusso gas secco [Nm³/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',

    // ========== RIEPILOGO ==========
    'Diamètre quench': 'Diametro QUENCH',
    'Pression pulvérisation': 'Pressione nebulizzazione',
    'Surface quench [m²]': 'Area superficiale QUENCH [m²]',
    'Hauteur quench [m]': 'Altezza QUENCH [m]',
    'Puissance pompe': 'Potenza pompa',
    'Consommation eau': 'Consumo acqua',
    'Surface des manches [m²]': 'Area manica [m²]',
    'Consommation air comprimé [Nm3/h]': 'Consumo aria compressa [Nm³/h]',
    'Pression air comprimé [Bar]': 'Pressione aria compressa [Bar]',
    'Residus du BHF [kg/h]': 'Residui BHF [kg/h]',
    'CO2 transport total [kg]': 'Totale CO2 trasporto [kg]',
    'Coût transport total [€]': 'Costo totale trasporto [€]',

    // ========== POMPA E CONSUMO ==========
    'pompe quench': 'Pompa QUENCH',
    'Nombre de cycles [Nb]': 'Numero cicli [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Aria compressa per ciclo [Nm³/ciclo]',
    'Conso élec air comprimé [kW]': 'Consumo elettrico aria compressa [kW]',
    'conso elec vis de transport [kW]': 'Consumo elettrico coclea di trasporto [kW]',
  },

  pt: {
    // ========== SEÇÕES PRINCIPAIS ==========
    'Calculation parameters': 'Parâmetros de cálculo',
    'Calculated parameters': 'Parâmetros calculados',
    'Flue gas composition': 'Composição dos gases de combustão',
    'Quench Configuration': 'Configuração QUENCH',
    'Back to Flow': 'Voltar ao fluxo',
    'Flue gases': 'Gases de combustão',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Design': 'Projeto',
    'Opex': 'Opex',
    'Pollutant Treatment Table': 'Tabela de tratamento de poluentes',
    'Résultats': 'Resultados',
    'Résumé des paramètres principaux': 'Resumo dos parâmetros principais',
    'Paramètres calculés détaillés': 'Parâmetros calculados detalhados',

    // ========== BOTÕES ==========
    'Clear memory': 'Limpar memória',
    'Reset to Default Values': 'Restaurar valores padrão',
    'Export': 'Exportar',

    // ========== PARÂMETROS GENÉRICOS ==========
    'Flue gas inlet at inlet temperature': 'Entrada de gás de combustão na temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de ar na temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Saída de gás de combustão na temperatura de saída',
    'Input flue gas': 'Gás de combustão de entrada',
    'Output flue gas': 'Gás de combustão de saída',

    // ========== CHAVES CRÍTICAS - CAMPOS DE FORMULÁRIO ==========
    'Flue gas temperature outlet [°C]': 'Temperatura de saída dos gases [°C]',
    'Ambient air temperature [°C]': 'Temperatura do ar ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume de entrada de ar [Nm³/h]',
    'Thermal losses [%]': 'Perdas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura da água de arrefecimento [°C]',

    // ========== PARÂMETROS EXIBIDOS ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Temperatura de entrada WATER INJECTION [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Temperatura de saída WATER INJECTION [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpias [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Água pulverizada/arrefecimento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume de gás de saída [Nm³/h]',

    // ========== MENSAGENS DE VALIDAÇÃO ==========
    'Valeur invalide': 'Valor inválido',
    'Veuillez entrer une valeur numérique': 'Por favor, insira um valor numérico',
    'Valeur hors limites': 'Valor fora do intervalo (0-10000)',

    // ========== PARÂMETROS DE POLUENTES ==========
    'Fly ashes content [g/Nm3]': 'Teor de cinzas volantes [g/Nm³]',
    'siccity bottom ash [%]': 'Secura de cinzas do fundo [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SOx reactif': 'Reagente SOx',
    'HCl reactif': 'Reagente HCl',
    'HF reactif': 'Reagente HF',
    'efficacite_SOx': 'Eficiência SOx [%]',
    'HCl efficacité': 'Eficiência HCl [%]',
    'HF efficacité': 'Eficiência HF [%]',
    'SOx stoechiométrie': 'Estequiometria SOx',
    'HCl stoechiométrie': 'Estequiometria HCl',
    'HF stoechiométrie': 'Estequiometria HF',
    'Pollutant': 'Poluente',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Eficiência (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Massa de saída',
    'Residue Mass': 'Massa de resíduos',
    'Reagent Mass': 'Massa do reagente',
    'Abated Mass': 'Massa reduzida',

    // ========== PARÂMETROS DE PROJETO QUENCH ==========
    'Pertes de charge aéraulique': 'Queda de pressão aerodinâmica',
    'Pression aéraulique [mmCE]': 'Pressão aerodinâmica [mmCE]',
    'PDC [mmCE]': 'Queda de pressão [mmCE]',
    'Pression de sortie [mmCE]': 'Pressão de saída [mmCE]',
    'Dimensionnement du Quench': 'Dimensionamento do QUENCH',
    'Quench diameter [m]': 'Diâmetro QUENCH [m]',
    'Pression pulverisation [bar]': 'Pressão de pulverização [bar]',
    'Type de buse': 'Tipo de bocal',
    'Type d\'eau': 'Tipo de água',
    'Consommation électrique de la pompe': 'Consumo elétrico da bomba',
    'Puissance pompe [kW]': 'Potência da bomba [kW]',
    'Rendement pompe [%]': 'Eficiência da bomba [%]',
    'Puissance pompe nominale [kW]': 'Potência nominal da bomba [kW]',
    'Consommation réelle [kW]': 'Consumo real [kW]',

    // ========== TIPOS DE BOCAIS ==========
    'cone creux': 'Cone oco',
    'cone plein': 'Cone cheio',
    'jet plat': 'Jato plano',
    'spirale': 'Espiral',
    'Distribution étroite, bon pour uniformité': 'Distribuição estreita, boa para uniformidade',
    'Distribution plus large, meilleure couverture': 'Distribuição mais ampla, melhor cobertura',
    'Distribution large, bon pour surfaces': 'Distribuição ampla, boa para superfícies',
    'Distribution très étroite, excellente atomisation': 'Distribuição muito estreita, excelente atomização',

    // ========== TIPOS DE ÁGUA ==========
    'Eau potable': 'Água potável',
    'Eau de refroidissement': 'Água de arrefecimento',
    'Eau déminéralisée': 'Água desmineralizada',
    'Eau adoucie': 'Água amolecida',
    'Eau de rivière': 'Água de rio',

    // ========== CARACTERÍSTICAS DO SPRAY ==========
    'Résultats du Quench': 'Resultados QUENCH',
    'Hauteur minimale du quench [m]': 'Altura mínima QUENCH [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter Mean Diameter) [µm]',
    'Vitesse des gouttes [m/s]': 'Velocidade das gotículas [m/s]',
    'Angle du spray [°]': 'Ângulo do spray [°]',
    'Qualité du spray - Atomisation': 'Qualidade do spray - Atomização',
    'Qualité du spray - Uniformité': 'Qualidade do spray - Uniformidade',
    'Qualité du spray - Couverture': 'Qualidade do spray - Cobertura',
    'Type de buse - Description': 'Tipo de bocal - Descrição',
    'Paramètre n (distribution)': 'Parâmetro n (distribuição)',
    'Taille moyenne des gouttes [µm]': 'Tamanho médio das gotículas [µm]',

    // ========== QUALIDADES DO SPRAY ==========
    'Excellente': 'Excelente',
    'Bonne': 'Boa',
    'Moyenne': 'Média',
    'Très uniforme': 'Muito uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Menos uniforme',
    'Large couverture': 'Cobertura ampla',
    'Couverture moyenne': 'Cobertura média',
    'Couverture concentrée': 'Cobertura concentrada',

    // ========== CARACTERÍSTICAS DOS GASES DE COMBUSTÃO ==========
    'Inlet temperature [K]': 'Temperatura de entrada [K]',
    'Outlet temperature [K]': 'Temperatura de saída [K]',
    'Flue gas flow rate [m3/h]': 'Taxa de fluxo de gás de combustão [m³/h]',
    'Water vapor in flue gas [m3/h]': 'Vapor de água em gás de combustão [m³/h]',
    'Quench surface area [m2]': 'Área de superfície QUENCH [m²]',
    'Spray pressure [bar]': 'Pressão do spray [bar]',
    'Débit eau [L/min]': 'Fluxo de água [L/min]',
    'Vitesse des gaz [m/s]': 'Velocidade do gás [m/s]',
    'Prix de l\'eau [€/m³]': 'Preço da água [€/m³]',
    'Coût eau par heure [€/h]': 'Custo da água por hora [€/h]',

    // ========== RESÍDUOS ==========
    'Residus calculated': 'Resíduos calculados',
    'Dry residus [kg/h]': 'Resíduos secos [kg/h]',
    'Wet residus [kg/h]': 'Resíduos úmidos [kg/h]',
    'Fly ash [kg/h]': 'Cinzas volantes [kg/h]',
    'Bottom ash [kg/h]': 'Cinzas do fundo [kg/h]',
    'Bottom ash wet [kg/h]': 'Cinzas do fundo úmidas [kg/h]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Waste Flow [kg/h]': 'Fluxo de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Fluxo de gás úmido [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Fluxo de gás seco [Nm³/h]',
    'O2 calculated [%]': 'O2 calculado [%]',

    // ========== RESUMO ==========
    'Diamètre quench': 'Diâmetro QUENCH',
    'Pression pulvérisation': 'Pressão de pulverização',
    'Surface quench [m²]': 'Área de superfície QUENCH [m²]',
    'Hauteur quench [m]': 'Altura QUENCH [m]',
    'Puissance pompe': 'Potência da bomba',
    'Consommation eau': 'Consumo de água',
    'Surface des manches [m²]': 'Área da manga [m²]',
    'Consommation air comprimé [Nm3/h]': 'Consumo de ar comprimido [Nm³/h]',
    'Pression air comprimé [Bar]': 'Pressão de ar comprimido [Bar]',
    'Residus du BHF [kg/h]': 'Resíduos BHF [kg/h]',
    'CO2 transport total [kg]': 'Total CO2 transporte [kg]',
    'Coût transport total [€]': 'Custo total de transporte [€]',

    // ========== BOMBA E CONSUMO ==========
    'pompe quench': 'Bomba QUENCH',
    'Nombre de cycles [Nb]': 'Número de ciclos [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Ar comprimido por ciclo [Nm³/ciclo]',
    'Conso élec air comprimé [kW]': 'Consumo elétrico de ar comprimido [kW]',
    'conso elec vis de transport [kW]': 'Consumo elétrico do parafuso de transporte [kW]',
  },

  es: {
    // ========== SECCIONES PRINCIPALES ==========
    'Calculation parameters': 'Parámetros de cálculo',
    'Calculated parameters': 'Parámetros calculados',
    'Flue gas composition': 'Composición de gases de combustión',
    'Quench Configuration': 'Configuración QUENCH',
    'Back to Flow': 'Volver al flujo',
    'Flue gases': 'Gases de combustión',
    'Pollutant Emissions': 'Emisiones de contaminantes',
    'Design': 'Diseño',
    'Opex': 'Opex',
    'Pollutant Treatment Table': 'Tabla de tratamiento de contaminantes',
    'Résultats': 'Resultados',
    'Résumé des paramètres principaux': 'Resumen de parámetros principales',
    'Paramètres calculés détaillés': 'Parámetros calculados detallados',

    // ========== BOTONES ==========
    'Clear memory': 'Borrar memoria',
    'Reset to Default Values': 'Restaurar valores predeterminados',
    'Export': 'Exportar',

    // ========== PARÁMETROS GENÉRICOS ==========
    'Flue gas inlet at inlet temperature': 'Entrada de gas de combustión a temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de aire a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Salida de gas de combustión a temperatura de salida',
    'Input flue gas': 'Gas de combustión de entrada',
    'Output flue gas': 'Gas de combustión de salida',

    // ========== CLAVES CRÍTICAS - CAMPOS DE FORMULARIO ==========
    'Flue gas temperature outlet [°C]': 'Temperatura de salida de gases [°C]',
    'Ambient air temperature [°C]': 'Temperatura del aire ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volumen de entrada de aire [Nm³/h]',
    'Thermal losses [%]': 'Pérdidas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura del agua de enfriamiento [°C]',

    // ========== PARÁMETROS MOSTRADOS ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Temperatura de entrada WATER INJECTION [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Temperatura de salida QUENCH [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta entalpías [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Agua pulverizada/enfriamiento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volumen de gas de salida [Nm³/h]',

    // ========== MENSAJES DE VALIDACIÓN ==========
    'Valeur invalide': 'Valor inválido',
    'Veuillez entrer une valeur numérique': 'Por favor, ingrese un valor numérico',
    'Valeur hors limites': 'Valor fuera de rango (0-10000)',

    // ========== PARÁMETROS DE CONTAMINANTES ==========
    'Fly ashes content [g/Nm3]': 'Contenido de cenizas volantes [g/Nm³]',
    'siccity bottom ash [%]': 'Sequedad de cenizas del fondo [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'SOx reactif': 'Reactivo SOx',
    'HCl reactif': 'Reactivo HCl',
    'HF reactif': 'Reactivo HF',
    'efficacite_SOx': 'Eficiencia SOx [%]',
    'HCl efficacité': 'Eficiencia HCl [%]',
    'HF efficacité': 'Eficiencia HF [%]',
    'SOx stoechiométrie': 'Estequiometría SOx',
    'HCl stoechiométrie': 'Estequiometría HCl',
    'HF stoechiométrie': 'Estequiometría HF',
    'Pollutant': 'Contaminante',
    'Reagent': 'Reactivo',
    'Mass (kg/h)': 'Masa (kg/h)',
    'Efficiency (%)': 'Eficiencia (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Masa de salida',
    'Residue Mass': 'Masa de residuos',
    'Reagent Mass': 'Masa del reactivo',
    'Abated Mass': 'Masa reducida',

    // ========== PARÁMETROS DE DISEÑO QUENCH ==========
    'Pertes de charge aéraulique': 'Caída de presión aerodinámica',
    'Pression aéraulique [mmCE]': 'Presión aerodinámica [mmCE]',
    'PDC [mmCE]': 'Caída de presión [mmCE]',
    'Pression de sortie [mmCE]': 'Presión de salida [mmCE]',
    'Dimensionnement du Quench': 'Dimensionamiento de QUENCH',
    'Quench diameter [m]': 'Diámetro QUENCH [m]',
    'Pression pulverisation [bar]': 'Presión de pulverización [bar]',
    'Type de buse': 'Tipo de boquilla',
    'Type d\'eau': 'Tipo de agua',
    'Consommation électrique de la pompe': 'Consumo eléctrico de la bomba',
    'Puissance pompe [kW]': 'Potencia de la bomba [kW]',
    'Rendement pompe [%]': 'Eficiencia de la bomba [%]',
    'Puissance pompe nominale [kW]': 'Potencia nominal de la bomba [kW]',
    'Consommation réelle [kW]': 'Consumo real [kW]',

    // ========== TIPOS DE BOQUILLAS ==========
    'cone creux': 'Cono hueco',
    'cone plein': 'Cono lleno',
    'jet plat': 'Chorro plano',
    'spirale': 'Espiral',
    'Distribution étroite, bon pour uniformité': 'Distribución estrecha, buena para uniformidad',
    'Distribution plus large, meilleure couverture': 'Distribución más amplia, mejor cobertura',
    'Distribution large, bon pour surfaces': 'Distribución amplia, buena para superficies',
    'Distribution très étroite, excellente atomisation': 'Distribución muy estrecha, excelente atomización',

    // ========== TIPOS DE AGUA ==========
    'Eau potable': 'Agua potable',
    'Eau de refroidissement': 'Agua de enfriamiento',
    'Eau déminéralisée': 'Agua desmineralizada',
    'Eau adoucie': 'Agua ablandada',
    'Eau de rivière': 'Agua de río',

    // ========== CARACTERÍSTICAS DEL SPRAY ==========
    'Résultats du Quench': 'Resultados QUENCH',
    'Hauteur minimale du quench [m]': 'Altura mínima QUENCH [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Diámetro medio de Sauter) [µm]',
    'Vitesse des gouttes [m/s]': 'Velocidad de gotitas [m/s]',
    'Angle du spray [°]': 'Ángulo del spray [°]',
    'Qualité du spray - Atomisation': 'Calidad del spray - Atomización',
    'Qualité du spray - Uniformité': 'Calidad del spray - Uniformidad',
    'Qualité du spray - Couverture': 'Calidad del spray - Cobertura',
    'Type de buse - Description': 'Tipo de boquilla - Descripción',
    'Paramètre n (distribution)': 'Parámetro n (distribución)',
    'Taille moyenne des gouttes [µm]': 'Tamaño medio de gotitas [µm]',

    // ========== CALIDADES DEL SPRAY ==========
    'Excellente': 'Excelente',
    'Bonne': 'Buena',
    'Moyenne': 'Media',
    'Très uniforme': 'Muy uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Menos uniforme',
    'Large couverture': 'Cobertura amplia',
    'Couverture moyenne': 'Cobertura media',
    'Couverture concentrée': 'Cobertura concentrada',

    // ========== CARACTERÍSTICAS DE GASES DE COMBUSTIÓN ==========
    'Inlet temperature [K]': 'Temperatura de entrada [K]',
    'Outlet temperature [K]': 'Temperatura de salida [K]',
    'Flue gas flow rate [m3/h]': 'Tasa de flujo de gas de combustión [m³/h]',
    'Water vapor in flue gas [m3/h]': 'Vapor de agua en gas de combustión [m³/h]',
    'Quench surface area [m2]': 'Área de superficie QUENCH [m²]',
    'Spray pressure [bar]': 'Presión del spray [bar]',
    'Débit eau [L/min]': 'Caudal de agua [L/min]',
    'Vitesse des gaz [m/s]': 'Velocidad del gas [m/s]',
    'Prix de l\'eau [€/m³]': 'Precio del agua [€/m³]',
    'Coût eau par heure [€/h]': 'Costo del agua por hora [€/h]',

    // ========== RESIDUOS ==========
    'Residus calculated': 'Residuos calculados',
    'Dry residus [kg/h]': 'Residuos secos [kg/h]',
    'Wet residus [kg/h]': 'Residuos húmedos [kg/h]',
    'Fly ash [kg/h]': 'Cenizas volantes [kg/h]',
    'Bottom ash [kg/h]': 'Cenizas del fondo [kg/h]',
    'Bottom ash wet [kg/h]': 'Cenizas del fondo húmedas [kg/h]',
    'inert mass [kg/h]': 'Masa inerte [kg/h]',
    'Waste Flow [kg/h]': 'Flujo de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flujo de gas húmedo [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flujo de gas seco [Nm³/h]',
    'O2 calculated [%]': 'O2 calculado [%]',

    // ========== RESUMEN ==========
    'Diamètre quench': 'Diámetro QUENCH',
    'Pression pulvérisation': 'Presión de pulverización',
    'Surface quench [m²]': 'Área de superficie QUENCH [m²]',
    'Hauteur quench [m]': 'Altura QUENCH [m]',
    'Puissance pompe': 'Potencia de la bomba',
    'Consommation eau': 'Consumo de agua',
    'Surface des manches [m²]': 'Área de manga [m²]',
    'Consommation air comprimé [Nm3/h]': 'Consumo de aire comprimido [Nm³/h]',
    'Pression air comprimé [Bar]': 'Presión de aire comprimido [Bar]',
    'Residus du BHF [kg/h]': 'Residuos BHF [kg/h]',
    'CO2 transport total [kg]': 'Total CO2 transporte [kg]',
    'Coût transport total [€]': 'Costo total de transporte [€]',

    // ========== BOMBA Y CONSUMO ==========
    'pompe quench': 'Bomba QUENCH',
    'Nombre de cycles [Nb]': 'Número de ciclos [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Aire comprimido por ciclo [Nm³/ciclo]',
    'Conso élec air comprimé [kW]': 'Consumo eléctrico de aire comprimido [kW]',
    'conso elec vis de transport [kW]': 'Consumo eléctrico del tornillo de transporte [kW]',
  },

  zh: {
    // ========== 主要部分 ==========
    'Calculation parameters': '计算参数',
    'Calculated parameters': '计算结果参数',
    'Flue gas composition': '烟气成分',
    'Quench Configuration': '冷却系统配置',
    'Back to Flow': '返回流程',
    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Design': '设计',
    'Opex': '运营成本',
    'Pollutant Treatment Table': '污染物处理表',
    'Résultats': '结果',
    'Résumé des paramètres principaux': '主要参数摘要',
    'Paramètres calculés détaillés': '详细计算参数',

    // ========== 按钮 ==========
    'Clear memory': '清除内存',
    'Reset to Default Values': '恢复默认值',
    'Export': '导出',

    // ========== 通用参数 ==========
    'Flue gas inlet at inlet temperature': '在入口温度下的烟气入口',
    'Air ingress at ambient temperature': '在环境温度下的空气进入',
    'Flue gas outlet at outlet temperature': '在出口温度下的烟气出口',
    'Input flue gas': '输入烟气',
    'Output flue gas': '输出烟气',

    // ========== 关键字段 - 表单字段 ==========
    'Flue gas temperature outlet [°C]': '烟气出口温度 [°C]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空气进入体积 [Nm³/h]',
    'Thermal losses [%]': '热损失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',

    // ========== 显示的参数 ==========
    'Temperature inlet WATER_INJECTION [°C]': '水喷射入口温度 [°C]',
    'Temperature outlet WATER_INJECTION [°C]': '水喷射出口温度 [°C]',
    'Delta enthalpies [kJ/kg]': '焓变 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '喷雾/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '烟气出口体积 [Nm³/h]',

    // ========== 验证消息 ==========
    'Valeur invalide': '无效值',
    'Veuillez entrer une valeur numérique': '请输入数值',
    'Valeur hors limites': '值超出范围 (0-10000)',

    // ========== 污染物参数 ==========
    'Fly ashes content [g/Nm3]': '飞灰含量 [g/Nm³]',
    'siccity bottom ash [%]': '底灰干度 [%]',
    'O2 ref [%]': 'O2参考 [%]',
    'SOx reactif': 'SOx反应剂',
    'HCl reactif': 'HCl反应剂',
    'HF reactif': 'HF反应剂',
    'efficacite_SOx': 'SOx效率 [%]',
    'HCl efficacité': 'HCl效率 [%]',
    'HF efficacité': 'HF效率 [%]',
    'SOx stoechiométrie': 'SOx化学计量',
    'HCl stoechiométrie': 'HCl化学计量',
    'HF stoechiométrie': 'HF化学计量',
    'Pollutant': '污染物',
    'Reagent': '反应剂',
    'Mass (kg/h)': '质量 (kg/h)',
    'Efficiency (%)': '效率 (%)',
    'Stoich. Coeff.': '化学计量系数',
    'Output Mass': '输出质量',
    'Residue Mass': '残留质量',
    'Reagent Mass': '反应剂质量',
    'Abated Mass': '减少的质量',

    // ========== 冷却系统设计参数 ==========
    'Pertes de charge aéraulique': '空气动力压力损失',
    'Pression aéraulique [mmCE]': '空气动力压力 [mmCE]',
    'PDC [mmCE]': '压力降 [mmCE]',
    'Pression de sortie [mmCE]': '出口压力 [mmCE]',
    'Dimensionnement du Quench': '冷却系统尺寸设计',
    'Quench diameter [m]': '冷却系统直径 [m]',
    'Pression pulverisation [bar]': '喷雾压力 [bar]',
    'Type de buse': '喷嘴类型',
    'Type d\'eau': '水类型',
    'Consommation électrique de la pompe': '泵电耗',
    'Puissance pompe [kW]': '泵功率 [kW]',
    'Rendement pompe [%]': '泵效率 [%]',
    'Puissance pompe nominale [kW]': '泵额定功率 [kW]',
    'Consommation réelle [kW]': '实际消耗 [kW]',

    // ========== 喷嘴类型 ==========
    'cone creux': '空心锥',
    'cone plein': '实心锥',
    'jet plat': '平射流',
    'spirale': '螺旋',
    'Distribution étroite, bon pour uniformité': '窄分布，适合均匀性',
    'Distribution plus large, meilleure couverture': '宽分布，覆盖面积好',
    'Distribution large, bon pour surfaces': '大分布，适合表面',
    'Distribution très étroite, excellente atomisation': '超窄分布，优异的雾化',

    // ========== 水类型 ==========
    'Eau potable': '饮用水',
    'Eau de refroidissement': '冷却水',
    'Eau déminéralisée': '去离子水',
    'Eau adoucie': '软化水',
    'Eau de rivière': '河水',

    // ========== 喷雾特性 ==========
    'Résultats du Quench': '冷却系统结果',
    'Hauteur minimale du quench [m]': '冷却系统最小高度 [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter平均直径) [µm]',
    'Vitesse des gouttes [m/s]': '液滴速度 [m/s]',
    'Angle du spray [°]': '喷雾角度 [°]',
    'Qualité du spray - Atomisation': '喷雾质量 - 雾化',
    'Qualité du spray - Uniformité': '喷雾质量 - 均匀性',
    'Qualité du spray - Couverture': '喷雾质量 - 覆盖',
    'Type de buse - Description': '喷嘴类型 - 描述',
    'Paramètre n (distribution)': '参数n (分布)',
    'Taille moyenne des gouttes [µm]': '液滴平均尺寸 [µm]',

    // ========== 喷雾质量 ==========
    'Excellente': '优异',
    'Bonne': '良好',
    'Moyenne': '中等',
    'Très uniforme': '非常均匀',
    'Uniforme': '均匀',
    'Moins uniforme': '不够均匀',
    'Large couverture': '宽覆盖',
    'Couverture moyenne': '中等覆盖',
    'Couverture concentrée': '集中覆盖',

    // ========== 烟气特性 ==========
    'Inlet temperature [K]': '入口温度 [K]',
    'Outlet temperature [K]': '出口温度 [K]',
    'Flue gas flow rate [m3/h]': '烟气流量 [m³/h]',
    'Water vapor in flue gas [m3/h]': '烟气中的水蒸气 [m³/h]',
    'Quench surface area [m2]': '冷却系统表面积 [m²]',
    'Spray pressure [bar]': '喷雾压力 [bar]',
    'Débit eau [L/min]': '水流量 [L/min]',
    'Vitesse des gaz [m/s]': '气体速度 [m/s]',
    'Prix de l\'eau [€/m³]': '水价 [€/m³]',
    'Coût eau par heure [€/h]': '每小时水成本 [€/h]',

    // ========== 残留物 ==========
    'Residus calculated': '计算的残留物',
    'Dry residus [kg/h]': '干残留物 [kg/h]',
    'Wet residus [kg/h]': '湿残留物 [kg/h]',
    'Fly ash [kg/h]': '飞灰 [kg/h]',
    'Bottom ash [kg/h]': '底灰 [kg/h]',
    'Bottom ash wet [kg/h]': '湿底灰 [kg/h]',
    'inert mass [kg/h]': '惯性质量 [kg/h]',
    'Waste Flow [kg/h]': '废物流 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流 [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流 [Nm³/h]',
    'O2 calculated [%]': 'O2计算值 [%]',

    // ========== 总结 ==========
    'Diamètre quench': '冷却系统直径',
    'Pression pulvérisation': '喷雾压力',
    'Surface quench [m²]': '冷却系统表面积 [m²]',
    'Hauteur quench [m]': '冷却系统高度 [m]',
    'Puissance pompe': '泵功率',
    'Consommation eau': '水消耗',
    'Surface des manches [m²]': '袋面积 [m²]',
    'Consommation air comprimé [Nm3/h]': '压缩空气消耗 [Nm³/h]',
    'Pression air comprimé [Bar]': '压缩空气压力 [Bar]',
    'Residus du BHF [kg/h]': 'BHF残留物 [kg/h]',
    'CO2 transport total [kg]': '总运输CO2 [kg]',
    'Coût transport total [€]': '总运输成本 [€]',

    // ========== 泵和消耗 ==========
    'pompe quench': '冷却系统泵',
    'Nombre de cycles [Nb]': '循环次数 [Nb]',
    'Air comprime par cycle [Nm3/cycle]': '每个循环的压缩空气 [Nm³/循环]',
    'Conso élec air comprimé [kW]': '压缩空气电消耗 [kW]',
    'conso elec vis de transport [kW]': '运输螺杆电消耗 [kW]',
  },

  ja: {
    // ========== メインセクション ==========
    'Calculation parameters': '計算パラメータ',
    'Calculated parameters': '計算されたパラメータ',
    'Flue gas composition': '燃焼ガス組成',
    'Quench Configuration': 'クエンチ構成',
    'Back to Flow': 'フローに戻る',
    'Flue gases': '燃焼ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Design': '設計',
    'Opex': 'Opex',
    'Pollutant Treatment Table': '汚染物質処理表',
    'Résultats': '結果',
    'Résumé des paramètres principaux': '主要パラメータの概要',
    'Paramètres calculés détaillés': '詳細な計算パラメータ',

    // ========== ボタン ==========
    'Clear memory': 'メモリをクリア',
    'Reset to Default Values': 'デフォルト値にリセット',
    'Export': 'エクスポート',

    // ========== 一般的なパラメータ ==========
    'Flue gas inlet at inlet temperature': '入口温度での燃焼ガス入口',
    'Air ingress at ambient temperature': '環境温度での空気進入',
    'Flue gas outlet at outlet temperature': '出口温度での燃焼ガス出口',
    'Input flue gas': '入力燃焼ガス',
    'Output flue gas': '出力燃焼ガス',

    // ========== 重要なキー - フォームフィールド ==========
    'Flue gas temperature outlet [°C]': 'ガス出口温度 [°C]',
    'Ambient air temperature [°C]': '環境空気温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空気進入量 [Nm³/h]',
    'Thermal losses [%]': '熱損失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',

    // ========== 表示されるパラメータ ==========
    'Temperature inlet WATER_INJECTION [°C]': '水噴射入口温度 [°C]',
    'Temperature outlet WATER_INJECTION [°C]': '水噴射出口温度 [°C]',
    'Delta enthalpies [kJ/kg]': 'エンタルピー変化 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '噴霧/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'ガス出口体積 [Nm³/h]',

    // ========== 検証メッセージ ==========
    'Valeur invalide': '無効な値',
    'Veuillez entrer une valeur numérique': '数値を入力してください',
    'Valeur hors limites': '範囲外の値 (0-10000)',

    // ========== 汚染物質パラメータ ==========
    'Fly ashes content [g/Nm3]': '飛灰含有量 [g/Nm³]',
    'siccity bottom ash [%]': '底灰の乾燥度 [%]',
    'O2 ref [%]': 'O2基準 [%]',
    'SOx reactif': 'SOx反応剤',
    'HCl reactif': 'HCl反応剤',
    'HF reactif': 'HF反応剤',
    'efficacite_SOx': 'SOx効率 [%]',
    'HCl efficacité': 'HCl効率 [%]',
    'HF efficacité': 'HF効率 [%]',
    'SOx stoechiométrie': 'SOx化学量論',
    'HCl stoechiométrie': 'HCl化学量論',
    'HF stoechiométrie': 'HF化学量論',
    'Pollutant': '汚染物質',
    'Reagent': '反応剤',
    'Mass (kg/h)': '質量 (kg/h)',
    'Efficiency (%)': '効率 (%)',
    'Stoich. Coeff.': '化学量論係数',
    'Output Mass': '出力質量',
    'Residue Mass': '残留質量',
    'Reagent Mass': '反応剤質量',
    'Abated Mass': '低減質量',

    // ========== クエンチ設計パラメータ ==========
    'Pertes de charge aéraulique': '空気力圧力損失',
    'Pression aéraulique [mmCE]': '空気力圧力 [mmCE]',
    'PDC [mmCE]': '圧力損失 [mmCE]',
    'Pression de sortie [mmCE]': '出口圧力 [mmCE]',
    'Dimensionnement du Quench': 'クエンチ設計',
    'Quench diameter [m]': 'クエンチ直径 [m]',
    'Pression pulverisation [bar]': '噴霧圧力 [bar]',
    'Type de buse': 'ノズルタイプ',
    'Type d\'eau': '水のタイプ',
    'Consommation électrique de la pompe': 'ポンプの消費電力',
    'Puissance pompe [kW]': 'ポンプ出力 [kW]',
    'Rendement pompe [%]': 'ポンプ効率 [%]',
    'Puissance pompe nominale [kW]': 'ポンプ定格出力 [kW]',
    'Consommation réelle [kW]': '実消費 [kW]',

    // ========== ノズルタイプ ==========
    'cone creux': '空コーン',
    'cone plein': '実コーン',
    'jet plat': 'フラットジェット',
    'spirale': 'スパイラル',
    'Distribution étroite, bon pour uniformité': '狭い分布、均一性に適している',
    'Distribution plus large, meilleure couverture': 'より広い分布、カバレッジが向上',
    'Distribution large, bon pour surfaces': '広い分布、表面に適している',
    'Distribution très étroite, excellente atomisation': '非常に狭い分布、優れた噴霧化',

    // ========== 水のタイプ ==========
    'Eau potable': '飲料水',
    'Eau de refroidissement': '冷却水',
    'Eau déminéralisée': 'イオン交換水',
    'Eau adoucie': '軟化水',
    'Eau de rivière': '河川水',

    // ========== スプレー特性 ==========
    'Résultats du Quench': 'クエンチ結果',
    'Hauteur minimale du quench [m]': 'クエンチ最小高さ [m]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Sauter平均直径) [µm]',
    'Vitesse des gouttes [m/s]': 'しぶき速度 [m/s]',
    'Angle du spray [°]': 'スプレー角度 [°]',
    'Qualité du spray - Atomisation': 'スプレー品質 - 噴霧化',
    'Qualité du spray - Uniformité': 'スプレー品質 - 均一性',
    'Qualité du spray - Couverture': 'スプレー品質 - カバレッジ',
    'Type de buse - Description': 'ノズルタイプ - 説明',
    'Paramètre n (distribution)': 'パラメータn (分布)',
    'Taille moyenne des gouttes [µm]': 'しぶき平均サイズ [µm]',

    // ========== スプレー品質 ==========
    'Excellente': '優秀',
    'Bonne': '良い',
    'Moyenne': '平均',
    'Très uniforme': '非常に均一',
    'Uniforme': '均一',
    'Moins uniforme': 'あまり均一でない',
    'Large couverture': '広いカバレッジ',
    'Couverture moyenne': '平均カバレッジ',
    'Couverture concentrée': '集中カバレッジ',

    // ========== 燃焼ガス特性 ==========
    'Inlet temperature [K]': '入口温度 [K]',
    'Outlet temperature [K]': '出口温度 [K]',
    'Flue gas flow rate [m3/h]': '燃焼ガス流量 [m³/h]',
    'Water vapor in flue gas [m3/h]': '燃焼ガス中の水蒸気 [m³/h]',
    'Quench surface area [m2]': 'クエンチ表面積 [m²]',
    'Spray pressure [bar]': 'スプレー圧力 [bar]',
    'Débit eau [L/min]': '水流量 [L/分]',
    'Vitesse des gaz [m/s]': 'ガス速度 [m/s]',
    'Prix de l\'eau [€/m³]': '水価格 [€/m³]',
    'Coût eau par heure [€/h]': '1時間あたりの水コスト [€/h]',

    // ========== 残留物 ==========
    'Residus calculated': '計算された残留物',
    'Dry residus [kg/h]': '乾燥残留物 [kg/h]',
    'Wet residus [kg/h]': '湿った残留物 [kg/h]',
    'Fly ash [kg/h]': '飛灰 [kg/h]',
    'Bottom ash [kg/h]': '底灰 [kg/h]',
    'Bottom ash wet [kg/h]': '湿った底灰 [kg/h]',
    'inert mass [kg/h]': '不活性質量 [kg/h]',
    'Waste Flow [kg/h]': '廃棄物流 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿ったガス流 [Nm³/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾燥ガス流 [Nm³/h]',
    'O2 calculated [%]': '計算されたO2 [%]',

    // ========== 概要 ==========
    'Diamètre quench': 'クエンチ直径',
    'Pression pulvérisation': '噴霧圧力',
    'Surface quench [m²]': 'クエンチ表面積 [m²]',
    'Hauteur quench [m]': 'クエンチ高さ [m]',
    'Puissance pompe': 'ポンプ出力',
    'Consommation eau': '水消費',
    'Surface des manches [m²]': 'スリーブ表面積 [m²]',
    'Consommation air comprimé [Nm3/h]': '圧縮空気消費 [Nm³/h]',
    'Pression air comprimé [Bar]': '圧縮空気圧力 [Bar]',
    'Residus du BHF [kg/h]': 'BHF残留物 [kg/h]',
    'CO2 transport total [kg]': '総輸送CO2 [kg]',
    'Coût transport total [€]': '総輸送コスト [€]',

    // ========== ポンプと消費 ==========
    'pompe quench': 'クエンチポンプ',
    'Nombre de cycles [Nb]': 'サイクル数 [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'サイクルあたりの圧縮空気 [Nm³/サイクル]',
    'Conso élec air comprimé [kW]': '圧縮空気電力消費 [kW]',
    'conso elec vis de transport [kW]': '搬送スクリュー電力消費 [kW]',
  },

  ru: {
    // ========== ОСНОВНЫЕ РАЗДЕЛЫ ==========
    'Calculation parameters': 'Параметры расчета',
    'Calculated parameters': 'Рассчитанные параметры',
    'Flue gas composition': 'Состав дымовых газов',
    'Quench Configuration': 'Конфигурация системы закалки',
    'Back to Flow': 'Вернуться к потоку',
    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязняющих веществ',
    'Design': 'Проектирование',
    'Opex': 'Opex',
    'Pollutant Treatment Table': 'Таблица обработки загрязняющих веществ',
    'Résultats': 'Результаты',
    'Résumé des paramètres principaux': 'Краткое описание основных параметров',
    'Paramètres calculés détaillés': 'Подробные рассчитанные параметры',

    // ========== КНОПКИ ==========
    'Clear memory': 'Очистить память',
    'Reset to Default Values': 'Восстановить значения по умолчанию',
    'Export': 'Экспортировать',

    // ========== ОБЩИЕ ПАРАМЕТРЫ ==========
    'Flue gas inlet at inlet temperature': 'Вход дымовых газов при температуре входа',
    'Air ingress at ambient temperature': 'Поступление воздуха при температуре окружающей среды',
    'Flue gas outlet at outlet temperature': 'Выход дымовых газов при температуре выхода',
    'Input flue gas': 'Входящие дымовые газы',
    'Output flue gas': 'Выходящие дымовые газы',

    // ========== КРИТИЧЕСКИЕ КЛЮЧИ - ПОЛЯ ФОРМЫ ==========
    'Flue gas temperature outlet [°C]': 'Температура выхода газов [°C]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Volume of air ingress [Nm3/h]': 'Объем поступления воздуха [Nm³/h]',
    'Thermal losses [%]': 'Тепловые потери [%]',
    'Cooling water temperature [°C]': 'Температура охлаждающей воды [°C]',

    // ========== ОТОБРАЖАЕМЫЕ ПАРАМЕТРЫ ==========
    'Temperature inlet WATER_INJECTION [°C]': 'Температура входа системы закалки [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'Температура выхода системы закалки [°C]',
    'Delta enthalpies [kJ/kg]': 'Изменение энтальпии [кДж/кг]',
    'Sprayed/cooling water [kg/h]': 'Распыляемая/охлаждающая вода [кг/ч]',
    'Outlet flue gas volume [Nm3/h]': 'Объем выходящих дымовых газов [Nm³/h]',

    // ========== СООБЩЕНИЯ ВАЛИДАЦИИ ==========
    'Valeur invalide': 'Неверное значение',
    'Veuillez entrer une valeur numérique': 'Пожалуйста, введите числовое значение',
    'Valeur hors limites': 'Значение вне допустимого диапазона (0-10000)',

    // ========== ПАРАМЕТРЫ ЗАГРЯЗНЯЮЩИХ ВЕЩЕСТВ ==========
    'Fly ashes content [g/Nm3]': 'Содержание летучей золы [г/Nm³]',
    'siccity bottom ash [%]': 'Сухость шлака на дне [%]',
    'O2 ref [%]': 'O2 эталон [%]',
    'SOx reactif': 'Реагент SOx',
    'HCl reactif': 'Реагент HCl',
    'HF reactif': 'Реагент HF',
    'efficacite_SOx': 'Эффективность SOx [%]',
    'HCl efficacité': 'Эффективность HCl [%]',
    'HF efficacité': 'Эффективность HF [%]',
    'SOx stoechiométrie': 'Стехиометрия SOx',
    'HCl stoechiométrie': 'Стехиометрия HCl',
    'HF stoechiométrie': 'Стехиометрия HF',
    'Pollutant': 'Загрязняющее вещество',
    'Reagent': 'Реагент',
    'Mass (kg/h)': 'Масса (кг/ч)',
    'Efficiency (%)': 'Эффективность (%)',
    'Stoich. Coeff.': 'Стехиом. коэффициент',
    'Output Mass': 'Выходная масса',
    'Residue Mass': 'Масса остатка',
    'Reagent Mass': 'Масса реагента',
    'Abated Mass': 'Снятая масса',

    // ========== ПАРАМЕТРЫ ПРОЕКТИРОВАНИЯ СИСТЕМЫ ЗАКАЛКИ ==========
    'Pertes de charge aéraulique': 'Аэродинамические потери давления',
    'Pression aéraulique [mmCE]': 'Аэродинамическое давление [ммВе]',
    'PDC [mmCE]': 'Перепад давления [ммВе]',
    'Pression de sortie [mmCE]': 'Давление на выходе [ммВе]',
    'Dimensionnement du Quench': 'Размеры системы закалки',
    'Quench diameter [m]': 'Диаметр системы закалки [м]',
    'Pression pulverisation [bar]': 'Давление распыления [бар]',
    'Type de buse': 'Тип форсунки',
    'Type d\'eau': 'Тип воды',
    'Consommation électrique de la pompe': 'Электрическое потребление насоса',
    'Puissance pompe [kW]': 'Мощность насоса [кВт]',
    'Rendement pompe [%]': 'КПД насоса [%]',
    'Puissance pompe nominale [kW]': 'Номинальная мощность насоса [кВт]',
    'Consommation réelle [kW]': 'Фактическое потребление [кВт]',

    // ========== ТИПЫ ФОРСУНОК ==========
    'cone creux': 'Полый конус',
    'cone plein': 'Полный конус',
    'jet plat': 'Плоский поток',
    'spirale': 'Спираль',
    'Distribution étroite, bon pour uniformité': 'Узкое распределение, хорошо для равномерности',
    'Distribution plus large, meilleure couverture': 'Более широкое распределение, лучшее покрытие',
    'Distribution large, bon pour surfaces': 'Широкое распределение, хорошо для поверхностей',
    'Distribution très étroite, excellente atomisation': 'Очень узкое распределение, отличная атомизация',

    // ========== ТИПЫ ВОДЫ ==========
    'Eau potable': 'Питьевая вода',
    'Eau de refroidissement': 'Охлаждающая вода',
    'Eau déminéralisée': 'Деминерализованная вода',
    'Eau adoucie': 'Мягкая вода',
    'Eau de rivière': 'Речная вода',

    // ========== ХАРАКТЕРИСТИКИ РАСПЫЛЕНИЯ ==========
    'Résultats du Quench': 'Результаты системы закалки',
    'Hauteur minimale du quench [m]': 'Минимальная высота системы закалки [м]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (Средний диаметр Саутера) [мкм]',
    'Vitesse des gouttes [m/s]': 'Скорость капель [м/с]',
    'Angle du spray [°]': 'Угол распыления [°]',
    'Qualité du spray - Atomisation': 'Качество распыления - Атомизация',
    'Qualité du spray - Uniformité': 'Качество распыления - Равномерность',
    'Qualité du spray - Couverture': 'Качество распыления - Покрытие',
    'Type de buse - Description': 'Тип форсунки - Описание',
    'Paramètre n (distribution)': 'Параметр n (распределение)',
    'Taille moyenne des gouttes [µm]': 'Средний размер капель [мкм]',

    // ========== КАЧЕСТВО РАСПЫЛЕНИЯ ==========
    'Excellente': 'Отличное',
    'Bonne': 'Хорошее',
    'Moyenne': 'Среднее',
    'Très uniforme': 'Очень однородное',
    'Uniforme': 'Однородное',
    'Moins uniforme': 'Менее однородное',
    'Large couverture': 'Широкое покрытие',
    'Couverture moyenne': 'Среднее покрытие',
    'Couverture concentrée': 'Сосредоточенное покрытие',

    // ========== ХАРАКТЕРИСТИКИ ДЫМОВЫХ ГАЗОВ ==========
    'Inlet temperature [K]': 'Температура входа [K]',
    'Outlet temperature [K]': 'Температура выхода [K]',
    'Flue gas flow rate [m3/h]': 'Расход дымовых газов [м³/ч]',
    'Water vapor in flue gas [m3/h]': 'Водяной пар в дымовых газах [м³/ч]',
    'Quench surface area [m2]': 'Площадь поверхности системы закалки [м²]',
    'Spray pressure [bar]': 'Давление распыления [бар]',
    'Débit eau [L/min]': 'Расход воды [л/мин]',
    'Vitesse des gaz [m/s]': 'Скорость газа [м/с]',
    'Prix de l\'eau [€/m³]': 'Цена воды [€/м³]',
    'Coût eau par heure [€/h]': 'Стоимость воды в час [€/ч]',

    // ========== ОСТАТКИ ==========
    'Residus calculated': 'Рассчитанные остатки',
    'Dry residus [kg/h]': 'Сухие остатки [кг/ч]',
    'Wet residus [kg/h]': 'Влажные остатки [кг/ч]',
    'Fly ash [kg/h]': 'Летучая зола [кг/ч]',
    'Bottom ash [kg/h]': 'Шлак на дне [кг/ч]',
    'Bottom ash wet [kg/h]': 'Влажный шлак на дне [кг/ч]',
    'inert mass [kg/h]': 'Инертная масса [кг/ч]',
    'Waste Flow [kg/h]': 'Поток отходов [кг/ч]',
    'Flue gas Flow Wet [Nm3/h]': 'Поток влажных дымовых газов [Nm³/ч]',
    'Flue gas Flow Dry [Nm3/h]': 'Поток сухих дымовых газов [Nm³/ч]',
    'O2 calculated [%]': 'Рассчитанный O2 [%]',

    // ========== РЕЗЮМЕ ==========
    'Diamètre quench': 'Диаметр системы закалки',
    'Pression pulvérisation': 'Давление распыления',
    'Surface quench [m²]': 'Площадь поверхности системы закалки [м²]',
    'Hauteur quench [m]': 'Высота системы закалки [м]',
    'Puissance pompe': 'Мощность насоса',
    'Consommation eau': 'Расход воды',
    'Surface des manches [m²]': 'Площадь рукава [м²]',
    'Consommation air comprimé [Nm3/h]': 'Расход сжатого воздуха [Nm³/ч]',
    'Pression air comprimé [Bar]': 'Давление сжатого воздуха [бар]',
    'Residus du BHF [kg/h]': 'Остатки BHF [кг/ч]',
    'CO2 transport total [kg]': 'Всего CO2 транспорт [кг]',
    'Coût transport total [€]': 'Общая стоимость транспорта [€]',

    // ========== НАСОС И ПОТРЕБЛЕНИЕ ==========
    'pompe quench': 'Насос системы закалки',
    'Nombre de cycles [Nb]': 'Количество циклов [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'Сжатый воздух на цикл [Nm³/цикл]',
    'Conso élec air comprimé [kW]': 'Электрическое потребление сжатого воздуха [кВт]',
    'conso elec vis de transport [kW]': 'Электрическое потребление транспортного винта [кВт]',
  },

  ar: {
    // ========== الأقسام الرئيسية ==========
    'Calculation parameters': 'معاملات الحساب',
    'Calculated parameters': 'المعاملات المحسوبة',
    'Flue gas composition': 'تكوين غازات العادم',
    'Quench Configuration': 'تكوين نظام التبريد السريع',
    'Back to Flow': 'العودة إلى التدفق',
    'Flue gases': 'غازات العادم',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Design': 'التصميم',
    'Opex': 'نفقات التشغيل',
    'Pollutant Treatment Table': 'جدول معالجة الملوثات',
    'Résultats': 'النتائج',
    'Résumé des paramètres principaux': 'ملخص المعاملات الرئيسية',
    'Paramètres calculés détaillés': 'المعاملات المحسوبة التفصيلية',

    // ========== الأزرار ==========
    'Clear memory': 'مسح الذاكرة',
    'Reset to Default Values': 'إعادة تعيين القيم الافتراضية',
    'Export': 'تصدير',

    // ========== المعاملات العامة ==========
    'Flue gas inlet at inlet temperature': 'مدخل غازات العادم عند درجة حرارة المدخل',
    'Air ingress at ambient temperature': 'دخول الهواء عند درجة الحرارة المحيطة',
    'Flue gas outlet at outlet temperature': 'مخرج غازات العادم عند درجة حرارة المخرج',
    'Input flue gas': 'غازات العادم المدخلة',
    'Output flue gas': 'غازات العادم المخرجة',

    // ========== المفاتيح الحرجة - حقول النموذج ==========
    'Flue gas temperature outlet [°C]': 'درجة حرارة مخرج الغازات [°C]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Volume of air ingress [Nm3/h]': 'حجم دخول الهواء [Nm³/h]',
    'Thermal losses [%]': 'الخسائر الحرارية [%]',
    'Cooling water temperature [°C]': 'درجة حرارة ماء التبريد [°C]',

    // ========== المعاملات المعروضة ==========
    'Temperature inlet WATER_INJECTION [°C]': 'درجة حرارة مدخل نظام التبريد [°C]',
    'Temperature outlet WATER_INJECTION [°C]': 'درجة حرارة مخرج نظام التبريد [°C]',
    'Delta enthalpies [kJ/kg]': 'تغير الإنثالبيا [كيلوجول/كغ]',
    'Sprayed/cooling water [kg/h]': 'ماء مرذوذ/تبريد [كغ/ساعة]',
    'Outlet flue gas volume [Nm3/h]': 'حجم مخرج غازات العادم [Nm³/h]',

    // ========== رسائل التحقق ==========
    'Valeur invalide': 'قيمة غير صحيحة',
    'Veuillez entrer une valeur numérique': 'يرجى إدخال قيمة رقمية',
    'Valeur hors limites': 'القيمة خارج النطاق (0-10000)',

    // ========== معاملات الملوثات ==========
    'Fly ashes content [g/Nm3]': 'محتوى الرماد الطائر [غ/Nm³]',
    'siccity bottom ash [%]': 'جفاف الرماد السفلي [%]',
    'O2 ref [%]': 'مرجع O2 [%]',
    'SOx reactif': 'كاشف SOx',
    'HCl reactif': 'كاشف HCl',
    'HF reactif': 'كاشف HF',
    'efficacite_SOx': 'كفاءة SOx [%]',
    'HCl efficacité': 'كفاءة HCl [%]',
    'HF efficacité': 'كفاءة HF [%]',
    'SOx stoechiométrie': 'القياس المتكافئ SOx',
    'HCl stoechiométrie': 'القياس المتكافئ HCl',
    'HF stoechiométrie': 'القياس المتكافئ HF',
    'Pollutant': 'ملوث',
    'Reagent': 'كاشف',
    'Mass (kg/h)': 'الكتلة (كغ/ساعة)',
    'Efficiency (%)': 'الكفاءة (%)',
    'Stoich. Coeff.': 'معامل القياس المتكافئ',
    'Output Mass': 'كتلة المخرج',
    'Residue Mass': 'كتلة البقايا',
    'Reagent Mass': 'كتلة الكاشف',
    'Abated Mass': 'الكتلة المقللة',

    // ========== معاملات تصميم نظام التبريد ==========
    'Pertes de charge aéraulique': 'فقدان الضغط الديناميكي الهوائي',
    'Pression aéraulique [mmCE]': 'الضغط الديناميكي الهوائي [ملم ماء]',
    'PDC [mmCE]': 'فقدان الضغط [ملم ماء]',
    'Pression de sortie [mmCE]': 'ضغط المخرج [ملم ماء]',
    'Dimensionnement du Quench': 'تحديد حجم نظام التبريد السريع',
    'Quench diameter [m]': 'قطر نظام التبريد السريع [م]',
    'Pression pulverisation [bar]': 'ضغط الرش [بار]',
    'Type de buse': 'نوع الفوهة',
    'Type d\'eau': 'نوع الماء',
    'Consommation électrique de la pompe': 'الاستهلاك الكهربائي للمضخة',
    'Puissance pompe [kW]': 'قوة المضخة [كيلوواط]',
    'Rendement pompe [%]': 'كفاءة المضخة [%]',
    'Puissance pompe nominale [kW]': 'القوة المقيمة للمضخة [كيلوواط]',
    'Consommation réelle [kW]': 'الاستهلاك الفعلي [كيلوواط]',

    // ========== أنواع الفوهات ==========
    'cone creux': 'مخروط مجوف',
    'cone plein': 'مخروط مصمت',
    'jet plat': 'نفاثة مسطحة',
    'spirale': 'حلزون',
    'Distribution étroite, bon pour uniformité': 'توزيع ضيق، جيد للتوحيد',
    'Distribution plus large, meilleure couverture': 'توزيع أوسع، تغطية أفضل',
    'Distribution large, bon pour surfaces': 'توزيع واسع، جيد للأسطح',
    'Distribution très étroite, excellente atomisation': 'توزيع ضيق جداً، تذرية ممتازة',

    // ========== أنواع المياه ==========
    'Eau potable': 'ماء الشرب',
    'Eau de refroidissement': 'ماء التبريد',
    'Eau déminéralisée': 'ماء منزوع المعادن',
    'Eau adoucie': 'ماء ناعم',
    'Eau de rivière': 'ماء النهر',

    // ========== خصائص الرش ==========
    'Résultats du Quench': 'نتائج نظام التبريد السريع',
    'Hauteur minimale du quench [m]': 'الحد الأدنى لارتفاع نظام التبريد [م]',
    'SMD (Sauter Mean Diameter) [µm]': 'SMD (متوسط قطر Sauter) [ميكرومتر]',
    'Vitesse des gouttes [m/s]': 'سرعة القطيرات [م/ث]',
    'Angle du spray [°]': 'زاوية الرش [°]',
    'Qualité du spray - Atomisation': 'جودة الرش - التذرية',
    'Qualité du spray - Uniformité': 'جودة الرش - التوحيد',
    'Qualité du spray - Couverture': 'جودة الرش - التغطية',
    'Type de buse - Description': 'نوع الفوهة - الوصف',
    'Paramètre n (distribution)': 'المعامل n (التوزيع)',
    'Taille moyenne des gouttes [µm]': 'متوسط حجم القطيرات [ميكرومتر]',

    // ========== جودة الرش ==========
    'Excellente': 'ممتازة',
    'Bonne': 'جيدة',
    'Moyenne': 'متوسطة',
    'Très uniforme': 'موحدة جداً',
    'Uniforme': 'موحدة',
    'Moins uniforme': 'أقل توحداً',
    'Large couverture': 'تغطية واسعة',
    'Couverture moyenne': 'تغطية متوسطة',
    'Couverture concentrée': 'تغطية مركزة',

    // ========== خصائص غازات العادم ==========
    'Inlet temperature [K]': 'درجة حرارة المدخل [K]',
    'Outlet temperature [K]': 'درجة حرارة المخرج [K]',
    'Flue gas flow rate [m3/h]': 'معدل تدفق غازات العادم [م³/ساعة]',
    'Water vapor in flue gas [m3/h]': 'بخار الماء في غازات العادم [م³/ساعة]',
    'Quench surface area [m2]': 'منطقة السطح لنظام التبريد [م²]',
    'Spray pressure [bar]': 'ضغط الرش [بار]',
    'Débit eau [L/min]': 'معدل تدفق الماء [لتر/دقيقة]',
    'Vitesse des gaz [m/s]': 'سرعة الغاز [م/ث]',
    'Prix de l\'eau [€/m³]': 'سعر الماء [€/م³]',
    'Coût eau par heure [€/h]': 'تكلفة الماء في الساعة [€/ساعة]',

    // ========== البقايا ==========
    'Residus calculated': 'البقايا المحسوبة',
    'Dry residus [kg/h]': 'البقايا الجافة [كغ/ساعة]',
    'Wet residus [kg/h]': 'البقايا الرطبة [كغ/ساعة]',
    'Fly ash [kg/h]': 'الرماد الطائر [كغ/ساعة]',
    'Bottom ash [kg/h]': 'الرماد السفلي [كغ/ساعة]',
    'Bottom ash wet [kg/h]': 'الرماد السفلي الرطب [كغ/ساعة]',
    'inert mass [kg/h]': 'الكتلة الخاملة [كغ/ساعة]',
    'Waste Flow [kg/h]': 'تدفق النفايات [كغ/ساعة]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق غازات العادم الرطبة [Nm³/ساعة]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق غازات العادم الجافة [Nm³/ساعة]',
    'O2 calculated [%]': 'O2 المحسوبة [%]',

    // ========== الملخص ==========
    'Diamètre quench': 'قطر نظام التبريد السريع',
    'Pression pulvérisation': 'ضغط الرش',
    'Surface quench [m²]': 'منطقة نظام التبريد [م²]',
    'Hauteur quench [m]': 'ارتفاع نظام التبريد [م]',
    'Puissance pompe': 'قوة المضخة',
    'Consommation eau': 'استهلاك الماء',
    'Surface des manches [m²]': 'منطقة الكم [م²]',
    'Consommation air comprimé [Nm3/h]': 'استهلاك الهواء المضغوط [Nm³/ساعة]',
    'Pression air comprimé [Bar]': 'ضغط الهواء المضغوط [بار]',
    'Residus du BHF [kg/h]': 'بقايا BHF [كغ/ساعة]',
    'CO2 transport total [kg]': 'إجمالي نقل CO2 [كغ]',
    'Coût transport total [€]': 'إجمالي تكلفة النقل [€]',

    // ========== المضخة والاستهلاك ==========
    'pompe quench': 'مضخة نظام التبريد السريع',
    'Nombre de cycles [Nb]': 'عدد الدورات [Nb]',
    'Air comprime par cycle [Nm3/cycle]': 'الهواء المضغوط في الدورة [Nm³/دورة]',
    'Conso élec air comprimé [kW]': 'الاستهلاك الكهربائي للهواء المضغوط [كيلوواط]',
    'conso elec vis de transport [kW]': 'الاستهلاك الكهربائي لنقل المسمار [كيلوواط]',
  }






};