export const translations = {
  fr: {
    stackConfiguration: 'Configuration REACTOR',
    backToFlow: 'Retour au flux',
    clearMemory: 'Effacer la mémoire',
    resetToDefaultValues: 'Réinitialiser les valeurs par défaut',
    note: 'Note',
    none: 'Aucun',
    flueGases: 'Gaz de fumée',
    pollutantEmissions: 'Émissions de polluants',
    design: 'Design',
    opex: 'Opex',
    rapport: 'Rapport',
    calculationParameters: 'Paramètres de calcul',
    calculatedParameters: 'Paramètres calculés',
    resetValues: 'Réinitialiser les valeurs',
    temperatureInletREACTOR: 'Température entrée REACTOR [°C]',
    deltaEnthalpies: 'Delta enthalpies [kJ/h]',
    sprayedCoolingWater: 'Eau pulvérisée/refroidissement [kg/h]',
    flueGasHumidTotal: 'Gaz de fumée total humide [Nm³/h]',
    flueGasInletAtInletTemperature: 'Composition gaz de fumée à l\'entrée',
    airIngressAtAmbientTemperature: 'Entrée d\'air à température ambiante',
    flueGasOutletAtOutletTemperature: 'Composition gaz de fumée à la sortie',
    wasteFlow: 'Débit des déchets [kg/h]',
    flueGasFlowWet: 'Débit gaz de fumée humide [Nm³/h]',
    flueGasFlowDry: 'Débit gaz de fumée sec [Nm³/h]',
    O2Calculated: 'O2 calculé [%]',
    inertMass: 'Masse inerte [kg/h]',
    bottomAsh: 'Cendres lourdes [kg/h]',
    bottomAshWet: 'Cendres lourdes humides [kg/h]',
    flyAsh: 'Cendres volantes [kg/h]',
    pollutantTreatmentTable: 'Tableau de traitement des polluants',
    pollutant: 'Polluant',
    reactif: 'Réactif',
    mass: 'Masse (kg/h)',
    efficiency: 'Efficacité (%)',
    stoichiometryCoeff: 'Coeff. Stoéch',
    outputMass: 'Masse sortie',
    residueMass: 'Masse résidu',
    reactifMass: 'Masse réactif',
    abatedMass: 'Masse abattue',
    inputFlueGas: 'Gaz de fumée en entrée',
    outputFlueGas: 'Gaz de fumée en sortie',
    bottomAshesCalculated: 'Cendres lourdes calculées',
    aeraulicPressureLoss: 'Pertes de charge aéraulique',
    reactorDesign: 'Dimensionnement Réacteur',
    designResults: 'Résultats du dimensionnement',
    electricConsumptionVisBelt: 'Consommation électrique vis sans fin',
    visBeltConsumption: 'Consommation vis sans fin',
    compressedAirConsumption: 'Consommation air comprimé',
    evacuationREACTORResidues: 'Évacuation des résidus REACTOR',
    residuesTransport: 'Transport des résidus',
    reactorVolume: 'Volume réacteur [m³]',
    diameter: 'Diamètre [m]',
    height: 'Hauteur [m]',
    residenceTime: 'Temps de séjour [s]',
    gasVelocity: 'Vitesse gaz [m/s]',
    pressureLoss: 'Perte de charge [mmCE]',
    agitationPower: 'Puissance agitation [kW]',
    agitationAir: 'Air agitation [Nm³/h]',
    consumptionVisBelt: 'Consommation vis transport [kW]',
    compressedAirPressure: 'Pression air comprimé [Bar]',
    airConsumption: 'Consommation air [Nm³/h]',
    reactorDiameter: 'Diamètre réacteur [m]',
    reactorHeight: 'Hauteur réacteur [m]',
    reactorAgitation: 'Dont agitation réacteur [Nm³/h]',
    filterCleaning: 'Dont nettoyage filtres [Nm³/h]',
    compressedAirElecConsumption: 'Conso élec air comprimé [kW]',
    residuesREACTOR: 'Résidus du REACTOR [kg/h]',
    truckType: 'Type de camion',
    distance: 'Distance [km]',
    CO2TransportTotal: 'CO2 transport total [kg]',
    costTransportTotal: 'Coût transport total [€]',
    P_out_mmCE: 'P sortie [mmCE]',
    visBelt: 'Vis sans fin',
    compressedAir: 'Air comprimé',
    mechanicalAgitation: 'Agitation mécanique',
    notUsed: 'Non utilisé',
    pump: 'Pompe',
    reactor: 'Réacteur',
    summaryMainParameters: 'Résumé des paramètres principaux',
    evacuatedAsh: 'Cendres évacuées',
    detailedCalculatedParameters: 'Paramètres calculés détaillés',
    pressureAeraulique: 'Pression aéraulique [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Débit fumées [Nm³/h]',
    temperature: 'Température [°C]',
    ldRatio: 'Ratio L/D',
    agitationType: 'Type agitation',
    mechanical: 'Mécanique',
    air: 'Pneumatique',
    consoElecVis: 'Conso élec vis de transport [kW]',
    nombreCycles: 'Nombre de cycles [Nb]',
    pressionAirComprime: 'Pression air comprimé [Bar]',
    airComprimeCycle: 'Air comprime par cycle [Nm3/cycle]',
    typesCamion: 'Type de camion',
    distanceTransport: 'Distance [km]',
    flueGasTemperatureOutlet: 'Température sortie gaz [°C]',
    ambientAirTemperature: 'Température air ambiant [°C]',
    volumeAirIngress: 'Volume admission air [Nm³/h]',
    thermalLosses: 'Pertes thermiques [%]',
    coolingWaterTemperature: 'Température eau refroidissement [°C]',
    flyAshesContent: 'Teneur en cendres volantes [g/Nm³]',
    siccityBottomAsh: 'Siccité cendres lourdes [%]',
    O2ref: 'O2 référence [%]',
    'Fly ashes content [g/Nm3]': 'Contenu en cendres volantes [g/Nm³]',
    'siccity bottom ash [%]': 'Siccité des cendres de fond [%]',
    'siccity residus [%]': 'Siccité des résidus [%]',
    'O2 ref [%]': 'O2 référence [%]',
    'Aeraulic Pressure Loss': 'Pertes de charge aéraulique',
    'Reactor Design': 'Dimensionnement Réacteur',
    'Electric Consumption Belt': 'Consommation électrique vis sans fin',
    'Compressed Air Consumption': 'Consommation air comprimé',
    'Ash Evacuation': 'Évacuation des résidus',
    'Summary of Main Parameters': 'Résumé des paramètres principaux',
    'Detailed Calculated Parameters': 'Paramètres calculés détaillés',
    'Aeraulic Pressure [mmCE]': 'Pression aéraulique [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Pression de sortie [mmCE]',
    'Flow Rate [Nm3/h]': 'Débit fumées [Nm³/h]',
    'Temperature [°C]': 'Température [°C]',
    'Residence Time [s]': 'Temps de séjour [s]',
    'L/D Ratio': 'Ratio L/D',
    'Agitation Type': 'Type agitation',
    'Design Results': 'Résultats du dimensionnement',
    'Reactor Volume [m³]': 'Volume réacteur [m³]',
    'Diameter [m]': 'Diamètre [m]',
    'Height [m]': 'Hauteur [m]',
    'Agitation Power [kW]': 'Puissance agitation [kW]',
    'Air Consumption [Nm3/h]': 'Consommation air [Nm³/h]',
    'Electric consumption belt [kW]': 'Conso élec vis de transport [kW]',
    'Belt Consumption [kW]': 'Consommation vis transport [kW]',
    'Number of cycles [Nb]': 'Nombre de cycles [Nb]',
    'Compressed air pressure [Bar]': 'Pression air comprimé [Bar]',
    'Air per cycle [Nm3/cycle]': 'Air comprime par cycle [Nm3/cycle]',
    'Electric Consumption [kW]': 'Conso électrique [kW]',
    'Truck Type': 'Type de camion',
    'Distance [km]': 'Distance [km]',
    'Residues [kg/h]': 'Résidus [kg/h]',
    'CO2 Transport [kg]': 'CO2 transport [kg]',
    'Cost Transport [€]': 'Coût transport [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Réacteur à sec — Rapport de synthèse',
    rpt_section_combustion: '1. Gaz de combustion',
    rpt_temp_sortie: 'Température de sortie',
    rpt_o2_mesure_sec: 'O₂ mesuré (sec)',
    rpt_debit_humide_total: 'Débit humide total [kg/h]',
    rpt_debit_sec: 'Débit sec [Nm³/h]',
    rpt_debit_humide: 'Débit humide [Nm³/h]',
    rpt_composition_gaz_sortie: 'Composition gaz de sortie',
    rpt_section_emissions: '2. Émissions polluantes',
    rpt_gaz_entree: 'Gaz en entrée [kg/h]',
    rpt_gaz_sortie: 'Gaz en sortie [kg/h]',
    rpt_residus_calcules: 'Résidus calculés',
    rpt_cendres_lourdes_seches: 'Cendres lourdes sèches [kg/h]',
    rpt_cendres_volantes: 'Cendres volantes [kg/h]',
    rpt_conso_reactifs: 'Consommation réactifs',
    rpt_eau_potable: 'Eau potable [m³/h]',
    rpt_eau_demineralisee: 'Eau déminéralisée [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ sec [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Design',
    rpt_conso_electriques: 'Consommations électriques',
    rpt_donnees_indisponibles_design: 'Données non disponibles (ouvrir l\'onglet Design)',
    rpt_conso_eau: 'Consommation d\'eau',
    rpt_energie_auxiliaire: 'Énergie auxiliaire',
    rpt_gaz_haute_valeur: 'Gaz haute valeur [MW]',
    rpt_fuel: 'Fuel [MW]',
    rpt_section_opex: '4. OPEX — Coûts horaires',
    rpt_opex_unavailable: 'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.',
    rpt_electricite: 'Électricité',
    rpt_eau: 'Eau',
    rpt_reactifs: 'Réactifs',
    rpt_energie: 'Énergie',
    rpt_total_cout: 'Total coût',
    rpt_cout_horaire: 'Coût horaire',
    rpt_cout_annuel: 'Coût annuel',
    rpt_total_co2_kgh: 'Total CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ électricité',
    rpt_co2_energie: 'CO₂ énergie',
    rpt_total_co2: 'Total CO₂',
    rpt_consommateur: 'Consommateur',
    rpt_total: 'Total',
    rpt_footer: 'Rapport généré automatiquement',
  },

  en: {
    stackConfiguration: 'REACTOR Configuration',
    backToFlow: 'Back to Flow',
    clearMemory: 'Clear memory',
    resetToDefaultValues: 'Reset to Default Values',
    note: 'Note',
    none: 'None',
    flueGases: 'Flue gases',
    pollutantEmissions: 'Pollutant Emissions',
    design: 'Design',
    opex: 'Opex',
    calculationParameters: 'Calculation parameters',
    calculatedParameters: 'Calculated parameters',
    resetValues: 'Reset values',
    temperatureInletREACTOR: 'Temperature inlet REACTOR [°C]',
    deltaEnthalpies: 'Delta enthalpies [kJ/h]',
    sprayedCoolingWater: 'Sprayed/cooling water [kg/h]',
    flueGasHumidTotal: 'Flue gas total humid [Nm³/h]',
    flueGasInletAtInletTemperature: 'Flue gas composition at inlet',
    airIngressAtAmbientTemperature: 'Air ingress at ambient temperature',
    flueGasOutletAtOutletTemperature: 'Flue gas composition at outlet',
    wasteFlow: 'Waste Flow [kg/h]',
    flueGasFlowWet: 'Flue gas Flow Wet [Nm³/h]',
    flueGasFlowDry: 'Flue gas Flow Dry [Nm³/h]',
    O2Calculated: 'O2 calculated [%]',
    inertMass: 'inert mass [kg/h]',
    bottomAsh: 'Bottom ash [kg/h]',
    bottomAshWet: 'Bottom ash wet [kg/h]',
    flyAsh: 'Fly ash [kg/h]',
    pollutantTreatmentTable: 'Pollutant Treatment Table',
    pollutant: 'Pollutant',
    reactif: 'Reactif',
    mass: 'Mass (kg/h)',
    efficiency: 'Efficiency (%)',
    stoichiometryCoeff: 'Stoichiometry Coeff',
    outputMass: 'Output Mass',
    residueMass: 'Residue Mass',
    reactifMass: 'Reactif Mass',
    abatedMass: 'Abated Mass',
    inputFlueGas: 'Input flue gas',
    outputFlueGas: 'Output flue gas',
    bottomAshesCalculated: 'Bottom ashes calculated',
    aeraulicPressureLoss: 'Aeraulic Pressure Loss',
    reactorDesign: 'Reactor Design',
    designResults: 'Design Results',
    electricConsumptionVisBelt: 'Electric Consumption Vis Belt',
    visBeltConsumption: 'Vis Belt Consumption',
    compressedAirConsumption: 'Compressed Air Consumption',
    evacuationREACTORResidues: 'Evacuation REACTOR Residues',
    residuesTransport: 'Residues Transport',
    reactorVolume: 'Reactor Volume [m³]',
    diameter: 'Diameter [m]',
    height: 'Height [m]',
    residenceTime: 'Residence Time [s]',
    gasVelocity: 'Gas Velocity [m/s]',
    pressureLoss: 'Pressure Loss [mmCE]',
    agitationPower: 'Agitation Power [kW]',
    agitationAir: 'Agitation Air [Nm³/h]',
    consumptionVisBelt: 'Consumption Vis Belt [kW]',
    compressedAirPressure: 'Compressed Air Pressure [Bar]',
    airConsumption: 'Air Consumption [Nm³/h]',
    reactorDiameter: 'Reactor Diameter [m]',
    reactorHeight: 'Reactor Height [m]',
    reactorAgitation: 'Thereof reactor agitation [Nm³/h]',
    filterCleaning: 'Thereof filter cleaning [Nm³/h]',
    compressedAirElecConsumption: 'Compressed Air Elec Consumption [kW]',
    residuesREACTOR: 'Residues REACTOR [kg/h]',
    truckType: 'Truck Type',
    distance: 'Distance [km]',
    CO2TransportTotal: 'CO2 Transport Total [kg]',
    costTransportTotal: 'Cost Transport Total [€]',
    P_out_mmCE: 'P out [mmCE]',
    visBelt: 'Vis Belt',
    compressedAir: 'Compressed Air',
    mechanicalAgitation: 'Mechanical Agitation',
    notUsed: 'Not Used',
    pump: 'Pump',
    reactor: 'Reactor',
    summaryMainParameters: 'Summary Main Parameters',
    evacuatedAsh: 'Evacuated Ash',
    detailedCalculatedParameters: 'Detailed Calculated Parameters',
    pressureAeraulique: 'Aeraulic Pressure [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Flue gas Flow [Nm³/h]',
    temperature: 'Temperature [°C]',
    ldRatio: 'L/D Ratio',
    agitationType: 'Agitation Type',
    mechanical: 'Mechanical',
    air: 'Pneumatic',
    consoElecVis: 'Electric consumption vis [kW]',
    nombreCycles: 'Number of cycles [Nb]',
    pressionAirComprime: 'Compressed Air Pressure [Bar]',
    airComprimeCycle: 'Compressed air per cycle [Nm3/cycle]',
    typesCamion: 'Truck Type',
    distanceTransport: 'Distance [km]',
    flueGasTemperatureOutlet: 'Flue gas outlet temperature [°C]',
    ambientAirTemperature: 'Ambient air temperature [°C]',
    volumeAirIngress: 'Air ingress volume [Nm³/h]',
    thermalLosses: 'Thermal losses [%]',
    coolingWaterTemperature: 'Cooling water temperature [°C]',
    flyAshesContent: 'Fly ash content [g/Nm³]',
    siccityBottomAsh: 'Bottom ash siccity [%]',
    O2ref: 'Reference O2 [%]',
    'Fly ashes content [g/Nm3]': 'Fly ash content [g/Nm³]',
    'siccity bottom ash [%]': 'Bottom ash siccity [%]',
    'siccity residus [%]': 'Residues siccity [%]',
    'O2 ref [%]': 'Reference O2 [%]',
    'Aeraulic Pressure Loss': 'Aeraulic Pressure Loss',
    'Reactor Design': 'Reactor Design',
    'Electric Consumption Belt': 'Electric Consumption Belt',
    'Compressed Air Consumption': 'Compressed Air Consumption',
    'Ash Evacuation': 'Ash Evacuation',
    'Summary of Main Parameters': 'Summary of Main Parameters',
    'Detailed Calculated Parameters': 'Detailed Calculated Parameters',
    'Aeraulic Pressure [mmCE]': 'Aeraulic Pressure [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Output Pressure [mmCE]',
    'Flow Rate [Nm3/h]': 'Flow Rate [Nm³/h]',
    'Temperature [°C]': 'Temperature [°C]',
    'Residence Time [s]': 'Residence Time [s]',
    'L/D Ratio': 'L/D Ratio',
    'Agitation Type': 'Agitation Type',
    'Design Results': 'Design Results',
    'Reactor Volume [m³]': 'Reactor Volume [m³]',
    'Diameter [m]': 'Diameter [m]',
    'Height [m]': 'Height [m]',
    'Agitation Power [kW]': 'Agitation Power [kW]',
    'Air Consumption [Nm3/h]': 'Air Consumption [Nm³/h]',
    'Electric consumption belt [kW]': 'Electric consumption belt [kW]',
    'Belt Consumption [kW]': 'Belt Consumption [kW]',
    'Number of cycles [Nb]': 'Number of cycles [Nb]',
    'Compressed air pressure [Bar]': 'Compressed Air Pressure [Bar]',
    'Air per cycle [Nm3/cycle]': 'Air per cycle [Nm³/cycle]',
    'Electric Consumption [kW]': 'Electric Consumption [kW]',
    'Truck Type': 'Truck Type',
    'Distance [km]': 'Distance [km]',
    'Residues [kg/h]': 'Residues [kg/h]',
    'CO2 Transport [kg]': 'CO2 Transport [kg]',
    'Cost Transport [€]': 'Cost Transport [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Dry Reactor — Synthesis Report',
    rpt_section_combustion: '1. Flue Gases',
    rpt_temp_sortie: 'Outlet temperature',
    rpt_o2_mesure_sec: 'O₂ measured (dry)',
    rpt_debit_humide_total: 'Total wet flow rate [kg/h]',
    rpt_debit_sec: 'Dry flow rate [Nm³/h]',
    rpt_debit_humide: 'Wet flow rate [Nm³/h]',
    rpt_composition_gaz_sortie: 'Outlet gas composition',
    rpt_section_emissions: '2. Pollutant Emissions',
    rpt_gaz_entree: 'Inlet gases [kg/h]',
    rpt_gaz_sortie: 'Outlet gases [kg/h]',
    rpt_residus_calcules: 'Calculated residues',
    rpt_cendres_lourdes_seches: 'Dry bottom ash [kg/h]',
    rpt_cendres_volantes: 'Fly ash [kg/h]',
    rpt_conso_reactifs: 'Reagent consumption',
    rpt_eau_potable: 'Potable water [m³/h]',
    rpt_eau_demineralisee: 'Demineralised water [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ dry [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Design',
    rpt_conso_electriques: 'Electrical consumptions',
    rpt_donnees_indisponibles_design: 'Data unavailable (open the Design tab)',
    rpt_conso_eau: 'Water consumption',
    rpt_energie_auxiliaire: 'Auxiliary energy',
    rpt_gaz_haute_valeur: 'High-value gas [MW]',
    rpt_fuel: 'Fuel [MW]',
    rpt_section_opex: '4. OPEX — Hourly costs',
    rpt_opex_unavailable: 'OPEX costs unavailable — open the Design and Opex tabs.',
    rpt_electricite: 'Electricity',
    rpt_eau: 'Water',
    rpt_reactifs: 'Reagents',
    rpt_energie: 'Energy',
    rpt_total_cout: 'Total cost',
    rpt_cout_horaire: 'Hourly cost',
    rpt_cout_annuel: 'Annual cost',
    rpt_total_co2_kgh: 'Total CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ electricity',
    rpt_co2_energie: 'CO₂ energy',
    rpt_total_co2: 'Total CO₂',
    rpt_consommateur: 'Consumer',
    rpt_total: 'Total',
    rpt_footer: 'Automatically generated report',
  },

  de: {
    stackConfiguration: 'REACTOR-Konfiguration',
    backToFlow: 'Zurück zum Fluss',
    clearMemory: 'Speicher löschen',
    resetToDefaultValues: 'Auf Standardwerte zurücksetzen',
    note: 'Hinweis',
    none: 'Keine',
    flueGases: 'Rauchgase',
    pollutantEmissions: 'Schadstoffemissionen',
    design: 'Design',
    opex: 'Opex',
    calculationParameters: 'Berechnungsparameter',
    calculatedParameters: 'Berechnete Parameter',
    resetValues: 'Werte zurücksetzen',
    temperatureInletREACTOR: 'Temperatur Einlass REACTOR [°C]',
    deltaEnthalpies: 'Delta Enthalpien [kJ/h]',
    sprayedCoolingWater: 'Gesprühtes/Kühlwasser [kg/h]',
    flueGasHumidTotal: 'Gesamte feuchte Rauchgase [Nm³/h]',
    flueGasInletAtInletTemperature: 'Rauchgaszusammensetzung beim Einlass',
    airIngressAtAmbientTemperature: 'Lufteintritt bei Umgebungstemperatur',
    flueGasOutletAtOutletTemperature: 'Rauchgaszusammensetzung beim Auslass',
    wasteFlow: 'Abfallfluss [kg/h]',
    flueGasFlowWet: 'Rauchgasstrom feucht [Nm³/h]',
    flueGasFlowDry: 'Rauchgasstrom trocken [Nm³/h]',
    O2Calculated: 'Berechnetes O2 [%]',
    inertMass: 'Inertmasse [kg/h]',
    bottomAsh: 'Flugasche [kg/h]',
    bottomAshWet: 'Flugasche nass [kg/h]',
    flyAsh: 'Flugasche [kg/h]',
    pollutantTreatmentTable: 'Schadstoffbehandlungstabelle',
    pollutant: 'Schadstoff',
    reactif: 'Reagenz',
    mass: 'Masse (kg/h)',
    efficiency: 'Effizienz (%)',
    stoichiometryCoeff: 'Stoich. Koeff',
    outputMass: 'Ausgabemasse',
    residueMass: 'Restmasse',
    reactifMass: 'Reagenzmasse',
    abatedMass: 'Verminderte Masse',
    inputFlueGas: 'Eingangsrauchgas',
    outputFlueGas: 'Ausgangsrauchgas',
    bottomAshesCalculated: 'Berechnete Flugasche',
    aeraulicPressureLoss: 'Aeroraulische Druckverluste',
    reactorDesign: 'Reaktorauslegung',
    designResults: 'Auslegungsergebnisse',
    electricConsumptionVisBelt: 'Stromverbrauch Schneckenförderer',
    visBeltConsumption: 'Stromverbrauch Schneckenförderer',
    compressedAirConsumption: 'Druckluftverbrauch',
    evacuationREACTORResidues: 'Evakuierung von REACTOR-Rückständen',
    residuesTransport: 'Rückstandstransport',
    reactorVolume: 'Reaktorvolumen [m³]',
    diameter: 'Durchmesser [m]',
    height: 'Höhe [m]',
    residenceTime: 'Verweilzeit [s]',
    gasVelocity: 'Gasgeschwindigkeit [m/s]',
    pressureLoss: 'Druckverlust [mmCE]',
    agitationPower: 'Rührleistung [kW]',
    agitationAir: 'Rührlüftung [Nm³/h]',
    consumptionVisBelt: 'Stromverbrauch Schneckenförderer [kW]',
    compressedAirPressure: 'Druckluffdruck [Bar]',
    airConsumption: 'Luftverbrauch [Nm³/h]',
    reactorDiameter: 'Reaktordurchmesser [m]',
    reactorHeight: 'Reaktorhöhe [m]',
    reactorAgitation: 'Davon Reaktorrührung [Nm³/h]',
    filterCleaning: 'Davon Filterreinigung [Nm³/h]',
    compressedAirElecConsumption: 'Stromverbrauch Druckluft [kW]',
    residuesREACTOR: 'REACTOR-Rückstände [kg/h]',
    truckType: 'Lastkraftwagentyp',
    distance: 'Entfernung [km]',
    CO2TransportTotal: 'Gesamtverkehrs-CO2 [kg]',
    costTransportTotal: 'Gesamttransportkosten [€]',
    P_out_mmCE: 'Druck aus [mmCE]',
    visBelt: 'Schneckenförderer',
    compressedAir: 'Druckluft',
    mechanicalAgitation: 'Mechanische Rührung',
    notUsed: 'Nicht verwendet',
    pump: 'Pumpe',
    reactor: 'Reaktor',
    summaryMainParameters: 'Zusammenfassung der Hauptparameter',
    evacuatedAsh: 'Evakuierte Asche',
    detailedCalculatedParameters: 'Detaillierte berechnete Parameter',
    pressureAeraulique: 'Aerostatischer Druck [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Rauchgasstrom [Nm³/h]',
    temperature: 'Temperatur [°C]',
    ldRatio: 'L/D Verhältnis',
    agitationType: 'Rührungstyp',
    mechanical: 'Mechanisch',
    air: 'Pneumatisch',
    consoElecVis: 'Stromverbrauch Schneckenförderer [kW]',
    nombreCycles: 'Anzahl der Zyklen [Nb]',
    pressionAirComprime: 'Druckluffdruck [Bar]',
    airComprimeCycle: 'Druckluft pro Zyklus [Nm3/Zyklus]',
    typesCamion: 'Lastkraftwagentyp',
    distanceTransport: 'Entfernung [km]',
    flueGasTemperatureOutlet: 'Rauchgasaustrittstemperatur [°C]',
    ambientAirTemperature: 'Umgebungslufttemperatur [°C]',
    volumeAirIngress: 'Lufteinlassvolumen [Nm³/h]',
    thermalLosses: 'Thermische Verluste [%]',
    coolingWaterTemperature: 'Kühlwassertemperatur [°C]',
    flyAshesContent: 'Flugaschegehalt [g/Nm³]',
    siccityBottomAsh: 'Siccität der Bodenasche [%]',
    O2ref: 'Referenz O2 [%]',
    'Fly ashes content [g/Nm3]': 'Flugaschegehalt [g/Nm³]',
    'siccity bottom ash [%]': 'Feuchte der Bodenasche [%]',
    'siccity residus [%]': 'Feuchte der Rückstände [%]',
    'O2 ref [%]': 'Referenz O2 [%]',
    'Aeraulic Pressure Loss': 'Aeroraulische Druckverluste',
    'Reactor Design': 'Reaktorauslegung',
    'Electric Consumption Belt': 'Stromverbrauch Schneckenförderer',
    'Compressed Air Consumption': 'Druckluftverbrauch',
    'Ash Evacuation': 'Evakuierung von Rückständen',
    'Summary of Main Parameters': 'Zusammenfassung der Hauptparameter',
    'Detailed Calculated Parameters': 'Detaillierte berechnete Parameter',
    'Aeraulic Pressure [mmCE]': 'Aerostatischer Druck [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Ausgangsdruck [mmCE]',
    'Flow Rate [Nm3/h]': 'Rauchgasstrom [Nm³/h]',
    'Temperature [°C]': 'Temperatur [°C]',
    'Residence Time [s]': 'Verweilzeit [s]',
    'L/D Ratio': 'L/D Verhältnis',
    'Agitation Type': 'Rührungstyp',
    'Design Results': 'Auslegungsergebnisse',
    'Reactor Volume [m³]': 'Reaktorvolumen [m³]',
    'Diameter [m]': 'Durchmesser [m]',
    'Height [m]': 'Höhe [m]',
    'Agitation Power [kW]': 'Rührleistung [kW]',
    'Air Consumption [Nm3/h]': 'Luftverbrauch [Nm³/h]',
    'Electric consumption belt [kW]': 'Stromverbrauch Schneckenförderer [kW]',
    'Belt Consumption [kW]': 'Stromverbrauch Schneckenförderer [kW]',
    'Number of cycles [Nb]': 'Anzahl der Zyklen [Nb]',
    'Compressed air pressure [Bar]': 'Druckluffdruck [Bar]',
    'Air per cycle [Nm3/cycle]': 'Druckluft pro Zyklus [Nm³/Zyklus]',
    'Electric Consumption [kW]': 'Stromverbrauch [kW]',
    'Truck Type': 'Lastkraftwagentyp',
    'Distance [km]': 'Entfernung [km]',
    'Residues [kg/h]': 'Rückstände [kg/h]',
    'CO2 Transport [kg]': 'Verkehrs-CO2 [kg]',
    'Cost Transport [€]': 'Transportkosten [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Trockenreaktor — Synthesebericht',
    rpt_section_combustion: '1. Rauchgase',
    rpt_temp_sortie: 'Auslasstemperatur',
    rpt_o2_mesure_sec: 'O₂ gemessen (trocken)',
    rpt_debit_humide_total: 'Gesamter Nassvolumenstrom [kg/h]',
    rpt_debit_sec: 'Trockener Volumenstrom [Nm³/h]',
    rpt_debit_humide: 'Nasser Volumenstrom [Nm³/h]',
    rpt_composition_gaz_sortie: 'Auslassgaszusammensetzung',
    rpt_section_emissions: '2. Schadstoffemissionen',
    rpt_gaz_entree: 'Eingangsgas [kg/h]',
    rpt_gaz_sortie: 'Ausgangsgas [kg/h]',
    rpt_residus_calcules: 'Berechnete Rückstände',
    rpt_cendres_lourdes_seches: 'Trockene Bodenasche [kg/h]',
    rpt_cendres_volantes: 'Flugasche [kg/h]',
    rpt_conso_reactifs: 'Reagenzverbrauch',
    rpt_eau_potable: 'Trinkwasser [m³/h]',
    rpt_eau_demineralisee: 'Entmineralisiertes Wasser [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ trocken [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Design',
    rpt_conso_electriques: 'Stromverbräuche',
    rpt_donnees_indisponibles_design: 'Daten nicht verfügbar (Design-Tab öffnen)',
    rpt_conso_eau: 'Wasserverbrauch',
    rpt_energie_auxiliaire: 'Hilfsenergie',
    rpt_gaz_haute_valeur: 'Hochwertiges Gas [MW]',
    rpt_fuel: 'Kraftstoff [MW]',
    rpt_section_opex: '4. OPEX — Stündliche Kosten',
    rpt_opex_unavailable: 'OPEX-Kosten nicht verfügbar — Design- und Opex-Tabs öffnen.',
    rpt_electricite: 'Strom',
    rpt_eau: 'Wasser',
    rpt_reactifs: 'Reagenzien',
    rpt_energie: 'Energie',
    rpt_total_cout: 'Gesamtkosten',
    rpt_cout_horaire: 'Stündliche Kosten',
    rpt_cout_annuel: 'Jährliche Kosten',
    rpt_total_co2_kgh: 'Gesamt CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ Strom',
    rpt_co2_energie: 'CO₂ Energie',
    rpt_total_co2: 'Gesamt CO₂',
    rpt_consommateur: 'Verbraucher',
    rpt_total: 'Gesamt',
    rpt_footer: 'Automatisch generierter Bericht',
  },

  es: {
    stackConfiguration: 'Configuración REACTOR',
    backToFlow: 'Volver al flujo',
    clearMemory: 'Limpiar memoria',
    resetToDefaultValues: 'Restablecer valores predeterminados',
    note: 'Nota',
    none: 'Ninguno',
    flueGases: 'Gases de escape',
    pollutantEmissions: 'Emisiones de contaminantes',
    design: 'Diseño',
    opex: 'Opex',
    calculationParameters: 'Parámetros de cálculo',
    calculatedParameters: 'Parámetros calculados',
    resetValues: 'Restablecer valores',
    temperatureInletREACTOR: 'Temperatura entrada REACTOR [°C]',
    deltaEnthalpies: 'Delta entalpías [kJ/h]',
    sprayedCoolingWater: 'Agua pulverizada/enfriamiento [kg/h]',
    flueGasHumidTotal: 'Gas de escape total húmedo [Nm³/h]',
    flueGasInletAtInletTemperature: 'Composición de gas de escape en la entrada',
    airIngressAtAmbientTemperature: 'Entrada de aire a temperatura ambiente',
    flueGasOutletAtOutletTemperature: 'Composición de gas de escape en la salida',
    wasteFlow: 'Caudal de residuos [kg/h]',
    flueGasFlowWet: 'Caudal de gas de escape húmedo [Nm³/h]',
    flueGasFlowDry: 'Caudal de gas de escape seco [Nm³/h]',
    O2Calculated: 'O2 calculado [%]',
    inertMass: 'Masa inerte [kg/h]',
    bottomAsh: 'Ceniza de fondo [kg/h]',
    bottomAshWet: 'Ceniza de fondo húmeda [kg/h]',
    flyAsh: 'Ceniza volante [kg/h]',
    pollutantTreatmentTable: 'Tabla de tratamiento de contaminantes',
    pollutant: 'Contaminante',
    reactif: 'Reactivo',
    mass: 'Masa (kg/h)',
    efficiency: 'Eficiencia (%)',
    stoichiometryCoeff: 'Coef. Estequiometría',
    outputMass: 'Masa de salida',
    residueMass: 'Masa de residuo',
    reactifMass: 'Masa de reactivo',
    abatedMass: 'Masa reducida',
    inputFlueGas: 'Gas de escape de entrada',
    outputFlueGas: 'Gas de escape de salida',
    bottomAshesCalculated: 'Ceniza de fondo calculada',
    aeraulicPressureLoss: 'Pérdida de presión aeráulica',
    reactorDesign: 'Diseño de reactor',
    designResults: 'Resultados de diseño',
    electricConsumptionVisBelt: 'Consumo eléctrico transportador de tornillo',
    visBeltConsumption: 'Consumo transportador de tornillo',
    compressedAirConsumption: 'Consumo de aire comprimido',
    evacuationREACTORResidues: 'Evacuación de residuos REACTOR',
    residuesTransport: 'Transporte de residuos',
    reactorVolume: 'Volumen del reactor [m³]',
    diameter: 'Diámetro [m]',
    height: 'Altura [m]',
    residenceTime: 'Tiempo de residencia [s]',
    gasVelocity: 'Velocidad del gas [m/s]',
    pressureLoss: 'Pérdida de presión [mmCE]',
    agitationPower: 'Potencia de agitación [kW]',
    agitationAir: 'Aire de agitación [Nm³/h]',
    consumptionVisBelt: 'Consumo transportador de tornillo [kW]',
    compressedAirPressure: 'Presión aire comprimido [Bar]',
    airConsumption: 'Consumo de aire [Nm³/h]',
    reactorDiameter: 'Diámetro del reactor [m]',
    reactorHeight: 'Altura del reactor [m]',
    reactorAgitation: 'De los cuales agitación reactor [Nm³/h]',
    filterCleaning: 'De los cuales limpieza de filtros [Nm³/h]',
    compressedAirElecConsumption: 'Consumo eléctrico aire comprimido [kW]',
    residuesREACTOR: 'Residuos REACTOR [kg/h]',
    truckType: 'Tipo de camión',
    distance: 'Distancia [km]',
    CO2TransportTotal: 'CO2 transporte total [kg]',
    costTransportTotal: 'Costo transporte total [€]',
    P_out_mmCE: 'P salida [mmCE]',
    visBelt: 'Transportador de tornillo',
    compressedAir: 'Aire comprimido',
    mechanicalAgitation: 'Agitación mecánica',
    notUsed: 'No utilizado',
    pump: 'Bomba',
    reactor: 'Reactor',
    summaryMainParameters: 'Resumen de parámetros principales',
    evacuatedAsh: 'Ceniza evacuada',
    detailedCalculatedParameters: 'Parámetros calculados detallados',
    pressureAeraulique: 'Presión aeráulica [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Caudal gases [Nm³/h]',
    temperature: 'Temperatura [°C]',
    ldRatio: 'Relación L/D',
    agitationType: 'Tipo de agitación',
    mechanical: 'Mecánico',
    air: 'Neumático',
    consoElecVis: 'Consumo eléctrico tornillo [kW]',
    nombreCycles: 'Número de ciclos [Nb]',
    pressionAirComprime: 'Presión aire comprimido [Bar]',
    airComprimeCycle: 'Aire comprimido por ciclo [Nm3/ciclo]',
    typesCamion: 'Tipo de camión',
    distanceTransport: 'Distancia [km]',
    flueGasTemperatureOutlet: 'Temperatura de salida de gases de escape [°C]',
    ambientAirTemperature: 'Temperatura del aire ambiente [°C]',
    volumeAirIngress: 'Volumen de entrada de aire [Nm³/h]',
    thermalLosses: 'Pérdidas térmicas [%]',
    coolingWaterTemperature: 'Temperatura del agua de refrigeración [°C]',
    flyAshesContent: 'Contenido ceniza volante [g/Nm³]',
    siccityBottomAsh: 'Siccidad ceniza fondo [%]',
    O2ref: 'O2 referencia [%]',
    'Fly ashes content [g/Nm3]': 'Contenido ceniza volante [g/Nm³]',
    'siccity bottom ash [%]': 'Siccidad ceniza fondo [%]',
    'siccity residus [%]': 'Siccidad residuos [%]',
    'O2 ref [%]': 'O2 referencia [%]',
    'Aeraulic Pressure Loss': 'Pérdida de presión aeráulica',
    'Reactor Design': 'Diseño de reactor',
    'Electric Consumption Belt': 'Consumo eléctrico transportador de tornillo',
    'Compressed Air Consumption': 'Consumo de aire comprimido',
    'Ash Evacuation': 'Evacuación de residuos',
    'Summary of Main Parameters': 'Resumen de parámetros principales',
    'Detailed Calculated Parameters': 'Parámetros calculados detallados',
    'Aeraulic Pressure [mmCE]': 'Presión aeráulica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Presión salida [mmCE]',
    'Flow Rate [Nm3/h]': 'Caudal gases [Nm³/h]',
    'Temperature [°C]': 'Temperatura [°C]',
    'Residence Time [s]': 'Tiempo de residencia [s]',
    'L/D Ratio': 'Relación L/D',
    'Agitation Type': 'Tipo de agitación',
    'Design Results': 'Resultados de diseño',
    'Reactor Volume [m³]': 'Volumen del reactor [m³]',
    'Diameter [m]': 'Diámetro [m]',
    'Height [m]': 'Altura [m]',
    'Agitation Power [kW]': 'Potencia de agitación [kW]',
    'Air Consumption [Nm3/h]': 'Consumo de aire [Nm³/h]',
    'Electric consumption belt [kW]': 'Consumo eléctrico tornillo [kW]',
    'Belt Consumption [kW]': 'Consumo transportador de tornillo [kW]',
    'Number of cycles [Nb]': 'Número de ciclos [Nb]',
    'Compressed air pressure [Bar]': 'Presión aire comprimido [Bar]',
    'Air per cycle [Nm3/cycle]': 'Aire comprimido por ciclo [Nm³/ciclo]',
    'Electric Consumption [kW]': 'Consumo eléctrico [kW]',
    'Truck Type': 'Tipo de camión',
    'Distance [km]': 'Distancia [km]',
    'Residues [kg/h]': 'Residuos [kg/h]',
    'CO2 Transport [kg]': 'CO2 transporte [kg]',
    'Cost Transport [€]': 'Costo transporte [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Reactor seco — Informe de síntesis',
    rpt_section_combustion: '1. Gases de combustión',
    rpt_temp_sortie: 'Temperatura de salida',
    rpt_o2_mesure_sec: 'O₂ medido (seco)',
    rpt_debit_humide_total: 'Caudal húmedo total [kg/h]',
    rpt_debit_sec: 'Caudal seco [Nm³/h]',
    rpt_debit_humide: 'Caudal húmedo [Nm³/h]',
    rpt_composition_gaz_sortie: 'Composición del gas de salida',
    rpt_section_emissions: '2. Emisiones contaminantes',
    rpt_gaz_entree: 'Gas de entrada [kg/h]',
    rpt_gaz_sortie: 'Gas de salida [kg/h]',
    rpt_residus_calcules: 'Residuos calculados',
    rpt_cendres_lourdes_seches: 'Ceniza de fondo seca [kg/h]',
    rpt_cendres_volantes: 'Ceniza volante [kg/h]',
    rpt_conso_reactifs: 'Consumo de reactivos',
    rpt_eau_potable: 'Agua potable [m³/h]',
    rpt_eau_demineralisee: 'Agua desmineralizada [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ seco [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Diseño',
    rpt_conso_electriques: 'Consumos eléctricos',
    rpt_donnees_indisponibles_design: 'Datos no disponibles (abrir la pestaña Diseño)',
    rpt_conso_eau: 'Consumo de agua',
    rpt_energie_auxiliaire: 'Energía auxiliar',
    rpt_gaz_haute_valeur: 'Gas de alto valor [MW]',
    rpt_fuel: 'Combustible [MW]',
    rpt_section_opex: '4. OPEX — Costos horarios',
    rpt_opex_unavailable: 'Costos OPEX no disponibles — abrir las pestañas Diseño y Opex.',
    rpt_electricite: 'Electricidad',
    rpt_eau: 'Agua',
    rpt_reactifs: 'Reactivos',
    rpt_energie: 'Energía',
    rpt_total_cout: 'Costo total',
    rpt_cout_horaire: 'Costo horario',
    rpt_cout_annuel: 'Costo anual',
    rpt_total_co2_kgh: 'Total CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ electricidad',
    rpt_co2_energie: 'CO₂ energía',
    rpt_total_co2: 'Total CO₂',
    rpt_consommateur: 'Consumidor',
    rpt_total: 'Total',
    rpt_footer: 'Informe generado automáticamente',
  },

  it: {
    stackConfiguration: 'Configurazione REACTOR',
    backToFlow: 'Torna al flusso',
    clearMemory: 'Cancella memoria',
    resetToDefaultValues: 'Ripristina valori predefiniti',
    note: 'Nota',
    none: 'Nessuno',
    flueGases: 'Gas di scarico',
    pollutantEmissions: 'Emissioni di inquinanti',
    design: 'Design',
    opex: 'Opex',
    calculationParameters: 'Parametri di calcolo',
    calculatedParameters: 'Parametri calcolati',
    resetValues: 'Ripristina valori',
    temperatureInletREACTOR: 'Temperatura ingresso REACTOR [°C]',
    deltaEnthalpies: 'Delta entalpie [kJ/h]',
    sprayedCoolingWater: 'Acqua polverizzata/raffreddamento [kg/h]',
    flueGasHumidTotal: 'Gas di scarico totale umido [Nm³/h]',
    flueGasInletAtInletTemperature: 'Composizione gas di scarico all\'ingresso',
    airIngressAtAmbientTemperature: 'Ingresso aria a temperatura ambiente',
    flueGasOutletAtOutletTemperature: 'Composizione gas di scarico all\'uscita',
    wasteFlow: 'Portata rifiuti [kg/h]',
    flueGasFlowWet: 'Portata gas di scarico umido [Nm³/h]',
    flueGasFlowDry: 'Portata gas di scarico secco [Nm³/h]',
    O2Calculated: 'O2 calcolato [%]',
    inertMass: 'Massa inerte [kg/h]',
    bottomAsh: 'Cenere di fondo [kg/h]',
    bottomAshWet: 'Cenere di fondo bagnata [kg/h]',
    flyAsh: 'Cenere volante [kg/h]',
    pollutantTreatmentTable: 'Tabella trattamento inquinanti',
    pollutant: 'Inquinante',
    reactif: 'Reagente',
    mass: 'Massa (kg/h)',
    efficiency: 'Efficienza (%)',
    stoichiometryCoeff: 'Coeff. Stechiometria',
    outputMass: 'Massa in uscita',
    residueMass: 'Massa residua',
    reactifMass: 'Massa reagente',
    abatedMass: 'Massa ridotta',
    inputFlueGas: 'Gas di scarico in ingresso',
    outputFlueGas: 'Gas di scarico in uscita',
    bottomAshesCalculated: 'Cenere di fondo calcolata',
    aeraulicPressureLoss: 'Perdita di pressione aerodinamica',
    reactorDesign: 'Progettazione del reattore',
    designResults: 'Risultati di progettazione',
    electricConsumptionVisBelt: 'Consumo elettrico trasportatore a vite',
    visBeltConsumption: 'Consumo trasportatore a vite',
    compressedAirConsumption: 'Consumo aria compressa',
    evacuationREACTORResidues: 'Evacuazione residui REACTOR',
    residuesTransport: 'Trasporto residui',
    reactorVolume: 'Volume reattore [m³]',
    diameter: 'Diametro [m]',
    height: 'Altezza [m]',
    residenceTime: 'Tempo di permanenza [s]',
    gasVelocity: 'Velocità gas [m/s]',
    pressureLoss: 'Perdita di pressione [mmCE]',
    agitationPower: 'Potenza agitazione [kW]',
    agitationAir: 'Aria agitazione [Nm³/h]',
    consumptionVisBelt: 'Consumo trasportatore a vite [kW]',
    compressedAirPressure: 'Pressione aria compressa [Bar]',
    airConsumption: 'Consumo aria [Nm³/h]',
    reactorDiameter: 'Diametro reattore [m]',
    reactorHeight: 'Altezza reattore [m]',
    reactorAgitation: 'Di cui agitazione reattore [Nm³/h]',
    filterCleaning: 'Di cui pulizia filtri [Nm³/h]',
    compressedAirElecConsumption: 'Consumo elettrico aria compressa [kW]',
    residuesREACTOR: 'Residui REACTOR [kg/h]',
    truckType: 'Tipo di camion',
    distance: 'Distanza [km]',
    CO2TransportTotal: 'CO2 trasporto totale [kg]',
    costTransportTotal: 'Costo trasporto totale [€]',
    P_out_mmCE: 'P uscita [mmCE]',
    visBelt: 'Trasportatore a vite',
    compressedAir: 'Aria compressa',
    mechanicalAgitation: 'Agitazione meccanica',
    notUsed: 'Non utilizzato',
    pump: 'Pompa',
    reactor: 'Reattore',
    summaryMainParameters: 'Riepilogo parametri principali',
    evacuatedAsh: 'Cenere evacuata',
    detailedCalculatedParameters: 'Parametri calcolati dettagliati',
    pressureAeraulique: 'Pressione aerodinamica [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Portata gas [Nm³/h]',
    temperature: 'Temperatura [°C]',
    ldRatio: 'Rapporto L/D',
    agitationType: 'Tipo agitazione',
    mechanical: 'Meccanico',
    air: 'Pneumatico',
    consoElecVis: 'Consumo elettrico trasportatore [kW]',
    nombreCycles: 'Numero di cicli [Nb]',
    pressionAirComprime: 'Pressione aria compressa [Bar]',
    airComprimeCycle: 'Aria compressa per ciclo [Nm3/ciclo]',
    typesCamion: 'Tipo di camion',
    distanceTransport: 'Distanza [km]',
    flueGasTemperatureOutlet: 'Temperatura di uscita dei gas di scarico [°C]',
    ambientAirTemperature: 'Temperatura dell\'aria ambiente [°C]',
    volumeAirIngress: 'Volume di ingresso dell\'aria [Nm³/h]',
    thermalLosses: 'Perdite termiche [%]',
    coolingWaterTemperature: 'Temperatura dell\'acqua di raffreddamento [°C]',
    flyAshesContent: 'Contenuto cenere volante [g/Nm³]',
    siccityBottomAsh: 'Siccità cenere di fondo [%]',
    O2ref: 'O2 riferimento [%]',
    'Fly ashes content [g/Nm3]': 'Contenuto cenere volante [g/Nm³]',
    'siccity bottom ash [%]': 'Siccità cenere di fondo [%]',
    'siccity residus [%]': 'Siccità residui [%]',
    'O2 ref [%]': 'O2 riferimento [%]',
    'Aeraulic Pressure Loss': 'Perdita di pressione aerodinamica',
    'Reactor Design': 'Progettazione del reattore',
    'Electric Consumption Belt': 'Consumo elettrico trasportatore a vite',
    'Compressed Air Consumption': 'Consumo aria compressa',
    'Ash Evacuation': 'Evacuazione residui',
    'Summary of Main Parameters': 'Riepilogo parametri principali',
    'Detailed Calculated Parameters': 'Parametri calcolati dettagliati',
    'Aeraulic Pressure [mmCE]': 'Pressione aerodinamica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Pressione uscita [mmCE]',
    'Flow Rate [Nm3/h]': 'Portata gas [Nm³/h]',
    'Temperature [°C]': 'Temperatura [°C]',
    'Residence Time [s]': 'Tempo di permanenza [s]',
    'L/D Ratio': 'Rapporto L/D',
    'Agitation Type': 'Tipo agitazione',
    'Design Results': 'Risultati di progettazione',
    'Reactor Volume [m³]': 'Volume reattore [m³]',
    'Diameter [m]': 'Diametro [m]',
    'Height [m]': 'Altezza [m]',
    'Agitation Power [kW]': 'Potenza agitazione [kW]',
    'Air Consumption [Nm3/h]': 'Consumo aria [Nm³/h]',
    'Electric consumption belt [kW]': 'Consumo elettrico trasportatore [kW]',
    'Belt Consumption [kW]': 'Consumo trasportatore a vite [kW]',
    'Number of cycles [Nb]': 'Numero di cicli [Nb]',
    'Compressed air pressure [Bar]': 'Pressione aria compressa [Bar]',
    'Air per cycle [Nm3/cycle]': 'Aria compressa per ciclo [Nm³/ciclo]',
    'Electric Consumption [kW]': 'Consumo elettrico [kW]',
    'Truck Type': 'Tipo di camion',
    'Distance [km]': 'Distanza [km]',
    'Residues [kg/h]': 'Residui [kg/h]',
    'CO2 Transport [kg]': 'CO2 trasporto [kg]',
    'Cost Transport [€]': 'Costo trasporto [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Reattore a secco — Rapporto di sintesi',
    rpt_section_combustion: '1. Gas di combustione',
    rpt_temp_sortie: 'Temperatura di uscita',
    rpt_o2_mesure_sec: 'O₂ misurato (secco)',
    rpt_debit_humide_total: 'Portata umida totale [kg/h]',
    rpt_debit_sec: 'Portata secca [Nm³/h]',
    rpt_debit_humide: 'Portata umida [Nm³/h]',
    rpt_composition_gaz_sortie: 'Composizione gas di uscita',
    rpt_section_emissions: '2. Emissioni inquinanti',
    rpt_gaz_entree: 'Gas in ingresso [kg/h]',
    rpt_gaz_sortie: 'Gas in uscita [kg/h]',
    rpt_residus_calcules: 'Residui calcolati',
    rpt_cendres_lourdes_seches: 'Ceneri pesanti secche [kg/h]',
    rpt_cendres_volantes: 'Ceneri volanti [kg/h]',
    rpt_conso_reactifs: 'Consumo reagenti',
    rpt_eau_potable: 'Acqua potabile [m³/h]',
    rpt_eau_demineralisee: 'Acqua demineralizzata [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ secco [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Progettazione',
    rpt_conso_electriques: 'Consumi elettrici',
    rpt_donnees_indisponibles_design: 'Dati non disponibili (aprire la scheda Progettazione)',
    rpt_conso_eau: 'Consumo acqua',
    rpt_energie_auxiliaire: 'Energia ausiliaria',
    rpt_gaz_haute_valeur: 'Gas ad alto valore [MW]',
    rpt_fuel: 'Carburante [MW]',
    rpt_section_opex: '4. OPEX — Costi orari',
    rpt_opex_unavailable: 'Costi OPEX non disponibili — aprire le schede Progettazione e Opex.',
    rpt_electricite: 'Elettricità',
    rpt_eau: 'Acqua',
    rpt_reactifs: 'Reagenti',
    rpt_energie: 'Energia',
    rpt_total_cout: 'Costo totale',
    rpt_cout_horaire: 'Costo orario',
    rpt_cout_annuel: 'Costo annuale',
    rpt_total_co2_kgh: 'Totale CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ elettricità',
    rpt_co2_energie: 'CO₂ energia',
    rpt_total_co2: 'Totale CO₂',
    rpt_consommateur: 'Consumatore',
    rpt_total: 'Totale',
    rpt_footer: 'Rapporto generato automaticamente',
  },

  pt: {
    stackConfiguration: 'Configuração REACTOR',
    backToFlow: 'Voltar ao fluxo',
    clearMemory: 'Limpar memória',
    resetToDefaultValues: 'Redefinir para valores padrão',
    note: 'Nota',
    none: 'Nenhum',
    flueGases: 'Gases de combustão',
    pollutantEmissions: 'Emissões de poluentes',
    design: 'Design',
    opex: 'Opex',
    calculationParameters: 'Parâmetros de cálculo',
    calculatedParameters: 'Parâmetros calculados',
    resetValues: 'Redefinir valores',
    temperatureInletREACTOR: 'Temperatura entrada REACTOR [°C]',
    deltaEnthalpies: 'Delta entalpias [kJ/h]',
    sprayedCoolingWater: 'Água pulverizada/resfriamento [kg/h]',
    flueGasHumidTotal: 'Gás de combustão total úmido [Nm³/h]',
    flueGasInletAtInletTemperature: 'Composição gás de combustão na entrada',
    airIngressAtAmbientTemperature: 'Entrada de ar à temperatura ambiente',
    flueGasOutletAtOutletTemperature: 'Composição gás de combustão na saída',
    wasteFlow: 'Vazão de resíduos [kg/h]',
    flueGasFlowWet: 'Vazão gás de combustão úmido [Nm³/h]',
    flueGasFlowDry: 'Vazão gás de combustão seco [Nm³/h]',
    O2Calculated: 'O2 calculado [%]',
    inertMass: 'Massa inerte [kg/h]',
    bottomAsh: 'Cinza de fundo [kg/h]',
    bottomAshWet: 'Cinza de fundo úmida [kg/h]',
    flyAsh: 'Cinza volante [kg/h]',
    pollutantTreatmentTable: 'Tabela de tratamento de poluentes',
    pollutant: 'Poluente',
    reactif: 'Reagente',
    mass: 'Massa (kg/h)',
    efficiency: 'Eficiência (%)',
    stoichiometryCoeff: 'Coef. Estequiometria',
    outputMass: 'Massa de saída',
    residueMass: 'Massa de resíduo',
    reactifMass: 'Massa de reagente',
    abatedMass: 'Massa reduzida',
    inputFlueGas: 'Gás de combustão de entrada',
    outputFlueGas: 'Gás de combustão de saída',
    bottomAshesCalculated: 'Cinza de fundo calculada',
    aeraulicPressureLoss: 'Perda de pressão aerodinâmica',
    reactorDesign: 'Projeto do reator',
    designResults: 'Resultados do projeto',
    electricConsumptionVisBelt: 'Consumo elétrico do transportador de parafuso',
    visBeltConsumption: 'Consumo do transportador de parafuso',
    compressedAirConsumption: 'Consumo de ar comprimido',
    evacuationREACTORResidues: 'Evacuação de resíduos REACTOR',
    residuesTransport: 'Transporte de resíduos',
    reactorVolume: 'Volume do reator [m³]',
    diameter: 'Diâmetro [m]',
    height: 'Altura [m]',
    residenceTime: 'Tempo de residência [s]',
    gasVelocity: 'Velocidade do gás [m/s]',
    pressureLoss: 'Perda de pressão [mmCE]',
    agitationPower: 'Potência de agitação [kW]',
    agitationAir: 'Ar de agitação [Nm³/h]',
    consumptionVisBelt: 'Consumo transportador de parafuso [kW]',
    compressedAirPressure: 'Pressão ar comprimido [Bar]',
    airConsumption: 'Consumo de ar [Nm³/h]',
    reactorDiameter: 'Diâmetro do reator [m]',
    reactorHeight: 'Altura do reator [m]',
    reactorAgitation: 'Dos quais agitação reator [Nm³/h]',
    filterCleaning: 'Dos quais limpeza de filtros [Nm³/h]',
    compressedAirElecConsumption: 'Consumo elétrico ar comprimido [kW]',
    residuesREACTOR: 'Resíduos REACTOR [kg/h]',
    truckType: 'Tipo de caminhão',
    distance: 'Distância [km]',
    CO2TransportTotal: 'CO2 transporte total [kg]',
    costTransportTotal: 'Custo transporte total [€]',
    P_out_mmCE: 'P saída [mmCE]',
    visBelt: 'Transportador de parafuso',
    compressedAir: 'Ar comprimido',
    mechanicalAgitation: 'Agitação mecânica',
    notUsed: 'Não utilizado',
    pump: 'Bomba',
    reactor: 'Reator',
    summaryMainParameters: 'Resumo de parâmetros principais',
    evacuatedAsh: 'Cinza evacuada',
    detailedCalculatedParameters: 'Parâmetros calculados detalhados',
    pressureAeraulique: 'Pressão aerodinâmica [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Vazão de gases [Nm³/h]',
    temperature: 'Temperatura [°C]',
    ldRatio: 'Proporção L/D',
    agitationType: 'Tipo de agitação',
    mechanical: 'Mecânico',
    air: 'Pneumático',
    consoElecVis: 'Consumo elétrico transportador [kW]',
    nombreCycles: 'Número de ciclos [Nb]',
    pressionAirComprime: 'Pressão ar comprimido [Bar]',
    airComprimeCycle: 'Ar comprimido por ciclo [Nm3/ciclo]',
    typesCamion: 'Tipo de caminhão',
    distanceTransport: 'Distância [km]',
    flueGasTemperatureOutlet: 'Temperatura de saída de gases de combustão [°C]',
    ambientAirTemperature: 'Temperatura do ar ambiente [°C]',
    volumeAirIngress: 'Volume de entrada de ar [Nm³/h]',
    thermalLosses: 'Perdas térmicas [%]',
    coolingWaterTemperature: 'Temperatura da água de resfriamento [°C]',
    flyAshesContent: 'Conteúdo cinza volante [g/Nm³]',
    siccityBottomAsh: 'Siccidade cinza fundo [%]',
    O2ref: 'O2 referência [%]',
    'Fly ashes content [g/Nm3]': 'Conteúdo cinza volante [g/Nm³]',
    'siccity bottom ash [%]': 'Siccidade cinza fundo [%]',
    'siccity residus [%]': 'Siccidade resíduos [%]',
    'O2 ref [%]': 'O2 referência [%]',
    'Aeraulic Pressure Loss': 'Perda de pressão aerodinâmica',
    'Reactor Design': 'Projeto do reator',
    'Electric Consumption Belt': 'Consumo elétrico do transportador de parafuso',
    'Compressed Air Consumption': 'Consumo de ar comprimido',
    'Ash Evacuation': 'Evacuação de resíduos',
    'Summary of Main Parameters': 'Resumo de parâmetros principais',
    'Detailed Calculated Parameters': 'Parâmetros calculados detalhados',
    'Aeraulic Pressure [mmCE]': 'Pressão aerodinâmica [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Pressão saída [mmCE]',
    'Flow Rate [Nm3/h]': 'Vazão de gases [Nm³/h]',
    'Temperature [°C]': 'Temperatura [°C]',
    'Residence Time [s]': 'Tempo de residência [s]',
    'L/D Ratio': 'Proporção L/D',
    'Agitation Type': 'Tipo de agitação',
    'Design Results': 'Resultados do projeto',
    'Reactor Volume [m³]': 'Volume do reator [m³]',
    'Diameter [m]': 'Diâmetro [m]',
    'Height [m]': 'Altura [m]',
    'Agitation Power [kW]': 'Potência de agitação [kW]',
    'Air Consumption [Nm3/h]': 'Consumo de ar [Nm³/h]',
    'Electric consumption belt [kW]': 'Consumo elétrico transportador [kW]',
    'Belt Consumption [kW]': 'Consumo transportador de parafuso [kW]',
    'Number of cycles [Nb]': 'Número de ciclos [Nb]',
    'Compressed air pressure [Bar]': 'Pressão ar comprimido [Bar]',
    'Air per cycle [Nm3/cycle]': 'Ar comprimido por ciclo [Nm³/ciclo]',
    'Electric Consumption [kW]': 'Consumo elétrico [kW]',
    'Truck Type': 'Tipo de caminhão',
    'Distance [km]': 'Distância [km]',
    'Residues [kg/h]': 'Resíduos [kg/h]',
    'CO2 Transport [kg]': 'CO2 transporte [kg]',
    'Cost Transport [€]': 'Custo transporte [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Reator a seco — Relatório de síntese',
    rpt_section_combustion: '1. Gases de combustão',
    rpt_temp_sortie: 'Temperatura de saída',
    rpt_o2_mesure_sec: 'O₂ medido (seco)',
    rpt_debit_humide_total: 'Caudal húmido total [kg/h]',
    rpt_debit_sec: 'Caudal seco [Nm³/h]',
    rpt_debit_humide: 'Caudal húmido [Nm³/h]',
    rpt_composition_gaz_sortie: 'Composição do gás de saída',
    rpt_section_emissions: '2. Emissões poluentes',
    rpt_gaz_entree: 'Gás de entrada [kg/h]',
    rpt_gaz_sortie: 'Gás de saída [kg/h]',
    rpt_residus_calcules: 'Resíduos calculados',
    rpt_cendres_lourdes_seches: 'Cinzas pesadas secas [kg/h]',
    rpt_cendres_volantes: 'Cinzas volantes [kg/h]',
    rpt_conso_reactifs: 'Consumo de reagentes',
    rpt_eau_potable: 'Água potável [m³/h]',
    rpt_eau_demineralisee: 'Água desmineralizada [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ seco [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Design',
    rpt_conso_electriques: 'Consumos elétricos',
    rpt_donnees_indisponibles_design: 'Dados não disponíveis (abrir o separador Design)',
    rpt_conso_eau: 'Consumo de água',
    rpt_energie_auxiliaire: 'Energia auxiliar',
    rpt_gaz_haute_valeur: 'Gás de alto valor [MW]',
    rpt_fuel: 'Combustível [MW]',
    rpt_section_opex: '4. OPEX — Custos horários',
    rpt_opex_unavailable: 'Custos OPEX não disponíveis — abrir os separadores Design e Opex.',
    rpt_electricite: 'Eletricidade',
    rpt_eau: 'Água',
    rpt_reactifs: 'Reagentes',
    rpt_energie: 'Energia',
    rpt_total_cout: 'Custo total',
    rpt_cout_horaire: 'Custo horário',
    rpt_cout_annuel: 'Custo anual',
    rpt_total_co2_kgh: 'Total CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ electricidade',
    rpt_co2_energie: 'CO₂ energia',
    rpt_total_co2: 'Total CO₂',
    rpt_consommateur: 'Consumidor',
    rpt_total: 'Total',
    rpt_footer: 'Relatório gerado automaticamente',
  },

  ru: {
    stackConfiguration: 'Конфигурация REACTOR',
    backToFlow: 'Вернуться к потоку',
    clearMemory: 'Очистить память',
    resetToDefaultValues: 'Восстановить значения по умолчанию',
    note: 'Примечание',
    none: 'Нет',
    flueGases: 'Дымовые газы',
    pollutantEmissions: 'Выбросы загрязнителей',
    design: 'Проектирование',
    opex: 'Opex',
    calculationParameters: 'Параметры расчета',
    calculatedParameters: 'Рассчитанные параметры',
    resetValues: 'Восстановить значения',
    temperatureInletREACTOR: 'Температура на входе REACTOR [°C]',
    deltaEnthalpies: 'Дельта энтальпии [кДж/ч]',
    sprayedCoolingWater: 'Распыляемая/охлаждающая вода [кг/ч]',
    flueGasHumidTotal: 'Общий влажный дымовой газ [Nm³/ч]',
    flueGasInletAtInletTemperature: 'Состав дымовых газов на входе',
    airIngressAtAmbientTemperature: 'Поступление воздуха при температуре окружающей среды',
    flueGasOutletAtOutletTemperature: 'Состав дымовых газов на выходе',
    wasteFlow: 'Поток отходов [кг/ч]',
    flueGasFlowWet: 'Поток дымовых газов влажный [Nm³/ч]',
    flueGasFlowDry: 'Поток дымовых газов сухой [Nm³/ч]',
    O2Calculated: 'Рассчитанный O2 [%]',
    inertMass: 'Инертная масса [кг/ч]',
    bottomAsh: 'Шлак [кг/ч]',
    bottomAshWet: 'Влажный шлак [кг/ч]',
    flyAsh: 'Летучая зола [кг/ч]',
    pollutantTreatmentTable: 'Таблица обработки загрязнителей',
    pollutant: 'Загрязнитель',
    reactif: 'Реагент',
    mass: 'Масса (кг/ч)',
    efficiency: 'Эффективность (%)',
    stoichiometryCoeff: 'Коэф. Стехиометрия',
    outputMass: 'Выходная масса',
    residueMass: 'Остаток массы',
    reactifMass: 'Масса реагента',
    abatedMass: 'Снятая масса',
    inputFlueGas: 'Входящий дымовой газ',
    outputFlueGas: 'Выходящий дымовой газ',
    bottomAshesCalculated: 'Рассчитанный шлак',
    aeraulicPressureLoss: 'Потеря аэродинамического давления',
    reactorDesign: 'Проектирование реактора',
    designResults: 'Результаты проектирования',
    electricConsumptionVisBelt: 'Электрическое потребление шнекового конвейера',
    visBeltConsumption: 'Потребление шнекового конвейера',
    compressedAirConsumption: 'Потребление сжатого воздуха',
    evacuationREACTORResidues: 'Эвакуация остатков REACTOR',
    residuesTransport: 'Транспорт остатков',
    reactorVolume: 'Объем реактора [m³]',
    diameter: 'Диаметр [м]',
    height: 'Высота [м]',
    residenceTime: 'Время пребывания [с]',
    gasVelocity: 'Скорость газа [м/с]',
    pressureLoss: 'Потеря давления [mmCE]',
    agitationPower: 'Мощность перемешивания [кВт]',
    agitationAir: 'Воздух перемешивания [Nm³/ч]',
    consumptionVisBelt: 'Потребление шнекового конвейера [кВт]',
    compressedAirPressure: 'Давление сжатого воздуха [Бар]',
    airConsumption: 'Потребление воздуха [Nm³/ч]',
    reactorDiameter: 'Диаметр реактора [м]',
    reactorHeight: 'Высота реактора [м]',
    reactorAgitation: 'Из них перемешивание реактора [Nm³/ч]',
    filterCleaning: 'Из них очистка фильтров [Nm³/ч]',
    compressedAirElecConsumption: 'Электрическое потребление сжатого воздуха [кВт]',
    residuesREACTOR: 'Остатки REACTOR [кг/ч]',
    truckType: 'Тип грузовика',
    distance: 'Расстояние [км]',
    CO2TransportTotal: 'Общее CO2 доставки [кг]',
    costTransportTotal: 'Общая стоимость доставки [€]',
    P_out_mmCE: 'P выход [mmCE]',
    visBelt: 'Шнековый конвейер',
    compressedAir: 'Сжатый воздух',
    mechanicalAgitation: 'Механическое перемешивание',
    notUsed: 'Не используется',
    pump: 'Насос',
    reactor: 'Реактор',
    summaryMainParameters: 'Сводка основных параметров',
    evacuatedAsh: 'Эвакуированная зола',
    detailedCalculatedParameters: 'Подробные рассчитанные параметры',
    pressureAeraulique: 'Аэродинамическое давление [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'Поток газов [Nm³/h]',
    temperature: 'Температура [°C]',
    ldRatio: 'Соотношение L/D',
    agitationType: 'Тип перемешивания',
    mechanical: 'Механическое',
    air: 'Пневматическое',
    consoElecVis: 'Электрическое потребление транспортера [кВт]',
    nombreCycles: 'Количество циклов [Nb]',
    pressionAirComprime: 'Давление сжатого воздуха [Бар]',
    airComprimeCycle: 'Сжатый воздух на цикл [Nm3/цикл]',
    typesCamion: 'Тип грузовика',
    distanceTransport: 'Расстояние [км]',
    flueGasTemperatureOutlet: 'Температура выхода дымовых газов [°C]',
    ambientAirTemperature: 'Температура окружающего воздуха [°C]',
    volumeAirIngress: 'Объем поступления воздуха [Nm³/h]',
    thermalLosses: 'Тепловые потери [%]',
    coolingWaterTemperature: 'Температура охлаждающей воды [°C]',
    flyAshesContent: 'Содержание летучей золы [g/Nm³]',
    siccityBottomAsh: 'Влажность шлака [%]',
    O2ref: 'Эталонный O2 [%]',
    'Fly ashes content [g/Nm3]': 'Содержание летучей золы [g/Nm³]',
    'siccity bottom ash [%]': 'Влажность шлака [%]',
    'siccity residus [%]': 'Влажность остатков [%]',
    'O2 ref [%]': 'Эталонный O2 [%]',
    'Aeraulic Pressure Loss': 'Потеря аэродинамического давления',
    'Reactor Design': 'Проектирование реактора',
    'Electric Consumption Belt': 'Электрическое потребление шнекового конвейера',
    'Compressed Air Consumption': 'Потребление сжатого воздуха',
    'Ash Evacuation': 'Эвакуация остатков',
    'Summary of Main Parameters': 'Сводка основных параметров',
    'Detailed Calculated Parameters': 'Подробные рассчитанные параметры',
    'Aeraulic Pressure [mmCE]': 'Аэродинамическое давление [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'Давление выход [mmCE]',
    'Flow Rate [Nm3/h]': 'Поток газов [Nm³/h]',
    'Temperature [°C]': 'Температура [°C]',
    'Residence Time [s]': 'Время пребывания [s]',
    'L/D Ratio': 'Соотношение L/D',
    'Agitation Type': 'Тип перемешивания',
    'Design Results': 'Результаты проектирования',
    'Reactor Volume [m³]': 'Объем реактора [m³]',
    'Diameter [m]': 'Диаметр [m]',
    'Height [m]': 'Высота [m]',
    'Agitation Power [kW]': 'Мощность перемешивания [kW]',
    'Air Consumption [Nm3/h]': 'Потребление воздуха [Nm³/h]',
    'Electric consumption belt [kW]': 'Электрическое потребление транспортера [kW]',
    'Belt Consumption [kW]': 'Потребление шнекового конвейера [kW]',
    'Number of cycles [Nb]': 'Количество циклов [Nb]',
    'Compressed air pressure [Bar]': 'Давление сжатого воздуха [Bar]',
    'Air per cycle [Nm3/cycle]': 'Сжатый воздух на цикл [Nm³/цикл]',
    'Electric Consumption [kW]': 'Электрическое потребление [kW]',
    'Truck Type': 'Тип грузовика',
    'Distance [km]': 'Расстояние [km]',
    'Residues [kg/h]': 'Остатки [kg/h]',
    'CO2 Transport [kg]': 'CO2 доставка [kg]',
    'Cost Transport [€]': 'Стоимость доставки [€]',
    // ===== REACTOR_Report =====
    rpt_reactor_title: 'Сухой реактор — Сводный отчёт',
    rpt_section_combustion: '1. Дымовые газы',
    rpt_temp_sortie: 'Температура на выходе',
    rpt_o2_mesure_sec: 'O₂ измеренный (сухой)',
    rpt_debit_humide_total: 'Общий влажный расход [kg/h]',
    rpt_debit_sec: 'Сухой расход [Nm³/h]',
    rpt_debit_humide: 'Влажный расход [Nm³/h]',
    rpt_composition_gaz_sortie: 'Состав выходного газа',
    rpt_section_emissions: '2. Загрязняющие выбросы',
    rpt_gaz_entree: 'Входной газ [kg/h]',
    rpt_gaz_sortie: 'Выходной газ [kg/h]',
    rpt_residus_calcules: 'Рассчитанные остатки',
    rpt_cendres_lourdes_seches: 'Сухая донная зола [kg/h]',
    rpt_cendres_volantes: 'Летучая зола [kg/h]',
    rpt_conso_reactifs: 'Расход реагентов',
    rpt_eau_potable: 'Питьевая вода [m³/h]',
    rpt_eau_demineralisee: 'Деминерализованная вода [m³/h]',
    rpt_caoh2_sec: 'Ca(OH)₂ сухой [kg/h]',
    rpt_nahco3: 'NaHCO₃ [kg/h]',
    rpt_nh3: 'NH₃ [kg/h]',
    rpt_cap: 'CAP [kg/h]',
    rpt_section_design: '3. Проектирование',
    rpt_conso_electriques: 'Электропотребление',
    rpt_donnees_indisponibles_design: 'Данные недоступны (открыть вкладку Проектирование)',
    rpt_conso_eau: 'Потребление воды',
    rpt_energie_auxiliaire: 'Вспомогательная энергия',
    rpt_gaz_haute_valeur: 'Высококалорийный газ [MW]',
    rpt_fuel: 'Топливо [MW]',
    rpt_section_opex: '4. OPEX — Почасовые затраты',
    rpt_opex_unavailable: 'OPEX-затраты недоступны — открыть вкладки Проектирование и Opex.',
    rpt_electricite: 'Электричество',
    rpt_eau: 'Вода',
    rpt_reactifs: 'Реагенты',
    rpt_energie: 'Энергия',
    rpt_total_cout: 'Итоговые затраты',
    rpt_cout_horaire: 'Почасовые затраты',
    rpt_cout_annuel: 'Годовые затраты',
    rpt_total_co2_kgh: 'Итого CO₂ [kg/h]',
    rpt_co2_electricite: 'CO₂ электричество',
    rpt_co2_energie: 'CO₂ энергия',
    rpt_total_co2: 'Итого CO₂',
    rpt_consommateur: 'Потребитель',
    rpt_total: 'Итого',
    rpt_footer: 'Отчёт сформирован автоматически',
  },

  zh: {
    stackConfiguration: '反应器配置',
    backToFlow: '返回流程',
    clearMemory: '清除内存',
    resetToDefaultValues: '重置为默认值',
    note: '注意',
    none: '无',
    flueGases: '烟气',
    pollutantEmissions: '污染物排放',
    design: '设计',
    opex: 'Opex',
    calculationParameters: '计算参数',
    calculatedParameters: '计算的参数',
    resetValues: '重置值',
    temperatureInletREACTOR: '反应器进口温度 [°C]',
    deltaEnthalpies: '焓增量 [kJ/h]',
    sprayedCoolingWater: '喷洒/冷却水 [kg/h]',
    flueGasHumidTotal: '总湿烟气 [Nm³/h]',
    flueGasInletAtInletTemperature: '进口烟气成分',
    airIngressAtAmbientTemperature: '环境温度空气进入',
    flueGasOutletAtOutletTemperature: '出口烟气成分',
    wasteFlow: '废物流 [kg/h]',
    flueGasFlowWet: '湿烟气流 [Nm³/h]',
    flueGasFlowDry: '干烟气流 [Nm³/h]',
    O2Calculated: '计算O2 [%]',
    inertMass: '惰性质量 [kg/h]',
    bottomAsh: '底灰 [kg/h]',
    bottomAshWet: '湿底灰 [kg/h]',
    flyAsh: '飞灰 [kg/h]',
    pollutantTreatmentTable: '污染物处理表',
    pollutant: '污染物',
    reactif: '试剂',
    mass: '质量 (kg/h)',
    efficiency: '效率 (%)',
    stoichiometryCoeff: '化学计量系数',
    outputMass: '输出质量',
    residueMass: '残留质量',
    reactifMass: '试剂质量',
    abatedMass: '削减的质量',
    inputFlueGas: '入口烟气',
    outputFlueGas: '出口烟气',
    bottomAshesCalculated: '计算的底灰',
    aeraulicPressureLoss: '空气动力压力损失',
    reactorDesign: '反应器设计',
    designResults: '设计结果',
    electricConsumptionVisBelt: '螺旋输送机电耗',
    visBeltConsumption: '螺旋输送机耗电',
    compressedAirConsumption: '压缩空气消耗',
    evacuationREACTORResidues: '反应器残留物排出',
    residuesTransport: '残留物运输',
    reactorVolume: '反应器体积 [m³]',
    diameter: '直径 [m]',
    height: '高度 [m]',
    residenceTime: '停留时间 [s]',
    gasVelocity: '气体速度 [m/s]',
    pressureLoss: '压力损失 [mmCE]',
    agitationPower: '搅拌功率 [kW]',
    agitationAir: '搅拌空气 [Nm³/h]',
    consumptionVisBelt: '螺旋输送机电耗 [kW]',
    compressedAirPressure: '压缩空气压力 [Bar]',
    airConsumption: '空气消耗 [Nm³/h]',
    reactorDiameter: '反应器直径 [m]',
    reactorHeight: '反应器高度 [m]',
    reactorAgitation: '其中反应器搅拌 [Nm³/h]',
    filterCleaning: '其中过滤器清洁 [Nm³/h]',
    compressedAirElecConsumption: '压缩空气电耗 [kW]',
    residuesREACTOR: '反应器残留物 [kg/h]',
    truckType: '卡车类型',
    distance: '距离 [km]',
    CO2TransportTotal: '总运输CO2 [kg]',
    costTransportTotal: '总运输成本 [€]',
    P_out_mmCE: 'P输出 [mmCE]',
    visBelt: '螺旋输送机',
    compressedAir: '压缩空气',
    mechanicalAgitation: '机械搅拌',
    notUsed: '未使用',
    pump: '泵',
    reactor: '反应器',
    summaryMainParameters: '主要参数摘要',
    evacuatedAsh: '排出的灰',
    detailedCalculatedParameters: '详细计算的参数',
    pressureAeraulique: '空气动力压力 [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: '气体流速 [Nm³/h]',
    temperature: '温度 [°C]',
    ldRatio: 'L/D比',
    agitationType: '搅拌类型',
    mechanical: '机械',
    air: '气动',
    consoElecVis: '传送带电耗 [kW]',
    nombreCycles: '循环数 [Nb]',
    pressionAirComprime: '压缩空气压力 [Bar]',
    airComprimeCycle: '每个循环的压缩空气 [Nm3/循环]',
    typesCamion: '卡车类型',
    distanceTransport: '距离 [km]',
    flueGasTemperatureOutlet: '烟气出口温度 [°C]',
    ambientAirTemperature: '环境空气温度 [°C]',
    volumeAirIngress: '空气进入体积 [Nm³/h]',
    thermalLosses: '热损失 [%]',
    coolingWaterTemperature: '冷却水温度 [°C]',
    flyAshesContent: '飞灰含量 [g/Nm³]',
    siccityBottomAsh: '底灰含水量 [%]',
    O2ref: '参考O2 [%]',
    'Fly ashes content [g/Nm3]': '飞灰含量 [g/Nm³]',
    'siccity bottom ash [%]': '底灰含水量 [%]',
    'siccity residus [%]': '残留物含水量 [%]',
    'O2 ref [%]': '参考O2 [%]',
    'Aeraulic Pressure Loss': '空气动力压力损失',
    'Reactor Design': '反应器设计',
    'Electric Consumption Belt': '螺旋输送机电力消耗',
    'Compressed Air Consumption': '压缩空气消耗',
    'Ash Evacuation': '灰烬排出',
    'Summary of Main Parameters': '主要参数摘要',
    'Detailed Calculated Parameters': '详细计算的参数',
    'Aeraulic Pressure [mmCE]': '空气动力压力 [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': '输出压力 [mmCE]',
    'Flow Rate [Nm3/h]': '气体流量 [Nm³/h]',
    'Temperature [°C]': '温度 [°C]',
    'Residence Time [s]': '停留时间 [s]',
    'L/D Ratio': 'L/D比例',
    'Agitation Type': '搅拌类型',
    'Design Results': '设计结果',
    'Reactor Volume [m³]': '反应器体积 [m³]',
    'Diameter [m]': '直径 [m]',
    'Height [m]': '高度 [m]',
    'Agitation Power [kW]': '搅拌功率 [kW]',
    'Air Consumption [Nm3/h]': '空气消耗 [Nm³/h]',
    'Electric consumption belt [kW]': '传送带电耗 [kW]',
    'Belt Consumption [kW]': '螺旋输送机电耗 [kW]',
    'Number of cycles [Nb]': '循环数 [Nb]',
    'Compressed air pressure [Bar]': '压缩空气压力 [Bar]',
    'Air per cycle [Nm3/cycle]': '每个循环的压缩空气 [Nm³/循环]',
    'Electric Consumption [kW]': '电力消耗 [kW]',
    'Truck Type': '卡车类型',
    'Distance [km]': '距离 [km]',
    'Residues [kg/h]': '残留物 [kg/h]',
    'CO2 Transport [kg]': 'CO2运输 [kg]',
    'Cost Transport [€]': '运输成本 [€]',
  },

  ja: {
    stackConfiguration: 'リアクター構成',
    backToFlow: 'フローに戻る',
    clearMemory: 'メモリをクリア',
    resetToDefaultValues: 'デフォルト値にリセット',
    note: 'メモ',
    none: 'なし',
    flueGases: '排気ガス',
    pollutantEmissions: '汚染物排出',
    design: 'デザイン',
    opex: 'Opex',
    calculationParameters: '計算パラメータ',
    calculatedParameters: '計算されたパラメータ',
    resetValues: '値をリセット',
    temperatureInletREACTOR: 'リアクター入口温度 [°C]',
    deltaEnthalpies: 'デルタエンタルピー [kJ/h]',
    sprayedCoolingWater: '噴霧/冷却水 [kg/h]',
    flueGasHumidTotal: '総湿排気ガス [Nm³/h]',
    flueGasInletAtInletTemperature: '入口排気ガス成分',
    airIngressAtAmbientTemperature: '環境温度での空気流入',
    flueGasOutletAtOutletTemperature: '出口排気ガス成分',
    wasteFlow: '廃棄物流 [kg/h]',
    flueGasFlowWet: '湿排気ガス流 [Nm³/h]',
    flueGasFlowDry: '乾排気ガス流 [Nm³/h]',
    O2Calculated: '計算O2 [%]',
    inertMass: '不活性質量 [kg/h]',
    bottomAsh: 'ボトムアッシュ [kg/h]',
    bottomAshWet: '湿ボトムアッシュ [kg/h]',
    flyAsh: 'フライアッシュ [kg/h]',
    pollutantTreatmentTable: '汚染物処理表',
    pollutant: '汚染物',
    reactif: '試薬',
    mass: '質量 (kg/h)',
    efficiency: '効率 (%)',
    stoichiometryCoeff: '化学量論係数',
    outputMass: '出力質量',
    residueMass: '残留質量',
    reactifMass: '試薬質量',
    abatedMass: '削減質量',
    inputFlueGas: '入口排気ガス',
    outputFlueGas: '出口排気ガス',
    bottomAshesCalculated: '計算されたボトムアッシュ',
    aeraulicPressureLoss: '空気力学的圧力損失',
    reactorDesign: 'リアクター設計',
    designResults: '設計結果',
    electricConsumptionVisBelt: 'スクリューコンベアー電力消費',
    visBeltConsumption: 'スクリューコンベアー消費',
    compressedAirConsumption: '圧縮空気消費',
    evacuationREACTORResidues: 'リアクター残留物の排出',
    residuesTransport: '残留物の輸送',
    reactorVolume: 'リアクター容積 [m³]',
    diameter: '直径 [m]',
    height: '高さ [m]',
    residenceTime: '滞留時間 [s]',
    gasVelocity: 'ガス速度 [m/s]',
    pressureLoss: '圧力損失 [mmCE]',
    agitationPower: '撹拌動力 [kW]',
    agitationAir: '撹拌空気 [Nm³/h]',
    consumptionVisBelt: 'スクリューコンベアー電力消費 [kW]',
    compressedAirPressure: '圧縮空気圧 [Bar]',
    airConsumption: '空気消費 [Nm³/h]',
    reactorDiameter: 'リアクター直径 [m]',
    reactorHeight: 'リアクター高さ [m]',
    reactorAgitation: 'うちリアクター撹拌 [Nm³/h]',
    filterCleaning: 'うちフィルター清掃 [Nm³/h]',
    compressedAirElecConsumption: '圧縮空気電力消費 [kW]',
    residuesREACTOR: 'リアクター残留物 [kg/h]',
    truckType: 'トラックタイプ',
    distance: '距離 [km]',
    CO2TransportTotal: '総運送CO2 [kg]',
    costTransportTotal: '総運送コスト [€]',
    P_out_mmCE: 'P出力 [mmCE]',
    visBelt: 'スクリューコンベアー',
    compressedAir: '圧縮空気',
    mechanicalAgitation: '機械的撹拌',
    notUsed: '未使用',
    pump: 'ポンプ',
    reactor: 'リアクター',
    summaryMainParameters: 'メインパラメータサマリー',
    evacuatedAsh: '排出灰',
    detailedCalculatedParameters: '詳細計算パラメータ',
    pressureAeraulique: '空気力学的圧 [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'ガス流量 [Nm³/h]',
    temperature: '温度 [°C]',
    ldRatio: 'L/D比',
    agitationType: '撹拌タイプ',
    mechanical: '機械',
    air: '空気圧',
    consoElecVis: 'コンベアー電力消費 [kW]',
    nombreCycles: 'サイクル数 [Nb]',
    pressionAirComprime: '圧縮空気圧 [Bar]',
    airComprimeCycle: 'サイクルあたりの圧縮空気 [Nm3/サイクル]',
    typesCamion: 'トラックタイプ',
    distanceTransport: '距離 [km]',
    flueGasTemperatureOutlet: '排気ガス出口温度 [°C]',
    ambientAirTemperature: '環境空気温度 [°C]',
    volumeAirIngress: '空気流入量 [Nm³/h]',
    thermalLosses: '熱損失 [%]',
    coolingWaterTemperature: '冷却水温度 [°C]',
    flyAshesContent: 'フライアッシュ含量 [g/Nm³]',
    siccityBottomAsh: 'ボトムアッシュ含水量 [%]',
    O2ref: '参考O2 [%]',
    'Fly ashes content [g/Nm3]': 'フライアッシュ含量 [g/Nm³]',
    'siccity bottom ash [%]': 'ボトムアッシュ含水量 [%]',
    'siccity residus [%]': '残留物含水量 [%]',
    'O2 ref [%]': '参考O2 [%]',
    'Aeraulic Pressure Loss': '空気力学的圧力損失',
    'Reactor Design': 'リアクター設計',
    'Electric Consumption Belt': 'スクリューコンベアー電力消費',
    'Compressed Air Consumption': '圧縮空気消費',
    'Ash Evacuation': '灰の排出',
    'Summary of Main Parameters': 'メインパラメータサマリー',
    'Detailed Calculated Parameters': '詳細計算パラメータ',
    'Aeraulic Pressure [mmCE]': '空気力学的圧 [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': '出力圧 [mmCE]',
    'Flow Rate [Nm3/h]': 'ガス流量 [Nm³/h]',
    'Temperature [°C]': '温度 [°C]',
    'Residence Time [s]': '滞留時間 [s]',
    'L/D Ratio': 'L/D比',
    'Agitation Type': '撹拌タイプ',
    'Design Results': '設計結果',
    'Reactor Volume [m³]': 'リアクター容積 [m³]',
    'Diameter [m]': '直径 [m]',
    'Height [m]': '高さ [m]',
    'Agitation Power [kW]': '撹拌動力 [kW]',
    'Air Consumption [Nm3/h]': '空気消費 [Nm³/h]',
    'Electric consumption belt [kW]': 'コンベアー電力消費 [kW]',
    'Belt Consumption [kW]': 'スクリューコンベアー電力消費 [kW]',
    'Number of cycles [Nb]': 'サイクル数 [Nb]',
    'Compressed air pressure [Bar]': '圧縮空気圧 [Bar]',
    'Air per cycle [Nm3/cycle]': 'サイクルあたりの圧縮空気 [Nm³/サイクル]',
    'Electric Consumption [kW]': '電力消費 [kW]',
    'Truck Type': 'トラックタイプ',
    'Distance [km]': '距離 [km]',
    'Residues [kg/h]': '残留物 [kg/h]',
    'CO2 Transport [kg]': 'CO2運送 [kg]',
    'Cost Transport [€]': '運送費用 [€]',
  },

  ar: {
    stackConfiguration: 'تكوين المفاعل',
    backToFlow: 'العودة إلى التدفق',
    clearMemory: 'مسح الذاكرة',
    resetToDefaultValues: 'إعادة تعيين إلى القيم الافتراضية',
    note: 'ملاحظة',
    none: 'لا أحد',
    flueGases: 'غازات العادم',
    pollutantEmissions: 'انبعاثات الملوثات',
    design: 'التصميم',
    opex: 'Opex',
    calculationParameters: 'معاملات الحساب',
    calculatedParameters: 'المعاملات المحسوبة',
    resetValues: 'إعادة تعيين القيم',
    temperatureInletREACTOR: 'درجة حرارة مدخل المفاعل [°C]',
    deltaEnthalpies: 'دلتا الإنتالبيا [كيلوجول/ساعة]',
    sprayedCoolingWater: 'المياه المرشوشة/التبريد [كجم/ساعة]',
    flueGasHumidTotal: 'إجمالي الغاز الرطب [Nm³/h]',
    flueGasInletAtInletTemperature: 'تركيب غاز العادم عند الدخول',
    airIngressAtAmbientTemperature: 'دخول الهواء في درجة الحرارة المحيطة',
    flueGasOutletAtOutletTemperature: 'تركيب غاز العادم عند الخروج',
    wasteFlow: 'تدفق النفايات [كجم/ساعة]',
    flueGasFlowWet: 'تدفق غاز العادم الرطب [Nm³/h]',
    flueGasFlowDry: 'تدفق غاز العادم الجاف [Nm³/h]',
    O2Calculated: 'O2 المحسوبة [%]',
    inertMass: 'الكتلة الخاملة [كجم/ساعة]',
    bottomAsh: 'الرماد السفلي [كجم/ساعة]',
    bottomAshWet: 'الرماد السفلي الرطب [كجم/ساعة]',
    flyAsh: 'الرماد المتطاير [كجم/ساعة]',
    pollutantTreatmentTable: 'جدول معالجة الملوثات',
    pollutant: 'ملوث',
    reactif: 'محاليل',
    mass: 'الكتلة (كجم/ساعة)',
    efficiency: 'الكفاءة (%)',
    stoichiometryCoeff: 'معامل الكيمياء الحسابية',
    outputMass: 'كتلة الإخراج',
    residueMass: 'كتلة البقايا',
    reactifMass: 'كتلة المحاليل',
    abatedMass: 'الكتلة المخففة',
    inputFlueGas: 'غاز العادم المدخل',
    outputFlueGas: 'غاز العادم المخرج',
    bottomAshesCalculated: 'الرماد السفلي المحسوب',
    aeraulicPressureLoss: 'فقدان الضغط الهوائي',
    reactorDesign: 'تصميم المفاعل',
    designResults: 'نتائج التصميم',
    electricConsumptionVisBelt: 'استهلاك الكهرباء حزام اللولب',
    visBeltConsumption: 'استهلاك حزام اللولب',
    compressedAirConsumption: 'استهلاك الهواء المضغوط',
    evacuationREACTORResidues: 'إزالة بقايا المفاعل',
    residuesTransport: 'نقل البقايا',
    reactorVolume: 'حجم المفاعل [m³]',
    diameter: 'القطر [m]',
    height: 'الارتفاع [m]',
    residenceTime: 'وقت الإقامة [s]',
    gasVelocity: 'سرعة الغاز [m/s]',
    pressureLoss: 'فقدان الضغط [mmCE]',
    agitationPower: 'قوة التحريك [kW]',
    agitationAir: 'الهواء المحرك [Nm³/h]',
    consumptionVisBelt: 'استهلاك حزام اللولب [kW]',
    compressedAirPressure: 'ضغط الهواء المضغوط [Bar]',
    airConsumption: 'استهلاك الهواء [Nm³/h]',
    reactorDiameter: 'قطر المفاعل [m]',
    reactorHeight: 'ارتفاع المفاعل [m]',
    reactorAgitation: 'منها تحريك المفاعل [Nm³/h]',
    filterCleaning: 'منها تنظيف الفلاتر [Nm³/h]',
    compressedAirElecConsumption: 'استهلاك الكهرباء للهواء المضغوط [kW]',
    residuesREACTOR: 'بقايا المفاعل [كجم/ساعة]',
    truckType: 'نوع الشاحنة',
    distance: 'المسافة [km]',
    CO2TransportTotal: 'إجمالي CO2 النقل [kg]',
    costTransportTotal: 'إجمالي تكلفة النقل [€]',
    P_out_mmCE: 'P الخروج [mmCE]',
    visBelt: 'حزام اللولب',
    compressedAir: 'هواء مضغوط',
    mechanicalAgitation: 'التحريك الميكانيكي',
    notUsed: 'غير مستخدم',
    pump: 'مضخة',
    reactor: 'مفاعل',
    summaryMainParameters: 'ملخص المعاملات الرئيسية',
    evacuatedAsh: 'الرماد المزال',
    detailedCalculatedParameters: 'المعاملات المحسوبة التفصيلية',
    pressureAeraulique: 'الضغط الهوائي [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    flowRate: 'معدل تدفق الغاز [Nm³/h]',
    temperature: 'درجة الحرارة [°C]',
    ldRatio: 'نسبة L/D',
    agitationType: 'نوع التحريك',
    mechanical: 'ميكانيكي',
    air: 'هوائي',
    consoElecVis: 'استهلاك الكهرباء للناقل [kW]',
    nombreCycles: 'عدد الدورات [Nb]',
    pressionAirComprime: 'ضغط الهواء المضغوط [Bar]',
    airComprimeCycle: 'الهواء المضغوط لكل دورة [Nm3/دورة]',
    typesCamion: 'نوع الشاحنة',
    distanceTransport: 'المسافة [km]',
    flueGasTemperatureOutlet: 'درجة حرارة مخرج غازات العادم [°C]',
    ambientAirTemperature: 'درجة حرارة الهواء المحيط [°C]',
    volumeAirIngress: 'حجم دخول الهواء [Nm³/h]',
    thermalLosses: 'الخسائر الحرارية [%]',
    coolingWaterTemperature: 'درجة حرارة ماء التبريد [°C]',
    flyAshesContent: 'محتوى الرماد المتطاير [g/Nm³]',
    siccityBottomAsh: 'رطوبة الرماد السفلي [%]',
    O2ref: 'مرجع O2 [%]',
    'Fly ashes content [g/Nm3]': 'محتوى الرماد المتطاير [g/Nm³]',
    'siccity bottom ash [%]': 'رطوبة الرماد السفلي [%]',
    'siccity residus [%]': 'رطوبة البقايا [%]',
    'O2 ref [%]': 'مرجع O2 [%]',
    'Aeraulic Pressure Loss': 'فقدان الضغط الهوائي',
    'Reactor Design': 'تصميم المفاعل',
    'Electric Consumption Belt': 'استهلاك الكهرباء حزام اللولب',
    'Compressed Air Consumption': 'استهلاك الهواء المضغوط',
    'Ash Evacuation': 'إزالة الرماد',
    'Summary of Main Parameters': 'ملخص المعاملات الرئيسية',
    'Detailed Calculated Parameters': 'المعاملات المحسوبة التفصيلية',
    'Aeraulic Pressure [mmCE]': 'الضغط الهوائي [mmCE]',
    'PDC [mmCE]': 'PDC [mmCE]',
    'Output Pressure [mmCE]': 'ضغط الخروج [mmCE]',
    'Flow Rate [Nm3/h]': 'معدل تدفق الغاز [Nm³/h]',
    'Temperature [°C]': 'درجة الحرارة [°C]',
    'Residence Time [s]': 'وقت الإقامة [s]',
    'L/D Ratio': 'نسبة L/D',
    'Agitation Type': 'نوع التحريك',
    'Design Results': 'نتائج التصميم',
    'Reactor Volume [m³]': 'حجم المفاعل [m³]',
    'Diameter [m]': 'القطر [m]',
    'Height [m]': 'الارتفاع [m]',
    'Agitation Power [kW]': 'قوة التحريك [kW]',
    'Air Consumption [Nm3/h]': 'استهلاك الهواء [Nm³/h]',
    'Electric consumption belt [kW]': 'استهلاك الكهرباء الناقل [kW]',
    'Belt Consumption [kW]': 'استهلاك حزام اللولب [kW]',
    'Number of cycles [Nb]': 'عدد الدورات [Nb]',
    'Compressed air pressure [Bar]': 'ضغط الهواء المضغوط [Bar]',
    'Air per cycle [Nm3/cycle]': 'الهواء المضغوط لكل دورة [Nm³/دورة]',
    'Electric Consumption [kW]': 'استهلاك الكهرباء [kW]',
    'Truck Type': 'نوع الشاحنة',
    'Distance [km]': 'المسافة [km]',
    'Residues [kg/h]': 'البقايا [kg/h]',
    'CO2 Transport [kg]': 'نقل CO2 [kg]',
    'Cost Transport [€]': 'تكلفة النقل [€]',
  },
};