// RK_traduction.js
export const translations = {
  fr: {
    // Main navigation
    title: 'Configuration du Four Rotatif et SCC',
    combustionParameters: 'Paramètres de combustion',
    flueGases: 'Gaz de combustion',
    pollutantEmissions: 'Émissions polluantes',
    design: 'Conception',
    opex: 'Opex',
    backToFlow: 'Retour au flux',
    sendData: 'Envoyer les données',
    rapport: 'Rapport',
    
    // Flue Gas Parameters (2_Flue_gas.jsx)
    calculationParameters: 'Paramètres de calcul',
    calculatedParameters: 'Paramètres calculés',
    combustionAirComposition: 'Composition de l\'air de combustion',
    atStoichiometry: 'À la stœchiométrie',
    atAdiabaticity: 'À l\'adiabaticité',
    combustionAirTotal: 'Air de combustion total',
    flueGasComposition: 'Composition des gaz de combustion',
    flueGasAtStoichiometry: 'Gaz de combustion à la stœchiométrie',
    outputFlueGasWithoutWater: 'Gaz de combustion en sortie sans eau de l\'extracteur',
    outputFlueGasWithWater: 'Gaz de combustion en sortie avec eau de l\'extracteur',
    resetValues: 'Remettre à zéro',
    export: 'Exporter',
    
    // Parameter labels
    flueGasTemperatureOutlet: 'Température de sortie des gaz de combustion [°C]',
    airFactor: 'Facteur d\'air',
    combustionAirTemperature: 'Température de l\'air de combustion [°C]',
    wasteTemperature: 'Température des déchets [°C]',
    steamWaterTemperature: 'Température de l\'eau vapeur',
    estimatedThermalLosses: 'Pertes thermiques estimées [%]',
    airPreheatingPart: 'Partie préchauffage d\'air [%]',
    airPreheatingTemperature: 'Température de préchauffage d\'air [°C]',
    airRelativeMoisture: 'Humidité relative de l\'air [%]',
    waterVaporizedFromExtractor: 'Eau vaporisée de l\'extracteur [kg/h]',
    
    // Calculated parameters
    airStoechio: 'Air stœchiométrique [Kmole]',
    calculatedTemperature: 'Température calculée [°C]',
    waterContent: 'Teneur en eau [kg/Nm3]',
    hSystem: 'H_système',
    airFactorCalculated: 'Facteur d\'air calculé',

    // Combustion Parameters (1_CombustionParameters.jsx)
    resetDefaultValues: 'Réinitialiser les valeurs par défaut',
    mass: 'Masse [kg/h]',
    wasteFlow: 'Débit de déchets [kg/h]',
    flueGasFlowWet: 'Débit de gaz humide [Nm3/h]',
    flueGasFlowDry: 'Débit de gaz sec [Nm3/h]',
    o2Calculated: 'O2 calculé [%]',
    inertMass: 'Masse inerte [kg/h]',

    // Pollutant Emissions (3_Pollutant_Emission.jsx)
    mercuryTreatmentThreshold: 'Seuil de traitement du mercure [micro g/Nm3]',
    noxIn: 'NOx EN [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Teneur en cendres volantes [g/Nm3]',
    siccityBottomAsh: 'Siccité des mâchefers [%]',
    o2Ref: 'O2 réf [%]',
    sncr: 'SNCR (Réduction catalytique sélective)',
    sncrtEnabled: 'SNCR activé',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Stœchiométrie',
    mercuryTreatment: 'Traitement du mercure',
    hgTreatmentEnabled: 'Traitement Hg activé',
    brHgRatio: 'Rapport Br/Hg',
    pollutantTreatmentTable: 'Tableau de traitement des polluants',
    pollutant: 'Polluant',
    reactif: 'Réactif',
    massInput: 'Masse entrée',
    efficiency: 'Efficacité (%)',
    stoechCoeff: 'Coeff. Stœch',
    massOutput: 'Masse sortie',
    massResidue: 'Masse résidu',
    massReactif: 'Masse réactif',
    massReduced: 'Masse abattue',
    inputFlueGas: 'Gaz de combustion en entrée',
    outputFlueGas: 'Gaz de combustion en sortie',
    bottomAshesCalculated: 'Mâchefers calculés',
    bottomAsh: 'Mâchefers [kg/h]',
    bottomAshWet: 'Mâchefers humides [kg/h]',
    flyAsh: 'Cendres volantes [kg/h]',
    nh3Consumption: 'Consommation NH3 [kg/h]',
    hgMass: 'Masse Hg [kg/h]',
    bromideConsumption: 'Consommation bromure [kg/h]',

    // Design (4_RK_Design.jsx)
    aeraulicPressureLoss: 'Perte de charge aéraulique',
    thermicalLossParameters: 'Paramètres pertes thermiques du four',
    rotaryKilnDesign: 'Conception du four rotatif',
    lanceEstimation: 'Estimation du nombre de lances sur la facade',
    facadeCooling: 'Paramètres du refroidissement de la facade',
    facadeThermicalLosses: 'Paramètres pertes thermiques du four',
    shellCooling: 'Refroidissement de la virole',
    sccDimensioning: 'Dimensionnement de la SCC',
    sccBurners: 'Brûleurs de la SCC',
    sccThermicalLosses: 'Estimation des pertes thermiques SCC',
    extractorConsumption: 'Estimation consommation extracteur',
    combustionAirFan: 'Estimation consommation ventilateur air combustion',
    extractorWaterEvaporation: 'Estimation eau évaporée extracteur',
    warningSlope: '⚠️ Attention : La pente du four dépasse la limite recommandée (2-5°)',
    warningFillRate: '⚠️ Attention : Le taux de remplissage dépasse la limite recommandée (max 5%)',
    warningVelocity: '⚠️ Attention : La vitesse des fumées dans la SCC dépasse la limite recommandée de 3 m/s',
  },
  
  en: {
    // Main navigation
    title: 'Rotary Kiln and SCC Configuration',
    combustionParameters: 'Combustion Parameters',
    flueGases: 'Flue gases',
    pollutantEmissions: 'Pollutant Emissions',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Back to Flow',
    sendData: 'Send Data',
    rapport: 'Report',
    
    // Flue Gas Parameters
    calculationParameters: 'Calculation parameters',
    calculatedParameters: 'Calculated parameters',
    combustionAirComposition: 'Combustion air composition',
    atStoichiometry: 'At the stoichiometry',
    atAdiabaticity: 'At the adiabaticity',
    combustionAirTotal: 'Combustion air total',
    flueGasComposition: 'Flue gas composition',
    flueGasAtStoichiometry: 'Flue gas at the stoichiometry',
    outputFlueGasWithoutWater: 'Output flue gas without water from extractor',
    outputFlueGasWithWater: 'Output flue gas with water from extractor',
    resetValues: 'Reset values',
    export: 'Export',
    
    // Parameter labels
    flueGasTemperatureOutlet: 'Flue gas temperature outlet [°C]',
    airFactor: 'Air factor',
    combustionAirTemperature: 'Combustion Air Temperature [°C]',
    wasteTemperature: 'Waste Temperature [°C]',
    steamWaterTemperature: 'Steam water temperature',
    estimatedThermalLosses: 'Estimated thermal Losses [%]',
    airPreheatingPart: 'Air preheating part [%]',
    airPreheatingTemperature: 'Air preheating temperature [°C]',
    airRelativeMoisture: 'Air Relative Moisture [%]',
    waterVaporizedFromExtractor: 'Water vaporized from extractor [kg/h]',
    
    // Calculated parameters
    airStoechio: 'Air Stoechio [Kmole]',
    calculatedTemperature: 'Calculated temperature [°C]',
    waterContent: 'Water Content [kg/Nm3]',
    hSystem: 'H_system',
    airFactorCalculated: 'Air factor calculated',

    // Combustion Parameters
    resetDefaultValues: 'Reset default values',
    mass: 'Mass [kg/h]',
    wasteFlow: 'Waste Flow [kg/h]',
    flueGasFlowWet: 'Flue gas Flow Wet [Nm3/h]',
    flueGasFlowDry: 'Flue gas Flow Dry [Nm3/h]',
    o2Calculated: 'O2 calculated [%]',
    inertMass: 'Inert mass [kg/h]',

    // Pollutant Emissions
    mercuryTreatmentThreshold: 'Mercury treatment threshold [micro g/Nm3]',
    noxIn: 'NOx IN [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Fly ashes content [g/Nm3]',
    siccityBottomAsh: 'Siccity bottom ash [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Selective Non-Catalytic Reduction)',
    sncrtEnabled: 'SNCR enabled',
    noxLimit: 'NOx limit [mg/Nm3]',
    stoichiometry: 'Stoichiometry',
    mercuryTreatment: 'Mercury Treatment',
    hgTreatmentEnabled: 'Hg treatment enabled',
    brHgRatio: 'Br/Hg ratio',
    pollutantTreatmentTable: 'Pollutant Treatment Table',
    pollutant: 'Pollutant',
    reactif: 'Reagent',
    massInput: 'Mass input',
    efficiency: 'Efficiency (%)',
    stoechCoeff: 'Stoech. Coeff',
    massOutput: 'Mass output',
    massResidue: 'Mass residue',
    massReactif: 'Reagent mass',
    massReduced: 'Mass reduced',
    inputFlueGas: 'Input flue gas',
    outputFlueGas: 'Output flue gas',
    bottomAshesCalculated: 'Bottom ashes calculated',
    bottomAsh: 'Bottom ash [kg/h]',
    bottomAshWet: 'Bottom ash wet [kg/h]',
    flyAsh: 'Fly ash [kg/h]',
    nh3Consumption: 'NH3 consumption [kg/h]',
    hgMass: 'Hg mass [kg/h]',
    bromideConsumption: 'Bromide consumption [kg/h]',

    // Design
    aeraulicPressureLoss: 'Aeraulic pressure loss',
    thermicalLossParameters: 'Thermal loss parameters',
    rotaryKilnDesign: 'Rotary Kiln Design',
    lanceEstimation: 'Lance estimation on facade',
    facadeCooling: 'Facade cooling parameters',
    facadeThermicalLosses: 'Facade thermal losses parameters',
    shellCooling: 'Shell cooling',
    sccDimensioning: 'SCC dimensioning',
    sccBurners: 'SCC burners',
    sccThermicalLosses: 'SCC thermal losses estimation',
    extractorConsumption: 'Extractor consumption estimation',
    combustionAirFan: 'Combustion air fan consumption estimation',
    extractorWaterEvaporation: 'Extractor water evaporation estimation',
    warningSlope: '⚠️ Warning: Kiln slope exceeds recommended limit (2-5°)',
    warningFillRate: '⚠️ Warning: Fill rate exceeds recommended limit (max 5%)',
    warningVelocity: '⚠️ Warning: Flue gas velocity in SCC exceeds recommended limit of 3 m/s',
  },

  es: {
    // Main navigation
    title: 'Configuración de Horno Rotativo y SCC',
    combustionParameters: 'Parámetros de combustión',
    flueGases: 'Gases de combustión',
    pollutantEmissions: 'Emisiones contaminantes',
    design: 'Diseño',
    opex: 'Opex',
    backToFlow: 'Volver al flujo',
    sendData: 'Enviar datos',
    rapport: 'Informe',
    
    calculationParameters: 'Parámetros de cálculo',
    calculatedParameters: 'Parámetros calculados',
    combustionAirComposition: 'Composición del aire de combustión',
    atStoichiometry: 'En la estequiometría',
    atAdiabaticity: 'En la adiabaticidad',
    combustionAirTotal: 'Aire de combustión total',
    flueGasComposition: 'Composición de gases de combustión',
    flueGasAtStoichiometry: 'Gases de combustión en la estequiometría',
    outputFlueGasWithoutWater: 'Gases de combustión de salida sin agua del extractor',
    outputFlueGasWithWater: 'Gases de combustión de salida con agua del extractor',
    resetValues: 'Restablecer valores',
    export: 'Exportar',
    
    flueGasTemperatureOutlet: 'Temperatura de salida de gases de combustión [°C]',
    airFactor: 'Factor de aire',
    combustionAirTemperature: 'Temperatura del aire de combustión [°C]',
    wasteTemperature: 'Temperatura de residuos [°C]',
    steamWaterTemperature: 'Temperatura del agua vapor',
    estimatedThermalLosses: 'Pérdidas térmicas estimadas [%]',
    airPreheatingPart: 'Parte de precalentamiento de aire [%]',
    airPreheatingTemperature: 'Temperatura de precalentamiento de aire [°C]',
    airRelativeMoisture: 'Humedad relativa del aire [%]',
    waterVaporizedFromExtractor: 'Agua vaporizada del extractor [kg/h]',
    
    airStoechio: 'Aire estequiométrico [Kmole]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Contenido de agua [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Factor de aire calculado',

    resetDefaultValues: 'Restablecer valores predeterminados',
    mass: 'Masa [kg/h]',
    wasteFlow: 'Flujo de residuos [kg/h]',
    flueGasFlowWet: 'Flujo de gas húmedo [Nm3/h]',
    flueGasFlowDry: 'Flujo de gas seco [Nm3/h]',
    o2Calculated: 'O2 calculado [%]',
    inertMass: 'Masa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Umbral de tratamiento de mercurio [micro g/Nm3]',
    noxIn: 'NOx ENTRADA [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Contenido de cenizas volantes [g/Nm3]',
    siccityBottomAsh: 'Sequedad de escorias [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Reducción Catalítica Selectiva)',
    sncrtEnabled: 'SNCR activado',
    noxLimit: 'Límite NOx [mg/Nm3]',
    stoichiometry: 'Estequiometría',
    mercuryTreatment: 'Tratamiento de mercurio',
    hgTreatmentEnabled: 'Tratamiento Hg activado',
    brHgRatio: 'Relación Br/Hg',
    pollutantTreatmentTable: 'Tabla de tratamiento de contaminantes',
    pollutant: 'Contaminante',
    reactif: 'Reactivo',
    massInput: 'Masa entrada',
    efficiency: 'Eficiencia (%)',
    stoechCoeff: 'Coef. Estequiom.',
    massOutput: 'Masa salida',
    massResidue: 'Masa residuo',
    massReactif: 'Masa reactivo',
    massReduced: 'Masa reducida',
    inputFlueGas: 'Gas de combustión de entrada',
    outputFlueGas: 'Gas de combustión de salida',
    bottomAshesCalculated: 'Escorias calculadas',
    bottomAsh: 'Escorias [kg/h]',
    bottomAshWet: 'Escorias húmedas [kg/h]',
    flyAsh: 'Cenizas volantes [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Masa Hg [kg/h]',
    bromideConsumption: 'Consumo de bromuro [kg/h]',

    aeraulicPressureLoss: 'Pérdida de carga aeráulica',
    thermicalLossParameters: 'Parámetros de pérdidas térmicas',
    rotaryKilnDesign: 'Diseño de horno rotativo',
    lanceEstimation: 'Estimación de lanzas en fachada',
    facadeCooling: 'Parámetros de refrigeración de fachada',
    facadeThermicalLosses: 'Parámetros de pérdidas térmicas de fachada',
    shellCooling: 'Refrigeración de carcasa',
    sccDimensioning: 'Dimensionamiento SCC',
    sccBurners: 'Quemadores SCC',
    sccThermicalLosses: 'Estimación de pérdidas térmicas SCC',
    extractorConsumption: 'Estimación consumo extractor',
    combustionAirFan: 'Estimación consumo ventilador aire combustión',
    extractorWaterEvaporation: 'Estimación evaporación agua extractor',
    warningSlope: '⚠️ Advertencia: La pendiente del horno supera el límite recomendado (2-5°)',
    warningFillRate: '⚠️ Advertencia: La tasa de llenado supera el límite recomendado (máx 5%)',
    warningVelocity: '⚠️ Advertencia: La velocidad del gas en SCC supera el límite recomendado de 3 m/s',
  },

  de: {
    // Main navigation
    title: 'Drehrohrofen und SCC Konfiguration',
    combustionParameters: 'Verbrennungsparameter',
    flueGases: 'Rauchgase',
    pollutantEmissions: 'Schadstoffemissionen',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Zurück zum Fluss',
    sendData: 'Daten senden',
    rapport: 'Bericht',
    
    calculationParameters: 'Berechnungsparameter',
    calculatedParameters: 'Berechnete Parameter',
    combustionAirComposition: 'Verbrennungsluftzusammensetzung',
    atStoichiometry: 'Bei der Stöchiometrie',
    atAdiabaticity: 'Bei der Adiabatik',
    combustionAirTotal: 'Verbrennungsluft gesamt',
    flueGasComposition: 'Rauchgaszusammensetzung',
    flueGasAtStoichiometry: 'Rauchgas bei der Stöchiometrie',
    outputFlueGasWithoutWater: 'Ausgangsrauchgas ohne Wasser aus Extraktor',
    outputFlueGasWithWater: 'Ausgangsrauchgas mit Wasser aus Extraktor',
    resetValues: 'Werte zurücksetzen',
    export: 'Exportieren',
    
    flueGasTemperatureOutlet: 'Rauchgas-Austrittstemperatur [°C]',
    airFactor: 'Luftfaktor',
    combustionAirTemperature: 'Verbrennungslufttemperatur [°C]',
    wasteTemperature: 'Abfalltemperatur [°C]',
    steamWaterTemperature: 'Dampfwassertemperatur',
    estimatedThermalLosses: 'Geschätzte Wärmeverluste [%]',
    airPreheatingPart: 'Luftvorwärmungsanteil [%]',
    airPreheatingTemperature: 'Luftvorwärmungstemperatur [°C]',
    airRelativeMoisture: 'Relative Luftfeuchtigkeit [%]',
    waterVaporizedFromExtractor: 'Verdampftes Wasser aus Extraktor [kg/h]',
    
    airStoechio: 'Stöchiometrische Luft [Kmole]',
    calculatedTemperature: 'Berechnete Temperatur [°C]',
    waterContent: 'Wassergehalt [kg/Nm3]',
    hSystem: 'H_System',
    airFactorCalculated: 'Berechneter Luftfaktor',

    resetDefaultValues: 'Standardwerte zurücksetzen',
    mass: 'Masse [kg/h]',
    wasteFlow: 'Abfallstrom [kg/h]',
    flueGasFlowWet: 'Feuchter Rauchgasstrom [Nm3/h]',
    flueGasFlowDry: 'Trockener Rauchgasstrom [Nm3/h]',
    o2Calculated: 'O2 berechnet [%]',
    inertMass: 'Inerte Masse [kg/h]',

    mercuryTreatmentThreshold: 'Quecksilberbehandlungsschwelle [micro g/Nm3]',
    noxIn: 'NOx EINGANG [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Flugaschegehalt [g/Nm3]',
    siccityBottomAsh: 'Trockenheit der Schlacke [%]',
    o2Ref: 'O2 Ref [%]',
    sncr: 'SNCR (Selektive Nicht-Katalytische Reduktion)',
    sncrtEnabled: 'SNCR aktiviert',
    noxLimit: 'NOx-Grenze [mg/Nm3]',
    stoichiometry: 'Stöchiometrie',
    mercuryTreatment: 'Quecksilberbehandlung',
    hgTreatmentEnabled: 'Hg-Behandlung aktiviert',
    brHgRatio: 'Br/Hg-Verhältnis',
    pollutantTreatmentTable: 'Schadstoffbehandlungstabelle',
    pollutant: 'Schadstoff',
    reactif: 'Reagenz',
    massInput: 'Eingangsmasse',
    efficiency: 'Wirkungsgrad (%)',
    stoechCoeff: 'Stöch. Koeff',
    massOutput: 'Ausgangsmasse',
    massResidue: 'Rückstandsmasse',
    massReactif: 'Reagenzmasse',
    massReduced: 'Reduzierte Masse',
    inputFlueGas: 'Eingangsrauchgas',
    outputFlueGas: 'Ausgangsrauchgas',
    bottomAshesCalculated: 'Berechnete Schlacke',
    bottomAsh: 'Schlacke [kg/h]',
    bottomAshWet: 'Feuchte Schlacke [kg/h]',
    flyAsh: 'Flugasche [kg/h]',
    nh3Consumption: 'NH3-Verbrauch [kg/h]',
    hgMass: 'Hg-Masse [kg/h]',
    bromideConsumption: 'Bromidverbrauch [kg/h]',

    aeraulicPressureLoss: 'Aeraulischer Druckverlust',
    thermicalLossParameters: 'Wärmeverlustparameter',
    rotaryKilnDesign: 'Drehrohrofen-Design',
    lanceEstimation: 'Lanzenschätzung an Fassade',
    facadeCooling: 'Fassadenkühlungsparameter',
    facadeThermicalLosses: 'Fassadenwärmeverlustparameter',
    shellCooling: 'Mantelkühlung',
    sccDimensioning: 'SCC-Dimensionierung',
    sccBurners: 'SCC-Brenner',
    sccThermicalLosses: 'SCC-Wärmeverlustschätzung',
    extractorConsumption: 'Extraktorverbrauchsschätzung',
    combustionAirFan: 'Verbrennungsluftgebläseverbrauchsschätzung',
    extractorWaterEvaporation: 'Extraktor-Wasserverdampfungsschätzung',
    warningSlope: '⚠️ Warnung: Ofenneigung überschreitet empfohlene Grenze (2-5°)',
    warningFillRate: '⚠️ Warnung: Füllrate überschreitet empfohlene Grenze (max 5%)',
    warningVelocity: '⚠️ Warnung: Rauchgasgeschwindigkeit in SCC überschreitet empfohlene Grenze von 3 m/s',
  },

  it: {
    // Main navigation
    title: 'Configurazione Forno Rotativo e SCC',
    combustionParameters: 'Parametri di combustione',
    flueGases: 'Gas di combustione',
    pollutantEmissions: 'Emissioni inquinanti',
    design: 'Progettazione',
    opex: 'Opex',
    backToFlow: 'Torna al flusso',
    sendData: 'Invia dati',
    rapport: 'Rapporto',
    
    calculationParameters: 'Parametri di calcolo',
    calculatedParameters: 'Parametri calcolati',
    combustionAirComposition: 'Composizione aria di combustione',
    atStoichiometry: 'Alla stechiometria',
    atAdiabaticity: 'All\'adiabaticità',
    combustionAirTotal: 'Aria di combustione totale',
    flueGasComposition: 'Composizione gas di combustione',
    flueGasAtStoichiometry: 'Gas di combustione alla stechiometria',
    outputFlueGasWithoutWater: 'Gas di combustione in uscita senza acqua dall\'estrattore',
    outputFlueGasWithWater: 'Gas di combustione in uscita con acqua dall\'estrattore',
    resetValues: 'Ripristina valori',
    export: 'Esporta',
    
    flueGasTemperatureOutlet: 'Temperatura di uscita gas di combustione [°C]',
    airFactor: 'Fattore aria',
    combustionAirTemperature: 'Temperatura aria di combustione [°C]',
    wasteTemperature: 'Temperatura rifiuti [°C]',
    steamWaterTemperature: 'Temperatura acqua vapore',
    estimatedThermalLosses: 'Perdite termiche stimate [%]',
    airPreheatingPart: 'Parte preriscaldamento aria [%]',
    airPreheatingTemperature: 'Temperatura preriscaldamento aria [°C]',
    airRelativeMoisture: 'Umidità relativa aria [%]',
    waterVaporizedFromExtractor: 'Acqua vaporizzata dall\'estrattore [kg/h]',
    
    airStoechio: 'Aria stechiometrica [Kmole]',
    calculatedTemperature: 'Temperatura calcolata [°C]',
    waterContent: 'Contenuto acqua [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Fattore aria calcolato',

    resetDefaultValues: 'Ripristina valori predefiniti',
    mass: 'Massa [kg/h]',
    wasteFlow: 'Flusso rifiuti [kg/h]',
    flueGasFlowWet: 'Flusso gas umido [Nm3/h]',
    flueGasFlowDry: 'Flusso gas secco [Nm3/h]',
    o2Calculated: 'O2 calcolato [%]',
    inertMass: 'Massa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Soglia trattamento mercurio [micro g/Nm3]',
    noxIn: 'NOx INGRESSO [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Contenuto ceneri volanti [g/Nm3]',
    siccityBottomAsh: 'Siccità scorie [%]',
    o2Ref: 'O2 rif [%]',
    sncr: 'SNCR (Riduzione Catalitica Selettiva)',
    sncrtEnabled: 'SNCR attivato',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Stechiometria',
    mercuryTreatment: 'Trattamento mercurio',
    hgTreatmentEnabled: 'Trattamento Hg attivato',
    brHgRatio: 'Rapporto Br/Hg',
    pollutantTreatmentTable: 'Tabella trattamento inquinanti',
    pollutant: 'Inquinante',
    reactif: 'Reagente',
    massInput: 'Massa ingresso',
    efficiency: 'Efficienza (%)',
    stoechCoeff: 'Coeff. Stechiom.',
    massOutput: 'Massa uscita',
    massResidue: 'Massa residuo',
    massReactif: 'Massa reagente',
    massReduced: 'Massa ridotta',
    inputFlueGas: 'Gas di combustione ingresso',
    outputFlueGas: 'Gas di combustione uscita',
    bottomAshesCalculated: 'Scorie calcolate',
    bottomAsh: 'Scorie [kg/h]',
    bottomAshWet: 'Scorie umide [kg/h]',
    flyAsh: 'Ceneri volanti [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Massa Hg [kg/h]',
    bromideConsumption: 'Consumo bromuro [kg/h]',

    aeraulicPressureLoss: 'Perdita di carico aeraulica',
    thermicalLossParameters: 'Parametri perdite termiche',
    rotaryKilnDesign: 'Progettazione forno rotativo',
    lanceEstimation: 'Stima lance su facciata',
    facadeCooling: 'Parametri raffreddamento facciata',
    facadeThermicalLosses: 'Parametri perdite termiche facciata',
    shellCooling: 'Raffreddamento involucro',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Bruciatori SCC',
    sccThermicalLosses: 'Stima perdite termiche SCC',
    extractorConsumption: 'Stima consumo estrattore',
    combustionAirFan: 'Stima consumo ventilatore aria combustione',
    extractorWaterEvaporation: 'Stima evaporazione acqua estrattore',
    warningSlope: '⚠️ Attenzione: Pendenza forno supera limite raccomandato (2-5°)',
    warningFillRate: '⚠️ Attenzione: Tasso riempimento supera limite raccomandato (max 5%)',
    warningVelocity: '⚠️ Attenzione: Velocità gas in SCC supera limite raccomandato di 3 m/s',
  },

  pt: {
    // Main navigation
    title: 'Configuração de Forno Rotativo e SCC',
    combustionParameters: 'Parâmetros de combustão',
    flueGases: 'Gases de combustão',
    pollutantEmissions: 'Emissões poluentes',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Voltar ao fluxo',
    sendData: 'Enviar dados',
    rapport: 'Relatório',
    
    calculationParameters: 'Parâmetros de cálculo',
    calculatedParameters: 'Parâmetros calculados',
    combustionAirComposition: 'Composição do ar de combustão',
    atStoichiometry: 'Na estequiometria',
    atAdiabaticity: 'Na adiabacidade',
    combustionAirTotal: 'Ar de combustão total',
    flueGasComposition: 'Composição dos gases de combustão',
    flueGasAtStoichiometry: 'Gases de combustão na estequiometria',
    outputFlueGasWithoutWater: 'Gases de combustão de saída sem água do extrator',
    outputFlueGasWithWater: 'Gases de combustão de saída com água do extrator',
    resetValues: 'Redefinir valores',
    export: 'Exportar',
    
    flueGasTemperatureOutlet: 'Temperatura de saída dos gases de combustão [°C]',
    airFactor: 'Fator de ar',
    combustionAirTemperature: 'Temperatura do ar de combustão [°C]',
    wasteTemperature: 'Temperatura dos resíduos [°C]',
    steamWaterTemperature: 'Temperatura da água vapor',
    estimatedThermalLosses: 'Perdas térmicas estimadas [%]',
    airPreheatingPart: 'Parte de pré-aquecimento do ar [%]',
    airPreheatingTemperature: 'Temperatura de pré-aquecimento do ar [°C]',
    airRelativeMoisture: 'Umidade relativa do ar [%]',
    waterVaporizedFromExtractor: 'Água vaporizada do extrator [kg/h]',
    
    airStoechio: 'Ar estequiométrico [Kmole]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Conteúdo de água [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Fator de ar calculado',

    resetDefaultValues: 'Redefinir valores padrão',
    mass: 'Massa [kg/h]',
    wasteFlow: 'Fluxo de resíduos [kg/h]',
    flueGasFlowWet: 'Fluxo de gás úmido [Nm3/h]',
    flueGasFlowDry: 'Fluxo de gás seco [Nm3/h]',
    o2Calculated: 'O2 calculado [%]',
    inertMass: 'Massa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Limiar de tratamento de mercúrio [micro g/Nm3]',
    noxIn: 'NOx ENTRADA [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Conteúdo de cinzas volantes [g/Nm3]',
    siccityBottomAsh: 'Secura das escórias [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Redução Catalítica Seletiva)',
    sncrtEnabled: 'SNCR ativado',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Estequiometria',
    mercuryTreatment: 'Tratamento de mercúrio',
    hgTreatmentEnabled: 'Tratamento Hg ativado',
    brHgRatio: 'Relação Br/Hg',
    pollutantTreatmentTable: 'Tabela de tratamento de poluentes',
    pollutant: 'Poluente',
    reactif: 'Reagente',
    massInput: 'Massa entrada',
    efficiency: 'Eficiência (%)',
    stoechCoeff: 'Coef. Estequiom.',
    massOutput: 'Massa saída',
    massResidue: 'Massa resíduo',
    massReactif: 'Massa reagente',
    massReduced: 'Massa reduzida',
    inputFlueGas: 'Gás de combustão entrada',
    outputFlueGas: 'Gás de combustão saída',
    bottomAshesCalculated: 'Escórias calculadas',
    bottomAsh: 'Escórias [kg/h]',
    bottomAshWet: 'Escórias úmidas [kg/h]',
    flyAsh: 'Cinzas volantes [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Massa Hg [kg/h]',
    bromideConsumption: 'Consumo de brometo [kg/h]',

    aeraulicPressureLoss: 'Perda de carga aeráulica',
    thermicalLossParameters: 'Parâmetros de perdas térmicas',
    rotaryKilnDesign: 'Projeto de forno rotativo',
    lanceEstimation: 'Estimativa de lanças na fachada',
    facadeCooling: 'Parâmetros de refrigeração da fachada',
    facadeThermicalLosses: 'Parâmetros de perdas térmicas da fachada',
    shellCooling: 'Refrigeração da carcaça',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Queimadores SCC',
    sccThermicalLosses: 'Estimativa de perdas térmicas SCC',
    extractorConsumption: 'Estimativa de consumo do extrator',
    combustionAirFan: 'Estimativa de consumo do ventilador de ar de combustão',
    extractorWaterEvaporation: 'Estimativa de evaporação de água do extrator',
    warningSlope: '⚠️ Aviso: Inclinação do forno excede limite recomendado (2-5°)',
    warningFillRate: '⚠️ Aviso: Taxa de enchimento excede limite recomendado (máx 5%)',
    warningVelocity: '⚠️ Aviso: Velocidade do gás em SCC excede limite recomendado de 3 m/s',
  },

  ru: {
    // Main navigation
    title: 'Конфигурация вращающейся печи и SCC',
    combustionParameters: 'Параметры сгорания',
    flueGases: 'Дымовые газы',
    pollutantEmissions: 'Выбросы загрязняющих веществ',
    design: 'Проектирование',
    opex: 'Эксплуатационные расходы',
    backToFlow: 'Вернуться к потоку',
    sendData: 'Отправить данные',
    rapport: 'Отчёт',
    
    calculationParameters: 'Параметры расчета',
    calculatedParameters: 'Расчетные параметры',
    combustionAirComposition: 'Состав воздуха для сгорания',
    atStoichiometry: 'При стехиометрии',
    atAdiabaticity: 'При адиабатности',
    combustionAirTotal: 'Общий воздух для сгорания',
    flueGasComposition: 'Состав дымовых газов',
    flueGasAtStoichiometry: 'Дымовые газы при стехиометрии',
    outputFlueGasWithoutWater: 'Выходящие дымовые газы без воды из экстрактора',
    outputFlueGasWithWater: 'Выходящие дымовые газы с водой из экстрактора',
    resetValues: 'Сбросить значения',
    export: 'Экспорт',
    
    flueGasTemperatureOutlet: 'Температура выхода дымовых газов [°C]',
    airFactor: 'Коэффициент воздуха',
    combustionAirTemperature: 'Температура воздуха для сгорания [°C]',
    wasteTemperature: 'Температура отходов [°C]',
    steamWaterTemperature: 'Температура водяного пара',
    estimatedThermalLosses: 'Предполагаемые тепловые потери [%]',
    airPreheatingPart: 'Часть подогрева воздуха [%]',
    airPreheatingTemperature: 'Температура подогрева воздуха [°C]',
    airRelativeMoisture: 'Относительная влажность воздуха [%]',
    waterVaporizedFromExtractor: 'Испаренная вода из экстрактора [kg/h]',
    
    airStoechio: 'Стехиометрический воздух [Kmole]',
    calculatedTemperature: 'Расчетная температура [°C]',
    waterContent: 'Содержание воды [kg/Nm3]',
    hSystem: 'H_система',
    airFactorCalculated: 'Расчетный коэффициент воздуха',

    resetDefaultValues: 'Сбросить значения по умолчанию',
    mass: 'Масса [kg/h]',
    wasteFlow: 'Поток отходов [kg/h]',
    flueGasFlowWet: 'Поток влажного газа [Nm3/h]',
    flueGasFlowDry: 'Поток сухого газа [Nm3/h]',
    o2Calculated: 'O2 рассчитано [%]',
    inertMass: 'Инертная масса [kg/h]',

    mercuryTreatmentThreshold: 'Порог обработки ртути [micro g/Nm3]',
    noxIn: 'NOx ВХОД [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Содержание летучей золы [g/Nm3]',
    siccityBottomAsh: 'Сухость шлака [%]',
    o2Ref: 'O2 эталон [%]',
    sncr: 'SNCR (Селективное некаталитическое восстановление)',
    sncrtEnabled: 'SNCR активирован',
    noxLimit: 'Предел NOx [mg/Nm3]',
    stoichiometry: 'Стехиометрия',
    mercuryTreatment: 'Обработка ртути',
    hgTreatmentEnabled: 'Обработка Hg активирована',
    brHgRatio: 'Соотношение Br/Hg',
    pollutantTreatmentTable: 'Таблица обработки загрязняющих веществ',
    pollutant: 'Загрязняющее вещество',
    reactif: 'Реагент',
    massInput: 'Входная масса',
    efficiency: 'Эффективность (%)',
    stoechCoeff: 'Стехиом. коэфф.',
    massOutput: 'Выходная масса',
    massResidue: 'Масса остатка',
    massReactif: 'Масса реагента',
    massReduced: 'Уменьшенная масса',
    inputFlueGas: 'Входящий дымовой газ',
    outputFlueGas: 'Выходящий дымовой газ',
    bottomAshesCalculated: 'Рассчитанный шлак',
    bottomAsh: 'Шлак [kg/h]',
    bottomAshWet: 'Влажный шлак [kg/h]',
    flyAsh: 'Летучая зола [kg/h]',
    nh3Consumption: 'Потребление NH3 [kg/h]',
    hgMass: 'Масса Hg [kg/h]',
    bromideConsumption: 'Потребление бромида [kg/h]',

    aeraulicPressureLoss: 'Аэродинамическая потеря давления',
    thermicalLossParameters: 'Параметры тепловых потерь',
    rotaryKilnDesign: 'Проектирование вращающейся печи',
    lanceEstimation: 'Оценка форсунок на фасаде',
    facadeCooling: 'Параметры охлаждения фасада',
    facadeThermicalLosses: 'Параметры тепловых потерь фасада',
    shellCooling: 'Охлаждение корпуса',
    sccDimensioning: 'Размеры SCC',
    sccBurners: 'Горелки SCC',
    sccThermicalLosses: 'Оценка тепловых потерь SCC',
    extractorConsumption: 'Оценка потребления экстрактора',
    combustionAirFan: 'Оценка потребления вентилятора воздуха для горения',
    extractorWaterEvaporation: 'Оценка испарения воды экстрактора',
    warningSlope: '⚠️ Предупреждение: Наклон печи превышает рекомендуемый предел (2-5°)',
    warningFillRate: '⚠️ Предупреждение: Коэффициент заполнения превышает рекомендуемый предел (макс 5%)',
    warningVelocity: '⚠️ Предупреждение: Скорость газа в SCC превышает рекомендуемый предел 3 м/с',
  },

  ja: {
    // Main navigation
    title: 'ロータリーキルンとSCC設定',
    combustionParameters: '燃焼パラメータ',
    flueGases: '燃焼ガス',
    pollutantEmissions: '汚染物質排出',
    design: '設計',
    opex: '運営費',
    backToFlow: 'フローに戻る',
    sendData: 'データ送信',
    rapport: 'レポート',
    
    calculationParameters: '計算パラメータ',
    calculatedParameters: '計算されたパラメータ',
    combustionAirComposition: '燃焼空気組成',
    atStoichiometry: '化学量論で',
    atAdiabaticity: '断熱で',
    combustionAirTotal: '燃焼空気合計',
    flueGasComposition: '燃焼ガス組成',
    flueGasAtStoichiometry: '化学量論での燃焼ガス',
    outputFlueGasWithoutWater: '抽出器からの水なしの出力燃焼ガス',
    outputFlueGasWithWater: '抽出器からの水ありの出力燃焼ガス',
    resetValues: '値をリセット',
    export: 'エクスポート',
    
    flueGasTemperatureOutlet: '燃焼ガス出口温度 [°C]',
    airFactor: '空気率',
    combustionAirTemperature: '燃焼空気温度 [°C]',
    wasteTemperature: '廃棄物温度 [°C]',
    steamWaterTemperature: '蒸気水温度',
    estimatedThermalLosses: '推定熱損失 [%]',
    airPreheatingPart: '空気予熱部分 [%]',
    airPreheatingTemperature: '空気予熱温度 [°C]',
    airRelativeMoisture: '空気相対湿度 [%]',
    waterVaporizedFromExtractor: '抽出器からの蒸発水 [kg/h]',
    
    airStoechio: '化学量論空気 [Kmole]',
    calculatedTemperature: '計算温度 [°C]',
    waterContent: '水分含有量 [kg/Nm3]',
    hSystem: 'H_システム',
    airFactorCalculated: '計算された空気率',

    resetDefaultValues: 'デフォルト値にリセット',
    mass: '質量 [kg/h]',
    wasteFlow: '廃棄物流量 [kg/h]',
    flueGasFlowWet: '湿潤ガス流量 [Nm3/h]',
    flueGasFlowDry: '乾燥ガス流量 [Nm3/h]',
    o2Calculated: 'O2計算値 [%]',
    inertMass: '不活性質量 [kg/h]',

    mercuryTreatmentThreshold: '水銀処理閾値 [micro g/Nm3]',
    noxIn: 'NOx入力 [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: '飛灰含有量 [g/Nm3]',
    siccityBottomAsh: '底灰乾燥度 [%]',
    o2Ref: 'O2基準 [%]',
    sncr: 'SNCR（選択的非触媒還元）',
    sncrtEnabled: 'SNCR有効',
    noxLimit: 'NOx制限 [mg/Nm3]',
    stoichiometry: '化学量論',
    mercuryTreatment: '水銀処理',
    hgTreatmentEnabled: 'Hg処理有効',
    brHgRatio: 'Br/Hg比',
    pollutantTreatmentTable: '汚染物質処理表',
    pollutant: '汚染物質',
    reactif: '試薬',
    massInput: '入力質量',
    efficiency: '効率 (%)',
    stoechCoeff: '化学量論係数',
    massOutput: '出力質量',
    massResidue: '残留質量',
    massReactif: '試薬質量',
    massReduced: '削減質量',
    inputFlueGas: '入力燃焼ガス',
    outputFlueGas: '出力燃焼ガス',
    bottomAshesCalculated: '計算された底灰',
    bottomAsh: '底灰 [kg/h]',
    bottomAshWet: '湿潤底灰 [kg/h]',
    flyAsh: '飛灰 [kg/h]',
    nh3Consumption: 'NH3消費 [kg/h]',
    hgMass: 'Hg質量 [kg/h]',
    bromideConsumption: '臭化物消費 [kg/h]',

    aeraulicPressureLoss: '空気圧力損失',
    thermicalLossParameters: '熱損失パラメータ',
    rotaryKilnDesign: 'ロータリーキルン設計',
    lanceEstimation: 'ファサードランス推定',
    facadeCooling: 'ファサード冷却パラメータ',
    facadeThermicalLosses: 'ファサード熱損失パラメータ',
    shellCooling: 'シェル冷却',
    sccDimensioning: 'SCCサイジング',
    sccBurners: 'SCCバーナー',
    sccThermicalLosses: 'SCC熱損失推定',
    extractorConsumption: '抽出器消費推定',
    combustionAirFan: '燃焼空気ファン消費推定',
    extractorWaterEvaporation: '抽出器水蒸発推定',
    warningSlope: '⚠️ 警告：キルン傾斜が推奨制限（2-5°）を超えています',
    warningFillRate: '⚠️ 警告：充填率が推奨制限（最大5%）を超えています',
    warningVelocity: '⚠️ 警告：SCCのガス速度が推奨制限3 m/sを超えています',
  },

  zh: {
    // Main navigation
    title: '回转窑和SCC配置',
    combustionParameters: '燃烧参数',
    flueGases: '烟气',
    pollutantEmissions: '污染物排放',
    design: '设计',
    opex: '运营费用',
    backToFlow: '返回流程',
    sendData: '发送数据',
    rapport: '报告',
    
    calculationParameters: '计算参数',
    calculatedParameters: '计算得出的参数',
    combustionAirComposition: '燃烧空气组成',
    atStoichiometry: '在化学计量比',
    atAdiabaticity: '在绝热性',
    combustionAirTotal: '燃烧空气总量',
    flueGasComposition: '烟气组成',
    flueGasAtStoichiometry: '化学计量比下的烟气',
    outputFlueGasWithoutWater: '不含提取器水的输出烟气',
    outputFlueGasWithWater: '含提取器水的输出烟气',
    resetValues: '重置数值',
    export: '导出',
    
    flueGasTemperatureOutlet: '烟气出口温度 [°C]',
    airFactor: '空气系数',
    combustionAirTemperature: '燃烧空气温度 [°C]',
    wasteTemperature: '废料温度 [°C]',
    steamWaterTemperature: '蒸汽水温度',
    estimatedThermalLosses: '估计热损失 [%]',
    airPreheatingPart: '空气预热部分 [%]',
    airPreheatingTemperature: '空气预热温度 [°C]',
    airRelativeMoisture: '空气相对湿度 [%]',
    waterVaporizedFromExtractor: '提取器蒸发水 [kg/h]',
    
    airStoechio: '化学计量空气 [Kmole]',
    calculatedTemperature: '计算温度 [°C]',
    waterContent: '含水量 [kg/Nm3]',
    hSystem: 'H_系统',
    airFactorCalculated: '计算的空气系数',

    resetDefaultValues: '重置默认值',
    mass: '质量 [kg/h]',
    wasteFlow: '废物流量 [kg/h]',
    flueGasFlowWet: '湿气流量 [Nm3/h]',
    flueGasFlowDry: '干气流量 [Nm3/h]',
    o2Calculated: 'O2计算值 [%]',
    inertMass: '惰性质量 [kg/h]',

    mercuryTreatmentThreshold: '汞处理阈值 [micro g/Nm3]',
    noxIn: 'NOx输入 [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: '飞灰含量 [g/Nm3]',
    siccityBottomAsh: '底灰干燥度 [%]',
    o2Ref: 'O2参考 [%]',
    sncr: 'SNCR（选择性非催化还原）',
    sncrtEnabled: 'SNCR启用',
    noxLimit: 'NOx限制 [mg/Nm3]',
    stoichiometry: '化学计量',
    mercuryTreatment: '汞处理',
    hgTreatmentEnabled: 'Hg处理启用',
    brHgRatio: 'Br/Hg比',
    pollutantTreatmentTable: '污染物处理表',
    pollutant: '污染物',
    reactif: '试剂',
    massInput: '输入质量',
    efficiency: '效率 (%)',
    stoechCoeff: '化学计量系数',
    massOutput: '输出质量',
    massResidue: '残留质量',
    massReactif: '试剂质量',
    massReduced: '减少质量',
    inputFlueGas: '输入烟气',
    outputFlueGas: '输出烟气',
    bottomAshesCalculated: '计算的底灰',
    bottomAsh: '底灰 [kg/h]',
    bottomAshWet: '湿底灰 [kg/h]',
    flyAsh: '飞灰 [kg/h]',
    nh3Consumption: 'NH3消耗 [kg/h]',
    hgMass: 'Hg质量 [kg/h]',
    bromideConsumption: '溴化物消耗 [kg/h]',

    aeraulicPressureLoss: '气动压力损失',
    thermicalLossParameters: '热损失参数',
    rotaryKilnDesign: '回转窑设计',
    lanceEstimation: '正面喷枪估算',
    facadeCooling: '正面冷却参数',
    facadeThermicalLosses: '正面热损失参数',
    shellCooling: '外壳冷却',
    sccDimensioning: 'SCC尺寸设计',
    sccBurners: 'SCC燃烧器',
    sccThermicalLosses: 'SCC热损失估算',
    extractorConsumption: '提取器消耗估算',
    combustionAirFan: '燃烧空气风扇消耗估算',
    extractorWaterEvaporation: '提取器水蒸发估算',
    warningSlope: '⚠️ 警告：窑倾斜超过推荐限制（2-5°）',
    warningFillRate: '⚠️ 警告：填充率超过推荐限制（最大5%）',
    warningVelocity: '⚠️ 警告：SCC中的气体速度超过推荐限制3 m/s',
  },

  ar: {
    // Main navigation
    title: 'تكوين الفرن الدوار و SCC',
    combustionParameters: 'معاملات الاحتراق',
    flueGases: 'غازات المداخن',
    pollutantEmissions: 'انبعاثات الملوثات',
    design: 'التصميم',
    opex: 'نفقات التشغيل',
    backToFlow: 'العودة إلى التدفق',
    sendData: 'إرسال البيانات',
    rapport: 'تقرير',
    
    calculationParameters: 'معاملات الحساب',
    calculatedParameters: 'المعاملات المحسوبة',
    combustionAirComposition: 'تركيب هواء الاحتراق',
    atStoichiometry: 'عند التكافؤ الكيميائي',
    atAdiabaticity: 'عند الحالة الأديباتية',
    combustionAirTotal: 'إجمالي هواء الاحتراق',
    flueGasComposition: 'تركيب غازات المداخن',
    flueGasAtStoichiometry: 'غازات المداخن عند التكافؤ الكيميائي',
    outputFlueGasWithoutWater: 'غازات المداخن الخارجة بدون ماء من المستخرج',
    outputFlueGasWithWater: 'غازات المداخن الخارجة مع ماء من المستخرج',
    resetValues: 'إعادة تعيين القيم',
    export: 'تصدير',
    
    flueGasTemperatureOutlet: 'درجة حرارة مخرج غازات المداخن [°C]',
    airFactor: 'معامل الهواء',
    combustionAirTemperature: 'درجة حرارة هواء الاحتراق [°C]',
    wasteTemperature: 'درجة حرارة النفايات [°C]',
    steamWaterTemperature: 'درجة حرارة الماء البخاري',
    estimatedThermalLosses: 'الخسائر الحرارية المقدرة [%]',
    airPreheatingPart: 'جزء تسخين الهواء المسبق [%]',
    airPreheatingTemperature: 'درجة حرارة تسخين الهواء المسبق [°C]',
    airRelativeMoisture: 'الرطوبة النسبية للهواء [%]',
    waterVaporizedFromExtractor: 'الماء المتبخر من المستخرج [kg/h]',
    
    airStoechio: 'الهواء التكافئي [Kmole]',
    calculatedTemperature: 'درجة الحرارة المحسوبة [°C]',
    waterContent: 'محتوى الماء [kg/Nm3]',
    hSystem: 'H_النظام',
    airFactorCalculated: 'معامل الهواء المحسوب',

    resetDefaultValues: 'إعادة تعيين القيم الافتراضية',
    mass: 'الكتلة [kg/h]',
    wasteFlow: 'تدفق النفايات [kg/h]',
    flueGasFlowWet: 'تدفق الغاز الرطب [Nm3/h]',
    flueGasFlowDry: 'تدفق الغاز الجاف [Nm3/h]',
    o2Calculated: 'O2 محسوب [%]',
    inertMass: 'الكتلة الخاملة [kg/h]',

    mercuryTreatmentThreshold: 'عتبة معالجة الزئبق [micro g/Nm3]',
    noxIn: 'NOx دخول [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'محتوى الرماد المتطاير [g/Nm3]',
    siccityBottomAsh: 'جفاف الخبث [%]',
    o2Ref: 'O2 مرجع [%]',
    sncr: 'SNCR (الاختزال غير التحفيزي الانتقائي)',
    sncrtEnabled: 'SNCR مفعل',
    noxLimit: 'حد NOx [mg/Nm3]',
    stoichiometry: 'التكافؤ الكيميائي',
    mercuryTreatment: 'معالجة الزئبق',
    hgTreatmentEnabled: 'معالجة Hg مفعلة',
    brHgRatio: 'نسبة Br/Hg',
    pollutantTreatmentTable: 'جدول معالجة الملوثات',
    pollutant: 'ملوث',
    reactif: 'كاشف',
    massInput: 'كتلة الدخول',
    efficiency: 'الكفاءة (%)',
    stoechCoeff: 'معامل التكافؤ',
    massOutput: 'كتلة الخروج',
    massResidue: 'كتلة المخلفات',
    massReactif: 'كتلة الكاشف',
    massReduced: 'الكتلة المخفضة',
    inputFlueGas: 'غاز مداخن الدخول',
    outputFlueGas: 'غاز مداخن الخروج',
    bottomAshesCalculated: 'الخبث المحسوب',
    bottomAsh: 'خبث [kg/h]',
    bottomAshWet: 'خبث رطب [kg/h]',
    flyAsh: 'رماد متطاير [kg/h]',
    nh3Consumption: 'استهلاك NH3 [kg/h]',
    hgMass: 'كتلة Hg [kg/h]',
    bromideConsumption: 'استهلاك البروميد [kg/h]',

    aeraulicPressureLoss: 'فقدان الضغط الهوائي',
    thermicalLossParameters: 'معاملات الفقد الحراري',
    rotaryKilnDesign: 'تصميم الفرن الدوار',
    lanceEstimation: 'تقدير الرماح على الواجهة',
    facadeCooling: 'معاملات تبريد الواجهة',
    facadeThermicalLosses: 'معاملات الفقد الحراري للواجهة',
    shellCooling: 'تبريد الغلاف',
    sccDimensioning: 'تحديد أبعاد SCC',
    sccBurners: 'موقد SCC',
    sccThermicalLosses: 'تقدير الفقد الحراري لـ SCC',
    extractorConsumption: 'تقدير استهلاك المستخرج',
    combustionAirFan: 'تقدير استهلاك مروحة هواء الاحتراق',
    extractorWaterEvaporation: 'تقدير تبخر ماء المستخرج',
    warningSlope: '⚠️ تحذير: ميل الفرن يتجاوز الحد الموصى به (2-5°)',
    warningFillRate: '⚠️ تحذير: معدل الملء يتجاوز الحد الموصى به (الحد الأقصى 5%)',
    warningVelocity: '⚠️ تحذير: سرعة الغاز في SCC تتجاوز الحد الموصى به 3 م/ث',
  },
};